# Copyright (c) Microsoft Corporation. All rights reserved.
# Module Name:
# winpackagefamily.h
# Abstract:
# API family partitioning based on packages.
# nonstandard extension 'single line comment' was used
# defined(_MSC_VER) and !defined(MOFCOMP_PASS)

WINAPI_FAMILY_SERVER = 0x00000005
WINAPI_FAMILY_DESKTOP_APP = 0x00000064
WINAPI_FAMILY = WINAPI_FAMILY_DESKTOP_APP

# The value of WINAPI_FAMILY_DESKTOP_APP may change in future SDKs.
WINAPI_FAMILY_DESKTOP_APP = 0x00000064
WINAPI_PARTITION_SERVER = WINAPI_FAMILY == WINAPI_FAMILY_SERVER
# * PARTITIONS based on packages are each #undef'ed below, and then will be
# #define-ed
# * to be either 1 or 0 or depending on the active WINAPI_FAMILY.
# * PARTITIONS for feature packages. Each package might be active for one or
# more editions
WINAPI_PARTITION_PKG_WINTRUST = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_WEBSERVICES = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_EVENTLOGSERVICE = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_VHD = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_PERFCOUNTER = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_SECURESTARTUP = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_REMOTEFS = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_BOOTABLESKU = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_CMDTOOLS = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_DISM = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_CORESETUP = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_APPRUNTIME = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_ESENT = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_WINMGMT = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_WNV = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_CLUSTER = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_VSS = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_TRAFFIC = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_ISCSI = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_STORAGE = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_MPSSVC = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_APPXDEPLOYMENT = WINAPI_PARTITION_SERVER == 1
WINAPI_PARTITION_PKG_WER = WINAPI_PARTITION_SERVER == 1
# !_INC_WINPACKAGEFAMILY
