__REQUIRED_RPCNDR_H_VERSION__ = 0x1F4
__REQUIRED_RPCSAL_H_VERSION__ = 0x64
# from rpc_h import * # NOQA
# from rpcndr_h import * # NOQA

import ctypes

from ctypes.wintypes import (
    VARIANT_BOOL,
    SMALL_RECT,
    _COORD as COORD,
    MSG,
    WIN32_FIND_DATAA,
    WIN32_FIND_DATAW,
)

cdecl = ctypes.CFUNCTYPE
CDECL = cdecl

pascal = ctypes.WINFUNCTYPE
PASCAL = pascal

CALLBACK = ctypes.CFUNCTYPE

WINAPIV = ctypes.CFUNCTYPE
WINAPI = ctypes.WINFUNCTYPE
WINAPI_INLINE = WINAPI
APIENTRY = WINAPI
APIPRIVATE = WINAPI


VOID = ctypes.c_void_p
LPCOLESTR = ctypes.c_wchar_p
LPOLESTR = ctypes.c_wchar_p
OLESTR = ctypes.c_wchar_p
LPCVOID = ctypes.c_void_p
LPVOID = ctypes.c_void_p


POINTER = ctypes.POINTER
POINTER_32 = POINTER
POINTER_64 = POINTER
POINTER_SIGNED = POINTER
POINTER_UNSIGNED = POINTER

ENUM = ctypes.c_int
ATOM = ctypes.c_ushort

PROC = LPCVOID

far = LPCVOID
FAR = far
FARPROC = far

near = LPCVOID
NEAR = near
NEARPROC = near


if ctypes.sizeof(ctypes.c_long) == ctypes.sizeof(ctypes.c_void_p):
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulong
    LONG_PTR = ctypes.c_long
    ULONG_PTR = ctypes.c_ulong
elif ctypes.sizeof(ctypes.c_longlong) == ctypes.sizeof(ctypes.c_void_p):
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulonglong
    LONG_PTR = ctypes.c_longlong
    ULONG_PTR = ctypes.c_ulonglong
else:
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulong
    LONG_PTR = ctypes.c_long
    ULONG_PTR =ctypes. c_ulong


PINT_PTR = POINTER(INT_PTR)
PUINT_PTR = POINTER(UINT_PTR)

PLONG_PTR = POINTER(LONG_PTR)
PULONG_PTR = POINTER(ULONG_PTR)

DWORD_PTR = ULONG_PTR
PDWORD_PTR = POINTER(DWORD_PTR)


BYTE = ctypes.c_byte
PBYTE = POINTER(BYTE)
LPBYTE = POINTER(BYTE)

TBYTE = ctypes.c_wchar
PTBYTE = POINTER(TBYTE)

WSTRING = ctypes.c_wchar_p
UBYTE = ctypes.c_ubyte

# noinspection PyTypeChecker
PBYTE256 = ctypes.c_ubyte * 256

WORD = ctypes.c_ushort
LPWORD = POINTER(WORD)
PWORD = POINTER(WORD)

BOOL = ctypes.c_long
PBOOL = POINTER(BOOL)
LPBOOL = POINTER(BOOL)

CHAR = ctypes.c_char
TCHAR = ctypes.c_wchar

INT = ctypes.c_int
PINT = POINTER(INT)
LPINT = POINTER(INT)

INT8 = ctypes.c_int8
PINT8 = POINTER(INT8)

INT16 = ctypes.c_int16
PINT16 = POINTER(INT16)

INT32 = ctypes.c_int32
PINT32 = POINTER(INT32)

INT64 = ctypes.c_int64
PINT64 = POINTER(INT64)

UINT = ctypes.c_uint
PUINT = POINTER(UINT)

UINT8 = ctypes.c_uint8
PUINT8 = POINTER(UINT8)

UINT16 = ctypes.c_uint16
PUINT16 = POINTER(UINT16)

UINT32 = ctypes.c_uint32
PUINT32 = POINTER(UINT32)

UINT64 = ctypes.c_uint64
PUINT64 = POINTER(UINT64)


HALF_PTR = ctypes.c_int
PHALF_PTR = POINTER(HALF_PTR)

UHALF_PTR = ctypes.c_uint
PUHALF_PTR = POINTER(UHALF_PTR)

LONG = ctypes.c_long
LPLONG = POINTER(LONG)

LONG32 = ctypes.c_int32
PLONG32 = POINTER(LONG32)

LONG64 = ctypes.c_int64
PLONG64 = POINTER(LONG64)

ULONG32 = ctypes.c_uint
PULONG32 = POINTER(ULONG32)

ULONG64 = ctypes.c_uint64
PULONG64 = POINTER(ULONG64)
import ctypes.wintypes
DWORD = ctypes.c_ulong
LPDWORD = POINTER(DWORD)
PDWORD = POINTER(DWORD)

DWORD32 = UINT32
PDWORD32 = POINTER(DWORD32)

DWORD64 = UINT64
PDWORD64 = POINTER(DWORD64)

DOUBLE = ctypes.c_double

FLOAT = ctypes.c_float
PFLOAT = POINTER(FLOAT)


SHORT = ctypes.c_short

SIZE_T = ctypes.c_size_t
PSIZE_T = POINTER(SIZE_T)

SSIZE_T = ctypes.c_ssize_t
PSSIZE_T = POINTER(SSIZE_T)

OLESTR = ctypes.c_wchar_p
LPOLESTR = POINTER(OLESTR)
LPCOLESTR = POINTER(OLESTR)

WPARAM = UINT_PTR
LPARAM = LONG_PTR
LRESULT = LONG_PTR
HFILE = INT
HEVENT = POINTER(VOID)

KAFFINITY = ULONG_PTR
PKAFFINITY = POINTER(KAFFINITY)


from .ntdef_h import (
    ALL_PROCESSOR_GROUPS,
    ANSI_NULL,
    ANSI_STRING,
    ANSI_STRING32,
    ANSI_STRING64,
    ANYSIZE_ARRAY,
    APPLICATION_ERROR_MASK,
    ARGUMENT_PRESENT,
    ARRAYSIZE,
    BOOLEAN,
    CANSI_STRING,
    CCHAR,
    CFORCEINLINE,
    CLONG,
    COMPARTMENT_ID,
    COMPILETIME_OR_2FLAGS,
    COMPILETIME_OR_3FLAGS,
    COMPILETIME_OR_4FLAGS,
    COMPILETIME_OR_5FLAGS,
    COMPILETIME_OR_6FLAGS,
    CONST,
    CONTAINING_RECORD,
    CSHORT,
    CSTRING,
    C_ASSERT,
    DBG_UNREFERENCED_LOCAL_VARIABLE,
    DBG_UNREFERENCED_PARAMETER,
    DECLARE_CONST_UNICODE_STRING,
    DECLARE_GLOBAL_CONST_UNICODE_STRING,
    DECLARE_HANDLE,
    DECLARE_UNICODE_STRING_SIZE,
    DECLSPEC_ADDRSAFE,
    DECLSPEC_ALIGN,
    DECLSPEC_CACHEALIGN,
    DECLSPEC_CHPE_GUEST,
    DECLSPEC_CHPE_PATCHABLE,
    DECLSPEC_DEPRECATED,
    DECLSPEC_DEPRECATED_DDK,
    DECLSPEC_GUARDIGNORE,
    DECLSPEC_GUARDNOCF,
    DECLSPEC_GUARD_SUPPRESS,
    DECLSPEC_IMPORT,
    DECLSPEC_NOINLINE,
    DECLSPEC_NORETURN,
    DECLSPEC_NOTHROW,
    DECLSPEC_NOVTABLE,
    DECLSPEC_SAFEBUFFERS,
    DECLSPEC_SELECTANY,
    DECLSPEC_UUID,
    DEFAULT_UNREACHABLE,
    DEFINE_ENUM_FLAG_OPERATORS,
    DUMMYUNIONNAME,
    DWORDLONG,
    ERROR_SEVERITY_ERROR,
    ERROR_SEVERITY_INFORMATIONAL,
    ERROR_SEVERITY_SUCCESS,
    ERROR_SEVERITY_WARNING,
    EVENT_TYPE,
    FALSE,
    FASTCALL,
    FCHAR,
    FIELD_OFFSET,
    FLOAT128,
    FLONG,
    FORCEINLINE,
    FSHORT,
    GROUP_AFFINITY,
    HANDLE,
    HRESULT,
    HighTime,
    IFACEMETHODIMP,
    IFACEMETHODIMPV,
    IFACEMETHODIMPV_,
    IFACEMETHODIMP_,
    InitializeObjectAttributes,
    Int32x32To64,
    Int64ShllMod32,
    Int64ShraMod32,
    Int64ShrlMod32,
    KIRQL,
    LANGID,
    LANGIDFROMLCID,
    LANG_AFRIKAANS,
    LANG_ALBANIAN,
    LANG_ALSATIAN,
    LANG_AMHARIC,
    LANG_ARABIC,
    LANG_ARMENIAN,
    LANG_ASSAMESE,
    LANG_AZERBAIJANI,
    LANG_AZERI,
    LANG_BANGLA,
    LANG_BASHKIR,
    LANG_BASQUE,
    LANG_BELARUSIAN,
    LANG_BENGALI,
    LANG_BOSNIAN,
    LANG_BOSNIAN_NEUTRAL,
    LANG_BRETON,
    LANG_BULGARIAN,
    LANG_CATALAN,
    LANG_CENTRAL_KURDISH,
    LANG_CHEROKEE,
    LANG_CHINESE,
    LANG_CHINESE_SIMPLIFIED,
    LANG_CHINESE_TRADITIONAL,
    LANG_CORSICAN,
    LANG_CROATIAN,
    LANG_CZECH,
    LANG_DANISH,
    LANG_DARI,
    LANG_DIVEHI,
    LANG_DUTCH,
    LANG_ENGLISH,
    LANG_ESTONIAN,
    LANG_FAEROESE,
    LANG_FARSI,
    LANG_FILIPINO,
    LANG_FINNISH,
    LANG_FRENCH,
    LANG_FRISIAN,
    LANG_FULAH,
    LANG_GALICIAN,
    LANG_GEORGIAN,
    LANG_GERMAN,
    LANG_GREEK,
    LANG_GREENLANDIC,
    LANG_GUJARATI,
    LANG_HAUSA,
    LANG_HAWAIIAN,
    LANG_HEBREW,
    LANG_HINDI,
    LANG_HUNGARIAN,
    LANG_ICELANDIC,
    LANG_IGBO,
    LANG_INDONESIAN,
    LANG_INUKTITUT,
    LANG_INVARIANT,
    LANG_IRISH,
    LANG_ITALIAN,
    LANG_JAPANESE,
    LANG_KANNADA,
    LANG_KASHMIRI,
    LANG_KAZAK,
    LANG_KHMER,
    LANG_KICHE,
    LANG_KINYARWANDA,
    LANG_KONKANI,
    LANG_KOREAN,
    LANG_KYRGYZ,
    LANG_LAO,
    LANG_LATVIAN,
    LANG_LITHUANIAN,
    LANG_LOWER_SORBIAN,
    LANG_LUXEMBOURGISH,
    LANG_MACEDONIAN,
    LANG_MALAY,
    LANG_MALAYALAM,
    LANG_MALTESE,
    LANG_MANIPURI,
    LANG_MAORI,
    LANG_MAPUDUNGUN,
    LANG_MARATHI,
    LANG_MOHAWK,
    LANG_MONGOLIAN,
    LANG_NEPALI,
    LANG_NEUTRAL,
    LANG_NORWEGIAN,
    LANG_OCCITAN,
    LANG_ODIA,
    LANG_ORIYA,
    LANG_PASHTO,
    LANG_PERSIAN,
    LANG_POLISH,
    LANG_PORTUGUESE,
    LANG_PULAR,
    LANG_PUNJABI,
    LANG_QUECHUA,
    LANG_ROMANIAN,
    LANG_ROMANSH,
    LANG_RUSSIAN,
    LANG_SAKHA,
    LANG_SAMI,
    LANG_SANSKRIT,
    LANG_SCOTTISH_GAELIC,
    LANG_SERBIAN,
    LANG_SERBIAN_NEUTRAL,
    LANG_SINDHI,
    LANG_SINHALESE,
    LANG_SLOVAK,
    LANG_SLOVENIAN,
    LANG_SOTHO,
    LANG_SPANISH,
    LANG_SWAHILI,
    LANG_SWEDISH,
    LANG_SYRIAC,
    LANG_SYSTEM_DEFAULT,
    LANG_TAJIK,
    LANG_TAMAZIGHT,
    LANG_TAMIL,
    LANG_TATAR,
    LANG_TELUGU,
    LANG_THAI,
    LANG_TIBETAN,
    LANG_TIGRIGNA,
    LANG_TIGRINYA,
    LANG_TSWANA,
    LANG_TURKISH,
    LANG_TURKMEN,
    LANG_UIGHUR,
    LANG_UKRAINIAN,
    LANG_UPPER_SORBIAN,
    LANG_URDU,
    LANG_USER_DEFAULT,
    LANG_UZBEK,
    LANG_VALENCIAN,
    LANG_VIETNAMESE,
    LANG_WELSH,
    LANG_WOLOF,
    LANG_XHOSA,
    LANG_YAKUT,
    LANG_YI,
    LANG_YORUBA,
    LANG_ZULU,
    LARGE_INTEGER,
    LCID,
    LIST_ENTRY,
    LIST_ENTRY32,
    LIST_ENTRY64,
    LOCALE_CUSTOM_DEFAULT,
    LOCALE_CUSTOM_UI_DEFAULT,
    LOCALE_CUSTOM_UNSPECIFIED,
    LOCALE_INVARIANT,
    LOCALE_NAME_MAX_LENGTH,
    LOCALE_NEUTRAL,
    LOCALE_SYSTEM_DEFAULT,
    LOCALE_TRANSIENT_KEYBOARD1,
    LOCALE_TRANSIENT_KEYBOARD2,
    LOCALE_TRANSIENT_KEYBOARD3,
    LOCALE_TRANSIENT_KEYBOARD4,
    LOCALE_UNASSIGNED_LCID,
    LOCALE_USER_DEFAULT,
    LOGICAL,
    LONGLONG,
    LP,
    LPCCH,
    LPCH,
    LPCSTR,
    LPCTCH,
    LPCTSTR,
    LPCUTSTR,
    LPCUWCHAR,
    LPCUWSTR,
    LPCWCH,
    LPCWCHAR,
    LPCWSTR,
    LPSTR,
    LPTCH,
    LPTSTR,
    LPUTSTR,
    LPUWSTR,
    LPWCH,
    LPWSTR,
    LUID,
    LowTime,
    MAKELANGID,
    MAKELCID,
    MAKESORTLCID,
    MAXCHAR,
    MAXIMUM_PROCESSORS,
    MAXIMUM_PROC_PER_GROUP,
    MAXLONG,
    MAXLONGLONG,
    MAXSHORT,
    MAXUCHAR,
    MAXULONG,
    MAXUSHORT,
    MAX_NATURAL_ALIGNMENT,
    MAX_UCSCHAR,
    MEMORY_ALLOCATION_ALIGNMENT,
    MINCHAR,
    MINLONG,
    MINSHORT,
    MIN_UCSCHAR,
    NLS_VALID_LOCALE_MASK,
    NOP_FUNCTION,
    NPSTR,
    NTAPI,
    NTAPI_INLINE,
    NTSTATUS,
    NTSYSAPI,
    NTSYSCALLAPI,
    NT_ERROR,
    NT_INFORMATION,
    NT_PRODUCT_TYPE,
    NT_SUCCESS,
    NT_WARNING,
    NULL,
    NULL64,
    NWPSTR,
    OBJECTID,
    OBJECT_ATTRIBUTES,
    OBJECT_ATTRIBUTES32,
    OBJECT_ATTRIBUTES64,
    OBJ_CASE_INSENSITIVE,
    OBJ_DONT_REPARSE,
    OBJ_EXCLUSIVE,
    OBJ_FORCE_ACCESS_CHECK,
    OBJ_HANDLE_TAGBITS,
    OBJ_IGNORE_IMPERSONATED_DEVICEMAP,
    OBJ_INHERIT,
    OBJ_KERNEL_HANDLE,
    OBJ_OPENIF,
    OBJ_OPENLINK,
    OBJ_PERMANENT,
    OBJ_VALID_ATTRIBUTES,
    OEM_STRING,
    PANSI_STRING,
    PANSI_STRING32,
    PANSI_STRING64,
    PBOOLEAN,
    PCANSI_STRING,
    PCCH,
    PCCHAR,
    PCH,
    PCHAR,
    PCLONG,
    PCNTSTATUS,
    PCNZCH,
    PCNZTCH,
    PCNZWCH,
    PCOBJECT_ATTRIBUTES,
    PCOBJECT_ATTRIBUTES32,
    PCOBJECT_ATTRIBUTES64,
    PCOEM_STRING,
    PCOMPARTMENT_ID,
    PCSCHAR,
    PCSHORT,
    PCSTR,
    PCSTRING,
    PCSZ,
    PCTCH,
    PCTSTR,
    PCUCHAR,
    PCUCSCHAR,
    PCUCSSTR,
    PCULONG,
    PCUNICODE_STRING,
    PCUNZTCH,
    PCUNZWCH,
    PCUQUAD,
    PCUSHORT,
    PCUTSTR,
    PCUUCSCHAR,
    PCUUCSSTR,
    PCUWCHAR,
    PCUWSTR,
    PCUZZTSTR,
    PCUZZWSTR,
    PCWCH,
    PCWCHAR,
    PCWNF_STATE_NAME,
    PCWSTR,
    PCZPCSTR,
    PCZPCWSTR,
    PCZPSTR,
    PCZPWSTR,
    PCZZSTR,
    PCZZTSTR,
    PCZZWSTR,
    PDWORDLONG,
    PFLOAT128,
    PFORCEINLINE,
    PGROUP_AFFINITY,
    PHANDLE,
    PHYSICAL_ADDRESS,
    PKIRQL,
    PLARGE_INTEGER,
    PLCID,
    PLIST_ENTRY,
    PLIST_ENTRY32,
    PLIST_ENTRY64,
    PLOGICAL,
    PLONG,
    PLONGLONG,
    PLUID,
    PNTSTATUS,
    PNT_PRODUCT_TYPE,
    PNZCH,
    PNZTCH,
    PNZWCH,
    POBJECT_ATTRIBUTES,
    POBJECT_ATTRIBUTES32,
    POBJECT_ATTRIBUTES64,
    POEM_STRING,
    PPHYSICAL_ADDRESS,
    PPROCESSOR_NUMBER,
    PQUAD,
    PRAGMA_DEPRECATED_DDK,
    PRIMARYLANGID,
    PROBE_ALIGNMENT,
    PROBE_ALIGNMENT32,
    PROCESSOR_NUMBER,
    PRODUCT_ANDROMEDA,
    PRODUCT_ARM64_SERVER,
    PRODUCT_AZURE_NANO_SERVER,
    PRODUCT_AZURE_SERVER_CORE,
    PRODUCT_BUSINESS,
    PRODUCT_BUSINESS_N,
    PRODUCT_CLOUD,
    PRODUCT_CLOUDN,
    PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER,
    PRODUCT_CLOUD_STORAGE_SERVER,
    PRODUCT_CLUSTER_SERVER,
    PRODUCT_CLUSTER_SERVER_V,
    PRODUCT_CONNECTED_CAR,
    PRODUCT_CORE,
    PRODUCT_CORE_ARM,
    PRODUCT_CORE_CONNECTED,
    PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC,
    PRODUCT_CORE_CONNECTED_N,
    PRODUCT_CORE_CONNECTED_SINGLELANGUAGE,
    PRODUCT_CORE_COUNTRYSPECIFIC,
    PRODUCT_CORE_N,
    PRODUCT_CORE_SINGLELANGUAGE,
    PRODUCT_DATACENTER_A_SERVER_CORE,
    PRODUCT_DATACENTER_EVALUATION_SERVER,
    PRODUCT_DATACENTER_EVALUATION_SERVER_CORE,
    PRODUCT_DATACENTER_NANO_SERVER,
    PRODUCT_DATACENTER_SERVER,
    PRODUCT_DATACENTER_SERVER_CORE,
    PRODUCT_DATACENTER_SERVER_CORE_V,
    PRODUCT_DATACENTER_SERVER_V,
    PRODUCT_DATACENTER_WS_SERVER_CORE,
    PRODUCT_EDUCATION,
    PRODUCT_EDUCATION_N,
    PRODUCT_EMBEDDED,
    PRODUCT_EMBEDDED_A,
    PRODUCT_EMBEDDED_AUTOMOTIVE,
    PRODUCT_EMBEDDED_E,
    PRODUCT_EMBEDDED_EVAL,
    PRODUCT_EMBEDDED_E_EVAL,
    PRODUCT_EMBEDDED_INDUSTRY,
    PRODUCT_EMBEDDED_INDUSTRY_A,
    PRODUCT_EMBEDDED_INDUSTRY_A_E,
    PRODUCT_EMBEDDED_INDUSTRY_E,
    PRODUCT_EMBEDDED_INDUSTRY_EVAL,
    PRODUCT_EMBEDDED_INDUSTRY_E_EVAL,
    PRODUCT_ENTERPRISE,
    PRODUCT_ENTERPRISEG,
    PRODUCT_ENTERPRISEGN,
    PRODUCT_ENTERPRISE_E,
    PRODUCT_ENTERPRISE_EVALUATION,
    PRODUCT_ENTERPRISE_N,
    PRODUCT_ENTERPRISE_N_EVALUATION,
    PRODUCT_ENTERPRISE_S,
    PRODUCT_ENTERPRISE_SERVER,
    PRODUCT_ENTERPRISE_SERVER_CORE,
    PRODUCT_ENTERPRISE_SERVER_CORE_V,
    PRODUCT_ENTERPRISE_SERVER_IA64,
    PRODUCT_ENTERPRISE_SERVER_V,
    PRODUCT_ENTERPRISE_SUBSCRIPTION,
    PRODUCT_ENTERPRISE_SUBSCRIPTION_N,
    PRODUCT_ENTERPRISE_S_EVALUATION,
    PRODUCT_ENTERPRISE_S_N,
    PRODUCT_ENTERPRISE_S_N_EVALUATION,
    PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL,
    PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC,
    PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT,
    PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC,
    PRODUCT_HOLOGRAPHIC,
    PRODUCT_HOME_BASIC,
    PRODUCT_HOME_BASIC_E,
    PRODUCT_HOME_BASIC_N,
    PRODUCT_HOME_PREMIUM,
    PRODUCT_HOME_PREMIUM_E,
    PRODUCT_HOME_PREMIUM_N,
    PRODUCT_HOME_PREMIUM_SERVER,
    PRODUCT_HOME_SERVER,
    PRODUCT_HUBOS,
    PRODUCT_HYPERV,
    PRODUCT_INDUSTRY_HANDHELD,
    PRODUCT_IOTUAP,
    PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT,
    PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING,
    PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY,
    PRODUCT_MULTIPOINT_PREMIUM_SERVER,
    PRODUCT_MULTIPOINT_STANDARD_SERVER,
    PRODUCT_NANO_SERVER,
    PRODUCT_ONECOREUPDATEOS,
    PRODUCT_PPI_PRO,
    PRODUCT_PROFESSIONAL,
    PRODUCT_PROFESSIONAL_E,
    PRODUCT_PROFESSIONAL_EMBEDDED,
    PRODUCT_PROFESSIONAL_N,
    PRODUCT_PROFESSIONAL_S,
    PRODUCT_PROFESSIONAL_STUDENT,
    PRODUCT_PROFESSIONAL_STUDENT_N,
    PRODUCT_PROFESSIONAL_S_N,
    PRODUCT_PROFESSIONAL_WMC,
    PRODUCT_PRO_CHINA,
    PRODUCT_PRO_FOR_EDUCATION,
    PRODUCT_PRO_FOR_EDUCATION_N,
    PRODUCT_PRO_SINGLE_LANGUAGE,
    PRODUCT_PRO_WORKSTATION,
    PRODUCT_PRO_WORKSTATION_N,
    PRODUCT_SB_SOLUTION_SERVER,
    PRODUCT_SB_SOLUTION_SERVER_EM,
    PRODUCT_SERVERRDSH,
    PRODUCT_SERVER_FOR_SB_SOLUTIONS,
    PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM,
    PRODUCT_SERVER_FOR_SMALLBUSINESS,
    PRODUCT_SERVER_FOR_SMALLBUSINESS_V,
    PRODUCT_SERVER_FOUNDATION,
    PRODUCT_SMALLBUSINESS_SERVER,
    PRODUCT_SMALLBUSINESS_SERVER_PREMIUM,
    PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE,
    PRODUCT_SOLUTION_EMBEDDEDSERVER,
    PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE,
    PRODUCT_STANDARD_A_SERVER_CORE,
    PRODUCT_STANDARD_EVALUATION_SERVER,
    PRODUCT_STANDARD_EVALUATION_SERVER_CORE,
    PRODUCT_STANDARD_NANO_SERVER,
    PRODUCT_STANDARD_SERVER,
    PRODUCT_STANDARD_SERVER_CORE,
    PRODUCT_STANDARD_SERVER_CORE_V,
    PRODUCT_STANDARD_SERVER_SOLUTIONS,
    PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE,
    PRODUCT_STANDARD_SERVER_V,
    PRODUCT_STANDARD_WS_SERVER_CORE,
    PRODUCT_STARTER,
    PRODUCT_STARTER_E,
    PRODUCT_STARTER_N,
    PRODUCT_STORAGE_ENTERPRISE_SERVER,
    PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE,
    PRODUCT_STORAGE_EXPRESS_SERVER,
    PRODUCT_STORAGE_EXPRESS_SERVER_CORE,
    PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER,
    PRODUCT_STORAGE_STANDARD_SERVER,
    PRODUCT_STORAGE_STANDARD_SERVER_CORE,
    PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER,
    PRODUCT_STORAGE_WORKGROUP_SERVER,
    PRODUCT_STORAGE_WORKGROUP_SERVER_CORE,
    PRODUCT_THINPC,
    PRODUCT_ULTIMATE,
    PRODUCT_ULTIMATE_E,
    PRODUCT_ULTIMATE_N,
    PRODUCT_UNDEFINED,
    PRODUCT_UNLICENSED,
    PRODUCT_UTILITY_VM,
    PRODUCT_WEB_SERVER,
    PRODUCT_WEB_SERVER_CORE,
    PRTL_BALANCED_NODE,
    PRTL_REFERENCE_COUNT,
    PRTL_REFERENCE_COUNT32,
    PSCHAR,
    PSHORT,
    PSINGLE_LIST_ENTRY,
    PSINGLE_LIST_ENTRY32,
    PSTR,
    PSTRING,
    PSTRING32,
    PSTRING64,
    PSZ,
    PTCH,
    PTCHAR,
    PTIME,
    PTSTR,
    PTUCHAR,
    PUCHAR,
    PUCSCHAR,
    PUCSSTR,
    PULARGE_INTEGER,
    PULONG,
    PULONGLONG,
    PUNICODE_STRING,
    PUNICODE_STRING32,
    PUNICODE_STRING64,
    PUNZTCH,
    PUNZWCH,
    PUQUAD,
    PUSHORT,
    PUTSTR,
    PUUCSCHAR,
    PUUCSSTR,
    PUWSTR,
    PUZZTSTR,
    PUZZWSTR,
    PVOID,
    PVOID64,
    PWCH,
    PWCHAR,
    PWNF_STATE_NAME,
    PWSTR,
    PZPCSTR,
    PZPCWSTR,
    PZPSTR,
    PZPTSTR,
    PZPWSTR,
    PZZSTR,
    PZZTSTR,
    PZZWSTR,
    QUAD,
    RESTRICTED_POINTER,
    RESTRICTED_POINTERPRLIST_ENTRY,
    RTL_BALANCED_NODE,
    RTL_BALANCED_NODE_GET_PARENT_POINTER,
    RTL_BALANCED_NODE_RESERVED_PARENT_MASK,
    RTL_BITS_OF,
    RTL_BITS_OF_FIELD,
    RTL_CONSTANT_OBJECT_ATTRIBUTES,
    RTL_CONSTANT_STRING,
    RTL_CONST_CAST,
    RTL_CONTAINS_FIELD,
    RTL_FIELD_SIZE,
    RTL_FIELD_TYPE,
    RTL_INIT_OBJECT_ATTRIBUTES,
    RTL_NUMBER_OF,
    RTL_NUMBER_OF_FIELD,
    RTL_NUMBER_OF_V1,
    RTL_NUMBER_OF_V2,
    RTL_PADDING_BETWEEN_FIELDS,
    RTL_REFERENCE_COUNT,
    RTL_REFERENCE_COUNT32,
    RTL_SIZEOF_THROUGH_FIELD,
    RTL_STRING_LENGTH_TYPE,
    RotateLeft16,
    RotateLeft32,
    RotateLeft64,
    RotateLeft8,
    RotateRight16,
    RotateRight32,
    RotateRight64,
    RotateRight8,
    SCHAR,
    SECURITY_STATUS,
    SINGLE_LIST_ENTRY,
    SINGLE_LIST_ENTRY32,
    SORTIDFROMLCID,
    SORTVERSIONFROMLCID,
    SORT_CHINESE_BIG5,
    SORT_CHINESE_BOPOMOFO,
    SORT_CHINESE_PRC,
    SORT_CHINESE_PRCP,
    SORT_CHINESE_RADICALSTROKE,
    SORT_CHINESE_UNICODE,
    SORT_DEFAULT,
    SORT_GEORGIAN_MODERN,
    SORT_GEORGIAN_TRADITIONAL,
    SORT_GERMAN_PHONE_BOOK,
    SORT_HUNGARIAN_DEFAULT,
    SORT_HUNGARIAN_TECHNICAL,
    SORT_INVARIANT_MATH,
    SORT_JAPANESE_RADICALSTROKE,
    SORT_JAPANESE_UNICODE,
    SORT_JAPANESE_XJIS,
    SORT_KOREAN_KSC,
    SORT_KOREAN_UNICODE,
    STDAPI,
    STDAPICALLTYPE,
    STDAPIV,
    STDAPIVCALLTYPE,
    STDAPIV_,
    STDAPI_,
    STDMETHODCALLTYPE,
    STDMETHODIMP,
    STDMETHODIMPV,
    STDMETHODIMPV_,
    STDMETHODIMP_,
    STDMETHODVCALLTYPE,
    STDOVERRIDEMETHODIMP,
    STDOVERRIDEMETHODIMPV,
    STDOVERRIDEMETHODIMPV_,
    STDOVERRIDEMETHODIMP_,
    STKFORCEINLINE,
    STRICT,
    STRING,
    STRING32,
    STRING64,
    SUBLANGID,
    SUBLANG_AFRIKAANS_SOUTH_AFRICA,
    SUBLANG_ALBANIAN_ALBANIA,
    SUBLANG_ALSATIAN_FRANCE,
    SUBLANG_AMHARIC_ETHIOPIA,
    SUBLANG_ARABIC_ALGERIA,
    SUBLANG_ARABIC_BAHRAIN,
    SUBLANG_ARABIC_EGYPT,
    SUBLANG_ARABIC_IRAQ,
    SUBLANG_ARABIC_JORDAN,
    SUBLANG_ARABIC_KUWAIT,
    SUBLANG_ARABIC_LEBANON,
    SUBLANG_ARABIC_LIBYA,
    SUBLANG_ARABIC_MOROCCO,
    SUBLANG_ARABIC_OMAN,
    SUBLANG_ARABIC_QATAR,
    SUBLANG_ARABIC_SAUDI_ARABIA,
    SUBLANG_ARABIC_SYRIA,
    SUBLANG_ARABIC_TUNISIA,
    SUBLANG_ARABIC_UAE,
    SUBLANG_ARABIC_YEMEN,
    SUBLANG_ARMENIAN_ARMENIA,
    SUBLANG_ASSAMESE_INDIA,
    SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC,
    SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN,
    SUBLANG_AZERI_CYRILLIC,
    SUBLANG_AZERI_LATIN,
    SUBLANG_BANGLA_BANGLADESH,
    SUBLANG_BANGLA_INDIA,
    SUBLANG_BASHKIR_RUSSIA,
    SUBLANG_BASQUE_BASQUE,
    SUBLANG_BELARUSIAN_BELARUS,
    SUBLANG_BENGALI_BANGLADESH,
    SUBLANG_BENGALI_INDIA,
    SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC,
    SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_BRETON_FRANCE,
    SUBLANG_BULGARIAN_BULGARIA,
    SUBLANG_CATALAN_CATALAN,
    SUBLANG_CENTRAL_KURDISH_IRAQ,
    SUBLANG_CHEROKEE_CHEROKEE,
    SUBLANG_CHINESE_HONGKONG,
    SUBLANG_CHINESE_MACAU,
    SUBLANG_CHINESE_SIMPLIFIED,
    SUBLANG_CHINESE_SINGAPORE,
    SUBLANG_CHINESE_TRADITIONAL,
    SUBLANG_CORSICAN_FRANCE,
    SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_CROATIAN_CROATIA,
    SUBLANG_CUSTOM_DEFAULT,
    SUBLANG_CUSTOM_UNSPECIFIED,
    SUBLANG_CZECH_CZECH_REPUBLIC,
    SUBLANG_DANISH_DENMARK,
    SUBLANG_DARI_AFGHANISTAN,
    SUBLANG_DEFAULT,
    SUBLANG_DIVEHI_MALDIVES,
    SUBLANG_DUTCH,
    SUBLANG_DUTCH_BELGIAN,
    SUBLANG_ENGLISH_AUS,
    SUBLANG_ENGLISH_BELIZE,
    SUBLANG_ENGLISH_CAN,
    SUBLANG_ENGLISH_CARIBBEAN,
    SUBLANG_ENGLISH_EIRE,
    SUBLANG_ENGLISH_INDIA,
    SUBLANG_ENGLISH_JAMAICA,
    SUBLANG_ENGLISH_MALAYSIA,
    SUBLANG_ENGLISH_NZ,
    SUBLANG_ENGLISH_PHILIPPINES,
    SUBLANG_ENGLISH_SINGAPORE,
    SUBLANG_ENGLISH_SOUTH_AFRICA,
    SUBLANG_ENGLISH_TRINIDAD,
    SUBLANG_ENGLISH_UK,
    SUBLANG_ENGLISH_US,
    SUBLANG_ENGLISH_ZIMBABWE,
    SUBLANG_ESTONIAN_ESTONIA,
    SUBLANG_FAEROESE_FAROE_ISLANDS,
    SUBLANG_FILIPINO_PHILIPPINES,
    SUBLANG_FINNISH_FINLAND,
    SUBLANG_FRENCH,
    SUBLANG_FRENCH_BELGIAN,
    SUBLANG_FRENCH_CANADIAN,
    SUBLANG_FRENCH_LUXEMBOURG,
    SUBLANG_FRENCH_MONACO,
    SUBLANG_FRENCH_SWISS,
    SUBLANG_FRISIAN_NETHERLANDS,
    SUBLANG_FULAH_SENEGAL,
    SUBLANG_GALICIAN_GALICIAN,
    SUBLANG_GEORGIAN_GEORGIA,
    SUBLANG_GERMAN,
    SUBLANG_GERMAN_AUSTRIAN,
    SUBLANG_GERMAN_LIECHTENSTEIN,
    SUBLANG_GERMAN_LUXEMBOURG,
    SUBLANG_GERMAN_SWISS,
    SUBLANG_GREEK_GREECE,
    SUBLANG_GREENLANDIC_GREENLAND,
    SUBLANG_GUJARATI_INDIA,
    SUBLANG_HAUSA_NIGERIA_LATIN,
    SUBLANG_HAWAIIAN_US,
    SUBLANG_HEBREW_ISRAEL,
    SUBLANG_HINDI_INDIA,
    SUBLANG_HUNGARIAN_HUNGARY,
    SUBLANG_ICELANDIC_ICELAND,
    SUBLANG_IGBO_NIGERIA,
    SUBLANG_INDONESIAN_INDONESIA,
    SUBLANG_INUKTITUT_CANADA,
    SUBLANG_INUKTITUT_CANADA_LATIN,
    SUBLANG_IRISH_IRELAND,
    SUBLANG_ITALIAN,
    SUBLANG_ITALIAN_SWISS,
    SUBLANG_JAPANESE_JAPAN,
    SUBLANG_KANNADA_INDIA,
    SUBLANG_KASHMIRI_INDIA,
    SUBLANG_KASHMIRI_SASIA,
    SUBLANG_KAZAK_KAZAKHSTAN,
    SUBLANG_KHMER_CAMBODIA,
    SUBLANG_KICHE_GUATEMALA,
    SUBLANG_KINYARWANDA_RWANDA,
    SUBLANG_KONKANI_INDIA,
    SUBLANG_KOREAN,
    SUBLANG_KYRGYZ_KYRGYZSTAN,
    SUBLANG_LAO_LAO,
    SUBLANG_LATVIAN_LATVIA,
    SUBLANG_LITHUANIAN,
    SUBLANG_LOWER_SORBIAN_GERMANY,
    SUBLANG_LUXEMBOURGISH_LUXEMBOURG,
    SUBLANG_MACEDONIAN_MACEDONIA,
    SUBLANG_MALAYALAM_INDIA,
    SUBLANG_MALAY_BRUNEI_DARUSSALAM,
    SUBLANG_MALAY_MALAYSIA,
    SUBLANG_MALTESE_MALTA,
    SUBLANG_MAORI_NEW_ZEALAND,
    SUBLANG_MAPUDUNGUN_CHILE,
    SUBLANG_MARATHI_INDIA,
    SUBLANG_MOHAWK_MOHAWK,
    SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA,
    SUBLANG_MONGOLIAN_PRC,
    SUBLANG_NEPALI_INDIA,
    SUBLANG_NEPALI_NEPAL,
    SUBLANG_NEUTRAL,
    SUBLANG_NORWEGIAN_BOKMAL,
    SUBLANG_NORWEGIAN_NYNORSK,
    SUBLANG_OCCITAN_FRANCE,
    SUBLANG_ODIA_INDIA,
    SUBLANG_ORIYA_INDIA,
    SUBLANG_PASHTO_AFGHANISTAN,
    SUBLANG_PERSIAN_IRAN,
    SUBLANG_POLISH_POLAND,
    SUBLANG_PORTUGUESE,
    SUBLANG_PORTUGUESE_BRAZILIAN,
    SUBLANG_PULAR_SENEGAL,
    SUBLANG_PUNJABI_INDIA,
    SUBLANG_PUNJABI_PAKISTAN,
    SUBLANG_QUECHUA_BOLIVIA,
    SUBLANG_QUECHUA_ECUADOR,
    SUBLANG_QUECHUA_PERU,
    SUBLANG_ROMANIAN_ROMANIA,
    SUBLANG_ROMANSH_SWITZERLAND,
    SUBLANG_RUSSIAN_RUSSIA,
    SUBLANG_SAKHA_RUSSIA,
    SUBLANG_SAMI_INARI_FINLAND,
    SUBLANG_SAMI_LULE_NORWAY,
    SUBLANG_SAMI_LULE_SWEDEN,
    SUBLANG_SAMI_NORTHERN_FINLAND,
    SUBLANG_SAMI_NORTHERN_NORWAY,
    SUBLANG_SAMI_NORTHERN_SWEDEN,
    SUBLANG_SAMI_SKOLT_FINLAND,
    SUBLANG_SAMI_SOUTHERN_NORWAY,
    SUBLANG_SAMI_SOUTHERN_SWEDEN,
    SUBLANG_SANSKRIT_INDIA,
    SUBLANG_SCOTTISH_GAELIC,
    SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC,
    SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_SERBIAN_CROATIA,
    SUBLANG_SERBIAN_CYRILLIC,
    SUBLANG_SERBIAN_LATIN,
    SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC,
    SUBLANG_SERBIAN_MONTENEGRO_LATIN,
    SUBLANG_SERBIAN_SERBIA_CYRILLIC,
    SUBLANG_SERBIAN_SERBIA_LATIN,
    SUBLANG_SINDHI_AFGHANISTAN,
    SUBLANG_SINDHI_INDIA,
    SUBLANG_SINDHI_PAKISTAN,
    SUBLANG_SINHALESE_SRI_LANKA,
    SUBLANG_SLOVAK_SLOVAKIA,
    SUBLANG_SLOVENIAN_SLOVENIA,
    SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA,
    SUBLANG_SPANISH,
    SUBLANG_SPANISH_ARGENTINA,
    SUBLANG_SPANISH_BOLIVIA,
    SUBLANG_SPANISH_CHILE,
    SUBLANG_SPANISH_COLOMBIA,
    SUBLANG_SPANISH_COSTA_RICA,
    SUBLANG_SPANISH_DOMINICAN_REPUBLIC,
    SUBLANG_SPANISH_ECUADOR,
    SUBLANG_SPANISH_EL_SALVADOR,
    SUBLANG_SPANISH_GUATEMALA,
    SUBLANG_SPANISH_HONDURAS,
    SUBLANG_SPANISH_MEXICAN,
    SUBLANG_SPANISH_MODERN,
    SUBLANG_SPANISH_NICARAGUA,
    SUBLANG_SPANISH_PANAMA,
    SUBLANG_SPANISH_PARAGUAY,
    SUBLANG_SPANISH_PERU,
    SUBLANG_SPANISH_PUERTO_RICO,
    SUBLANG_SPANISH_URUGUAY,
    SUBLANG_SPANISH_US,
    SUBLANG_SPANISH_VENEZUELA,
    SUBLANG_SWAHILI_KENYA,
    SUBLANG_SWEDISH,
    SUBLANG_SWEDISH_FINLAND,
    SUBLANG_SYRIAC_SYRIA,
    SUBLANG_SYS_DEFAULT,
    SUBLANG_TAJIK_TAJIKISTAN,
    SUBLANG_TAMAZIGHT_ALGERIA_LATIN,
    SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH,
    SUBLANG_TAMIL_INDIA,
    SUBLANG_TAMIL_SRI_LANKA,
    SUBLANG_TATAR_RUSSIA,
    SUBLANG_TELUGU_INDIA,
    SUBLANG_THAI_THAILAND,
    SUBLANG_TIBETAN_PRC,
    SUBLANG_TIGRIGNA_ERITREA,
    SUBLANG_TIGRINYA_ERITREA,
    SUBLANG_TIGRINYA_ETHIOPIA,
    SUBLANG_TSWANA_BOTSWANA,
    SUBLANG_TSWANA_SOUTH_AFRICA,
    SUBLANG_TURKISH_TURKEY,
    SUBLANG_TURKMEN_TURKMENISTAN,
    SUBLANG_UIGHUR_PRC,
    SUBLANG_UI_CUSTOM_DEFAULT,
    SUBLANG_UKRAINIAN_UKRAINE,
    SUBLANG_UPPER_SORBIAN_GERMANY,
    SUBLANG_URDU_INDIA,
    SUBLANG_URDU_PAKISTAN,
    SUBLANG_UZBEK_CYRILLIC,
    SUBLANG_UZBEK_LATIN,
    SUBLANG_VALENCIAN_VALENCIA,
    SUBLANG_VIETNAMESE_VIETNAM,
    SUBLANG_WELSH_UNITED_KINGDOM,
    SUBLANG_WOLOF_SENEGAL,
    SUBLANG_XHOSA_SOUTH_AFRICA,
    SUBLANG_YAKUT_RUSSIA,
    SUBLANG_YI_PRC,
    SUBLANG_YORUBA_NIGERIA,
    SUBLANG_ZULU_SOUTH_AFRICA,
    SUITE_TYPE,
    SYSTEM_CACHE_ALIGNMENT_SIZE,
    TCHAR,
    TEXT,
    TIME,
    TIMER_TYPE,
    TRUE,
    TUCHAR,
    TYPE_ALIGNMENT,
    UCHAR,
    UCSCHAR,
    UCSCHAR_INVALID_CHARACTER,
    UFIELD_OFFSET,
    UInt32x32To64,
    ULARGE_INTEGER,
    ULONGLONG,
    UNALIGNED,
    UNALIGNED64,
    UNICODE_NULL,
    UNICODE_STRING,
    UNICODE_STRING32,
    UNICODE_STRING64,
    UNICODE_STRING_MAX_BYTES,
    UNICODE_STRING_MAX_CHARS,
    UNREFERENCED_PARAMETER,
    UQUAD,
    USHORT,
    USN,
    VER_SERVER_NT,
    VER_SUITE_BACKOFFICE,
    VER_SUITE_BLADE,
    VER_SUITE_COMMUNICATIONS,
    VER_SUITE_COMPUTE_SERVER,
    VER_SUITE_DATACENTER,
    VER_SUITE_EMBEDDEDNT,
    VER_SUITE_EMBEDDED_RESTRICTED,
    VER_SUITE_ENTERPRISE,
    VER_SUITE_MULTIUSERTS,
    VER_SUITE_PERSONAL,
    VER_SUITE_SECURITY_APPLIANCE,
    VER_SUITE_SINGLEUSERTS,
    VER_SUITE_SMALLBUSINESS,
    VER_SUITE_SMALLBUSINESS_RESTRICTED,
    VER_SUITE_STORAGE_SERVER,
    VER_SUITE_TERMINAL,
    VER_SUITE_WH_SERVER,
    VER_WORKSTATION_NT,
    WAIT_TYPE,
    WCHAR,
    WNF_STATE_NAME,
    _ARRAYSIZE,
    _CSTRING,
    _ENUM_FLAG_CONSTEXPR,
    _EVENT_TYPE,
    _FLOAT128,
    _GROUP_AFFINITY,
    _LARGE_INTEGER,
    _LIST_ENTRY,
    _LUID,
    _NT_PRODUCT_TYPE,
    _OBJECTID,
    _OBJECT_ATTRIBUTES,
    _OBJECT_ATTRIBUTES32,
    _OBJECT_ATTRIBUTES64,
    _PROCESSOR_NUMBER,
    _QUAD,
    _RTL_BALANCED_NODE,
    _RTL_CONSTANT_STRING_remove_const_macro,
    _SINGLE_LIST_ENTRY,
    _SINGLE_LIST_ENTRY32,
    _STRING,
    _STRING32,
    _STRING64,
    _SUITE_TYPE,
    _TIME,
    _TIMER_TYPE,
    _ULARGE_INTEGER,
    _UNICODE_STRING,
    _WAIT_TYPE,
    _WNF_STATE_NAME,
    __TEXT,
    max,
    min,
)


SPHANDLE = POINTER(HANDLE)
LPHANDLE = POINTER(HANDLE)

HKEY = POINTER(VOID)
PHKEY = POINTER(HKEY)

HMODULE = POINTER(VOID)
HINSTANCE = POINTER(VOID)
HTASK = POINTER(VOID)
HDESK = POINTER(VOID)
HMF = POINTER(VOID)
HEMF = POINTER(VOID)
HPEN = POINTER(VOID)
HRSRC = POINTER(VOID)
HSTR = POINTER(VOID)
HWINSTA = POINTER(VOID)
HKL = POINTER(VOID)
HGDIOBJ = POINTER(VOID)
HACCEL = POINTER(VOID)
HBITMAP = POINTER(VOID)
HBRUSH = POINTER(VOID)
HCOLORSPACE = POINTER(VOID)
HCONV = POINTER(VOID)
HCONVLIST = POINTER(VOID)
HICON = POINTER(VOID)
HCURSOR = POINTER(VOID)
HDC = POINTER(VOID)
HDDEDATA = POINTER(VOID)
HDROP = POINTER(VOID)
HENHMETAFILE = POINTER(VOID)
HFONT = POINTER(VOID)
HGLOBAL = POINTER(VOID)
HHOOK = POINTER(VOID)
HLOCAL = POINTER(VOID)
HMENU = POINTER(VOID)
HMETAFILE = POINTER(VOID)
HMONITOR = POINTER(VOID)
HPALETTE = POINTER(VOID)
HRGN = POINTER(VOID)
HSZ = POINTER(VOID)
HWND = POINTER(VOID)
SERVICE_STATUS_HANDLE = POINTER(VOID)
HDWP = POINTER(VOID)
HSPRITE = POINTER(VOID)
HLSURF = POINTER(VOID)
HGLRC = POINTER(VOID)
HWINEVENTHOOK = POINTER(VOID)
HUMPD = POINTER(VOID)
GLOBALHANDLE = POINTER(VOID)
LOCALHANDLE = POINTER(VOID)
SC_HANDLE = POINTER(VOID)
HCONTEXT = POINTER(VOID)

HANDLE_PTR = UINT64
SHANDLE_PTR = INT64


SPOINTER_32 = POINTER_SIGNED
UPOINTER_32 = UINT32
POINTER_64_INT = UINT64

COLORREF = DWORD
LPCOLORREF = POINTER(DWORD)

LCTYPE = DWORD
LGRPID = DWORD

QWORD = UINT64
SC_LOCK = LPVOID


class tagRECT(ctypes.Structure):
    _fields_ = [
        ('left', LONG),
        ('top', LONG),
        ('right', LONG),
        ('bottom', LONG),
    ]


RECT = tagRECT
PRECT = POINTER(tagRECT)
LPRECT = POINTER(tagRECT)
LPCRECT = POINTER(RECT)
NPRECT = POINTER(tagRECT)


class _RECTL(ctypes.Structure):
    _fields_ = [
        ('left', LONG),
        ('top', LONG),
        ('right', LONG),
        ('bottom', LONG),
    ]


RECTL = _RECTL
PRECTL = POINTER(_RECTL)
LPRECTL = POINTER(_RECTL)
LPCRECTL = POINTER(RECTL)


class tagPOINT(ctypes.Structure):
    _fields_ = [
        ('x', LONG),
        ('y', LONG),
    ]


POINT = tagPOINT
PPOINT = POINTER(tagPOINT)
LPPOINT = POINTER(tagPOINT)
NPPOINT = POINTER(tagPOINT)


class _POINTL(ctypes.Structure):
    _fields_ = [
        ('x', LONG),
        ('y', LONG),
    ]


POINTL = _POINTL
PPOINTL = POINTER(_POINTL)


class tagSIZE(ctypes.Structure):
    _fields_ = [
        ('cx', LONG),
        ('cy', LONG),
    ]


SIZE = tagSIZE
PSIZE = POINTER(tagSIZE)
LPSIZE = POINTER(tagSIZE)


class tagSIZEL(ctypes.Structure):
    _fields_ = [
        ('cx', LONG),
        ('cy', LONG),
    ]


SIZEL = tagSIZEL
PSIZEL = POINTER(tagSIZEL)
LPSIZEL = POINTER(tagSIZEL)


class tagPOINTS(ctypes.Structure):
    _fields_ = [
        ('x', SHORT),
        ('y', SHORT),
        ('y', SHORT),
        ('x', SHORT),
    ]


POINTS = tagPOINTS
PPOINTS = POINTER(tagPOINTS)
LPPOINTS = POINTER(tagPOINTS)


from .guiddef_h import (
    GUID as _GUID,
    GUID_NULL as _GUID_NULL,
    LPGUID as _LPGUID,
    LPCGUID as _LPCGUID,
    IID as _IID,
    LPIID as _LPIID,
    IID_NULL as _IID_NULL,
    CLSID as _CLSID,
    LPCLSID as _LPCLSID,
    CLSID_NULL as _CLSID_NULL,
    FMTID as _FMTID,
    LPFMTID as _LPFMTID,
    FMTID_NULL as _FMTID_NULL,
    REFGUID as _REFGUID,
    REFIID as _REFIID,
    REFCLSID as _REFCLSID,
    REFFMTID as _REFFMTID
) # NOQA


GUID = _GUID
GUID_NULL = _GUID_NULL
LPGUID = _LPGUID
LPCGUID = _LPCGUID
IID = _IID
LPIID = _LPIID
IID_NULL = _IID_NULL
CLSID = _CLSID
LPCLSID = _LPCLSID
CLSID_NULL = _CLSID_NULL
FMTID = _FMTID
LPFMTID = _LPFMTID
FMTID_NULL = _FMTID_NULL
REFGUID = _REFGUID
REFIID = _REFIID
REFCLSID = _REFCLSID
REFFMTID = _REFFMTID


LPUINT = POINTER(UINT)
LPUINT32 = POINTER(UINT32)
HNSTIME = LONGLONG
REFERENCE_TIME = LONGLONG
LPREFERENCE_TIME = POINTER(REFERENCE_TIME)
LPUINT64 = POINTER(UINT64)
LPFLOAT = POINTER(FLOAT)

MFTIME = LONGLONG
FLOAT32 = FLOAT
FLOAT64 = DOUBLE


from .wtypesbase_h import (
    APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU,
    APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP,
    APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY,
    APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY,
    APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION,
    APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN,
    APPIDREGFLAGS_RESERVED1,
    APPIDREGFLAGS_RESERVED2,
    APPIDREGFLAGS_RESERVED3,
    APPIDREGFLAGS_RESERVED4,
    APPIDREGFLAGS_RESERVED5,
    APPIDREGFLAGS_RESERVED7,
    APPIDREGFLAGS_RESERVED8,
    APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND,
    CLSCTX_VALID_MASK,
    DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL,
    DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES,
    DCOMSCM_PING_DISALLOW_UNSECURE_CALL,
    DCOMSCM_PING_USE_MID_AUTHNSERVICE,
    DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL,
    DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES,
    OLECHAR,
    PACL,
    PSCODE,
    PSECURITY_DESCRIPTOR_CONTROL,
    PSID,
    ROTREGFLAGS_ALLOWANYCLIENT,
    SCODE,
    SECURITY_DESCRIPTOR_CONTROL,
    UP_BYTE_BLOB,
    BYTE_BLOB,
    DWORD_BLOB,
    FLAGGED_BYTE_BLOB,
    FLAGGED_WORD_BLOB,
    UP_DWORD_BLOB,
    UP_FLAGGED_BYTE_BLOB,
    UP_FLAGGED_WORD_BLOB,
    UP_WORD_BLOB,
    tagBLOB,
    tagCLSCTX,
    tagMEMCTX,
    tagMSHCTX,
    tagMSHLFLAGS,
    SECURITY_DESCRIPTOR,
    SECURITY_ATTRIBUTES,
    SID,
    COAUTHIDENTITY,
    WORD_BLOB,
    COAUTHINFO,
    SYSTEMTIME,
    ACL,
    BLOB,
    HYPER_SIZEDARR,
    SHORT_SIZEDARR,
    LONG_SIZEDARR,
    WORD_SIZEDARR,
    DWORD_SIZEDARR,
    BYTE_SIZEDARR,
    SID_IDENTIFIER_AUTHORITY,
    FILETIME,
    SID_AND_ATTRIBUTES,
    PFILETIME,
    LPFILETIME,
    ULONG
)# NOQA


class tagRemHGLOBAL(ctypes.Structure):
    _fields_ = [
        ('fNullHGlobal', LONG),
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHGLOBAL = tagRemHGLOBAL


class tagRemHMETAFILEPICT(ctypes.Structure):
    _fields_ = [
        ('mm', LONG),
        ('xExt', LONG),
        ('yExt', LONG),
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHMETAFILEPICT = tagRemHMETAFILEPICT


class tagRemHENHMETAFILE(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHENHMETAFILE = tagRemHENHMETAFILE


class tagRemHBITMAP(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHBITMAP = tagRemHBITMAP


class tagRemHPALETTE(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHPALETTE = tagRemHPALETTE


class tagRemBRUSH(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHBRUSH = tagRemBRUSH


class tagPALETTEENTRY(ctypes.Structure):
    _fields_ = [
        ('peRed', BYTE),
        ('peGreen', BYTE),
        ('peBlue', BYTE),
        ('peFlags', BYTE),
    ]


PALETTEENTRY = tagPALETTEENTRY
PPALETTEENTRY = POINTER(tagPALETTEENTRY)
LPPALETTEENTRY = POINTER(tagPALETTEENTRY)


class tagLOGPALETTE(ctypes.Structure):
    _fields_ = [
        ('palVersion', WORD),
        ('palNumEntries', WORD),
        ('palPalEntry', PALETTEENTRY * 1),
    ]


LOGPALETTE = tagLOGPALETTE
PLOGPALETTE = POINTER(tagLOGPALETTE)
LPLOGPALETTE = POINTER(tagLOGPALETTE)


ROTFLAGS_REGISTRATIONKEEPSALIVE = 0x1
ROTFLAGS_ALLOWANYCLIENT = 0x2
ROT_COMPARE_MAX = 0x800


class tagDVASPECT(ENUM):
    DVASPECT_CONTENT = 1
    DVASPECT_THUMBNAIL = 2
    DVASPECT_ICON = 4
    DVASPECT_DOCPRINT = 8


DVASPECT = tagDVASPECT


class tagSTGC(ENUM):
    STGC_DEFAULT = 0
    STGC_OVERWRITE = 1
    STGC_ONLYIFCURRENT = 2
    STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE = 4
    STGC_CONSOLIDATE = 8


STGC = tagSTGC


class tagSTGMOVE(ENUM):
    STGMOVE_MOVE = 0
    STGMOVE_COPY = 1
    STGMOVE_SHALLOWCOPY = 2


STGMOVE = tagSTGMOVE


class tagSTATFLAG(ENUM):
    STATFLAG_DEFAULT = 0
    STATFLAG_NONAME = 1
    STATFLAG_NOOPEN = 2


STATFLAG = tagSTATFLAG


WDT_INPROC_CALL = 0x48746457
WDT_REMOTE_CALL = 0x52746457
WDT_INPROC64_CALL = 0x50746457


class _userCLIPFORMAT(ctypes.Structure):

    class __MIDL_IWinTypes_0001(ctypes.Union):
        _fields_ = [
            ('dwValue', DWORD),
            ('pwszName', POINTER(WCHAR)),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0001),
    ]


userCLIPFORMAT = _userCLIPFORMAT
wireCLIPFORMAT = POINTER(userCLIPFORMAT)

CLIPFORMAT = WORD


class _GDI_NONREMOTE(ctypes.Structure):

    class __MIDL_IWinTypes_0002(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(DWORD_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0002),
    ]


GDI_NONREMOTE = _GDI_NONREMOTE


class _userHGLOBAL(ctypes.Structure):

    class __MIDL_IWinTypes_0003(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(FLAGGED_BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0003),
    ]


userHGLOBAL = _userHGLOBAL
wireHGLOBAL = POINTER(userHGLOBAL)


class _userHMETAFILE(ctypes.Structure):

    class __MIDL_IWinTypes_0004(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0004),
    ]


userHMETAFILE = _userHMETAFILE


class _remoteMETAFILEPICT(ctypes.Structure):
    _fields_ = [
        ('mm', LONG),
        ('xExt', LONG),
        ('yExt', LONG),
        ('hMF', POINTER(userHMETAFILE)),
    ]


remoteMETAFILEPICT = _remoteMETAFILEPICT


class _userHMETAFILEPICT(ctypes.Structure):

    class __MIDL_IWinTypes_0005(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(remoteMETAFILEPICT)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0005),
    ]


userHMETAFILEPICT = _userHMETAFILEPICT


class _userHENHMETAFILE(ctypes.Structure):

    class __MIDL_IWinTypes_0006(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0006),
    ]


userHENHMETAFILE = _userHENHMETAFILE


class _userBITMAP(ctypes.Structure):
    _fields_ = [
        ('bmType', LONG),
        ('bmWidth', LONG),
        ('bmHeight', LONG),
        ('bmWidthBytes', LONG),
        ('bmPlanes', WORD),
        ('bmBitsPixel', WORD),
        ('cbSize', ULONG),
        ('pBuffer', BYTE * 1),
    ]


userBITMAP = _userBITMAP


class _userHBITMAP(ctypes.Structure):

    class __MIDL_IWinTypes_0007(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(userBITMAP)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0007),
    ]


userHBITMAP = _userHBITMAP


class _userHPALETTE(ctypes.Structure):

    class __MIDL_IWinTypes_0008(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(LOGPALETTE)),
            ('hInproc64', INT64),
        ]


    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0008),
    ]


userHPALETTE = _userHPALETTE


class _RemotableHandle(ctypes.Structure):

    class __MIDL_IWinTypes_0009(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', LONG),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0009),
    ]


RemotableHandle = _RemotableHandle


wireHWND = POINTER(RemotableHandle)
wireHMENU = POINTER(RemotableHandle)
wireHACCEL = POINTER(RemotableHandle)
wireHBRUSH = POINTER(RemotableHandle)
wireHFONT = POINTER(RemotableHandle)
wireHDC = POINTER(RemotableHandle)
wireHICON = POINTER(RemotableHandle)
wireHRGN = POINTER(RemotableHandle)
wireHMONITOR = POINTER(RemotableHandle)


class tagTEXTMETRICW(ctypes.Structure):
    _fields_ = [
        ('tmHeight', LONG),
        ('tmAscent', LONG),
        ('tmDescent', LONG),
        ('tmInternalLeading', LONG),
        ('tmExternalLeading', LONG),
        ('tmAveCharWidth', LONG),
        ('tmMaxCharWidth', LONG),
        ('tmWeight', LONG),
        ('tmOverhang', LONG),
        ('tmDigitizedAspectX', LONG),
        ('tmDigitizedAspectY', LONG),
        ('tmFirstChar', WCHAR),
        ('tmLastChar', WCHAR),
        ('tmDefaultChar', WCHAR),
        ('tmBreakChar', WCHAR),
        ('tmItalic', BYTE),
        ('tmUnderlined', BYTE),
        ('tmStruckOut', BYTE),
        ('tmPitchAndFamily', BYTE),
        ('tmCharSet', BYTE),
    ]


TEXTMETRICW = tagTEXTMETRICW


PTEXTMETRICW = POINTER(tagTEXTMETRICW)
LPTEXTMETRICW = POINTER(tagTEXTMETRICW)


class tagMSG(ctypes.Structure):
    _fields_ = [
        ('hwnd', HWND),
        ('message', UINT),
        ('wParam', WPARAM),
        ('lParam', LPARAM),
        ('time', DWORD),
        ('pt', POINT),
    ]


MSG = tagMSG


PMSG = POINTER(tagMSG)
NPMSG = POINTER(tagMSG)
LPMSG = POINTER(tagMSG)

wireHBITMAP = POINTER(VOID)
wireHPALETTE = POINTER(VOID)
wireHENHMETAFILE = POINTER(VOID)
wireHMETAFILE = POINTER(VOID)
wireHMETAFILEPICT = POINTER(VOID)

HMETAFILEPICT = POINTER(VOID)

DATE = DOUBLE


class tagCY(ctypes.Union):

    class DUMMYSTRUCTNAME(ctypes.Structure):
        _fields_ = [
            ('Lo', ULONG),
            ('Hi', LONG),
        ]

    _fields_ = [
        ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
        ('INT64', LONGLONG),
    ]


CY = tagCY
LPCY = POINTER(CY)


class tagDEC(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        class DUMMYSTRUCTNAME(ctypes.Structure):
            _fields_ = [
                ('scale', BYTE),
                ('sign', BYTE),
            ]

        _fields_ = [
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
            ('signscale', USHORT),
        ]

    class DUMMYUNIONNAME2(ctypes.Union):

        class DUMMYSTRUCTNAME2(ctypes.Structure):
            _fields_ = [
                ('Lo32', ULONG),
                ('Mid32', ULONG),
            ]

        _fields_ = [
            ('DUMMYSTRUCTNAME2', DUMMYSTRUCTNAME2),
            ('Lo64', ULONGLONG),
        ]

    _fields_ = [
        ('wReserved', USHORT),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('Hi32', ULONG),
        ('DUMMYUNIONNAME2', DUMMYUNIONNAME2),
    ]


DECIMAL = tagDEC

DECIMAL_NEG = 0x80


def DECIMAL_SETZERO(dec):
    dec.Lo64 = 0
    dec.Hi32 = 0
    dec.signscale = 0
    return dec


LPDECIMAL = POINTER(DECIMAL)

wireBSTR = POINTER(FLAGGED_WORD_BLOB)

BSTR = POINTER(OLECHAR)
LPBSTR = POINTER(BSTR)

_VARIANT_BOOL = VARIANT_BOOL


class tagBSTRBLOB(ctypes.Structure):
    _fields_ = [
        ('cbSize', ULONG),
        ('pData', POINTER(BYTE)),
    ]


BSTRBLOB = tagBSTRBLOB
LPBSTRBLOB = POINTER(tagBSTRBLOB)

VARIANT_TRUE = -1
VARIANT_FALSE = 0


class tagCLIPDATA(ctypes.Structure):
    _fields_ = [
        ('cbSize', ULONG),
        ('ulClipFmt', LONG),
        ('pClipData', POINTER(BYTE)),
    ]


CLIPDATA = tagCLIPDATA


def CBPCLIPDATA(clipdata):
    return clipdata.cbSize - ctypes.sizeof(clipdata.ulClipFmt)


VARTYPE = USHORT
# * VARENUM usage key,
# *
# * * [V] - may appear in a VARIANT
# * * [T] - may appear in a TYPEDESC
# * * [P] - may appear in an OLE property set
# * * [S] - may appear in a Safe Array
# *
# *
# *  VT_EMPTY            [V]   [P]     nothing
# *  VT_NULL             [V]   [P]     SQL style Null
# *  VT_I2               [V][T][P][S]  2 byte INT
# *  VT_I4               [V][T][P][S]  4 byte INT
# *  VT_R4               [V][T][P][S]  4 byte real
# *  VT_R8               [V][T][P][S]  8 byte real
# *  VT_CY               [V][T][P][S]  currency
# *  VT_DATE             [V][T][P][S]  date
# *  VT_BSTR             [V][T][P][S]  OLE Automation string
# *  VT_DISPATCH         [V][T]   [S]  IDispatch *
# *  VT_ERROR            [V][T][P][S]  SCODE
# *  VT_BOOL             [V][T][P][S]  True=-1, False=0
# *  VT_VARIANT          [V][T][P][S]  VARIANT *
# *  VT_UNKNOWN          [V][T]   [S]  IUnknown *
# *  VT_DECIMAL          [V][T]   [S]  16 byte fixed poINT
# *  VT_RECORD           [V]   [P][S]  user defined type
# *  VT_I1               [V][T][P][s]  INT CHAR
# *  VT_UI1              [V][T][P][S]  UINT CHAR
# *  VT_UI2              [V][T][P][S]  UINT SHORT
# *  VT_UI4              [V][T][P][S]  ULONG
# *  VT_I8                  [T][P]     INT 64-bit INT
# *  VT_UI8                 [T][P]     UINT 64-bit INT
# *  VT_INT              [V][T][P][S]  INT machine INT
# *  VT_UINT             [V][T]   [S]  UINT machine INT
# *  VT_INT_PTR             [T]        INT machine register size width
# *  VT_UINT_PTR            [T]        UINT machine register size width
# *  VT_VOID                [T]        C style VOID
# *  VT_HRESULT             [T]        Standard return type
# *  VT_PTR                 [T]        poINTer type
# *  VT_SAFEARRAY           [T]        (use VT_ARRAY in VARIANT)
# *  VT_CARRAY              [T]        C style array
# *  VT_USERDEFINED         [T]        user defined type
# *  VT_LPSTR               [T][P]     null terminated string
# *  VT_LPWSTR              [T][P]     wide null terminated string
# *  VT_FILETIME               [P]     FILETIME
# *  VT_BLOB                   [P]     Length prefixed bytes
# *  VT_STREAM                 [P]     Name of the stream follows
# *  VT_STORAGE                [P]     Name of the storage follows
# *  VT_STREAMED_OBJECT        [P]     Stream contains an object
# *  VT_STORED_OBJECT          [P]     Storage contains an object
# *  VT_VERSIONED_STREAM       [P]     Stream with a GUID version
# *  VT_BLOB_OBJECT            [P]     Blob contains an object
# *  VT_CF                     [P]     Clipboard format
# *  VT_CLSID                  [P]     A Class ID
# *  VT_VECTOR                 [P]     simple counted array
# *  VT_ARRAY            [V]           SAFEARRAY*
# *  VT_BYREF            [V]           VOID* for local use
# *  VT_BSTR_BLOB                      Reserved for system use


class VARENUM(ENUM):
    VT_EMPTY = 0
    VT_NULL = 1
    VT_I2 = 2
    VT_I4 = 3
    VT_R4 = 4
    VT_R8 = 5
    VT_CY = 6
    VT_DATE = 7
    VT_BSTR = 8
    VT_DISPATCH = 9
    VT_ERROR = 10
    VT_BOOL = 11
    VT_VARIANT = 12
    VT_UNKNOWN = 13
    VT_DECIMAL = 14
    VT_I1 = 16
    VT_UI1 = 17
    VT_UI2 = 18
    VT_UI4 = 19
    VT_I8 = 20
    VT_UI8 = 21
    VT_INT = 22
    VT_UINT = 23
    VT_VOID = 24
    VT_HRESULT = 25
    VT_PTR = 26
    VT_SAFEARRAY = 27
    VT_CARRAY = 28
    VT_USERDEFINED = 29
    VT_LPSTR = 30
    VT_LPWSTR = 31
    VT_RECORD = 36
    VT_INT_PTR = 37
    VT_UINT_PTR = 38
    VT_FILETIME = 64
    VT_BLOB = 65
    VT_STREAM = 66
    VT_STORAGE = 67
    VT_STREAMED_OBJECT = 68
    VT_STORED_OBJECT = 69
    VT_BLOB_OBJECT = 70
    VT_CF = 71
    VT_CLSID = 72
    VT_VERSIONED_STREAM = 73
    VT_BSTR_BLOB = 0xfff
    VT_VECTOR = 0x1000
    VT_ARRAY = 0x2000
    VT_BYREF = 0x4000
    VT_RESERVED = 0x8000
    VT_ILLEGAL = 0xffff
    VT_ILLEGALMASKED = 0xfff
    VT_TYPEMASK = 0xfff


PROPID = ULONG


class _tagpropertykey(ctypes.Structure):
    _fields_ = [
        ('fmtid', GUID),
        ('pid', DWORD),
    ]


PROPERTYKEY = _tagpropertykey


class tagCSPLATFORM(ctypes.Structure):
    _fields_ = [
        ('dwPlatformId', DWORD),
        ('dwVersionHi', DWORD),
        ('dwVersionLo', DWORD),
        ('dwProcessorArch', DWORD),
    ]


CSPLATFORM = tagCSPLATFORM


class tagQUERYCONTEXT(ctypes.Structure):
    _fields_ = [
        ('dwContext', DWORD),
        ('Platform', CSPLATFORM),
        ('Locale', LCID),
        ('dwVersionHi', DWORD),
        ('dwVersionLo', DWORD),
    ]


QUERYCONTEXT = tagQUERYCONTEXT


class tagTYSPEC(ENUM):
    TYSPEC_CLSID = 0
    TYSPEC_FILEEXT = TYSPEC_CLSID + 1
    TYSPEC_MIMETYPE = TYSPEC_FILEEXT + 1
    TYSPEC_FILENAME = TYSPEC_MIMETYPE + 1
    TYSPEC_PROGID = TYSPEC_FILENAME + 1
    TYSPEC_PACKAGENAME = TYSPEC_PROGID + 1
    TYSPEC_OBJECTID = TYSPEC_PACKAGENAME + 1


TYSPEC = tagTYSPEC


class __MIDL___MIDL_itf_wtypes_0000_0001_0001(ctypes.Structure):
    class __MIDL___MIDL_itf_wtypes_0000_0001_0005(ctypes.Union):

        class ByName(ctypes.Structure):
            _fields_ = [
                ('pPackageName', LPOLESTR),
                ('PolicyId', GUID),
            ]

        class ByObjectId(ctypes.Structure):
            _fields_ = [
                ('ObjectId', GUID),
                ('PolicyId', GUID),
            ]

        _fields_ = [
            ('ByName', ByName),
            ('ByObjectId', ByObjectId),
            ('clsid', CLSID),
            ('pFileExt', LPOLESTR),
            ('pMimeType', LPOLESTR),
            ('pProgId', LPOLESTR),
            ('pFileName', LPOLESTR)
        ]

    _fields_ = [
        ('tyspec', DWORD),
        ('tagged_union', __MIDL___MIDL_itf_wtypes_0000_0001_0005),
    ]


uCLSSPEC = __MIDL___MIDL_itf_wtypes_0000_0001_0001


def _wcsicmp(s1, s2):
    if isinstance(s1, bytes):
        s1 = s1.decode('utf-8')

    if isinstance(s2, bytes):
        s2 = s2.decode('utf-8')

    try:
        if isinstance(s1, unicode):
            s1 = s1.decode('utf-8')

        if isinstance(s2, unicode):
            s2 = s2.decode('utf-8')
    except:
        pass

    res = 0

    s1 = list(s1)
    s2 = list(s2)

    for i, char in enumerate(s1):
        sc1 = ord(char)
        if len(s2) > 1:
            sc2 = ord(s2[i])
        else:
            sc2 = 0
        res += sc1 - sc2

    if len(s2) > len(s1):
        for char in s2[:len(s1) - 1]:
            res -= ord(char)

    return res


__all__ = (
    'SUBLANG_ITALIAN_SWISS', 'RTL_PADDING_BETWEEN_FIELDS', 'VER_SUITE_BLADE',
    'TEXT', 'RTL_NUMBER_OF_V1', 'LANG_AFRIKAANS', 'LANG_CENTRAL_KURDISH',
    'SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN', 'LANG_ROMANIAN', 'SORTIDFROMLCID',
    'PRODUCT_DATACENTER_SERVER_CORE_V', 'MINSHORT', 'SUBLANG_LATVIAN_LATVIA',
    'SUBLANG_VIETNAMESE_VIETNAM', 'DECLSPEC_CHPE_GUEST', 'RotateRight16',
    'PRODUCT_SERVERRDSH', 'LANG_TAJIK', 'SUBLANG_DEFAULT', 'LANG_OCCITAN',
    'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN', 'SUBLANG_ARABIC_YEMEN', 'max',
    'SUBLANG_MALAYALAM_INDIA', 'SUBLANG_CORSICAN_FRANCE', 'SUBLANGID', 'TIME',
    'PRODUCT_SERVER_FOR_SMALLBUSINESS_V', 'SUBLANG_ARABIC_JORDAN', 'C_ASSERT',
    'LANG_FINNISH', 'SUBLANG_FRENCH_SWISS', 'RTL_NUMBER_OF_V2', 'LANG_AZERI',
    'PRODUCT_EMBEDDED_E_EVAL', 'PRODUCT_STANDARD_SERVER_V', 'PRODUCT_CLOUDN',
    'SUBLANG_ARABIC_TUNISIA', 'SUBLANG_ENGLISH_INDIA', 'SUBLANG_ENGLISH_US',
    'SUBLANG_KASHMIRI_INDIA', 'ANYSIZE_ARRAY', 'SUBLANG_ARABIC_IRAQ', 'CONST',
    'PRODUCT_STANDARD_EVALUATION_SERVER', 'PRODUCT_EDUCATION', 'RTL_BITS_OF',
    'STKFORCEINLINE', 'UInt32x32To64', 'PRODUCT_EMBEDDED_E', 'LANG_ESTONIAN',
    'PRODUCT_EMBEDDED_A', 'RTL_CONSTANT_OBJECT_ATTRIBUTES', 'RotateLeft32',
    'LOCALE_CUSTOM_UI_DEFAULT', 'SUBLANG_FULAH_SENEGAL', 'DECLSPEC_NOVTABLE',
    'SUBLANG_KOREAN', 'SUBLANG_NEPALI_INDIA', 'LANG_GREEK', 'LANG_GEORGIAN',
    'SUBLANG_CHINESE_HONGKONG', 'SUBLANG_BELARUSIAN_BELARUS', 'LANG_ZULU',
    'STDOVERRIDEMETHODIMPV_', 'SUBLANG_GERMAN_SWISS', 'SORT_GEORGIAN_MODERN',
    'PRODUCT_SMALLBUSINESS_SERVER_PREMIUM', 'SUBLANG_ENGLISH_JAMAICA', 'TRUE',
    'PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY', 'DECLSPEC_ALIGN', '_ARRAYSIZE',
    'SUBLANG_TAMAZIGHT_ALGERIA_LATIN', 'SUBLANG_SPANISH_BOLIVIA', 'ARRAYSIZE',
    'PRODUCT_CLUSTER_SERVER_V', 'SORT_CHINESE_PRCP', 'NT_WARNING', 'MAKELCID',
    'SUBLANG_SAMI_NORTHERN_SWEDEN', 'PRODUCT_PROFESSIONAL_STUDENT', 'NULL64',
    'DBG_UNREFERENCED_PARAMETER', 'SUBLANG_ZULU_SOUTH_AFRICA', 'LANG_KAZAK',
    'NT_INFORMATION', 'PRODUCT_PROFESSIONAL_N', 'LANG_YAKUT', 'LANG_ROMANSH',
    'MAXIMUM_PROC_PER_GROUP', 'SUBLANG_SPANISH', 'SUBLANG_MONGOLIAN_PRC',
    'PRODUCT_ENTERPRISE_SERVER_CORE', 'PRODUCT_STANDARD_A_SERVER_CORE', 'min',
    'PRODUCT_EMBEDDED_INDUSTRY_E', 'PRODUCT_EMBEDDED_INDUSTRY_A', 'LANG_THAI',
    'DEFINE_ENUM_FLAG_OPERATORS', 'SUBLANG_SCOTTISH_GAELIC', 'LANG_DUTCH',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC', 'SUBLANG_SYS_DEFAULT', 'NULL',
    'LANG_ICELANDIC', 'IFACEMETHODIMPV_', 'RTL_CONSTANT_STRING', 'LANG_TAMIL',
    'SUBLANG_TAMIL_SRI_LANKA', 'SUBLANG_GEORGIAN_GEORGIA', 'SUBLANG_SWEDISH',
    'PRODUCT_WEB_SERVER_CORE', 'VER_SUITE_EMBEDDEDNT', 'PROBE_ALIGNMENT32',
    'SUBLANG_SPANISH_COSTA_RICA', 'PRODUCT_STORAGE_ENTERPRISE_SERVER', 'LUID',
    'SUBLANG_SPANISH_GUATEMALA', 'SUBLANG_GERMAN', 'LANG_DANISH', '_TIME',
    'SUBLANG_HUNGARIAN_HUNGARY', 'LANG_CROATIAN', 'SUBLANG_TIGRINYA_ERITREA',
    'LANG_BASHKIR', 'PRODUCT_CORE_CONNECTED_N', 'LANG_FILIPINO', 'LANG_CZECH',
    'Int32x32To64', 'OBJ_OPENLINK', 'SUBLANG_CHINESE_SIMPLIFIED', 'LANG_LAO',
    'SUBLANG_ENGLISH_MALAYSIA', 'PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE', 'PCH',
    'SORT_CHINESE_PRC', 'LANG_CATALAN', 'SUBLANG_SPANISH_ECUADOR', 'FASTCALL',
    'COMPILETIME_OR_2FLAGS', 'PRODUCT_AZURE_SERVER_CORE', 'DECLSPEC_IMPORT',
    'SUBLANG_DUTCH_BELGIAN', 'PRODUCT_CORE_N', 'HighTime', 'LANG_ARABIC',
    'ALL_PROCESSOR_GROUPS', 'SUBLANG_SPANISH_URUGUAY', 'PTIME', 'LANG_MOHAWK',
    'UNICODE_STRING_MAX_CHARS', 'LANG_TIGRIGNA', 'SUBLANG_TAJIK_TAJIKISTAN',
    'SUBLANG_PORTUGUESE', 'PRIMARYLANGID', 'UFIELD_OFFSET', 'LANG_PULAR',
    'LOCALE_SYSTEM_DEFAULT', 'SUBLANG_DANISH_DENMARK', 'LANG_AZERBAIJANI',
    'SUBLANG_CATALAN_CATALAN', 'COMPILETIME_OR_5FLAGS', 'RTL_BITS_OF_FIELD',
    'PRODUCT_PROFESSIONAL_STUDENT_N', 'SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA',
    'SUBLANG_ALBANIAN_ALBANIA', 'PRODUCT_HOLOGRAPHIC', 'STRICT', 'FALSE',
    'VER_SUITE_BACKOFFICE', 'LANG_MALTESE', 'LANG_QUECHUA', 'LANG_TURKISH',
    'STDAPICALLTYPE', 'SUBLANG_FAEROESE_FAROE_ISLANDS', 'VER_SUITE_WH_SERVER',
    'SUBLANG_SPANISH_VENEZUELA', 'COMPILETIME_OR_3FLAGS', 'FIELD_OFFSET',
    'SUBLANG_HEBREW_ISRAEL', 'SUBLANG_UZBEK_CYRILLIC', 'LANG_NEPALI', 'NTAPI',
    'PRODUCT_DATACENTER_NANO_SERVER', 'SUBLANG_PORTUGUESE_BRAZILIAN', 'LP',
    'PRODUCT_EMBEDDED_INDUSTRY_EVAL', 'SUBLANG_SPANISH_ARGENTINA', 'STDAPIV_',
    'PRODUCT_STANDARD_EVALUATION_SERVER_CORE', 'LANG_KANNADA', 'LANG_FRENCH',
    'PRODUCT_ENTERPRISE_S_EVALUATION', 'SUBLANG_SPANISH_US', 'LANG_CHEROKEE',
    'SUBLANG_CUSTOM_UNSPECIFIED', 'STDOVERRIDEMETHODIMP_', 'LANG_NEUTRAL',
    'SUBLANG_FRENCH_LUXEMBOURG', 'VER_SUITE_DATACENTER', 'LANG_MARATHI',
    'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC', 'DECLSPEC_NORETURN', 'USN',
    'SUBLANG_GERMAN_LUXEMBOURG', 'SUBLANG_ROMANIAN_ROMANIA', 'DECLSPEC_UUID',
    'PRODUCT_ENTERPRISEG', 'SUBLANG_SAMI_NORTHERN_FINLAND', 'MAKELANGID',
    'SUBLANG_ORIYA_INDIA', 'SUBLANG_ENGLISH_UK', 'SUBLANG_INUKTITUT_CANADA',
    'SUBLANG_SWEDISH_FINLAND', 'COMPILETIME_OR_6FLAGS', 'PRODUCT_ANDROMEDA',
    'SUBLANG_BULGARIAN_BULGARIA', 'SUBLANG_TSWANA_SOUTH_AFRICA', 'OBJ_OPENIF',
    'PRODUCT_CORE_CONNECTED', 'PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC',
    'Int64ShrlMod32', 'PRODUCT_STANDARD_SERVER', 'LANG_TIBETAN', 'LANG_SOTHO',
    'SUBLANG_IRISH_IRELAND', 'SUBLANG_SERBIAN_CYRILLIC', 'LANG_YORUBA', 'PSZ',
    'LANG_ALSATIAN', 'LANG_ASSAMESE', 'OBJ_DONT_REPARSE', 'PRODUCT_CLOUD',
    'SUBLANG_TATAR_RUSSIA', 'InitializeObjectAttributes', 'OBJ_KERNEL_HANDLE',
    'ERROR_SEVERITY_ERROR', 'OBJ_FORCE_ACCESS_CHECK', 'DECLSPEC_CACHEALIGN',
    'ERROR_SEVERITY_WARNING', 'DECLSPEC_CHPE_PATCHABLE', 'LANG_BOSNIAN',
    'PRODUCT_CORE_COUNTRYSPECIFIC', 'SUBLANG_ICELANDIC_ICELAND', 'MAXLONG',
    'PRODUCT_ENTERPRISE_SERVER', 'SUBLANG_CUSTOM_DEFAULT', 'PFORCEINLINE',
    'ERROR_SEVERITY_INFORMATIONAL', 'SUBLANG_SLOVAK_SLOVAKIA', 'MIN_UCSCHAR',
    'SUBLANG_SAMI_SKOLT_FINLAND', 'SUBLANG_YORUBA_NIGERIA', 'PROBE_ALIGNMENT',
    'PRODUCT_PROFESSIONAL', 'STDMETHODVCALLTYPE', 'SORT_GERMAN_PHONE_BOOK',
    'SUBLANG_SPANISH_COLOMBIA', 'SUBLANG_BENGALI_BANGLADESH', 'STDMETHODIMP_',
    'SUBLANG_ENGLISH_ZIMBABWE', 'VER_SUITE_SINGLEUSERTS', 'LANG_MONGOLIAN',
    'SUBLANG_FINNISH_FINLAND', 'LANG_LOWER_SORBIAN', 'SUBLANG_KONKANI_INDIA',
    'PRODUCT_ENTERPRISE_S_N_EVALUATION', 'PRODUCT_EMBEDDED_AUTOMOTIVE', 'ACL',
    'SUBLANG_SPANISH_PARAGUAY', 'SUBLANG_BENGALI_INDIA', 'LANG_SINDHI', 'FAR',
    'SUBLANG_ARABIC_SAUDI_ARABIA', 'SUBLANG_SERBIAN_SERBIA_CYRILLIC', '_LUID',
    'LANG_HUNGARIAN', 'SUBLANG_MAORI_NEW_ZEALAND', 'LANG_LUXEMBOURGISH',
    'SUBLANG_POLISH_POLAND', 'SORT_DEFAULT', 'PRODUCT_PROFESSIONAL_E', 'QUAD',
    'MAKESORTLCID', 'SUBLANG_HAWAIIAN_US', 'RTL_NUMBER_OF_FIELD', 'UNALIGNED',
    'LANG_ITALIAN', 'OBJ_INHERIT', 'PRODUCT_EMBEDDED', 'LANG_KYRGYZ', '_QUAD',
    'SUBLANG_MOHAWK_MOHAWK', 'PRODUCT_PROFESSIONAL_S', 'STDMETHODIMPV', 'HDC',
    'RTL_SIZEOF_THROUGH_FIELD', 'OBJ_CASE_INSENSITIVE', 'MAXIMUM_PROCESSORS',
    'OBJ_EXCLUSIVE', 'PRODUCT_DATACENTER_WS_SERVER_CORE', 'RTL_NUMBER_OF',
    'SORT_HUNGARIAN_DEFAULT', 'SUBLANG_SINHALESE_SRI_LANKA', 'Int64ShllMod32',
    'LANG_GUJARATI', 'PRODUCT_CORE_CONNECTED_SINGLELANGUAGE', 'NOP_FUNCTION',
    'PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER', 'LANG_RUSSIAN', 'STDAPI',
    'SUBLANG_SAMI_SOUTHERN_SWEDEN', 'SUBLANG_CZECH_CZECH_REPUBLIC', 'LANG_YI',
    'SUBLANG_THAI_THAILAND', 'MAXULONG', 'SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH',
    'SORT_KOREAN_UNICODE', 'SUBLANG_FILIPINO_PHILIPPINES', 'LANG_CHINESE',
    'SUBLANG_ENGLISH_NZ', 'PRODUCT_ENTERPRISE_SUBSCRIPTION_N', 'LANG_URDU',
    'PRODUCT_EMBEDDED_INDUSTRY', 'SUBLANG_SPANISH_MODERN', 'Int64ShraMod32',
    'LOCALE_USER_DEFAULT', 'PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE', '__TEXT',
    'ARGUMENT_PRESENT', 'SUBLANG_ENGLISH_SOUTH_AFRICA', 'SUBLANG_ODIA_INDIA',
    'OBJ_HANDLE_TAGBITS', 'VER_WORKSTATION_NT', 'ANSI_NULL', 'LANG_KHMER',
    'SUBLANG_CENTRAL_KURDISH_IRAQ', 'SUBLANG_SANSKRIT_INDIA', 'LANG_HINDI',
    'PRODUCT_PRO_SINGLE_LANGUAGE', '_ENUM_FLAG_CONSTEXPR', 'RTL_CONST_CAST',
    'CONTAINING_RECORD', 'VER_SUITE_SMALLBUSINESS_RESTRICTED', 'LANG_FULAH',
    'SORT_INVARIANT_MATH', 'PRODUCT_PRO_FOR_EDUCATION', 'SUBLANG_ENGLISH_CAN',
    'PRODUCT_HOME_PREMIUM_N', 'SUBLANG_SINDHI_PAKISTAN', 'STDAPIVCALLTYPE',
    'SUBLANG_GREENLANDIC_GREENLAND', 'PRODUCT_HOME_PREMIUM_E', 'LANG_BANGLA',
    'SUBLANG_SERBIAN_MONTENEGRO_LATIN', 'SUBLANG_GUJARATI_INDIA', 'NT_ERROR',
    'PRODUCT_STORAGE_WORKGROUP_SERVER_CORE', 'SUBLANG_ARABIC_QATAR', 'STRING',
    'SUBLANG_SPANISH_PUERTO_RICO', 'SUBLANG_SLOVENIAN_SLOVENIA', 'LANG_WOLOF',
    'PRAGMA_DEPRECATED_DDK', 'SUBLANG_ENGLISH_AUS', 'SUBLANG_DUTCH', 'PLUID',
    'SUBLANG_TURKISH_TURKEY', 'SUBLANG_FRENCH', 'SUBLANG_URDU_PAKISTAN',
    'LANG_LITHUANIAN', 'LANG_USER_DEFAULT', 'SUBLANG_ARABIC_LEBANON', 'PCCH',
    'SUBLANG_BANGLA_INDIA', 'DECLARE_CONST_UNICODE_STRING', 'LANG_PORTUGUESE',
    'SUBLANG_KYRGYZ_KYRGYZSTAN', 'PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM', 'PSTR',
    'SUBLANG_WELSH_UNITED_KINGDOM', 'SORT_HUNGARIAN_TECHNICAL', 'RotateLeft8',
    'LANG_BULGARIAN', 'LOCALE_NEUTRAL', 'UCSCHAR_INVALID_CHARACTER', 'PLCID',
    'SUBLANG_KHMER_CAMBODIA', 'LANG_ORIYA', 'SUBLANG_NORWEGIAN_NYNORSK',
    'SORT_CHINESE_RADICALSTROKE', 'SUBLANG_BASHKIR_RUSSIA', 'LANG_KOREAN',
    'SUBLANG_PUNJABI_INDIA', 'RTL_FIELD_SIZE', 'SUBLANG_XHOSA_SOUTH_AFRICA',
    'STDMETHODCALLTYPE', 'PRODUCT_ENTERPRISE_S', 'SUBLANG_SAMI_INARI_FINLAND',
    'PRODUCT_ENTERPRISE_N', 'PRODUCT_ENTERPRISE_E', 'LOCALE_UNASSIGNED_LCID',
    'PRODUCT_SERVER_FOR_SMALLBUSINESS', 'SUBLANG_UZBEK_LATIN', 'LANG_POLISH',
    'SUBLANG_KINYARWANDA_RWANDA', '_RTL_CONSTANT_STRING_remove_const_macro',
    'SUBLANG_GERMAN_AUSTRIAN', 'SUBLANG_UIGHUR_PRC', 'PRODUCT_HOME_BASIC',
    'DBG_UNREFERENCED_LOCAL_VARIABLE', 'PRODUCT_PRO_WORKSTATION_N', 'STDAPI_',
    'SUBLANG_RUSSIAN_RUSSIA', 'PRODUCT_ENTERPRISEGN', 'UNALIGNED64', 'SCHAR',
    'SUBLANG_CROATIAN_CROATIA', 'SUBLANG_ARABIC_LIBYA', 'LANG_BELARUSIAN',
    'PRODUCT_HOME_SERVER', 'SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN', 'HKL',
    'SUBLANG_CHEROKEE_CHEROKEE', 'SUBLANG_ARABIC_OMAN', 'PRODUCT_UNLICENSED',
    'PRODUCT_PROFESSIONAL_WMC', 'PRODUCT_SB_SOLUTION_SERVER', 'LANG_SYRIAC',
    'COMPILETIME_OR_4FLAGS', 'MAXSHORT', 'PRODUCT_ENTERPRISE_SERVER_CORE_V',
    'PRODUCT_STORAGE_STANDARD_SERVER_CORE', 'LANG_HAWAIIAN', 'LANG_MANIPURI',
    'SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC', 'PRODUCT_ENTERPRISE_SERVER_V',
    'LOCALE_CUSTOM_UNSPECIFIED', 'MAXUCHAR', 'LANG_TURKMEN', 'LANG_WELSH',
    'PRODUCT_PRO_FOR_EDUCATION_N', 'LANG_INDONESIAN', 'PRODUCT_HOME_PREMIUM',
    'SYSTEM_CACHE_ALIGNMENT_SIZE', 'SUBLANG_SPANISH_CHILE', 'STDMETHODIMPV_',
    'PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING', 'SORT_JAPANESE_XJIS', 'LPCWCH',
    'PRODUCT_PROFESSIONAL_EMBEDDED', 'SUBLANG_GERMAN_LIECHTENSTEIN', 'PNZCH',
    'SUBLANG_ARABIC_ALGERIA', 'PRODUCT_DATACENTER_EVALUATION_SERVER', 'PCWCH',
    'DECLSPEC_GUARDIGNORE', 'SUBLANG_AMHARIC_ETHIOPIA', 'SUBLANG_LAO_LAO',
    'LANG_IRISH', 'LANG_KICHE', 'SUBLANG_YAKUT_RUSSIA', 'RTL_CONTAINS_FIELD',
    'PRODUCT_PROFESSIONAL_S_N', 'DEFAULT_UNREACHABLE', 'SUBLANG_IGBO_NIGERIA',
    'SORT_JAPANESE_RADICALSTROKE', 'STDOVERRIDEMETHODIMPV', 'LANG_XHOSA',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL', 'PRODUCT_DATACENTER_SERVER',
    'SUBLANG_ASSAMESE_INDIA', 'PRODUCT_ONECOREUPDATEOS', 'TYPE_ALIGNMENT',
    'LANG_SLOVENIAN', 'NLS_VALID_LOCALE_MASK', 'SUBLANG_QUECHUA_PERU', 'LPCH',
    'SUBLANG_SAMI_SOUTHERN_NORWAY', 'SORTVERSIONFROMLCID', 'PRODUCT_IOTUAP',
    'PRODUCT_EMBEDDED_INDUSTRY_A_E', 'LANG_BOSNIAN_NEUTRAL', 'LANG_UZBEK',
    'LANG_SCOTTISH_GAELIC', 'SUBLANG_SPANISH_NICARAGUA', 'LANG_SERBIAN',
    'PRODUCT_STANDARD_WS_SERVER_CORE', 'OBJ_IGNORE_IMPERSONATED_DEVICEMAP',
    'SUBLANG_ARABIC_MOROCCO', 'SUBLANG_SPANISH_PANAMA', 'LANG_DARI', 'PUCHAR',
    'SUBLANG_ARABIC_EGYPT', 'PRODUCT_ENTERPRISE_N_EVALUATION', 'MAXCHAR',
    'LANG_MACEDONIAN', 'DUMMYUNIONNAME', 'OBJ_VALID_ATTRIBUTES', 'LANG_TATAR',
    'SUBLANG_SINDHI_INDIA', 'LANG_KINYARWANDA', 'SUBLANG_PASHTO_AFGHANISTAN',
    'LANG_TELUGU', 'SUBLANG_MALTESE_MALTA', 'SUBLANG_SINDHI_AFGHANISTAN',
    'PRODUCT_STORAGE_EXPRESS_SERVER_CORE', 'SUBLANG_ITALIAN', 'LANG_ARMENIAN',
    'PRODUCT_EMBEDDED_INDUSTRY_E_EVAL', 'SUBLANG_AZERI_LATIN', 'LANG_GERMAN',
    'SUBLANG_ENGLISH_PHILIPPINES', 'PRODUCT_BUSINESS_N', 'SUBLANG_NEUTRAL',
    'SUBLANG_KASHMIRI_SASIA', 'STDOVERRIDEMETHODIMP', 'LANG_ALBANIAN', 'PCSZ',
    'PRODUCT_CLOUD_STORAGE_SERVER', 'MEMORY_ALLOCATION_ALIGNMENT', 'MINLONG',
    'SUBLANG_ARABIC_KUWAIT', 'PRODUCT_STANDARD_SERVER_CORE_V', 'RotateLeft64',
    'SUBLANG_ENGLISH_CARIBBEAN', 'SORT_GEORGIAN_TRADITIONAL', 'LANG_GALICIAN',
    'PRODUCT_MULTIPOINT_STANDARD_SERVER', 'LANG_GREENLANDIC', 'LANG_KASHMIRI',
    'PRODUCT_PRO_WORKSTATION', 'RESTRICTED_POINTER', 'SUBLANG_HINDI_INDIA',
    'RTL_INIT_OBJECT_ATTRIBUTES', 'PRODUCT_INDUSTRY_HANDHELD', 'LANG_SAMI',
    'PRODUCT_STANDARD_SERVER_SOLUTIONS', 'PRODUCT_BUSINESS', 'LANG_TIGRINYA',
    'PRODUCT_ENTERPRISE_EVALUATION', 'PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT',
    'SUBLANG_SAKHA_RUSSIA', 'SUBLANG_ROMANSH_SWITZERLAND', 'IFACEMETHODIMP_',
    'SUBLANG_QUECHUA_BOLIVIA', 'SUBLANG_QUECHUA_ECUADOR', 'IFACEMETHODIMPV',
    'SUBLANG_CHINESE_MACAU', 'SUBLANG_KAZAK_KAZAKHSTAN', 'PRODUCT_ULTIMATE_N',
    'PRODUCT_AZURE_NANO_SERVER', 'PRODUCT_STANDARD_SERVER_CORE', 'LANG_MALAY',
    'VER_SUITE_EMBEDDED_RESTRICTED', 'SUBLANG_SPANISH_HONDURAS', 'NT_SUCCESS',
    'VER_SUITE_SMALLBUSINESS', 'PRODUCT_MULTIPOINT_PREMIUM_SERVER', 'LowTime',
    'PRODUCT_STANDARD_NANO_SERVER', 'SUBLANG_UPPER_SORBIAN_GERMANY', 'PNZWCH',
    'PRODUCT_CONNECTED_CAR', 'SUBLANG_ALSATIAN_FRANCE', 'SUBLANG_YI_PRC',
    'PRODUCT_DATACENTER_EVALUATION_SERVER_CORE', 'SUBLANG_CHINESE_SINGAPORE',
    'LOCALE_CUSTOM_DEFAULT', 'SUBLANG_ENGLISH_SINGAPORE', 'LANG_TSWANA',
    'PRODUCT_ULTIMATE_E', 'LANG_CHINESE_TRADITIONAL', 'LANG_AMHARIC', 'UQUAD',
    'LANG_KONKANI', 'SUBLANG_PERSIAN_IRAN', 'SUBLANG_UI_CUSTOM_DEFAULT',
    'SUBLANG_ARABIC_BAHRAIN', 'LANG_VALENCIAN', 'SUBLANG_SPANISH_EL_SALVADOR',
    'LANGIDFROMLCID', 'RotateLeft16', 'SUBLANG_ENGLISH_TRINIDAD', 'NTSYSAPI',
    'PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE', 'SUBLANG_SYRIAC_SYRIA', 'LPWCH',
    'RTL_FIELD_TYPE', 'PRODUCT_PPI_PRO', 'SUBLANG_OCCITAN_FRANCE', 'STDAPIV',
    'SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC', 'SUBLANG_TIBETAN_PRC', 'LANG_IGBO',
    'LANG_SYSTEM_DEFAULT', 'PRODUCT_ARM64_SERVER', 'SUBLANG_PULAR_SENEGAL',
    'SUBLANG_SPANISH_MEXICAN', 'PRODUCT_ULTIMATE', 'LANG_NORWEGIAN', 'PCCHAR',
    'SUBLANG_MARATHI_INDIA', 'PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE',
    'LANG_LATVIAN', 'PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER', 'MAXUSHORT',
    'LANG_MAPUDUNGUN', 'PRODUCT_NANO_SERVER', 'LANG_SANSKRIT', 'PRODUCT_CORE',
    'RTL_BALANCED_NODE_RESERVED_PARENT_MASK', 'SUBLANG_HAUSA_NIGERIA_LATIN',
    'SUBLANG_MAPUDUNGUN_CHILE', 'VER_SUITE_ENTERPRISE', 'NTSYSCALLAPI', 'HMF',
    'LOCALE_TRANSIENT_KEYBOARD4', 'RTL_BALANCED_NODE_GET_PARENT_POINTER',
    'PRODUCT_WEB_SERVER', 'SUBLANG_SWAHILI_KENYA', 'PRODUCT_UNDEFINED', 'INT',
    'SUBLANG_GREEK_GREECE', 'SUBLANG_ESTONIAN_ESTONIA', 'PRODUCT_STARTER_N',
    'LANG_SERBIAN_NEUTRAL', 'PRODUCT_ENTERPRISE_SERVER_IA64', 'RotateRight8',
    'PRODUCT_STARTER_E', 'PRODUCT_ENTERPRISE_SUBSCRIPTION', 'LANG_SWEDISH',
    'SUBLANG_ENGLISH_EIRE', 'LANG_FRISIAN', 'DECLSPEC_SELECTANY', 'LANG_ODIA',
    'LANG_MALAYALAM', 'LANG_BRETON', 'LANG_HAUSA', 'PRODUCT_CORE_ARM', 'PWCH',
    'DECLARE_UNICODE_STRING_SIZE', 'DECLSPEC_GUARDNOCF', 'PRODUCT_STARTER',
    'SUBLANG_GALICIAN_GALICIAN', 'PRODUCT_EMBEDDED_EVAL', 'DECLARE_HANDLE',
    'LOCALE_TRANSIENT_KEYBOARD2', 'SUBLANG_FRENCH_CANADIAN', 'MINCHAR', 'SID',
    'DECLSPEC_DEPRECATED', 'SUBLANG_ARABIC_UAE', 'SUBLANG_NORWEGIAN_BOKMAL',
    'LOCALE_INVARIANT', 'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN', 'CLONG',
    'LANG_FAEROESE', 'LANG_SPANISH', 'STDMETHODIMP', 'VER_SERVER_NT', 'PTCH',
    'PRODUCT_DATACENTER_SERVER_V', 'SORT_KOREAN_KSC', 'LANG_SAKHA', 'CSTRING',
    'LOCALE_TRANSIENT_KEYBOARD3', 'PRODUCT_SERVER_FOR_SB_SOLUTIONS', 'PTCHAR',
    'LOCALE_TRANSIENT_KEYBOARD1', 'SUBLANG_FRENCH_BELGIAN', 'LANG_UIGHUR',
    'DECLSPEC_NOINLINE', 'DECLSPEC_SAFEBUFFERS', 'SUBLANG_TAMIL_INDIA', 'far',
    'VER_SUITE_PERSONAL', 'SUBLANG_WOLOF_SENEGAL', 'SUBLANG_FRENCH_MONACO',
    'VER_SUITE_COMMUNICATIONS', 'SUBLANG_TIGRINYA_ETHIOPIA', 'MAXLONGLONG',
    'SUBLANG_INUKTITUT_CANADA_LATIN', 'LANG_BENGALI', 'PRODUCT_HOME_BASIC_E',
    'UNICODE_STRING_MAX_BYTES', 'APPLICATION_ERROR_MASK', 'LANG_PUNJABI',
    'PRODUCT_CORE_SINGLELANGUAGE', 'LOCALE_NAME_MAX_LENGTH', 'LANG_JAPANESE',
    'SUBLANG_CHINESE_TRADITIONAL', 'SORT_CHINESE_BIG5', 'DECLSPEC_ADDRSAFE',
    'PRODUCT_HOME_BASIC_N', 'SUBLANG_SPANISH_DOMINICAN_REPUBLIC', 'WAIT_TYPE',
    'SUBLANG_PUNJABI_PAKISTAN', 'LANG_SINHALESE', 'DECLSPEC_GUARD_SUPPRESS',
    'SUBLANG_INDONESIAN_INDONESIA', 'PRODUCT_SOLUTION_EMBEDDEDSERVER', 'LCID',
    'PRODUCT_CLUSTER_SERVER', 'SUBLANG_LITHUANIAN', 'VER_SUITE_MULTIUSERTS',
    'SORT_JAPANESE_UNICODE', 'SUBLANG_BASQUE_BASQUE', 'PRODUCT_HUBOS', 'ATOM',
    'SUBLANG_BANGLA_BANGLADESH', 'VER_SUITE_STORAGE_SERVER', 'PRODUCT_HYPERV',
    'SUBLANG_SPANISH_PERU', 'SUBLANG_SAMI_LULE_SWEDEN', 'PRODUCT_ENTERPRISE',
    'PRODUCT_ENTERPRISE_S_N', 'PRODUCT_SMALLBUSINESS_SERVER', 'LANG_PERSIAN',
    'SUBLANG_NEPALI_NEPAL', 'UNREFERENCED_PARAMETER', 'SUBLANG_TELUGU_INDIA',
    'SUBLANG_MALAY_BRUNEI_DARUSSALAM', 'LANG_MAORI', 'PRODUCT_PRO_CHINA',
    'VER_SUITE_SECURITY_APPLIANCE', 'PRODUCT_HOME_PREMIUM_SERVER', 'STRING32',
    'SUBLANG_AFRIKAANS_SOUTH_AFRICA', 'SUBLANG_SERBIAN_LATIN', 'LANG_FARSI',
    'LANG_VIETNAMESE', 'PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT', '_CSTRING',
    'NTAPI_INLINE', 'SUBLANG_KANNADA_INDIA', 'LANG_INVARIANT', 'CFORCEINLINE',
    'SUBLANG_LOWER_SORBIAN_GERMANY', 'SUBLANG_FRISIAN_NETHERLANDS', '_STRING',
    'SUBLANG_AZERI_CYRILLIC', 'LANG_SWAHILI', 'VER_SUITE_COMPUTE_SERVER',
    'FORCEINLINE', 'LANG_ENGLISH', 'SUBLANG_ARABIC_SYRIA', 'LANG_HEBREW',
    'SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA', 'MAX_UCSCHAR', 'LANG_BASQUE',
    'MAX_NATURAL_ALIGNMENT', 'SUBLANG_TSWANA_BOTSWANA', 'RotateRight64',
    'SUBLANG_DIVEHI_MALDIVES', 'LANG_DIVEHI', 'SUBLANG_KICHE_GUATEMALA',
    'PRODUCT_STORAGE_WORKGROUP_SERVER', 'PRODUCT_STORAGE_STANDARD_SERVER',
    'SUBLANG_URDU_INDIA', 'SUBLANG_TIGRIGNA_ERITREA', 'UNICODE_NULL', 'TCHAR',
    'LANG_UKRAINIAN', 'PRODUCT_UTILITY_VM', 'SUBLANG_DARI_AFGHANISTAN', 'SID',
    'SORT_CHINESE_BOPOMOFO', 'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC',
    'LANG_UPPER_SORBIAN', 'DECLARE_GLOBAL_CONST_UNICODE_STRING', 'EVENT_TYPE',
    'SUBLANG_LUXEMBOURGISH_LUXEMBOURG', 'IFACEMETHODIMP', 'PRODUCT_THINPC',
    'LANG_TAMAZIGHT', 'PRODUCT_DATACENTER_SERVER_CORE', 'LANG_PASHTO', 'BOOL',
    'SUBLANG_BRETON_FRANCE', 'SUBLANG_TURKMEN_TURKMENISTAN', 'OBJ_PERMANENT',
    'PRODUCT_DATACENTER_A_SERVER_CORE', 'PRODUCT_SB_SOLUTION_SERVER_EM',
    'SUBLANG_ARMENIAN_ARMENIA', 'SUBLANG_UKRAINIAN_UKRAINE', 'LANG_INUKTITUT',
    'PRODUCT_SERVER_FOUNDATION', 'DECLSPEC_DEPRECATED_DDK', 'LANG_SLOVAK',
    'SUBLANG_JAPANESE_JAPAN', 'SUBLANG_SAMI_LULE_NORWAY', 'RotateRight32',
    'SUBLANG_ENGLISH_BELIZE', 'SORT_CHINESE_UNICODE', 'PRODUCT_EDUCATION_N',
    'PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC', 'ERROR_SEVERITY_SUCCESS', 'ACL',
    'SUBLANG_MALAY_MALAYSIA', 'SUBLANG_VALENCIAN_VALENCIA', 'LANG_CORSICAN',
    'SUBLANG_SERBIAN_SERBIA_LATIN', 'SUBLANG_MACEDONIAN_MACEDONIA', 'PUSHORT',
    'LANG_CHINESE_SIMPLIFIED', 'PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER',
    'SUBLANG_SERBIAN_CROATIA', 'VER_SUITE_TERMINAL', 'DECLSPEC_NOTHROW',
    'PRODUCT_STORAGE_EXPRESS_SERVER', 'SUBLANG_SAMI_NORTHERN_NORWAY', 'KIRQL',
    '_NT_PRODUCT_TYPE', 'COMPARTMENT_ID', 'SUITE_TYPE', '_EVENT_TYPE', 'BSTR',
    '_TIMER_TYPE', 'TIMER_TYPE', '_WAIT_TYPE', 'NT_PRODUCT_TYPE', '_OBJECTID',
    'PCOMPARTMENT_ID', 'PNT_PRODUCT_TYPE', '_SUITE_TYPE', 'OBJECT_ATTRIBUTES',
    'PLIST_ENTRY', '_OBJECT_ATTRIBUTES32', 'OBJECT_ATTRIBUTES64', '_STRING32',
    'LARGE_INTEGER', 'LIST_ENTRY64', 'PSINGLE_LIST_ENTRY32', 'UNICODE_STRING',
    'PROCESSOR_NUMBER', 'PSINGLE_LIST_ENTRY', '_SINGLE_LIST_ENTRY32', 'PCTCH',
    'RTL_BALANCED_NODE', 'GROUP_AFFINITY', 'PWNF_STATE_NAME', 'STRING64',
    '_UNICODE_STRING', 'PCWNF_STATE_NAME', '_OBJECT_ATTRIBUTES64', 'OBJECTID',
    'PRTL_BALANCED_NODE', '_RTL_BALANCED_NODE', '_WNF_STATE_NAME', 'FLOAT128',
    '_FLOAT128', 'RESTRICTED_POINTERPRLIST_ENTRY', '_SINGLE_LIST_ENTRY',
    'OBJECT_ATTRIBUTES32', '_PROCESSOR_NUMBER', 'PPROCESSOR_NUMBER', 'LPCTCH',
    'SINGLE_LIST_ENTRY32', '_GROUP_AFFINITY', 'WNF_STATE_NAME', '_LIST_ENTRY',
    '_OBJECT_ATTRIBUTES', 'LIST_ENTRY32', 'SINGLE_LIST_ENTRY', '_STRING64',
    '_LARGE_INTEGER', '_ULARGE_INTEGER', 'ULARGE_INTEGER', 'PGROUP_AFFINITY',
    'LIST_ENTRY', 'PCOBJECT_ATTRIBUTES', 'PCUCSCHAR', 'PCZPCWSTR', 'PUZZWSTR',
    'POBJECT_ATTRIBUTES64', 'PLIST_ENTRY64', 'UNICODE_STRING64', 'PUCSCHAR',
    'PUNICODE_STRING', 'RTL_REFERENCE_COUNT', 'PLARGE_INTEGER', 'PCSCHAR',
    'PCUSHORT', 'PFLOAT128', 'LPCWSTR', 'LPCWCHAR', 'PCZPWSTR', 'PZPWSTR',
    'DWORDLONG', 'PNTSTATUS', 'PUUCSSTR', 'PCOBJECT_ATTRIBUTES32', 'PUNZWCH',
    'LOGICAL', 'PSTRING64', 'PSTRING', 'PZPTSTR', 'PCUCSSTR', 'LONGLONG',
    'PANSI_STRING32', 'PCZPSTR', 'LPCUTSTR', 'PULONGLONG', 'PCULONG', 'ULONG',
    'POBJECT_ATTRIBUTES32', 'PCNZCH', 'PCUNZWCH', 'PCNZWCH', 'CANSI_STRING',
    'PCUWCHAR', 'PWCHAR', 'PCZZSTR', 'ANSI_STRING32', 'PPHYSICAL_ADDRESS',
    'PKIRQL', 'PCSHORT', 'PCUZZWSTR', 'PULARGE_INTEGER', 'CSHORT', 'PZZWSTR',
    'RTL_REFERENCE_COUNT32', 'PSTRING32', 'PCZZWSTR', 'UCHAR', 'PCSTR',
    'RTL_STRING_LENGTH_TYPE', 'LPCUWSTR', 'LPWSTR', 'PCSTRING', 'PVOID64',
    'FSHORT', 'PCLONG', 'LPTCH', 'PHYSICAL_ADDRESS', 'PTUCHAR', 'PQUAD',
    'PCWSTR', 'PBOOLEAN', 'PLIST_ENTRY32', 'PCUZZTSTR', 'PCUUCSCHAR', 'WCHAR',
    'PUNZTCH', 'TUCHAR', 'PUWSTR', 'OEM_STRING', 'FCHAR', 'PCUNZTCH', 'LPCCH',
    'PUTSTR', 'PCZPCSTR', 'LPUWSTR', 'PCNZTCH', 'PZPCWSTR', 'NTSTATUS',
    'PLONG', 'PCWCHAR', 'CCHAR', 'PCOBJECT_ATTRIBUTES64', 'PUNICODE_STRING64',
    'SECURITY_STATUS', 'LPCTSTR', 'NPSTR', 'PUUCSCHAR', 'HANDLE', 'PZPSTR',
    'PCUWSTR', 'PDWORDLONG', 'PLONGLONG', 'PUCSSTR', 'PANSI_STRING64', 'BYTE',
    'PCUQUAD', 'LPUTSTR', 'UNICODE_STRING32', 'PCZZTSTR', 'PCOEM_STRING',
    'PUQUAD', 'USHORT', 'PTSTR', 'ANSI_STRING', 'BOOLEAN', 'PCUUCSSTR',
    'PANSI_STRING', 'LPSTR', 'PRTL_REFERENCE_COUNT', 'LPTSTR', 'PCTSTR',
    'PHANDLE', 'PCUNICODE_STRING', 'PZPCSTR', 'UCSCHAR', 'PUZZTSTR', 'LPCSTR',
    'PZZTSTR', 'PULONG', 'PCHAR', 'PCUTSTR', 'HRESULT', 'ULONGLONG', 'PSHORT',
    'PCUCHAR', 'PCNTSTATUS', 'LPCUWCHAR', 'PCANSI_STRING', 'PLOGICAL', 'CHAR',
    'PNZTCH', 'POEM_STRING', 'POBJECT_ATTRIBUTES', 'ANSI_STRING64', 'PWSTR',
    'NWPSTR', 'PRTL_REFERENCE_COUNT32', 'LANGID', 'PZZSTR', 'FLONG', 'PVOID',
    'PUNICODE_STRING32', 'PSCHAR', 'APIENTRY', 'APIPRIVATE', 'BYTE_BLOB',
    'APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU', 'APPIDREGFLAGS_RESERVED1',
    'APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP', 'APPIDREGFLAGS_RESERVED2',
    'APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY', 'BYTE_SIZEDARR', 'DATE',
    'APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY', 'CALLBACK',
    'APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION', 'CBPCLIPDATA',
    'APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN', 'CDECL', 'CLIPFORMAT',
    'APPIDREGFLAGS_RESERVED3', 'APPIDREGFLAGS_RESERVED4', 'CLSCTX_VALID_MASK',
    'APPIDREGFLAGS_RESERVED5', 'APPIDREGFLAGS_RESERVED7', 'CLSID', 'COLORREF',
    'APPIDREGFLAGS_RESERVED8', 'COAUTHIDENTITY', 'COAUTHINFO', 'DECIMAL_NEG',
    'APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND', 'DECIMAL_SETZERO',
    'DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL', 'DOUBLE', 'DWORD', 'DWORD32',
    'DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES', 'DWORD64', 'DWORD_BLOB',
    'DCOMSCM_PING_DISALLOW_UNSECURE_CALL', 'DWORD_PTR', 'ENUM', 'FARPROC',
    'DCOMSCM_PING_USE_MID_AUTHNSERVICE', 'FILETIME', 'FLAGGED_BYTE_BLOB',
    'DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL', 'FLAGGED_WORD_BLOB', 'FLOAT',
    'DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES', 'FLOAT32', 'GLOBALHANDLE',
    'GUID', 'HACCEL', 'HALF_PTR', 'HANDLE_PTR', 'HBITMAP', 'HBRUSH', 'HDESK',
    'HCOLORSPACE', 'HCONTEXT', 'HCURSOR', 'HEMF', 'HENHMETAFILE', 'HEVENT',
    'HFILE', 'HFONT', 'HGDIOBJ', 'HGLOBAL', 'HGLRC', 'HHOOK', 'HICON', 'HKEY',
    'HINSTANCE', 'HLOCAL', 'HLSURF', 'HMENU', 'HMETAFILE', 'HMETAFILEPICT',
    'HMODULE', 'HMONITOR', 'HNSTIME', 'HPALETTE', 'HPEN', 'HRGN', 'HRSRC',
    'HSPRITE', 'HSTR', 'HTASK', 'HUMPD', 'HWINEVENTHOOK', 'HWINSTA', 'HWND',
    'HYPER_SIZEDARR', 'INT16', 'INT32', 'INT64', 'INT8', 'INT_PTR', 'LONG',
    'KAFFINITY', 'LOCALHANDLE', 'LONG32', 'LONG64', 'LONG_PTR', 'LPARAM',
    'LPBSTR', 'LPBYTE', 'LPCGUID', 'LPCOLORREF', 'LPCRECT', 'LPCRECTL',
    'LPCY', 'LPDECIMAL', 'LPFILETIME', 'LPGUID', 'LPHANDLE', 'LPPOINT',
    'LPPOINTS', 'LPRECT', 'LPRECTL', 'LPSIZE', 'LPSIZEL', 'LPVOID', 'LRESULT',
    'NEAR', 'NEARPROC', 'NPPOINT', 'NPRECT', 'OLECHAR', 'PACL', 'PASCAL',
    'PBOOL', 'PDWORD32', 'PDWORD64', 'PDWORD_PTR', 'PFILETIME', 'PFLOAT',
    'PHALF_PTR', 'PHKEY', 'PINT32', 'PINT64', 'PINT8', 'PINT_PTR', 'PLONG32',
    'PLONG64', 'PLONG_PTR', 'POINT', 'POINTER', 'POINTER_32', 'POINTER_64',
    'POINTER_64_INT', 'POINTER_SIGNED', 'POINTER_UNSIGNED', 'POINTL', 'PRECT',
    'POINTS', 'PPOINT', 'PPOINTL', 'PPOINTS', 'PRECTL', 'PROC', 'PROPERTYKEY',
    'PROPID', 'PSCODE', 'PSECURITY_DESCRIPTOR_CONTROL', 'PSID', 'PSIZE',
    'PSIZEL', 'PSIZE_T', 'PSSIZE_T', 'PUHALF_PTR', 'PUINT', 'PUINT16', 'RECT',
    'PUINT32', 'PUINT64', 'PUINT8', 'PUINT_PTR', 'PULONG32', 'PULONG64',
    'PULONG_PTR', 'RECTL', 'REFERENCE_TIME', 'REFGUID', 'REFIID', 'SCODE',
    'ROTFLAGS_ALLOWANYCLIENT', 'ROTFLAGS_REGISTRATIONKEEPSALIVE', 'SHORT',
    'ROTREGFLAGS_ALLOWANYCLIENT', 'ROT_COMPARE_MAX', 'SECURITY_ATTRIBUTES',
    'SECURITY_DESCRIPTOR', 'SECURITY_DESCRIPTOR_CONTROL', 'SHANDLE_PTR',
    'SID_AND_ATTRIBUTES', 'SID_IDENTIFIER_AUTHORITY', 'SIZE', 'SIZEL', 'UINT',
    'SIZE_T', 'SPHANDLE', 'SPOINTER_32', 'SSIZE_T', 'SYSTEMTIME', 'UBYTE',
    'UHALF_PTR', 'UINT16', 'UINT32', 'UINT64', 'UINT8', 'UINT_PTR', 'ULONG32',
    'ULONG64', 'ULONG_PTR', 'UPOINTER_32', 'UP_BYTE_BLOB', 'UP_DWORD_BLOB',
    'UP_FLAGGED_BYTE_BLOB', 'UP_FLAGGED_WORD_BLOB', 'UP_WORD_BLOB', 'VARTYPE',
    'VARIANT_FALSE', 'VARIANT_TRUE', 'VOID', 'WDT_INPROC64_CALL', 'WINAPI',
    'WDT_INPROC_CALL', 'WDT_REMOTE_CALL', 'WINAPIV', 'WINAPI_INLINE', 'WORD',
    'WORD_BLOB', 'WPARAM', '_wcsicmp', 'cdecl', 'near', 'pascal', 'tagBLOB',
    'tagBSTRBLOB', 'tagCLIPDATA', 'tagCLSCTX', 'tagCSPLATFORM', 'tagCY',
    'tagDEC', 'tagDVASPECT', 'tagLOGPALETTE', 'tagMEMCTX', 'tagMSG', 'PACL',
    'tagMSHCTX', 'tagMSHLFLAGS', 'tagPALETTEENTRY', 'tagQUERYCONTEXT', 'PSID',
    'tagRemBRUSH', 'tagRemHBITMAP', 'tagRemHENHMETAFILE', 'tagRemHGLOBAL',
    'tagRemHMETAFILEPICT', 'tagRemHPALETTE', 'tagSIZEL', 'tagSTATFLAG',
    'tagSTGC', 'tagSTGMOVE', 'tagTEXTMETRICW', 'tagTYSPEC', 'wireBSTR',
    'wireCLIPFORMAT', 'wireHACCEL', 'wireHBITMAP', 'wireHBRUSH', 'wireHDC',
    'wireHENHMETAFILE', 'wireHFONT', 'wireHGLOBAL', 'wireHICON', 'wireHMENU',
    'wireHMETAFILE', 'wireHMETAFILEPICT', 'wireHMONITOR', 'wireHPALETTE',
    'wireHRGN', 'wireHWND', 'APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU',
    'APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP', 'APPIDREGFLAGS_RESERVED1',
    'APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY', 'CLSCTX_VALID_MASK',
    'APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY', 'OLECHAR',
    'APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION', 'PSCODE', 'SCODE',
    'APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN', 'UP_BYTE_BLOB', 'BLOB',
    'APPIDREGFLAGS_RESERVED2', 'APPIDREGFLAGS_RESERVED3', 'BYTE_BLOB',
    'APPIDREGFLAGS_RESERVED4', 'APPIDREGFLAGS_RESERVED5', 'DWORD_BLOB',
    'APPIDREGFLAGS_RESERVED7', 'APPIDREGFLAGS_RESERVED8', 'FLAGGED_BYTE_BLOB',
    'APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND', 'FLAGGED_WORD_BLOB',
    'DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL', 'ROTREGFLAGS_ALLOWANYCLIENT',
    'DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES', 'SECURITY_DESCRIPTOR_CONTROL',
    'DCOMSCM_PING_DISALLOW_UNSECURE_CALL', 'PSECURITY_DESCRIPTOR_CONTROL',
    'DCOMSCM_PING_USE_MID_AUTHNSERVICE', 'UP_DWORD_BLOB', 'UP_WORD_BLOB',
    'DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL', 'UP_FLAGGED_BYTE_BLOB', 'MSG',
    'DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES', 'UP_FLAGGED_WORD_BLOB', 'COORD',
    'tagBLOB', 'tagCLSCTX', 'tagMEMCTX', 'tagMSHCTX', 'tagMSHLFLAGS',
    'SECURITY_DESCRIPTOR', 'SECURITY_ATTRIBUTES', 'COAUTHIDENTITY',
    'WORD_BLOB', 'COAUTHINFO', 'SYSTEMTIME', 'HYPER_SIZEDARR', 'FILETIME',
    'SHORT_SIZEDARR', 'LONG_SIZEDARR', 'WORD_SIZEDARR', 'DWORD_SIZEDARR',
    'BYTE_SIZEDARR', 'SID_IDENTIFIER_AUTHORITY', 'SID_AND_ATTRIBUTES',
    'PFILETIME', 'LPFILETIME', 'WIN32_FIND_DATAA', 'WIN32_FIND_DATAW',
    'SMALL_RECT', 'POINTER_64_INT', 'KAFFINITY',
)
