from pyWinAPI import *

# + + BUILD Version: 0001 // Increment this if a change has global effects
# Copyright (c) 1991 Microsoft Corporation Module Name: bugcodes.mc Abstract:
# This module contains the definition of the system bug check codes. Notes: No
# message strings should be added to the bugcodes' entries. Their symbolic
# names take the place of message strings. - -

_BUGCODES_ = None
if not defined(_BUGCODES_):
    _BUGCODES_ = 1

    # Values are 32 bit values laid out as follows:
    # 3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
    # 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
    # + - - - + - + - + - - - - - - - - - - - - - - - - - - - - - - - + - - -
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
    # | Sev | C | R|  Facility  |   Code   |
    # + - - - + - + - + - - - - - - - - - - - - - - - - - - - - - - - + - - -
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
    # where
    # Sev - is the severity code
    # 00 - Success
    # 01 - Informational
    # 10 - Warning
    # 11 - Error
    # C - is the Customer code flag
    # R - is a reserved bit
    # Facility - is the facility code
    # Code - is the facility's status code
    # Define the facility codes
    # Define the severity codes
    # MessageId: HARDWARE_PROFILE_UNDOCKED_STRING
    # MessageText:
    # Undocked Profile
    HARDWARE_PROFILE_UNDOCKED_STRING = 0x40010001

    # MessageId: HARDWARE_PROFILE_DOCKED_STRING
    # MessageText:
    # Docked Profile
    HARDWARE_PROFILE_DOCKED_STRING = 0x40010002

    # MessageId: HARDWARE_PROFILE_UNKNOWN_STRING
    # MessageText:
    # Profile
    HARDWARE_PROFILE_UNKNOWN_STRING = 0x40010003

    # MessageId: WINDOWS_NT_BANNER
    # MessageText:
    # Microsoft (R) Windows (R) Version %hs (Build %u%hs)
    WINDOWS_NT_BANNER = 0x4000007E

    # MessageId: WINDOWS_NT_CSD_STRING
    # MessageText:
    # Service Pack
    WINDOWS_NT_CSD_STRING = 0x40000087

    # MessageId: WINDOWS_NT_INFO_STRING
    # MessageText:
    # %u System Processor [%u MB Memory] %Z
    WINDOWS_NT_INFO_STRING = 0x40000088

    # MessageId: WINDOWS_NT_MP_STRING
    # MessageText:
    # MultiProcessor Kernel
    WINDOWS_NT_MP_STRING = 0x40000089

    # MessageId: THREAD_TERMINATE_HELD_MUTEX
    # MessageText:
    # A kernel thread terminated while holding a mutex
    THREAD_TERMINATE_HELD_MUTEX = 0x4000008A

    # MessageId: WINDOWS_NT_INFO_STRING_PLURAL
    # MessageText:
    # %u System Processors [%u MB Memory] %Z
    WINDOWS_NT_INFO_STRING_PLURAL = 0x4000009D

    # MessageId: WINDOWS_NT_RC_STRING
    # MessageText:
    # RC
    WINDOWS_NT_RC_STRING = 0x4000009E

    # MessageId: APC_INDEX_MISMATCH
    # MessageText:
    # APC_INDEX_MISMATCH
    APC_INDEX_MISMATCH = 0x00000001

    # MessageId: DEVICE_QUEUE_NOT_BUSY
    # MessageText:
    # DEVICE_QUEUE_NOT_BUSY
    DEVICE_QUEUE_NOT_BUSY = 0x00000002

    # MessageId: INVALID_AFFINITY_SET
    # MessageText:
    # INVALID_AFFINITY_SET
    INVALID_AFFINITY_SET = 0x00000003

    # MessageId: INVALID_DATA_ACCESS_TRAP
    # MessageText:
    # INVALID_DATA_ACCESS_TRAP
    INVALID_DATA_ACCESS_TRAP = 0x00000004

    # MessageId: INVALID_PROCESS_ATTACH_ATTEMPT
    # MessageText:
    # INVALID_PROCESS_ATTACH_ATTEMPT
    INVALID_PROCESS_ATTACH_ATTEMPT = 0x00000005

    # MessageId: INVALID_PROCESS_DETACH_ATTEMPT
    # MessageText:
    # INVALID_PROCESS_DETACH_ATTEMPT
    INVALID_PROCESS_DETACH_ATTEMPT = 0x00000006

    # MessageId: INVALID_SOFTWARE_INTERRUPT
    # MessageText:
    # INVALID_SOFTWARE_INTERRUPT
    INVALID_SOFTWARE_INTERRUPT = 0x00000007

    # MessageId: IRQL_NOT_DISPATCH_LEVEL
    # MessageText:
    # IRQL_NOT_DISPATCH_LEVEL
    IRQL_NOT_DISPATCH_LEVEL = 0x00000008

    # MessageId: IRQL_NOT_GREATER_OR_EQUAL
    # MessageText:
    # IRQL_NOT_GREATER_OR_EQUAL
    IRQL_NOT_GREATER_OR_EQUAL = 0x00000009

    # MessageId: IRQL_NOT_LESS_OR_EQUAL
    # MessageText:
    # IRQL_NOT_LESS_OR_EQUAL
    IRQL_NOT_LESS_OR_EQUAL = 0x0000000A

    # MessageId: NO_EXCEPTION_HANDLING_SUPPORT
    # MessageText:
    # NO_EXCEPTION_HANDLING_SUPPORT
    NO_EXCEPTION_HANDLING_SUPPORT = 0x0000000B

    # MessageId: MAXIMUM_WAIT_OBJECTS_EXCEEDED
    # MessageText:
    # MAXIMUM_WAIT_OBJECTS_EXCEEDED
    MAXIMUM_WAIT_OBJECTS_EXCEEDED = 0x0000000C

    # MessageId: MUTEX_LEVEL_NUMBER_VIOLATION
    # MessageText:
    # MUTEX_LEVEL_NUMBER_VIOLATION
    MUTEX_LEVEL_NUMBER_VIOLATION = 0x0000000D

    # MessageId: NO_USER_MODE_CONTEXT
    # MessageText:
    # NO_USER_MODE_CONTEXT
    NO_USER_MODE_CONTEXT = 0x0000000E

    # MessageId: SPIN_LOCK_ALREADY_OWNED
    # MessageText:
    # SPIN_LOCK_ALREADY_OWNED
    SPIN_LOCK_ALREADY_OWNED = 0x0000000F

    # MessageId: SPIN_LOCK_NOT_OWNED
    # MessageText:
    # SPIN_LOCK_NOT_OWNED
    SPIN_LOCK_NOT_OWNED = 0x00000010

    # MessageId: THREAD_NOT_MUTEX_OWNER
    # MessageText:
    # THREAD_NOT_MUTEX_OWNER
    THREAD_NOT_MUTEX_OWNER = 0x00000011

    # MessageId: TRAP_CAUSE_UNKNOWN
    # MessageText:
    # TRAP_CAUSE_UNKNOWN
    TRAP_CAUSE_UNKNOWN = 0x00000012

    # MessageId: EMPTY_THREAD_REAPER_LIST
    # MessageText:
    # EMPTY_THREAD_REAPER_LIST
    EMPTY_THREAD_REAPER_LIST = 0x00000013

    # MessageId: CREATE_DELETE_LOCK_NOT_LOCKED
    # MessageText:
    # CREATE_DELETE_LOCK_NOT_LOCKED
    CREATE_DELETE_LOCK_NOT_LOCKED = 0x00000014

    # MessageId: LAST_CHANCE_CALLED_FROM_KMODE
    # MessageText:
    # LAST_CHANCE_CALLED_FROM_KMODE
    LAST_CHANCE_CALLED_FROM_KMODE = 0x00000015

    # MessageId: CID_HANDLE_CREATION
    # MessageText:
    # CID_HANDLE_CREATION
    CID_HANDLE_CREATION = 0x00000016

    # MessageId: CID_HANDLE_DELETION
    # MessageText:
    # CID_HANDLE_DELETION
    CID_HANDLE_DELETION = 0x00000017

    # MessageId: REFERENCE_BY_POINTER
    # MessageText:
    # REFERENCE_BY_POINTER
    REFERENCE_BY_POINTER = 0x00000018

    # MessageId: BAD_POOL_HEADER
    # MessageText:
    # BAD_POOL_HEADER
    BAD_POOL_HEADER = 0x00000019

    # MessageId: MEMORY_MANAGEMENT
    # MessageText:
    # MEMORY_MANAGEMENT
    MEMORY_MANAGEMENT = 0x0000001A

    # MessageId: PFN_SHARE_COUNT
    # MessageText:
    # PFN_SHARE_COUNT
    PFN_SHARE_COUNT = 0x0000001B

    # MessageId: PFN_REFERENCE_COUNT
    # MessageText:
    # PFN_REFERENCE_COUNT
    PFN_REFERENCE_COUNT = 0x0000001C

    # MessageId: NO_SPIN_LOCK_AVAILABLE
    # MessageText:
    # NO_SPIN_LOCK_AVAILABLE
    NO_SPIN_LOCK_AVAILABLE = 0x0000001D

    # MessageId: KMODE_EXCEPTION_NOT_HANDLED
    # MessageText:
    # KMODE_EXCEPTION_NOT_HANDLED
    KMODE_EXCEPTION_NOT_HANDLED = 0x0000001E

    # MessageId: SHARED_RESOURCE_CONV_ERROR
    # MessageText:
    # SHARED_RESOURCE_CONV_ERROR
    SHARED_RESOURCE_CONV_ERROR = 0x0000001F

    # MessageId: KERNEL_APC_PENDING_DURING_EXIT
    # MessageText:
    # KERNEL_APC_PENDING_DURING_EXIT
    KERNEL_APC_PENDING_DURING_EXIT = 0x00000020

    # MessageId: QUOTA_UNDERFLOW
    # MessageText:
    # QUOTA_UNDERFLOW
    QUOTA_UNDERFLOW = 0x00000021

    # MessageId: FILE_SYSTEM
    # MessageText:
    # FILE_SYSTEM
    FILE_SYSTEM = 0x00000022

    # MessageId: FAT_FILE_SYSTEM
    # MessageText:
    # FAT_FILE_SYSTEM
    FAT_FILE_SYSTEM = 0x00000023

    # MessageId: NTFS_FILE_SYSTEM
    # MessageText:
    # NTFS_FILE_SYSTEM
    NTFS_FILE_SYSTEM = 0x00000024

    # MessageId: NPFS_FILE_SYSTEM
    # MessageText:
    # NPFS_FILE_SYSTEM
    NPFS_FILE_SYSTEM = 0x00000025

    # MessageId: CDFS_FILE_SYSTEM
    # MessageText:
    # CDFS_FILE_SYSTEM
    CDFS_FILE_SYSTEM = 0x00000026

    # MessageId: RDR_FILE_SYSTEM
    # MessageText:
    # RDR_FILE_SYSTEM
    RDR_FILE_SYSTEM = 0x00000027

    # MessageId: CORRUPT_ACCESS_TOKEN
    # MessageText:
    # CORRUPT_ACCESS_TOKEN
    CORRUPT_ACCESS_TOKEN = 0x00000028

    # MessageId: SECURITY_SYSTEM
    # MessageText:
    # SECURITY_SYSTEM
    SECURITY_SYSTEM = 0x00000029

    # MessageId: INCONSISTENT_IRP
    # MessageText:
    # INCONSISTENT_IRP
    INCONSISTENT_IRP = 0x0000002A

    # MessageId: PANIC_STACK_SWITCH
    # MessageText:
    # PANIC_STACK_SWITCH
    PANIC_STACK_SWITCH = 0x0000002B

    # MessageId: PORT_DRIVER_INTERNAL
    # MessageText:
    # PORT_DRIVER_INTERNAL
    PORT_DRIVER_INTERNAL = 0x0000002C

    # MessageId: SCSI_DISK_DRIVER_INTERNAL
    # MessageText:
    # SCSI_DISK_DRIVER_INTERNAL
    SCSI_DISK_DRIVER_INTERNAL = 0x0000002D

    # MessageId: DATA_BUS_ERROR
    # MessageText:
    # DATA_BUS_ERROR
    DATA_BUS_ERROR = 0x0000002E

    # MessageId: INSTRUCTION_BUS_ERROR
    # MessageText:
    # INSTRUCTION_BUS_ERROR
    INSTRUCTION_BUS_ERROR = 0x0000002F

    # MessageId: SET_OF_INVALID_CONTEXT
    # MessageText:
    # SET_OF_INVALID_CONTEXT
    SET_OF_INVALID_CONTEXT = 0x00000030

    # MessageId: PHASE0_INITIALIZATION_FAILED
    # MessageText:
    # PHASE0_INITIALIZATION_FAILED
    PHASE0_INITIALIZATION_FAILED = 0x00000031

    # MessageId: PHASE1_INITIALIZATION_FAILED
    # MessageText:
    # PHASE1_INITIALIZATION_FAILED
    PHASE1_INITIALIZATION_FAILED = 0x00000032

    # MessageId: UNEXPECTED_INITIALIZATION_CALL
    # MessageText:
    # UNEXPECTED_INITIALIZATION_CALL
    UNEXPECTED_INITIALIZATION_CALL = 0x00000033

    # MessageId: CACHE_MANAGER
    # MessageText:
    # CACHE_MANAGER
    CACHE_MANAGER = 0x00000034

    # MessageId: NO_MORE_IRP_STACK_LOCATIONS
    # MessageText:
    # NO_MORE_IRP_STACK_LOCATIONS
    NO_MORE_IRP_STACK_LOCATIONS = 0x00000035

    # MessageId: DEVICE_REFERENCE_COUNT_NOT_ZERO
    # MessageText:
    # DEVICE_REFERENCE_COUNT_NOT_ZERO
    DEVICE_REFERENCE_COUNT_NOT_ZERO = 0x00000036

    # MessageId: FLOPPY_INTERNAL_ERROR
    # MessageText:
    # FLOPPY_INTERNAL_ERROR
    FLOPPY_INTERNAL_ERROR = 0x00000037

    # MessageId: SERIAL_DRIVER_INTERNAL
    # MessageText:
    # SERIAL_DRIVER_INTERNAL
    SERIAL_DRIVER_INTERNAL = 0x00000038

    # MessageId: SYSTEM_EXIT_OWNED_MUTEX
    # MessageText:
    # SYSTEM_EXIT_OWNED_MUTEX
    SYSTEM_EXIT_OWNED_MUTEX = 0x00000039

    # MessageId: SYSTEM_UNWIND_PREVIOUS_USER
    # MessageText:
    # SYSTEM_UNWIND_PREVIOUS_USER
    SYSTEM_UNWIND_PREVIOUS_USER = 0x0000003A

    # MessageId: SYSTEM_SERVICE_EXCEPTION
    # MessageText:
    # SYSTEM_SERVICE_EXCEPTION
    SYSTEM_SERVICE_EXCEPTION = 0x0000003B

    # MessageId: INTERRUPT_UNWIND_ATTEMPTED
    # MessageText:
    # INTERRUPT_UNWIND_ATTEMPTED
    INTERRUPT_UNWIND_ATTEMPTED = 0x0000003C

    # MessageId: INTERRUPT_EXCEPTION_NOT_HANDLED
    # MessageText:
    # INTERRUPT_EXCEPTION_NOT_HANDLED
    INTERRUPT_EXCEPTION_NOT_HANDLED = 0x0000003D

    # MessageId: MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED
    # MessageText:
    # MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED
    MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED = 0x0000003E

    # MessageId: NO_MORE_SYSTEM_PTES
    # MessageText:
    # NO_MORE_SYSTEM_PTES
    NO_MORE_SYSTEM_PTES = 0x0000003F

    # MessageId: TARGET_MDL_TOO_SMALL
    # MessageText:
    # TARGET_MDL_TOO_SMALL
    TARGET_MDL_TOO_SMALL = 0x00000040

    # MessageId: MUST_SUCCEED_POOL_EMPTY
    # MessageText:
    # MUST_SUCCEED_POOL_EMPTY
    MUST_SUCCEED_POOL_EMPTY = 0x00000041

    # MessageId: ATDISK_DRIVER_INTERNAL
    # MessageText:
    # ATDISK_DRIVER_INTERNAL
    ATDISK_DRIVER_INTERNAL = 0x00000042

    # MessageId: NO_SUCH_PARTITION
    # MessageText:
    # NO_SUCH_PARTITION
    NO_SUCH_PARTITION = 0x00000043

    # MessageId: MULTIPLE_IRP_COMPLETE_REQUESTS
    # MessageText:
    # MULTIPLE_IRP_COMPLETE_REQUESTS
    MULTIPLE_IRP_COMPLETE_REQUESTS = 0x00000044

    # MessageId: INSUFFICIENT_SYSTEM_MAP_REGS
    # MessageText:
    # INSUFFICIENT_SYSTEM_MAP_REGS
    INSUFFICIENT_SYSTEM_MAP_REGS = 0x00000045

    # MessageId: DEREF_UNKNOWN_LOGON_SESSION
    # MessageText:
    # DEREF_UNKNOWN_LOGON_SESSION
    DEREF_UNKNOWN_LOGON_SESSION = 0x00000046

    # MessageId: REF_UNKNOWN_LOGON_SESSION
    # MessageText:
    # REF_UNKNOWN_LOGON_SESSION
    REF_UNKNOWN_LOGON_SESSION = 0x00000047

    # MessageId: CANCEL_STATE_IN_COMPLETED_IRP
    # MessageText:
    # CANCEL_STATE_IN_COMPLETED_IRP
    CANCEL_STATE_IN_COMPLETED_IRP = 0x00000048

    # MessageId: PAGE_FAULT_WITH_INTERRUPTS_OFF
    # MessageText:
    # PAGE_FAULT_WITH_INTERRUPTS_OFF
    PAGE_FAULT_WITH_INTERRUPTS_OFF = 0x00000049

    # MessageId: IRQL_GT_ZERO_AT_SYSTEM_SERVICE
    # MessageText:
    # IRQL_GT_ZERO_AT_SYSTEM_SERVICE
    IRQL_GT_ZERO_AT_SYSTEM_SERVICE = 0x0000004A

    # MessageId: STREAMS_INTERNAL_ERROR
    # MessageText:
    # STREAMS_INTERNAL_ERROR
    STREAMS_INTERNAL_ERROR = 0x0000004B

    # MessageId: FATAL_UNHANDLED_HARD_ERROR
    # MessageText:
    # FATAL_UNHANDLED_HARD_ERROR
    FATAL_UNHANDLED_HARD_ERROR = 0x0000004C

    # MessageId: NO_PAGES_AVAILABLE
    # MessageText:
    # NO_PAGES_AVAILABLE
    NO_PAGES_AVAILABLE = 0x0000004D

    # MessageId: PFN_LIST_CORRUPT
    # MessageText:
    # PFN_LIST_CORRUPT
    PFN_LIST_CORRUPT = 0x0000004E

    # MessageId: NDIS_INTERNAL_ERROR
    # MessageText:
    # NDIS_INTERNAL_ERROR
    NDIS_INTERNAL_ERROR = 0x0000004F

    # MessageId: PAGE_FAULT_IN_NONPAGED_AREA
    # MessageText:
    # PAGE_FAULT_IN_NONPAGED_AREA
    PAGE_FAULT_IN_NONPAGED_AREA = 0x00000050
    PAGE_FAULT_IN_NONPAGED_AREA_M = 0x10000050

    # MessageId: REGISTRY_ERROR
    # MessageText:
    # REGISTRY_ERROR
    REGISTRY_ERROR = 0x00000051

    # MessageId: MAILSLOT_FILE_SYSTEM
    # MessageText:
    # MAILSLOT_FILE_SYSTEM
    MAILSLOT_FILE_SYSTEM = 0x00000052

    # MessageId: NO_BOOT_DEVICE
    # MessageText:
    # NO_BOOT_DEVICE
    NO_BOOT_DEVICE = 0x00000053

    # MessageId: LM_SERVER_INTERNAL_ERROR
    # MessageText:
    # LM_SERVER_INTERNAL_ERROR
    LM_SERVER_INTERNAL_ERROR = 0x00000054

    # MessageId: DATA_COHERENCY_EXCEPTION
    # MessageText:
    # DATA_COHERENCY_EXCEPTION
    DATA_COHERENCY_EXCEPTION = 0x00000055

    # MessageId: INSTRUCTION_COHERENCY_EXCEPTION
    # MessageText:
    # INSTRUCTION_COHERENCY_EXCEPTION
    INSTRUCTION_COHERENCY_EXCEPTION = 0x00000056

    # MessageId: XNS_INTERNAL_ERROR
    # MessageText:
    # XNS_INTERNAL_ERROR
    XNS_INTERNAL_ERROR = 0x00000057

    # MessageId: VOLMGRX_INTERNAL_ERROR
    # MessageText:
    # VOLMGRX_INTERNAL_ERROR
    VOLMGRX_INTERNAL_ERROR = 0x00000058

    # MessageId: PINBALL_FILE_SYSTEM
    # MessageText:
    # PINBALL_FILE_SYSTEM
    PINBALL_FILE_SYSTEM = 0x00000059

    # MessageId: CRITICAL_SERVICE_FAILED
    # MessageText:
    # CRITICAL_SERVICE_FAILED
    CRITICAL_SERVICE_FAILED = 0x0000005A

    # MessageId: SET_ENV_VAR_FAILED
    # MessageText:
    # SET_ENV_VAR_FAILED
    SET_ENV_VAR_FAILED = 0x0000005B

    # MessageId: HAL_INITIALIZATION_FAILED
    # MessageText:
    # HAL_INITIALIZATION_FAILED
    HAL_INITIALIZATION_FAILED = 0x0000005C

    # MessageId: UNSUPPORTED_PROCESSOR
    # MessageText:
    # UNSUPPORTED_PROCESSOR
    UNSUPPORTED_PROCESSOR = 0x0000005D

    # MessageId: OBJECT_INITIALIZATION_FAILED
    # MessageText:
    # OBJECT_INITIALIZATION_FAILED
    OBJECT_INITIALIZATION_FAILED = 0x0000005E

    # MessageId: SECURITY_INITIALIZATION_FAILED
    # MessageText:
    # SECURITY_INITIALIZATION_FAILED
    SECURITY_INITIALIZATION_FAILED = 0x0000005F

    # MessageId: PROCESS_INITIALIZATION_FAILED
    # MessageText:
    # PROCESS_INITIALIZATION_FAILED
    PROCESS_INITIALIZATION_FAILED = 0x00000060

    # MessageId: HAL1_INITIALIZATION_FAILED
    # MessageText:
    # HAL1_INITIALIZATION_FAILED
    HAL1_INITIALIZATION_FAILED = 0x00000061

    # MessageId: OBJECT1_INITIALIZATION_FAILED
    # MessageText:
    # OBJECT1_INITIALIZATION_FAILED
    OBJECT1_INITIALIZATION_FAILED = 0x00000062

    # MessageId: SECURITY1_INITIALIZATION_FAILED
    # MessageText:
    # SECURITY1_INITIALIZATION_FAILED
    SECURITY1_INITIALIZATION_FAILED = 0x00000063

    # MessageId: SYMBOLIC_INITIALIZATION_FAILED
    # MessageText:
    # SYMBOLIC_INITIALIZATION_FAILED
    SYMBOLIC_INITIALIZATION_FAILED = 0x00000064

    # MessageId: MEMORY1_INITIALIZATION_FAILED
    # MessageText:
    # MEMORY1_INITIALIZATION_FAILED
    MEMORY1_INITIALIZATION_FAILED = 0x00000065

    # MessageId: CACHE_INITIALIZATION_FAILED
    # MessageText:
    # CACHE_INITIALIZATION_FAILED
    CACHE_INITIALIZATION_FAILED = 0x00000066

    # MessageId: CONFIG_INITIALIZATION_FAILED
    # MessageText:
    # CONFIG_INITIALIZATION_FAILED
    CONFIG_INITIALIZATION_FAILED = 0x00000067

    # MessageId: FILE_INITIALIZATION_FAILED
    # MessageText:
    # FILE_INITIALIZATION_FAILED
    FILE_INITIALIZATION_FAILED = 0x00000068

    # MessageId: IO1_INITIALIZATION_FAILED
    # MessageText:
    # IO1_INITIALIZATION_FAILED
    IO1_INITIALIZATION_FAILED = 0x00000069

    # MessageId: LPC_INITIALIZATION_FAILED
    # MessageText:
    # LPC_INITIALIZATION_FAILED
    LPC_INITIALIZATION_FAILED = 0x0000006A

    # MessageId: PROCESS1_INITIALIZATION_FAILED
    # MessageText:
    # PROCESS1_INITIALIZATION_FAILED
    PROCESS1_INITIALIZATION_FAILED = 0x0000006B

    # MessageId: REFMON_INITIALIZATION_FAILED
    # MessageText:
    # REFMON_INITIALIZATION_FAILED
    REFMON_INITIALIZATION_FAILED = 0x0000006C

    # MessageId: SESSION1_INITIALIZATION_FAILED
    # MessageText:
    # SESSION1_INITIALIZATION_FAILED
    SESSION1_INITIALIZATION_FAILED = 0x0000006D

    # MessageId: BOOTPROC_INITIALIZATION_FAILED
    # MessageText:
    # BOOTPROC_INITIALIZATION_FAILED
    BOOTPROC_INITIALIZATION_FAILED = 0x0000006E

    # MessageId: VSL_INITIALIZATION_FAILED
    # MessageText:
    # VSL_INITIALIZATION_FAILED
    VSL_INITIALIZATION_FAILED = 0x0000006F

    # MessageId: SOFT_RESTART_FATAL_ERROR
    # MessageText:
    # SOFT_RESTART_FATAL_ERROR
    SOFT_RESTART_FATAL_ERROR = 0x00000070

    # MessageId: ASSIGN_DRIVE_LETTERS_FAILED
    # MessageText:
    # ASSIGN_DRIVE_LETTERS_FAILED
    ASSIGN_DRIVE_LETTERS_FAILED = 0x00000072

    # MessageId: CONFIG_LIST_FAILED
    # MessageText:
    # CONFIG_LIST_FAILED
    CONFIG_LIST_FAILED = 0x00000073

    # MessageId: BAD_SYSTEM_CONFIG_INFO
    # MessageText:
    # BAD_SYSTEM_CONFIG_INFO
    BAD_SYSTEM_CONFIG_INFO = 0x00000074

    # MessageId: CANNOT_WRITE_CONFIGURATION
    # MessageText:
    # CANNOT_WRITE_CONFIGURATION
    CANNOT_WRITE_CONFIGURATION = 0x00000075

    # MessageId: PROCESS_HAS_LOCKED_PAGES
    # MessageText:
    # PROCESS_HAS_LOCKED_PAGES
    PROCESS_HAS_LOCKED_PAGES = 0x00000076

    # MessageId: KERNEL_STACK_INPAGE_ERROR
    # MessageText:
    # KERNEL_STACK_INPAGE_ERROR
    KERNEL_STACK_INPAGE_ERROR = 0x00000077

    # MessageId: PHASE0_EXCEPTION
    # MessageText:
    # PHASE0_EXCEPTION
    PHASE0_EXCEPTION = 0x00000078

    # MessageId: MISMATCHED_HAL
    # MessageText:
    # MISMATCHED_HAL
    MISMATCHED_HAL = 0x00000079

    # MessageId: KERNEL_DATA_INPAGE_ERROR
    # MessageText:
    # KERNEL_DATA_INPAGE_ERROR
    KERNEL_DATA_INPAGE_ERROR = 0x0000007A

    # MessageId: INACCESSIBLE_BOOT_DEVICE
    # MessageText:
    # INACCESSIBLE_BOOT_DEVICE
    INACCESSIBLE_BOOT_DEVICE = 0x0000007B

    # MessageId: BUGCODE_NDIS_DRIVER
    # MessageText:
    # BUGCODE_NDIS_DRIVER
    BUGCODE_NDIS_DRIVER = 0x0000007C

    # MessageId: INSTALL_MORE_MEMORY
    # MessageText:
    # INSTALL_MORE_MEMORY
    INSTALL_MORE_MEMORY = 0x0000007D

    # MessageId: SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
    # MessageText:
    # SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
    SYSTEM_THREAD_EXCEPTION_NOT_HANDLED = 0x0000007E
    SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M = 0x1000007E

    # MessageId: UNEXPECTED_KERNEL_MODE_TRAP
    # MessageText:
    # UNEXPECTED_KERNEL_MODE_TRAP
    UNEXPECTED_KERNEL_MODE_TRAP = 0x0000007F
    UNEXPECTED_KERNEL_MODE_TRAP_M = 0x1000007F

    # MessageId: NMI_HARDWARE_FAILURE
    # MessageText:
    # NMI_HARDWARE_FAILURE
    NMI_HARDWARE_FAILURE = 0x00000080

    # MessageId: SPIN_LOCK_INIT_FAILURE
    # MessageText:
    # SPIN_LOCK_INIT_FAILURE
    SPIN_LOCK_INIT_FAILURE = 0x00000081

    # MessageId: DFS_FILE_SYSTEM
    # MessageText:
    # DFS_FILE_SYSTEM
    DFS_FILE_SYSTEM = 0x00000082

    # MessageId: OFS_FILE_SYSTEM
    # MessageText:
    # OFS_FILE_SYSTEM
    OFS_FILE_SYSTEM = 0x00000083

    # MessageId: RECOM_DRIVER
    # MessageText:
    # RECOM_DRIVER
    RECOM_DRIVER = 0x00000084

    # MessageId: SETUP_FAILURE
    # MessageText:
    # SETUP_FAILURE
    SETUP_FAILURE = 0x00000085

    # MessageId: AUDIT_FAILURE
    # MessageText:
    # AUDIT_FAILURE
    AUDIT_FAILURE = 0x00000086

    # MessageId: MBR_CHECKSUM_MISMATCH
    # MessageText:
    # MBR_CHECKSUM_MISMATCH
    MBR_CHECKSUM_MISMATCH = 0x0000008B

    # MessageId: KERNEL_MODE_EXCEPTION_NOT_HANDLED
    # MessageText:
    # KERNEL_MODE_EXCEPTION_NOT_HANDLED
    KERNEL_MODE_EXCEPTION_NOT_HANDLED = 0x0000008E
    KERNEL_MODE_EXCEPTION_NOT_HANDLED_M = 0x1000008E

    # MessageId: PP0_INITIALIZATION_FAILED
    # MessageText:
    # PP0_INITIALIZATION_FAILED
    PP0_INITIALIZATION_FAILED = 0x0000008F

    # MessageId: PP1_INITIALIZATION_FAILED
    # MessageText:
    # PP1_INITIALIZATION_FAILED
    PP1_INITIALIZATION_FAILED = 0x00000090

    # MessageId: WIN32K_INIT_OR_RIT_FAILURE
    # MessageText:
    # WIN32K_INIT_OR_RIT_FAILURE
    WIN32K_INIT_OR_RIT_FAILURE = 0x00000091

    # MessageId: UP_DRIVER_ON_MP_SYSTEM
    # MessageText:
    # UP_DRIVER_ON_MP_SYSTEM
    UP_DRIVER_ON_MP_SYSTEM = 0x00000092

    # MessageId: INVALID_KERNEL_HANDLE
    # MessageText:
    # INVALID_KERNEL_HANDLE
    INVALID_KERNEL_HANDLE = 0x00000093

    # MessageId: KERNEL_STACK_LOCKED_AT_EXIT
    # MessageText:
    # KERNEL_STACK_LOCKED_AT_EXIT
    KERNEL_STACK_LOCKED_AT_EXIT = 0x00000094

    # MessageId: PNP_INTERNAL_ERROR
    # MessageText:
    # PNP_INTERNAL_ERROR
    PNP_INTERNAL_ERROR = 0x00000095

    # MessageId: INVALID_WORK_QUEUE_ITEM
    # MessageText:
    # INVALID_WORK_QUEUE_ITEM
    INVALID_WORK_QUEUE_ITEM = 0x00000096

    # MessageId: BOUND_IMAGE_UNSUPPORTED
    # MessageText:
    # BOUND_IMAGE_UNSUPPORTED
    BOUND_IMAGE_UNSUPPORTED = 0x00000097

    # MessageId: END_OF_NT_EVALUATION_PERIOD
    # MessageText:
    # END_OF_NT_EVALUATION_PERIOD
    END_OF_NT_EVALUATION_PERIOD = 0x00000098

    # MessageId: INVALID_REGION_OR_SEGMENT
    # MessageText:
    # INVALID_REGION_OR_SEGMENT
    INVALID_REGION_OR_SEGMENT = 0x00000099

    # MessageId: SYSTEM_LICENSE_VIOLATION
    # MessageText:
    # SYSTEM_LICENSE_VIOLATION
    SYSTEM_LICENSE_VIOLATION = 0x0000009A

    # MessageId: UDFS_FILE_SYSTEM
    # MessageText:
    # UDFS_FILE_SYSTEM
    UDFS_FILE_SYSTEM = 0x0000009B

    # MessageId: MACHINE_CHECK_EXCEPTION
    # MessageText:
    # MACHINE_CHECK_EXCEPTION
    MACHINE_CHECK_EXCEPTION = 0x0000009C

    # MessageId: USER_MODE_HEALTH_MONITOR
    # MessageText:
    # USER_MODE_HEALTH_MONITOR
    USER_MODE_HEALTH_MONITOR = 0x0000009E

    # MessageId: DRIVER_POWER_STATE_FAILURE
    # MessageText:
    # DRIVER_POWER_STATE_FAILURE
    DRIVER_POWER_STATE_FAILURE = 0x0000009F

    # MessageId: INTERNAL_POWER_ERROR
    # MessageText:
    # INTERNAL_POWER_ERROR
    INTERNAL_POWER_ERROR = 0x000000A0

    # MessageId: PCI_BUS_DRIVER_INTERNAL
    # MessageText:
    # PCI_BUS_DRIVER_INTERNAL
    PCI_BUS_DRIVER_INTERNAL = 0x000000A1

    # MessageId: MEMORY_IMAGE_CORRUPT
    # MessageText:
    # MEMORY_IMAGE_CORRUPT
    MEMORY_IMAGE_CORRUPT = 0x000000A2

    # MessageId: ACPI_DRIVER_INTERNAL
    # MessageText:
    # ACPI_DRIVER_INTERNAL
    ACPI_DRIVER_INTERNAL = 0x000000A3

    # MessageId: CNSS_FILE_SYSTEM_FILTER
    # MessageText:
    # CNSS_FILE_SYSTEM_FILTER
    CNSS_FILE_SYSTEM_FILTER = 0x000000A4

    # MessageId: ACPI_BIOS_ERROR
    # MessageText:
    # ACPI_BIOS_ERROR
    ACPI_BIOS_ERROR = 0x000000A5

    # MessageId: FP_EMULATION_ERROR
    # MessageText:
    # FP_EMULATION_ERROR
    FP_EMULATION_ERROR = 0x000000A6

    # MessageId: BAD_EXHANDLE
    # MessageText:
    # BAD_EXHANDLE
    BAD_EXHANDLE = 0x000000A7

    # MessageId: BOOTING_IN_SAFEMODE_MINIMAL
    # MessageText:
    # BOOTING_IN_SAFEMODE_MINIMAL
    BOOTING_IN_SAFEMODE_MINIMAL = 0x000000A8

    # MessageId: BOOTING_IN_SAFEMODE_NETWORK
    # MessageText:
    # BOOTING_IN_SAFEMODE_NETWORK
    BOOTING_IN_SAFEMODE_NETWORK = 0x000000A9

    # MessageId: BOOTING_IN_SAFEMODE_DSREPAIR
    # MessageText:
    # BOOTING_IN_SAFEMODE_DSREPAIR
    BOOTING_IN_SAFEMODE_DSREPAIR = 0x000000AA

    # MessageId: SESSION_HAS_VALID_POOL_ON_EXIT
    # MessageText:
    # SESSION_HAS_VALID_POOL_ON_EXIT
    SESSION_HAS_VALID_POOL_ON_EXIT = 0x000000AB

    # MessageId: HAL_MEMORY_ALLOCATION
    # MessageText:
    # HAL_MEMORY_ALLOCATION
    HAL_MEMORY_ALLOCATION = 0x000000AC

    # MessageId: VIDEO_DRIVER_DEBUG_REPORT_REQUEST
    # MessageText:
    # VIDEO_DRIVER_DEBUG_REPORT_REQUEST
    VIDEO_DRIVER_DEBUG_REPORT_REQUEST = 0x400000AD

    # MessageId: BGI_DETECTED_VIOLATION
    # MessageText:
    # BGI_DETECTED_VIOLATION
    BGI_DETECTED_VIOLATION = 0x000000B1

    # MessageId: VIDEO_DRIVER_INIT_FAILURE
    # MessageText:
    # VIDEO_DRIVER_INIT_FAILURE
    VIDEO_DRIVER_INIT_FAILURE = 0x000000B4

    # MessageId: BOOTLOG_LOADED
    # MessageText:
    # BOOTLOG_LOADED
    BOOTLOG_LOADED = 0x000000B5

    # MessageId: BOOTLOG_NOT_LOADED
    # MessageText:
    # BOOTLOG_NOT_LOADED
    BOOTLOG_NOT_LOADED = 0x000000B6

    # MessageId: BOOTLOG_ENABLED
    # MessageText:
    # BOOTLOG_ENABLED
    BOOTLOG_ENABLED = 0x000000B7

    # MessageId: ATTEMPTED_SWITCH_FROM_DPC
    # MessageText:
    # ATTEMPTED_SWITCH_FROM_DPC
    ATTEMPTED_SWITCH_FROM_DPC = 0x000000B8

    # MessageId: CHIPSET_DETECTED_ERROR
    # MessageText:
    # CHIPSET_DETECTED_ERROR
    CHIPSET_DETECTED_ERROR = 0x000000B9

    # MessageId: SESSION_HAS_VALID_VIEWS_ON_EXIT
    # MessageText:
    # SESSION_HAS_VALID_VIEWS_ON_EXIT
    SESSION_HAS_VALID_VIEWS_ON_EXIT = 0x000000BA

    # MessageId: NETWORK_BOOT_INITIALIZATION_FAILED
    # MessageText:
    # NETWORK_BOOT_INITIALIZATION_FAILED
    NETWORK_BOOT_INITIALIZATION_FAILED = 0x000000BB

    # MessageId: NETWORK_BOOT_DUPLICATE_ADDRESS
    # MessageText:
    # NETWORK_BOOT_DUPLICATE_ADDRESS
    NETWORK_BOOT_DUPLICATE_ADDRESS = 0x000000BC

    # MessageId: INVALID_HIBERNATED_STATE
    # MessageText:
    # INVALID_HIBERNATED_STATE
    INVALID_HIBERNATED_STATE = 0x000000BD

    # MessageId: ATTEMPTED_WRITE_TO_READONLY_MEMORY
    # MessageText:
    # ATTEMPTED_WRITE_TO_READONLY_MEMORY
    ATTEMPTED_WRITE_TO_READONLY_MEMORY = 0x000000BE

    # MessageId: MUTEX_ALREADY_OWNED
    # MessageText:
    # MUTEX_ALREADY_OWNED
    MUTEX_ALREADY_OWNED = 0x000000BF

    # MessageId: PCI_CONFIG_SPACE_ACCESS_FAILURE
    # MessageText:
    # PCI_CONFIG_SPACE_ACCESS_FAILURE
    PCI_CONFIG_SPACE_ACCESS_FAILURE = 0x000000C0

    # MessageId: SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION
    # MessageText:
    # SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION
    SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION = 0x000000C1

    # MessageId: BAD_POOL_CALLER
    # MessageText:
    # BAD_POOL_CALLER
    BAD_POOL_CALLER = 0x000000C2

    # MessageId: SYSTEM_IMAGE_BAD_SIGNATURE
    # MessageText:
    # SYSTEM_IMAGE_BAD_SIGNATURE
    SYSTEM_IMAGE_BAD_SIGNATURE = 0x000000C3

    # MessageId: DRIVER_VERIFIER_DETECTED_VIOLATION
    # MessageText:
    # DRIVER_VERIFIER_DETECTED_VIOLATION
    DRIVER_VERIFIER_DETECTED_VIOLATION = 0x000000C4

    # MessageId: DRIVER_CORRUPTED_EXPOOL
    # MessageText:
    # DRIVER_CORRUPTED_EXPOOL
    DRIVER_CORRUPTED_EXPOOL = 0x000000C5

    # MessageId: DRIVER_CAUGHT_MODIFYING_FREED_POOL
    # MessageText:
    # DRIVER_CAUGHT_MODIFYING_FREED_POOL
    DRIVER_CAUGHT_MODIFYING_FREED_POOL = 0x000000C6

    # MessageId: TIMER_OR_DPC_INVALID
    # MessageText:
    # TIMER_OR_DPC_INVALID
    TIMER_OR_DPC_INVALID = 0x000000C7

    # MessageId: IRQL_UNEXPECTED_VALUE
    # MessageText:
    # IRQL_UNEXPECTED_VALUE
    IRQL_UNEXPECTED_VALUE = 0x000000C8

    # MessageId: DRIVER_VERIFIER_IOMANAGER_VIOLATION
    # MessageText:
    # DRIVER_VERIFIER_IOMANAGER_VIOLATION
    DRIVER_VERIFIER_IOMANAGER_VIOLATION = 0x000000C9

    # MessageId: PNP_DETECTED_FATAL_ERROR
    # MessageText:
    # PNP_DETECTED_FATAL_ERROR
    PNP_DETECTED_FATAL_ERROR = 0x000000CA

    # MessageId: DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS
    # MessageText:
    # DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS
    DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS = 0x000000CB

    # MessageId: PAGE_FAULT_IN_FREED_SPECIAL_POOL
    # MessageText:
    # PAGE_FAULT_IN_FREED_SPECIAL_POOL
    PAGE_FAULT_IN_FREED_SPECIAL_POOL = 0x000000CC

    # MessageId: PAGE_FAULT_BEYOND_END_OF_ALLOCATION
    # MessageText:
    # PAGE_FAULT_BEYOND_END_OF_ALLOCATION
    PAGE_FAULT_BEYOND_END_OF_ALLOCATION = 0x000000CD

    # MessageId: DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS
    # MessageText:
    # DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS
    DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS = 0x000000CE

    # MessageId: TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE
    # MessageText:
    # TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE
    TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE = 0x000000CF

    # MessageId: DRIVER_CORRUPTED_MMPOOL
    # MessageText:
    # DRIVER_CORRUPTED_MMPOOL
    DRIVER_CORRUPTED_MMPOOL = 0x000000D0

    # MessageId: DRIVER_IRQL_NOT_LESS_OR_EQUAL
    # MessageText:
    # DRIVER_IRQL_NOT_LESS_OR_EQUAL
    DRIVER_IRQL_NOT_LESS_OR_EQUAL = 0x000000D1

    # MessageId: BUGCODE_ID_DRIVER
    # MessageText:
    # BUGCODE_ID_DRIVER
    BUGCODE_ID_DRIVER = 0x000000D2

    # MessageId: DRIVER_PORTION_MUST_BE_NONPAGED
    # MessageText:
    # DRIVER_PORTION_MUST_BE_NONPAGED
    DRIVER_PORTION_MUST_BE_NONPAGED = 0x000000D3

    # MessageId: SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD
    # MessageText:
    # SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD
    SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD = (
        0x000000D4
    )

    # MessageId: DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL
    # MessageText:
    # DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL
    DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL = 0x000000D5

    # MessageId: DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION
    # MessageText:
    # DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION
    DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION = 0x000000D6
    DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION_M = 0x100000D6

    # MessageId: DRIVER_UNMAPPING_INVALID_VIEW
    # MessageText:
    # DRIVER_UNMAPPING_INVALID_VIEW
    DRIVER_UNMAPPING_INVALID_VIEW = 0x000000D7

    # MessageId: DRIVER_USED_EXCESSIVE_PTES
    # MessageText:
    # DRIVER_USED_EXCESSIVE_PTES
    DRIVER_USED_EXCESSIVE_PTES = 0x000000D8

    # MessageId: LOCKED_PAGES_TRACKER_CORRUPTION
    # MessageText:
    # LOCKED_PAGES_TRACKER_CORRUPTION
    LOCKED_PAGES_TRACKER_CORRUPTION = 0x000000D9

    # MessageId: SYSTEM_PTE_MISUSE
    # MessageText:
    # SYSTEM_PTE_MISUSE
    SYSTEM_PTE_MISUSE = 0x000000DA

    # MessageId: DRIVER_CORRUPTED_SYSPTES
    # MessageText:
    # DRIVER_CORRUPTED_SYSPTES
    DRIVER_CORRUPTED_SYSPTES = 0x000000DB

    # MessageId: DRIVER_INVALID_STACK_ACCESS
    # MessageText:
    # DRIVER_INVALID_STACK_ACCESS
    DRIVER_INVALID_STACK_ACCESS = 0x000000DC

    # MessageId: POOL_CORRUPTION_IN_FILE_AREA
    # MessageText:
    # POOL_CORRUPTION_IN_FILE_AREA
    POOL_CORRUPTION_IN_FILE_AREA = 0x000000DE

    # MessageId: IMPERSONATING_WORKER_THREAD
    # MessageText:
    # IMPERSONATING_WORKER_THREAD
    IMPERSONATING_WORKER_THREAD = 0x000000DF

    # MessageId: ACPI_BIOS_FATAL_ERROR
    # MessageText:
    # ACPI_BIOS_FATAL_ERROR
    ACPI_BIOS_FATAL_ERROR = 0x000000E0

    # MessageId: WORKER_THREAD_RETURNED_AT_BAD_IRQL
    # MessageText:
    # WORKER_THREAD_RETURNED_AT_BAD_IRQL
    WORKER_THREAD_RETURNED_AT_BAD_IRQL = 0x000000E1

    # MessageId: MANUALLY_INITIATED_CRASH
    # MessageText:
    # MANUALLY_INITIATED_CRASH
    MANUALLY_INITIATED_CRASH = 0x000000E2

    # MessageId: RESOURCE_NOT_OWNED
    # MessageText:
    # RESOURCE_NOT_OWNED
    RESOURCE_NOT_OWNED = 0x000000E3

    # MessageId: WORKER_INVALID
    # MessageText:
    # WORKER_INVALID
    WORKER_INVALID = 0x000000E4

    # MessageId: POWER_FAILURE_SIMULATE
    # MessageText:
    # POWER_FAILURE_SIMULATE
    POWER_FAILURE_SIMULATE = 0x000000E5

    # MessageId: DRIVER_VERIFIER_DMA_VIOLATION
    # MessageText:
    # DRIVER_VERIFIER_DMA_VIOLATION
    DRIVER_VERIFIER_DMA_VIOLATION = 0x000000E6

    # MessageId: INVALID_FLOATING_POINT_STATE
    # MessageText:
    # INVALID_FLOATING_POINT_STATE
    INVALID_FLOATING_POINT_STATE = 0x000000E7

    # MessageId: INVALID_CANCEL_OF_FILE_OPEN
    # MessageText:
    # INVALID_CANCEL_OF_FILE_OPEN
    INVALID_CANCEL_OF_FILE_OPEN = 0x000000E8

    # MessageId: ACTIVE_EX_WORKER_THREAD_TERMINATION
    # MessageText:
    # ACTIVE_EX_WORKER_THREAD_TERMINATION
    ACTIVE_EX_WORKER_THREAD_TERMINATION = 0x000000E9

    # MessageId: SAVER_UNSPECIFIED
    # MessageText:
    # SAVER_UNSPECIFIED
    SAVER_UNSPECIFIED = 0x0000F000

    # MessageId: SAVER_BLANKSCREEN
    # MessageText:
    # SAVER_BLANKSCREEN
    SAVER_BLANKSCREEN = 0x0000F002

    # MessageId: SAVER_INPUT
    # MessageText:
    # SAVER_INPUT
    SAVER_INPUT = 0x0000F003

    # MessageId: SAVER_WATCHDOG
    # MessageText:
    # SAVER_WATCHDOG
    SAVER_WATCHDOG = 0x0000F004

    # MessageId: SAVER_STARTNOTVISIBLE
    # MessageText:
    # SAVER_STARTNOTVISIBLE
    SAVER_STARTNOTVISIBLE = 0x0000F005

    # MessageId: SAVER_NAVIGATIONMODEL
    # MessageText:
    # SAVER_NAVIGATIONMODEL
    SAVER_NAVIGATIONMODEL = 0x0000F006

    # MessageId: SAVER_OUTOFMEMORY
    # MessageText:
    # SAVER_OUTOFMEMORY
    SAVER_OUTOFMEMORY = 0x0000F007

    # MessageId: SAVER_GRAPHICS
    # MessageText:
    # SAVER_GRAPHICS
    SAVER_GRAPHICS = 0x0000F008

    # MessageId: SAVER_NAVSERVERTIMEOUT
    # MessageText:
    # SAVER_NAVSERVERTIMEOUT
    SAVER_NAVSERVERTIMEOUT = 0x0000F009

    # MessageId: SAVER_CHROMEPROCESSCRASH
    # MessageText:
    # SAVER_CHROMEPROCESSCRASH
    SAVER_CHROMEPROCESSCRASH = 0x0000F00A

    # MessageId: SAVER_NOTIFICATIONDISMISSAL
    # MessageText:
    # SAVER_NOTIFICATIONDISMISSAL
    SAVER_NOTIFICATIONDISMISSAL = 0x0000F00B

    # MessageId: SAVER_SPEECHDISMISSAL
    # MessageText:
    # SAVER_SPEECHDISMISSAL
    SAVER_SPEECHDISMISSAL = 0x0000F00C

    # MessageId: SAVER_CALLDISMISSAL
    # MessageText:
    # SAVER_CALLDISMISSAL
    SAVER_CALLDISMISSAL = 0x0000F00D

    # MessageId: SAVER_APPBARDISMISSAL
    # MessageText:
    # SAVER_APPBARDISMISSAL
    SAVER_APPBARDISMISSAL = 0x0000F00E

    # MessageId: SAVER_RILADAPTATIONCRASH
    # MessageText:
    # SAVER_RILADAPTATIONCRASH
    SAVER_RILADAPTATIONCRASH = 0x0000F00F

    # MessageId: SAVER_APPLISTUNREACHABLE
    # MessageText:
    # SAVER_APPLISTUNREACHABLE
    SAVER_APPLISTUNREACHABLE = 0x0000F010

    # MessageId: SAVER_REPORTNOTIFICATIONFAILURE
    # MessageText:
    # SAVER_REPORTNOTIFICATIONFAILURE
    SAVER_REPORTNOTIFICATIONFAILURE = 0x0000F011

    # MessageId: SAVER_UNEXPECTEDSHUTDOWN
    # MessageText:
    # SAVER_UNEXPECTEDSHUTDOWN
    SAVER_UNEXPECTEDSHUTDOWN = 0x0000F012

    # MessageId: SAVER_RPCFAILURE
    # MessageText:
    # SAVER_RPCFAILURE
    SAVER_RPCFAILURE = 0x0000F013

    # MessageId: SAVER_AUXILIARYFULLDUMP
    # MessageText:
    # SAVER_AUXILIARYFULLDUMP
    SAVER_AUXILIARYFULLDUMP = 0x0000F014

    # MessageId: SAVER_ACCOUNTPROVSVCINITFAILURE
    # MessageText:
    # SAVER_ACCOUNTPROVSVCINITFAILURE
    SAVER_ACCOUNTPROVSVCINITFAILURE = 0x0000F015

    # MessageId: SAVER_MTBFCOMMANDTIMEOUT
    # MessageText:
    # SAVER_MTBFCOMMANDTIMEOUT
    SAVER_MTBFCOMMANDTIMEOUT = 0x00000315

    # MessageId: SAVER_MTBFCOMMANDHANG
    # MessageText:
    # SAVER_MTBFCOMMANDHANG
    SAVER_MTBFCOMMANDHANG = 0x0000F101

    # MessageId: SAVER_MTBFPASSBUGCHECK
    # MessageText:
    # SAVER_MTBFPASSBUGCHECK
    SAVER_MTBFPASSBUGCHECK = 0x0000F102

    # MessageId: SAVER_MTBFIOERROR
    # MessageText:
    # SAVER_MTBFIOERROR
    SAVER_MTBFIOERROR = 0x0000F103

    # MessageId: SAVER_RENDERTHREADHANG
    # MessageText:
    # SAVER_RENDERTHREADHANG
    SAVER_RENDERTHREADHANG = 0x0000F200

    # MessageId: SAVER_RENDERMOBILEUIOOM
    # MessageText:
    # SAVER_RENDERMOBILEUIOOM
    SAVER_RENDERMOBILEUIOOM = 0x0000F201

    # MessageId: SAVER_DEVICEUPDATEUNSPECIFIED
    # MessageText:
    # SAVER_DEVICEUPDATEUNSPECIFIED
    SAVER_DEVICEUPDATEUNSPECIFIED = 0x0000F300

    # MessageId: SAVER_AUDIODRIVERHANG
    # MessageText:
    # SAVER_AUDIODRIVERHANG
    SAVER_AUDIODRIVERHANG = 0x0000F400

    # MessageId: SAVER_BATTERYPULLOUT
    # MessageText:
    # SAVER_BATTERYPULLOUT
    SAVER_BATTERYPULLOUT = 0x0000F500

    # MessageId: SAVER_MEDIACORETESTHANG
    # MessageText:
    # SAVER_MEDIACORETESTHANG
    SAVER_MEDIACORETESTHANG = 0x0000F600

    # MessageId: SAVER_RESOURCEMANAGEMENT
    # MessageText:
    # SAVER_RESOURCEMANAGEMENT
    SAVER_RESOURCEMANAGEMENT = 0x0000F700

    # MessageId: SAVER_CAPTURESERVICE
    # MessageText:
    # SAVER_CAPTURESERVICE
    SAVER_CAPTURESERVICE = 0x0000F800

    # MessageId: SAVER_WAITFORSHELLREADY
    # MessageText:
    # SAVER_WAITFORSHELLREADY
    SAVER_WAITFORSHELLREADY = 0x0000F900

    # MessageId: SAVER_NONRESPONSIVEPROCESS
    # MessageText:
    # SAVER_NONRESPONSIVEPROCESS
    SAVER_NONRESPONSIVEPROCESS = 0x00000194

    # MessageId: SAVER_SICKAPPLICATION
    # MessageText:
    # SAVER_SICKAPPLICATION
    SAVER_SICKAPPLICATION = 0x00008866

    # MessageId: THREAD_STUCK_IN_DEVICE_DRIVER
    # MessageText:
    # THREAD_STUCK_IN_DEVICE_DRIVER
    THREAD_STUCK_IN_DEVICE_DRIVER = 0x000000EA
    THREAD_STUCK_IN_DEVICE_DRIVER_M = 0x100000EA

    # MessageId: DIRTY_MAPPED_PAGES_CONGESTION
    # MessageText:
    # DIRTY_MAPPED_PAGES_CONGESTION
    DIRTY_MAPPED_PAGES_CONGESTION = 0x000000EB

    # MessageId: SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT
    # MessageText:
    # SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT
    SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT = 0x000000EC

    # MessageId: UNMOUNTABLE_BOOT_VOLUME
    # MessageText:
    # UNMOUNTABLE_BOOT_VOLUME
    UNMOUNTABLE_BOOT_VOLUME = 0x000000ED

    # MessageId: CRITICAL_PROCESS_DIED
    # MessageText:
    # CRITICAL_PROCESS_DIED
    CRITICAL_PROCESS_DIED = 0x000000EF

    # MessageId: STORAGE_MINIPORT_ERROR
    # MessageText:
    # STORAGE_MINIPORT_ERROR
    STORAGE_MINIPORT_ERROR = 0x000000F0

    # MessageId: SCSI_VERIFIER_DETECTED_VIOLATION
    # MessageText:
    # SCSI_VERIFIER_DETECTED_VIOLATION
    SCSI_VERIFIER_DETECTED_VIOLATION = 0x000000F1

    # MessageId: HARDWARE_INTERRUPT_STORM
    # MessageText:
    # HARDWARE_INTERRUPT_STORM
    HARDWARE_INTERRUPT_STORM = 0x000000F2

    # MessageId: DISORDERLY_SHUTDOWN
    # MessageText:
    # DISORDERLY_SHUTDOWN
    DISORDERLY_SHUTDOWN = 0x000000F3

    # MessageId: CRITICAL_OBJECT_TERMINATION
    # MessageText:
    # CRITICAL_OBJECT_TERMINATION
    CRITICAL_OBJECT_TERMINATION = 0x000000F4

    # MessageId: FLTMGR_FILE_SYSTEM
    # MessageText:
    # FLTMGR_FILE_SYSTEM
    FLTMGR_FILE_SYSTEM = 0x000000F5

    # MessageId: PCI_VERIFIER_DETECTED_VIOLATION
    # MessageText:
    # PCI_VERIFIER_DETECTED_VIOLATION
    PCI_VERIFIER_DETECTED_VIOLATION = 0x000000F6

    # MessageId: DRIVER_OVERRAN_STACK_BUFFER
    # MessageText:
    # DRIVER_OVERRAN_STACK_BUFFER
    DRIVER_OVERRAN_STACK_BUFFER = 0x000000F7

    # MessageId: RAMDISK_BOOT_INITIALIZATION_FAILED
    # MessageText:
    # RAMDISK_BOOT_INITIALIZATION_FAILED
    RAMDISK_BOOT_INITIALIZATION_FAILED = 0x000000F8

    # MessageId: DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN
    # MessageText:
    # DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN
    DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN = 0x000000F9

    # MessageId: HTTP_DRIVER_CORRUPTED
    # MessageText:
    # HTTP_DRIVER_CORRUPTED
    HTTP_DRIVER_CORRUPTED = 0x000000FA

    # MessageId: RECURSIVE_MACHINE_CHECK
    # MessageText:
    # RECURSIVE_MACHINE_CHECK
    RECURSIVE_MACHINE_CHECK = 0x000000FB

    # MessageId: ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY
    # MessageText:
    # ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY
    ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY = 0x000000FC

    # MessageId: DIRTY_NOWRITE_PAGES_CONGESTION
    # MessageText:
    # DIRTY_NOWRITE_PAGES_CONGESTION
    DIRTY_NOWRITE_PAGES_CONGESTION = 0x000000FD

    # MessageId: BUGCODE_USB_DRIVER
    # MessageText:
    # BUGCODE_USB_DRIVER
    BUGCODE_USB_DRIVER = 0x000000FE

    # MessageId: BC_BLUETOOTH_VERIFIER_FAULT
    # MessageText:
    # BC_BLUETOOTH_VERIFIER_FAULT
    BC_BLUETOOTH_VERIFIER_FAULT = 0x00000BFE

    # MessageId: BC_BTHMINI_VERIFIER_FAULT
    # MessageText:
    # BC_BTHMINI_VERIFIER_FAULT
    BC_BTHMINI_VERIFIER_FAULT = 0x00000BFF

    # MessageId: RESERVE_QUEUE_OVERFLOW
    # MessageText:
    # RESERVE_QUEUE_OVERFLOW
    RESERVE_QUEUE_OVERFLOW = 0x000000FF

    # MessageId: LOADER_BLOCK_MISMATCH
    # MessageText:
    # LOADER_BLOCK_MISMATCH
    LOADER_BLOCK_MISMATCH = 0x00000100

    # MessageId: CLOCK_WATCHDOG_TIMEOUT
    # MessageText:
    # CLOCK_WATCHDOG_TIMEOUT
    CLOCK_WATCHDOG_TIMEOUT = 0x00000101

    # MessageId: DPC_WATCHDOG_TIMEOUT
    # MessageText:
    # DPC_WATCHDOG_TIMEOUT
    DPC_WATCHDOG_TIMEOUT = 0x00000102

    # MessageId: MUP_FILE_SYSTEM
    # MessageText:
    # MUP_FILE_SYSTEM
    MUP_FILE_SYSTEM = 0x00000103

    # MessageId: AGP_INVALID_ACCESS
    # MessageText:
    # AGP_INVALID_ACCESS
    AGP_INVALID_ACCESS = 0x00000104

    # MessageId: AGP_GART_CORRUPTION
    # MessageText:
    # AGP_GART_CORRUPTION
    AGP_GART_CORRUPTION = 0x00000105

    # MessageId: AGP_ILLEGALLY_REPROGRAMMED
    # MessageText:
    # AGP_ILLEGALLY_REPROGRAMMED
    AGP_ILLEGALLY_REPROGRAMMED = 0x00000106

    # MessageId: KERNEL_EXPAND_STACK_ACTIVE
    # MessageText:
    # KERNEL_EXPAND_STACK_ACTIVE
    KERNEL_EXPAND_STACK_ACTIVE = 0x00000107

    # MessageId: THIRD_PARTY_FILE_SYSTEM_FAILURE
    # MessageText:
    # THIRD_PARTY_FILE_SYSTEM_FAILURE
    THIRD_PARTY_FILE_SYSTEM_FAILURE = 0x00000108

    # MessageId: CRITICAL_STRUCTURE_CORRUPTION
    # MessageText:
    # CRITICAL_STRUCTURE_CORRUPTION
    CRITICAL_STRUCTURE_CORRUPTION = 0x00000109

    # MessageId: APP_TAGGING_INITIALIZATION_FAILED
    # MessageText:
    # APP_TAGGING_INITIALIZATION_FAILED
    APP_TAGGING_INITIALIZATION_FAILED = 0x0000010A

    # MessageId: DFSC_FILE_SYSTEM
    # MessageText:
    # DFSC_FILE_SYSTEM
    DFSC_FILE_SYSTEM = 0x0000010B

    # MessageId: FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION
    # MessageText:
    # FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION
    FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION = 0x0000010C

    # MessageId: WDF_VIOLATION
    # MessageText:
    # WDF_VIOLATION
    WDF_VIOLATION = 0x0000010D

    # MessageId: VIDEO_MEMORY_MANAGEMENT_INTERNAL
    # MessageText:
    # VIDEO_MEMORY_MANAGEMENT_INTERNAL
    VIDEO_MEMORY_MANAGEMENT_INTERNAL = 0x0000010E

    # MessageId: DRIVER_INVALID_CRUNTIME_PARAMETER
    # MessageText:
    # DRIVER_INVALID_CRUNTIME_PARAMETER
    DRIVER_INVALID_CRUNTIME_PARAMETER = 0x00000110

    # MessageId: RECURSIVE_NMI
    # MessageText:
    # RECURSIVE_NMI
    RECURSIVE_NMI = 0x00000111

    # MessageId: MSRPC_STATE_VIOLATION
    # MessageText:
    # MSRPC_STATE_VIOLATION
    MSRPC_STATE_VIOLATION = 0x00000112

    # MessageId: VIDEO_DXGKRNL_FATAL_ERROR
    # MessageText:
    # VIDEO_DXGKRNL_FATAL_ERROR
    VIDEO_DXGKRNL_FATAL_ERROR = 0x00000113

    # MessageId: VIDEO_SHADOW_DRIVER_FATAL_ERROR
    # MessageText:
    # VIDEO_SHADOW_DRIVER_FATAL_ERROR
    VIDEO_SHADOW_DRIVER_FATAL_ERROR = 0x00000114

    # MessageId: AGP_INTERNAL
    # MessageText:
    # AGP_INTERNAL
    AGP_INTERNAL = 0x00000115

    # MessageId: VIDEO_TDR_FAILURE
    # MessageText:
    # VIDEO_TDR_FAILURE
    VIDEO_TDR_FAILURE = 0x00000116

    # MessageId: VIDEO_TDR_TIMEOUT_DETECTED
    # MessageText:
    # VIDEO_TDR_TIMEOUT_DETECTED
    VIDEO_TDR_TIMEOUT_DETECTED = 0x00000117

    # MessageId: NTHV_GUEST_ERROR
    # MessageText:
    # NTHV_GUEST_ERROR
    NTHV_GUEST_ERROR = 0x00000118

    # MessageId: VIDEO_SCHEDULER_INTERNAL_ERROR
    # MessageText:
    # VIDEO_SCHEDULER_INTERNAL_ERROR
    VIDEO_SCHEDULER_INTERNAL_ERROR = 0x00000119

    # MessageId: EM_INITIALIZATION_ERROR
    # MessageText:
    # EM_INITIALIZATION_ERROR
    EM_INITIALIZATION_ERROR = 0x0000011A

    # MessageId: DRIVER_RETURNED_HOLDING_CANCEL_LOCK
    # MessageText:
    # DRIVER_RETURNED_HOLDING_CANCEL_LOCK
    DRIVER_RETURNED_HOLDING_CANCEL_LOCK = 0x0000011B

    # MessageId: ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE
    # MessageText:
    # ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE
    ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE = 0x0000011C

    # MessageId: EVENT_TRACING_FATAL_ERROR
    # MessageText:
    # EVENT_TRACING_FATAL_ERROR
    EVENT_TRACING_FATAL_ERROR = 0x0000011D

    # MessageId: TOO_MANY_RECURSIVE_FAULTS
    # MessageText:
    # TOO_MANY_RECURSIVE_FAULTS
    TOO_MANY_RECURSIVE_FAULTS = 0x0000011E

    # MessageId: INVALID_DRIVER_HANDLE
    # MessageText:
    # INVALID_DRIVER_HANDLE
    INVALID_DRIVER_HANDLE = 0x0000011F

    # MessageId: BITLOCKER_FATAL_ERROR
    # MessageText:
    # BITLOCKER_FATAL_ERROR
    BITLOCKER_FATAL_ERROR = 0x00000120

    # MessageId: DRIVER_VIOLATION
    # MessageText:
    # DRIVER_VIOLATION
    DRIVER_VIOLATION = 0x00000121

    # MessageId: WHEA_INTERNAL_ERROR
    # MessageText:
    # WHEA_INTERNAL_ERROR
    WHEA_INTERNAL_ERROR = 0x00000122

    # MessageId: CRYPTO_SELF_TEST_FAILURE
    # MessageText:
    # CRYPTO_SELF_TEST_FAILURE
    CRYPTO_SELF_TEST_FAILURE = 0x00000123

    # MessageId: WHEA_UNCORRECTABLE_ERROR
    # MessageText:
    # WHEA_UNCORRECTABLE_ERROR
    WHEA_UNCORRECTABLE_ERROR = 0x00000124

    # MessageId: NMR_INVALID_STATE
    # MessageText:
    # NMR_INVALID_STATE
    NMR_INVALID_STATE = 0x00000125

    # MessageId: NETIO_INVALID_POOL_CALLER
    # MessageText:
    # NETIO_INVALID_POOL_CALLER
    NETIO_INVALID_POOL_CALLER = 0x00000126

    # MessageId: PAGE_NOT_ZERO
    # MessageText:
    # PAGE_NOT_ZERO
    PAGE_NOT_ZERO = 0x00000127

    # MessageId: WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY
    # MessageText:
    # WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY
    WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY = 0x00000128

    # MessageId: WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY
    # MessageText:
    # WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY
    WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY = 0x00000129

    # MessageId: MUI_NO_VALID_SYSTEM_LANGUAGE
    # MessageText:
    # MUI_NO_VALID_SYSTEM_LANGUAGE
    MUI_NO_VALID_SYSTEM_LANGUAGE = 0x0000012A

    # MessageId: FAULTY_HARDWARE_CORRUPTED_PAGE
    # MessageText:
    # FAULTY_HARDWARE_CORRUPTED_PAGE
    FAULTY_HARDWARE_CORRUPTED_PAGE = 0x0000012B

    # MessageId: EXFAT_FILE_SYSTEM
    # MessageText:
    # EXFAT_FILE_SYSTEM
    EXFAT_FILE_SYSTEM = 0x0000012C

    # MessageId: VOLSNAP_OVERLAPPED_TABLE_ACCESS
    # MessageText:
    # VOLSNAP_OVERLAPPED_TABLE_ACCESS
    VOLSNAP_OVERLAPPED_TABLE_ACCESS = 0x0000012D

    # MessageId: INVALID_MDL_RANGE
    # MessageText:
    # INVALID_MDL_RANGE
    INVALID_MDL_RANGE = 0x0000012E

    # MessageId: VHD_BOOT_INITIALIZATION_FAILED
    # MessageText:
    # VHD_BOOT_INITIALIZATION_FAILED
    VHD_BOOT_INITIALIZATION_FAILED = 0x0000012F

    # MessageId: DYNAMIC_ADD_PROCESSOR_MISMATCH
    # MessageText:
    # DYNAMIC_ADD_PROCESSOR_MISMATCH
    DYNAMIC_ADD_PROCESSOR_MISMATCH = 0x00000130

    # MessageId: INVALID_EXTENDED_PROCESSOR_STATE
    # MessageText:
    # INVALID_EXTENDED_PROCESSOR_STATE
    INVALID_EXTENDED_PROCESSOR_STATE = 0x00000131

    # MessageId: RESOURCE_OWNER_POINTER_INVALID
    # MessageText:
    # RESOURCE_OWNER_POINTER_INVALID
    RESOURCE_OWNER_POINTER_INVALID = 0x00000132

    # MessageId: DPC_WATCHDOG_VIOLATION
    # MessageText:
    # DPC_WATCHDOG_VIOLATION
    DPC_WATCHDOG_VIOLATION = 0x00000133

    # MessageId: DRIVE_EXTENDER
    # MessageText:
    # DRIVE_EXTENDER
    DRIVE_EXTENDER = 0x00000134

    # MessageId: REGISTRY_FILTER_DRIVER_EXCEPTION
    # MessageText:
    # REGISTRY_FILTER_DRIVER_EXCEPTION
    REGISTRY_FILTER_DRIVER_EXCEPTION = 0x00000135

    # MessageId: VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE
    # MessageText:
    # VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE
    VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE = 0x00000136

    # MessageId: WIN32K_HANDLE_MANAGER
    # MessageText:
    # WIN32K_HANDLE_MANAGER
    WIN32K_HANDLE_MANAGER = 0x00000137

    # MessageId: GPIO_CONTROLLER_DRIVER_ERROR
    # MessageText:
    # GPIO_CONTROLLER_DRIVER_ERROR
    GPIO_CONTROLLER_DRIVER_ERROR = 0x00000138

    # MessageId: KERNEL_SECURITY_CHECK_FAILURE
    # MessageText:
    # KERNEL_SECURITY_CHECK_FAILURE
    KERNEL_SECURITY_CHECK_FAILURE = 0x00000139

    # MessageId: KERNEL_MODE_HEAP_CORRUPTION
    # MessageText:
    # KERNEL_MODE_HEAP_CORRUPTION
    KERNEL_MODE_HEAP_CORRUPTION = 0x0000013A

    # MessageId: PASSIVE_INTERRUPT_ERROR
    # MessageText:
    # PASSIVE_INTERRUPT_ERROR
    PASSIVE_INTERRUPT_ERROR = 0x0000013B

    # MessageId: INVALID_IO_BOOST_STATE
    # MessageText:
    # INVALID_IO_BOOST_STATE
    INVALID_IO_BOOST_STATE = 0x0000013C

    # MessageId: CRITICAL_INITIALIZATION_FAILURE
    # MessageText:
    # CRITICAL_INITIALIZATION_FAILURE
    CRITICAL_INITIALIZATION_FAILURE = 0x0000013D

    # MessageId: ERRATA_WORKAROUND_UNSUCCESSFUL
    # MessageText:
    # ERRATA_WORKAROUND_UNSUCCESSFUL
    ERRATA_WORKAROUND_UNSUCCESSFUL = 0x0000013E

    # MessageId: STORAGE_DEVICE_ABNORMALITY_DETECTED
    # MessageText:
    # STORAGE_DEVICE_ABNORMALITY_DETECTED
    STORAGE_DEVICE_ABNORMALITY_DETECTED = 0x00000140

    # MessageId: VIDEO_ENGINE_TIMEOUT_DETECTED
    # MessageText:
    # VIDEO_ENGINE_TIMEOUT_DETECTED
    VIDEO_ENGINE_TIMEOUT_DETECTED = 0x00000141

    # MessageId: VIDEO_TDR_APPLICATION_BLOCKED
    # MessageText:
    # VIDEO_TDR_APPLICATION_BLOCKED
    VIDEO_TDR_APPLICATION_BLOCKED = 0x00000142

    # MessageId: PROCESSOR_DRIVER_INTERNAL
    # MessageText:
    # PROCESSOR_DRIVER_INTERNAL
    PROCESSOR_DRIVER_INTERNAL = 0x00000143

    # MessageId: BUGCODE_USB3_DRIVER
    # MessageText:
    # BUGCODE_USB3_DRIVER
    BUGCODE_USB3_DRIVER = 0x00000144

    # MessageId: SECURE_BOOT_VIOLATION
    # MessageText:
    # SECURE_BOOT_VIOLATION
    SECURE_BOOT_VIOLATION = 0x00000145

    # MessageId: NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED
    # MessageText:
    # NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED
    NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED = 0x00000146

    # MessageId: ABNORMAL_RESET_DETECTED
    # MessageText:
    # ABNORMAL_RESET_DETECTED
    ABNORMAL_RESET_DETECTED = 0x00000147

    # MessageId: IO_OBJECT_INVALID
    # MessageText:
    # IO_OBJECT_INVALID
    IO_OBJECT_INVALID = 0x00000148

    # MessageId: REFS_FILE_SYSTEM
    # MessageText:
    # REFS_FILE_SYSTEM
    REFS_FILE_SYSTEM = 0x00000149

    # MessageId: KERNEL_WMI_INTERNAL
    # MessageText:
    # KERNEL_WMI_INTERNAL
    KERNEL_WMI_INTERNAL = 0x0000014A

    # MessageId: SOC_SUBSYSTEM_FAILURE
    # MessageText:
    # SOC_SUBSYSTEM_FAILURE
    SOC_SUBSYSTEM_FAILURE = 0x0000014B

    # MessageId: FATAL_ABNORMAL_RESET_ERROR
    # MessageText:
    # FATAL_ABNORMAL_RESET_ERROR
    FATAL_ABNORMAL_RESET_ERROR = 0x0000014C

    # MessageId: EXCEPTION_SCOPE_INVALID
    # MessageText:
    # EXCEPTION_SCOPE_INVALID
    EXCEPTION_SCOPE_INVALID = 0x0000014D

    # MessageId: SOC_CRITICAL_DEVICE_REMOVED
    # MessageText:
    # SOC_CRITICAL_DEVICE_REMOVED
    SOC_CRITICAL_DEVICE_REMOVED = 0x0000014E

    # MessageId: PDC_WATCHDOG_TIMEOUT
    # MessageText:
    # PDC_WATCHDOG_TIMEOUT
    PDC_WATCHDOG_TIMEOUT = 0x0000014F

    # MessageId: TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK
    # MessageText:
    # TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK
    TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK = 0x00000150

    # MessageId: UNSUPPORTED_INSTRUCTION_MODE
    # MessageText:
    # UNSUPPORTED_INSTRUCTION_MODE
    UNSUPPORTED_INSTRUCTION_MODE = 0x00000151

    # MessageId: INVALID_PUSH_LOCK_FLAGS
    # MessageText:
    # INVALID_PUSH_LOCK_FLAGS
    INVALID_PUSH_LOCK_FLAGS = 0x00000152

    # MessageId: KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION
    # MessageText:
    # KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION
    KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION = 0x00000153

    # MessageId: UNEXPECTED_STORE_EXCEPTION
    # MessageText:
    # UNEXPECTED_STORE_EXCEPTION
    UNEXPECTED_STORE_EXCEPTION = 0x00000154

    # MessageId: OS_DATA_TAMPERING
    # MessageText:
    # OS_DATA_TAMPERING
    OS_DATA_TAMPERING = 0x00000155

    # MessageId: WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP
    # MessageText:
    # WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP
    WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP = 0x00000156

    # MessageId: KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION
    # MessageText:
    # KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION
    KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION = 0x00000157

    # MessageId: ILLEGAL_IOMMU_PAGE_FAULT
    # MessageText:
    # ILLEGAL_IOMMU_PAGE_FAULT
    ILLEGAL_IOMMU_PAGE_FAULT = 0x00000158

    # MessageId: HAL_ILLEGAL_IOMMU_PAGE_FAULT
    # MessageText:
    # HAL_ILLEGAL_IOMMU_PAGE_FAULT
    HAL_ILLEGAL_IOMMU_PAGE_FAULT = 0x00000159

    # MessageId: SDBUS_INTERNAL_ERROR
    # MessageText:
    # SDBUS_INTERNAL_ERROR
    SDBUS_INTERNAL_ERROR = 0x0000015A

    # MessageId: WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE
    # MessageText:
    # WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE
    WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE = 0x0000015B

    # MessageId: PDC_WATCHDOG_TIMEOUT_LIVEDUMP
    # MessageText:
    # PDC_WATCHDOG_TIMEOUT_LIVEDUMP
    PDC_WATCHDOG_TIMEOUT_LIVEDUMP = 0x0000015C

    # MessageId: SOC_SUBSYSTEM_FAILURE_LIVEDUMP
    # MessageText:
    # SOC_SUBSYSTEM_FAILURE_LIVEDUMP
    SOC_SUBSYSTEM_FAILURE_LIVEDUMP = 0x0000015D

    # MessageId: BUGCODE_NDIS_DRIVER_LIVE_DUMP
    # MessageText:
    # BUGCODE_NDIS_DRIVER_LIVE_DUMP
    BUGCODE_NDIS_DRIVER_LIVE_DUMP = 0x0000015E

    # MessageId: CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP
    # MessageText:
    # CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP
    CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP = 0x0000015F

    # MessageId: WIN32K_ATOMIC_CHECK_FAILURE
    # MessageText:
    # WIN32K_ATOMIC_CHECK_FAILURE
    WIN32K_ATOMIC_CHECK_FAILURE = 0x00000160

    # MessageId: LIVE_SYSTEM_DUMP
    # MessageText:
    # LIVE_SYSTEM_DUMP
    LIVE_SYSTEM_DUMP = 0x00000161

    # MessageId: KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE
    # MessageText:
    # KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE
    KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE = 0x00000162

    # MessageId: WORKER_THREAD_TEST_CONDITION
    # MessageText:
    # WORKER_THREAD_TEST_CONDITION
    WORKER_THREAD_TEST_CONDITION = 0x00000163

    # MessageId: WIN32K_CRITICAL_FAILURE
    # MessageText:
    # WIN32K_CRITICAL_FAILURE
    WIN32K_CRITICAL_FAILURE = 0x00000164

    # MessageId: CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP
    CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP = 0x00000165

    # MessageId: CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP
    CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP = 0x00000166

    # MessageId: CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP
    CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP = 0x00000167

    # MessageId: CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP
    CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP = 0x00000168

    # MessageId: CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP
    CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP = 0x00000169

    # MessageId: CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP
    CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP = 0x0000016A

    # MessageId: CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP
    CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP = 0x0000016B

    # MessageId: INVALID_RUNDOWN_PROTECTION_FLAGS
    # MessageText:
    # INVALID_RUNDOWN_PROTECTION_FLAGS
    INVALID_RUNDOWN_PROTECTION_FLAGS = 0x0000016C

    # MessageId: INVALID_SLOT_ALLOCATOR_FLAGS
    # MessageText:
    # INVALID_SLOT_ALLOCATOR_FLAGS
    INVALID_SLOT_ALLOCATOR_FLAGS = 0x0000016D

    # MessageId: ERESOURCE_INVALID_RELEASE
    # MessageText:
    # ERESOURCE_INVALID_RELEASE
    ERESOURCE_INVALID_RELEASE = 0x0000016E

    # MessageId: CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP
    CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP = 0x0000016F

    # MessageId: CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG
    # MessageText:
    # CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG
    CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG = 0x00000170

    # MessageId: CRYPTO_LIBRARY_INTERNAL_ERROR
    # MessageText:
    # CRYPTO_LIBRARY_INTERNAL_ERROR
    CRYPTO_LIBRARY_INTERNAL_ERROR = 0x00000171

    # MessageId: COREMSGCALL_INTERNAL_ERROR
    # MessageText:
    # COREMSGCALL_INTERNAL_ERROR
    COREMSGCALL_INTERNAL_ERROR = 0x00000173

    # MessageId: COREMSG_INTERNAL_ERROR
    # MessageText:
    # COREMSG_INTERNAL_ERROR
    COREMSG_INTERNAL_ERROR = 0x00000174

    # MessageId: PREVIOUS_FATAL_ABNORMAL_RESET_ERROR
    # MessageText:
    # PREVIOUS_FATAL_ABNORMAL_RESET_ERROR
    PREVIOUS_FATAL_ABNORMAL_RESET_ERROR = 0x00000175

    # MessageId: ELAM_DRIVER_DETECTED_FATAL_ERROR
    # MessageText:
    # ELAM_DRIVER_DETECTED_FATAL_ERROR
    ELAM_DRIVER_DETECTED_FATAL_ERROR = 0x00000178

    # MessageId: CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP
    # MessageText:
    # CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP
    CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP = 0x00000179

    # MessageId: PROFILER_CONFIGURATION_ILLEGAL
    # MessageText:
    # PROFILER_CONFIGURATION_ILLEGAL
    PROFILER_CONFIGURATION_ILLEGAL = 0x0000017B

    # MessageId: PDC_LOCK_WATCHDOG_LIVEDUMP
    # MessageText:
    # PDC_LOCK_WATCHDOG_LIVEDUMP
    PDC_LOCK_WATCHDOG_LIVEDUMP = 0x0000017C

    # MessageId: PDC_UNEXPECTED_REVOCATION_LIVEDUMP
    # MessageText:
    # PDC_UNEXPECTED_REVOCATION_LIVEDUMP
    PDC_UNEXPECTED_REVOCATION_LIVEDUMP = 0x0000017D

    # MessageId: WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT
    # MessageText:
    # WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT
    WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT = 0x00000180

    # MessageId: WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT
    # MessageText:
    # WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT
    WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT = 0x00000181

    # MessageId: WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT
    # MessageText:
    # WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT
    WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT = 0x00000182

    # MessageId: WVR_LIVEDUMP_APP_IO_TIMEOUT
    # MessageText:
    # WVR_LIVEDUMP_APP_IO_TIMEOUT
    WVR_LIVEDUMP_APP_IO_TIMEOUT = 0x00000183

    # MessageId: WVR_LIVEDUMP_MANUALLY_INITIATED
    # MessageText:
    # WVR_LIVEDUMP_MANUALLY_INITIATED
    WVR_LIVEDUMP_MANUALLY_INITIATED = 0x00000184

    # MessageId: WVR_LIVEDUMP_STATE_FAILURE
    # MessageText:
    # WVR_LIVEDUMP_STATE_FAILURE
    WVR_LIVEDUMP_STATE_FAILURE = 0x00000185

    # MessageId: WVR_LIVEDUMP_CRITICAL_ERROR
    # MessageText:
    # WVR_LIVEDUMP_CRITICAL_ERROR
    WVR_LIVEDUMP_CRITICAL_ERROR = 0x00000186

    # MessageId: VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD
    # MessageText:
    # VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD
    VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD = 0x00000187

    # MessageId: CLUSTER_CSVFS_LIVEDUMP
    # MessageText:
    # CLUSTER_CSVFS_LIVEDUMP
    CLUSTER_CSVFS_LIVEDUMP = 0x00000188

    # MessageId: BAD_OBJECT_HEADER
    # MessageText:
    # BAD_OBJECT_HEADER
    BAD_OBJECT_HEADER = 0x00000189

    # MessageId: SILO_CORRUPT
    # MessageText:
    # SILO_CORRUPT
    SILO_CORRUPT = 0x0000018A

    # MessageId: SECURE_KERNEL_ERROR
    # MessageText:
    # SECURE_KERNEL_ERROR
    SECURE_KERNEL_ERROR = 0x0000018B

    # MessageId: HYPERGUARD_VIOLATION
    # MessageText:
    # HYPERGUARD_VIOLATION
    HYPERGUARD_VIOLATION = 0x0000018C

    # MessageId: SECURE_FAULT_UNHANDLED
    # MessageText:
    # SECURE_FAULT_UNHANDLED
    SECURE_FAULT_UNHANDLED = 0x0000018D

    # MessageId: KERNEL_PARTITION_REFERENCE_VIOLATION
    # MessageText:
    # KERNEL_PARTITION_REFERENCE_VIOLATION
    KERNEL_PARTITION_REFERENCE_VIOLATION = 0x0000018E

    # MessageId: WIN32K_CRITICAL_FAILURE_LIVEDUMP
    # MessageText:
    # WIN32K_CRITICAL_FAILURE_LIVEDUMP
    WIN32K_CRITICAL_FAILURE_LIVEDUMP = 0x00000190

    # MessageId: PF_DETECTED_CORRUPTION
    # MessageText:
    # PF_DETECTED_CORRUPTION
    PF_DETECTED_CORRUPTION = 0x00000191

    # MessageId: KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL
    # MessageText:
    # KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL
    KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL = 0x00000192

    # MessageId: VIDEO_DXGKRNL_LIVEDUMP
    # MessageText:
    # VIDEO_DXGKRNL_LIVEDUMP
    VIDEO_DXGKRNL_LIVEDUMP = 0x00000193

    # MessageId: KERNEL_STORAGE_SLOT_IN_USE
    # MessageText:
    # KERNEL_STORAGE_SLOT_IN_USE
    KERNEL_STORAGE_SLOT_IN_USE = 0x00000199

    # MessageId: SMB_SERVER_LIVEDUMP
    # MessageText:
    # SMB_SERVER_LIVEDUMP
    SMB_SERVER_LIVEDUMP = 0x00000195

    # MessageId: LOADER_ROLLBACK_DETECTED
    # MessageText:
    # LOADER_ROLLBACK_DETECTED
    LOADER_ROLLBACK_DETECTED = 0x00000196

    # MessageId: WIN32K_SECURITY_FAILURE
    # MessageText:
    # WIN32K_SECURITY_FAILURE
    WIN32K_SECURITY_FAILURE = 0x00000197

    # MessageId: UFX_LIVEDUMP
    # MessageText:
    # UFX_LIVEDUMP
    UFX_LIVEDUMP = 0x00000198

    # MessageId: WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO
    # MessageText:
    # WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO
    WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO = 0x0000019A

    # MessageId: TTM_FATAL_ERROR
    # MessageText:
    # TTM_FATAL_ERROR
    TTM_FATAL_ERROR = 0x0000019B

    # MessageId: WIN32K_POWER_WATCHDOG_TIMEOUT
    # MessageText:
    # WIN32K_POWER_WATCHDOG_TIMEOUT
    WIN32K_POWER_WATCHDOG_TIMEOUT = 0x0000019C

    # MessageId: CLUSTER_SVHDX_LIVEDUMP
    # MessageText:
    # CLUSTER_SVHDX_LIVEDUMP
    CLUSTER_SVHDX_LIVEDUMP = 0x0000019D

    # MessageId: BUGCODE_NETADAPTER_DRIVER
    # MessageText:
    # BUGCODE_NETADAPTER_DRIVER
    BUGCODE_NETADAPTER_DRIVER = 0x0000019E

    # MessageId: PDC_PRIVILEGE_CHECK_LIVEDUMP
    # MessageText:
    # PDC_PRIVILEGE_CHECK_LIVEDUMP
    PDC_PRIVILEGE_CHECK_LIVEDUMP = 0x0000019F

    # MessageId: TTM_WATCHDOG_TIMEOUT
    # MessageText:
    # TTM_WATCHDOG_TIMEOUT
    TTM_WATCHDOG_TIMEOUT = 0x000001A0

    # MessageId: WIN32K_CALLOUT_WATCHDOG_LIVEDUMP
    # MessageText:
    # WIN32K_CALLOUT_WATCHDOG_LIVEDUMP
    WIN32K_CALLOUT_WATCHDOG_LIVEDUMP = 0x000001A1

    # MessageId: WIN32K_CALLOUT_WATCHDOG_BUGCHECK
    # MessageText:
    # WIN32K_CALLOUT_WATCHDOG_BUGCHECK
    WIN32K_CALLOUT_WATCHDOG_BUGCHECK = 0x000001A2

    # MessageId: CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP
    # MessageText:
    # CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP
    CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP = 0x000001A3

    # MessageId: DRIPS_SW_HW_DIVERGENCE_LIVEDUMP
    # MessageText:
    # DRIPS_SW_HW_DIVERGENCE_LIVEDUMP
    DRIPS_SW_HW_DIVERGENCE_LIVEDUMP = 0x000001A4

    # MessageId: USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP
    # MessageText:
    # USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP
    USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP = 0x000001A5

    # MessageId: DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP
    # MessageText:
    # DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP
    DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP = 0x000001C4

    # MessageId: IO_THREADPOOL_DEADLOCK_LIVEDUMP
    # MessageText:
    # IO_THREADPOOL_DEADLOCK_LIVEDUMP
    IO_THREADPOOL_DEADLOCK_LIVEDUMP = 0x000001C5

    # MessageId: FAST_ERESOURCE_PRECONDITION_VIOLATION
    # MessageText:
    # FAST_ERESOURCE_PRECONDITION_VIOLATION
    FAST_ERESOURCE_PRECONDITION_VIOLATION = 0x000001C6

    # MessageId: STORE_DATA_STRUCTURE_CORRUPTION
    # MessageText:
    # STORE_DATA_STRUCTURE_CORRUPTION
    STORE_DATA_STRUCTURE_CORRUPTION = 0x000001C7

    # MessageId: MANUALLY_INITIATED_POWER_BUTTON_HOLD
    # MessageText:
    # MANUALLY_INITIATED_POWER_BUTTON_HOLD
    MANUALLY_INITIATED_POWER_BUTTON_HOLD = 0x000001C8

    # MessageId: USER_MODE_HEALTH_MONITOR_LIVEDUMP
    # MessageText:
    # USER_MODE_HEALTH_MONITOR_LIVEDUMP
    USER_MODE_HEALTH_MONITOR_LIVEDUMP = 0x000001C9

    # MessageId: HYPERVISOR_WATCHDOG_TIMEOUT
    # MessageText:
    # HYPERVISOR_WATCHDOG_TIMEOUT
    HYPERVISOR_WATCHDOG_TIMEOUT = 0x000001CA

    # MessageId: INVALID_SILO_DETACH
    # MessageText:
    # INVALID_SILO_DETACH
    INVALID_SILO_DETACH = 0x000001CB

    # MessageId: EXRESOURCE_TIMEOUT_LIVEDUMP
    # MessageText:
    # EXRESOURCE_TIMEOUT_LIVEDUMP
    EXRESOURCE_TIMEOUT_LIVEDUMP = 0x000001CC

    # MessageId: INVALID_CALLBACK_STACK_ADDRESS
    # MessageText:
    # INVALID_CALLBACK_STACK_ADDRESS
    INVALID_CALLBACK_STACK_ADDRESS = 0x000001CD

    # MessageId: INVALID_KERNEL_STACK_ADDRESS
    # MessageText:
    # INVALID_KERNEL_STACK_ADDRESS
    INVALID_KERNEL_STACK_ADDRESS = 0x000001CE

    # MessageId: HARDWARE_WATCHDOG_TIMEOUT
    # MessageText:
    # HARDWARE_WATCHDOG_TIMEOUT
    HARDWARE_WATCHDOG_TIMEOUT = 0x000001CF

    # MessageId: ACPI_FIRMWARE_WATCHDOG_TIMEOUT
    # MessageText:
    # ACPI_FIRMWARE_WATCHDOG_TIMEOUT
    ACPI_FIRMWARE_WATCHDOG_TIMEOUT = 0x000001D0

    # MessageId: TELEMETRY_ASSERTS_LIVEDUMP
    # MessageText:
    # TELEMETRY_ASSERTS_LIVEDUMP
    TELEMETRY_ASSERTS_LIVEDUMP = 0x000001D1

    # MessageId: WORKER_THREAD_INVALID_STATE
    # MessageText:
    # WORKER_THREAD_INVALID_STATE
    WORKER_THREAD_INVALID_STATE = 0x000001D2

    # MessageId: WFP_INVALID_OPERATION
    # MessageText:
    # WFP_INVALID_OPERATION
    WFP_INVALID_OPERATION = 0x000001D3

    # MessageId: UCMUCSI_LIVEDUMP
    # MessageText:
    # UCMUCSI_LIVEDUMP
    UCMUCSI_LIVEDUMP = 0x000001D4

    # MessageId: DRIVER_PNP_WATCHDOG
    # MessageText:
    # DRIVER_PNP_WATCHDOG
    DRIVER_PNP_WATCHDOG = 0x000001D5

    # MessageId: XBOX_ERACTRL_CS_TIMEOUT
    # MessageText:
    # XBOX_ERACTRL_CS_TIMEOUT
    XBOX_ERACTRL_CS_TIMEOUT = 0x00000356

    # MessageId: XBOX_CORRUPTED_IMAGE
    # MessageText:
    # XBOX_CORRUPTED_IMAGE
    XBOX_CORRUPTED_IMAGE = 0x00000357

    # MessageId: XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW
    # MessageText:
    # XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW
    XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW = 0x00000358

    # MessageId: XBOX_CORRUPTED_IMAGE_BASE
    # MessageText:
    # XBOX_CORRUPTED_IMAGE_BASE
    XBOX_CORRUPTED_IMAGE_BASE = 0x00000359

    # MessageId: XBOX_360_SYSTEM_CRASH
    # MessageText:
    # XBOX_360_SYSTEM_CRASH
    XBOX_360_SYSTEM_CRASH = 0x00000360

    # MessageId: XBOX_360_SYSTEM_CRASH_RESERVED
    # MessageText:
    # XBOX_360_SYSTEM_CRASH_RESERVED
    XBOX_360_SYSTEM_CRASH_RESERVED = 0x00000420

    # MessageId: HYPERVISOR_ERROR
    # MessageText:
    # HYPERVISOR_ERROR
    HYPERVISOR_ERROR = 0x00020001
    WINLOGON_FATAL_ERROR = 0xC000021A
    MANUALLY_INITIATED_CRASH1 = 0xDEADDEAD
    BUGCHECK_CONTEXT_MODIFIER = 0x80000000
# END IF   _BUGCODES_
