__REQUIRED_RPCNDR_H_VERSION__ = 0x1F4
__REQUIRED_RPCSAL_H_VERSION__ = 0x64
# from rpc_h import * # NOQA
# from rpcndr_h import * # NOQA

import ctypes
import comtypes

from ctypes.wintypes import (
    VARIANT_BOOL,
    SMALL_RECT,
    _COORD as COORD,
    MSG,
    WIN32_FIND_DATAA,
    WIN32_FIND_DATAW,
)


def INTERFACE(name):
    return type(name, (comtypes.IUnknown,), {})


NULL = None

cdecl = ctypes.CFUNCTYPE
CDECL = cdecl

pascal = ctypes.WINFUNCTYPE
PASCAL = pascal

CALLBACK = ctypes.CFUNCTYPE

WINAPIV = ctypes.CFUNCTYPE
WINAPI = ctypes.WINFUNCTYPE
WINAPI_INLINE = WINAPI
APIENTRY = WINAPI
APIPRIVATE = WINAPI


VOID = ctypes.c_void_p
LPCOLESTR = ctypes.c_wchar_p
LPOLESTR = ctypes.c_wchar_p
OLESTR = ctypes.c_wchar_p
LPCVOID = ctypes.c_void_p
LPVOID = ctypes.c_void_p


POINTER = ctypes.POINTER
POINTER_32 = POINTER
POINTER_64 = POINTER
POINTER_SIGNED = POINTER
POINTER_UNSIGNED = POINTER

ENUM = ctypes.c_int
ATOM = ctypes.c_ushort

PROC = LPCVOID

far = LPCVOID
FAR = far
FARPROC = far

near = LPCVOID
NEAR = near
NEARPROC = near


if ctypes.sizeof(ctypes.c_long) == ctypes.sizeof(ctypes.c_void_p):
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulong
    LONG_PTR = ctypes.c_long
    ULONG_PTR = ctypes.c_ulong
elif ctypes.sizeof(ctypes.c_longlong) == ctypes.sizeof(ctypes.c_void_p):
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulonglong
    LONG_PTR = ctypes.c_longlong
    ULONG_PTR = ctypes.c_ulonglong
else:
    INT_PTR = ctypes.c_int64
    UINT_PTR = ctypes.c_ulong
    LONG_PTR = ctypes.c_long
    ULONG_PTR =ctypes. c_ulong


PINT_PTR = POINTER(INT_PTR)
PUINT_PTR = POINTER(UINT_PTR)

PLONG_PTR = POINTER(LONG_PTR)
PULONG_PTR = POINTER(ULONG_PTR)

DWORD_PTR = ULONG_PTR
PDWORD_PTR = POINTER(DWORD_PTR)


BYTE = ctypes.c_byte
PBYTE = POINTER(BYTE)
LPBYTE = POINTER(BYTE)

TBYTE = ctypes.c_wchar
PTBYTE = POINTER(TBYTE)

WSTRING = ctypes.c_wchar_p
UBYTE = ctypes.c_ubyte

# noinspection PyTypeChecker
PBYTE256 = ctypes.c_ubyte * 256

WORD = ctypes.c_ushort
LPWORD = POINTER(WORD)
PWORD = POINTER(WORD)

BOOL = ctypes.c_long
PBOOL = POINTER(BOOL)
LPBOOL = POINTER(BOOL)

CHAR = ctypes.c_char
TCHAR = ctypes.c_wchar

INT = ctypes.c_int
PINT = POINTER(INT)
LPINT = POINTER(INT)

INT8 = ctypes.c_int8
PINT8 = POINTER(INT8)

INT16 = ctypes.c_int16
PINT16 = POINTER(INT16)

INT32 = ctypes.c_int32
PINT32 = POINTER(INT32)

INT64 = ctypes.c_int64
PINT64 = POINTER(INT64)

UINT = ctypes.c_uint
PUINT = POINTER(UINT)

UINT8 = ctypes.c_uint8
PUINT8 = POINTER(UINT8)

UINT16 = ctypes.c_uint16
PUINT16 = POINTER(UINT16)

UINT32 = ctypes.c_uint32
PUINT32 = POINTER(UINT32)

UINT64 = ctypes.c_uint64
PUINT64 = POINTER(UINT64)


HALF_PTR = ctypes.c_int
PHALF_PTR = POINTER(HALF_PTR)

UHALF_PTR = ctypes.c_uint
PUHALF_PTR = POINTER(UHALF_PTR)

LONG = ctypes.c_long
LPLONG = POINTER(LONG)

LONG32 = ctypes.c_int32
PLONG32 = POINTER(LONG32)

LONG64 = ctypes.c_int64
PLONG64 = POINTER(LONG64)

ULONG32 = ctypes.c_uint
PULONG32 = POINTER(ULONG32)

ULONG64 = ctypes.c_uint64
PULONG64 = POINTER(ULONG64)

import ctypes.wintypes

DWORD = ctypes.c_ulong
LPDWORD = POINTER(DWORD)
PDWORD = POINTER(DWORD)

DWORD32 = UINT32
PDWORD32 = POINTER(DWORD32)

DWORD64 = UINT64
PDWORD64 = POINTER(DWORD64)

DOUBLE = ctypes.c_double

FLOAT = ctypes.c_float
PFLOAT = POINTER(FLOAT)

SHORT = ctypes.c_short

SIZE_T = ctypes.c_size_t
PSIZE_T = POINTER(SIZE_T)

SSIZE_T = ctypes.c_ssize_t
PSSIZE_T = POINTER(SSIZE_T)

OLESTR = ctypes.c_wchar_p
LPOLESTR = POINTER(OLESTR)
LPCOLESTR = POINTER(OLESTR)

WPARAM = UINT_PTR
LPARAM = LONG_PTR
LRESULT = LONG_PTR
HFILE = INT
HEVENT = POINTER(VOID)

KAFFINITY = ULONG_PTR
PKAFFINITY = POINTER(KAFFINITY)


from shared.ntdef_h import (
    ALL_PROCESSOR_GROUPS,
    ANSI_NULL,
    ANSI_STRING,
    ANSI_STRING32,
    ANSI_STRING64,
    ANYSIZE_ARRAY,
    APPLICATION_ERROR_MASK,
    ARGUMENT_PRESENT,
    ARRAYSIZE,
    BOOLEAN,
    CANSI_STRING,
    CCHAR,
    CFORCEINLINE,
    CLONG,
    COMPARTMENT_ID,
    COMPILETIME_OR_2FLAGS,
    COMPILETIME_OR_3FLAGS,
    COMPILETIME_OR_4FLAGS,
    COMPILETIME_OR_5FLAGS,
    COMPILETIME_OR_6FLAGS,
    CONST,
    CONTAINING_RECORD,
    CSHORT,
    CSTRING,
    C_ASSERT,
    DBG_UNREFERENCED_LOCAL_VARIABLE,
    DBG_UNREFERENCED_PARAMETER,
    DECLARE_CONST_UNICODE_STRING,
    DECLARE_GLOBAL_CONST_UNICODE_STRING,
    DECLARE_HANDLE,
    DECLARE_UNICODE_STRING_SIZE,
    DECLSPEC_ADDRSAFE,
    DECLSPEC_ALIGN,
    DECLSPEC_CACHEALIGN,
    DECLSPEC_CHPE_GUEST,
    DECLSPEC_CHPE_PATCHABLE,
    DECLSPEC_DEPRECATED,
    DECLSPEC_DEPRECATED_DDK,
    DECLSPEC_GUARDIGNORE,
    DECLSPEC_GUARDNOCF,
    DECLSPEC_GUARD_SUPPRESS,
    DECLSPEC_IMPORT,
    DECLSPEC_NOINLINE,
    DECLSPEC_NORETURN,
    DECLSPEC_NOTHROW,
    DECLSPEC_NOVTABLE,
    DECLSPEC_SAFEBUFFERS,
    DECLSPEC_SELECTANY,
    DECLSPEC_UUID,
    DEFAULT_UNREACHABLE,
    DEFINE_ENUM_FLAG_OPERATORS,
    DUMMYUNIONNAME,
    DWORDLONG,
    ERROR_SEVERITY_ERROR,
    ERROR_SEVERITY_INFORMATIONAL,
    ERROR_SEVERITY_SUCCESS,
    ERROR_SEVERITY_WARNING,
    EVENT_TYPE,
    FALSE,
    FASTCALL,
    FCHAR,
    FIELD_OFFSET,
    FLOAT128,
    FLONG,
    FORCEINLINE,
    FSHORT,
    GROUP_AFFINITY,
    HANDLE,
    HRESULT,
    HighTime,
    IFACEMETHODIMP,
    IFACEMETHODIMPV,
    IFACEMETHODIMPV_,
    IFACEMETHODIMP_,
    InitializeObjectAttributes,
    Int32x32To64,
    Int64ShllMod32,
    Int64ShraMod32,
    Int64ShrlMod32,
    KIRQL,
    LANGID,
    LANGIDFROMLCID,
    LANG_AFRIKAANS,
    LANG_ALBANIAN,
    LANG_ALSATIAN,
    LANG_AMHARIC,
    LANG_ARABIC,
    LANG_ARMENIAN,
    LANG_ASSAMESE,
    LANG_AZERBAIJANI,
    LANG_AZERI,
    LANG_BANGLA,
    LANG_BASHKIR,
    LANG_BASQUE,
    LANG_BELARUSIAN,
    LANG_BENGALI,
    LANG_BOSNIAN,
    LANG_BOSNIAN_NEUTRAL,
    LANG_BRETON,
    LANG_BULGARIAN,
    LANG_CATALAN,
    LANG_CENTRAL_KURDISH,
    LANG_CHEROKEE,
    LANG_CHINESE,
    LANG_CHINESE_SIMPLIFIED,
    LANG_CHINESE_TRADITIONAL,
    LANG_CORSICAN,
    LANG_CROATIAN,
    LANG_CZECH,
    LANG_DANISH,
    LANG_DARI,
    LANG_DIVEHI,
    LANG_DUTCH,
    LANG_ENGLISH,
    LANG_ESTONIAN,
    LANG_FAEROESE,
    LANG_FARSI,
    LANG_FILIPINO,
    LANG_FINNISH,
    LANG_FRENCH,
    LANG_FRISIAN,
    LANG_FULAH,
    LANG_GALICIAN,
    LANG_GEORGIAN,
    LANG_GERMAN,
    LANG_GREEK,
    LANG_GREENLANDIC,
    LANG_GUJARATI,
    LANG_HAUSA,
    LANG_HAWAIIAN,
    LANG_HEBREW,
    LANG_HINDI,
    LANG_HUNGARIAN,
    LANG_ICELANDIC,
    LANG_IGBO,
    LANG_INDONESIAN,
    LANG_INUKTITUT,
    LANG_INVARIANT,
    LANG_IRISH,
    LANG_ITALIAN,
    LANG_JAPANESE,
    LANG_KANNADA,
    LANG_KASHMIRI,
    LANG_KAZAK,
    LANG_KHMER,
    LANG_KICHE,
    LANG_KINYARWANDA,
    LANG_KONKANI,
    LANG_KOREAN,
    LANG_KYRGYZ,
    LANG_LAO,
    LANG_LATVIAN,
    LANG_LITHUANIAN,
    LANG_LOWER_SORBIAN,
    LANG_LUXEMBOURGISH,
    LANG_MACEDONIAN,
    LANG_MALAY,
    LANG_MALAYALAM,
    LANG_MALTESE,
    LANG_MANIPURI,
    LANG_MAORI,
    LANG_MAPUDUNGUN,
    LANG_MARATHI,
    LANG_MOHAWK,
    LANG_MONGOLIAN,
    LANG_NEPALI,
    LANG_NEUTRAL,
    LANG_NORWEGIAN,
    LANG_OCCITAN,
    LANG_ODIA,
    LANG_ORIYA,
    LANG_PASHTO,
    LANG_PERSIAN,
    LANG_POLISH,
    LANG_PORTUGUESE,
    LANG_PULAR,
    LANG_PUNJABI,
    LANG_QUECHUA,
    LANG_ROMANIAN,
    LANG_ROMANSH,
    LANG_RUSSIAN,
    LANG_SAKHA,
    LANG_SAMI,
    LANG_SANSKRIT,
    LANG_SCOTTISH_GAELIC,
    LANG_SERBIAN,
    LANG_SERBIAN_NEUTRAL,
    LANG_SINDHI,
    LANG_SINHALESE,
    LANG_SLOVAK,
    LANG_SLOVENIAN,
    LANG_SOTHO,
    LANG_SPANISH,
    LANG_SWAHILI,
    LANG_SWEDISH,
    LANG_SYRIAC,
    LANG_SYSTEM_DEFAULT,
    LANG_TAJIK,
    LANG_TAMAZIGHT,
    LANG_TAMIL,
    LANG_TATAR,
    LANG_TELUGU,
    LANG_THAI,
    LANG_TIBETAN,
    LANG_TIGRIGNA,
    LANG_TIGRINYA,
    LANG_TSWANA,
    LANG_TURKISH,
    LANG_TURKMEN,
    LANG_UIGHUR,
    LANG_UKRAINIAN,
    LANG_UPPER_SORBIAN,
    LANG_URDU,
    LANG_USER_DEFAULT,
    LANG_UZBEK,
    LANG_VALENCIAN,
    LANG_VIETNAMESE,
    LANG_WELSH,
    LANG_WOLOF,
    LANG_XHOSA,
    LANG_YAKUT,
    LANG_YI,
    LANG_YORUBA,
    LANG_ZULU,
    LARGE_INTEGER,
    LCID,
    LIST_ENTRY,
    LIST_ENTRY32,
    LIST_ENTRY64,
    LOCALE_CUSTOM_DEFAULT,
    LOCALE_CUSTOM_UI_DEFAULT,
    LOCALE_CUSTOM_UNSPECIFIED,
    LOCALE_INVARIANT,
    LOCALE_NAME_MAX_LENGTH,
    LOCALE_NEUTRAL,
    LOCALE_SYSTEM_DEFAULT,
    LOCALE_TRANSIENT_KEYBOARD1,
    LOCALE_TRANSIENT_KEYBOARD2,
    LOCALE_TRANSIENT_KEYBOARD3,
    LOCALE_TRANSIENT_KEYBOARD4,
    LOCALE_UNASSIGNED_LCID,
    LOCALE_USER_DEFAULT,
    LOGICAL,
    LONGLONG,
    LP,
    LPCCH,
    LPCH,
    LPCSTR,
    LPCTCH,
    LPCTSTR,
    LPCUTSTR,
    LPCUWCHAR,
    LPCUWSTR,
    LPCWCH,
    LPCWCHAR,
    LPCWSTR,
    LPSTR,
    LPTCH,
    LPTSTR,
    LPUTSTR,
    LPUWSTR,
    LPWCH,
    LPWSTR,
    LUID,
    LowTime,
    MAKELANGID,
    MAKELCID,
    MAKESORTLCID,
    MAXCHAR,
    MAXIMUM_PROCESSORS,
    MAXIMUM_PROC_PER_GROUP,
    MAXLONG,
    MAXLONGLONG,
    MAXSHORT,
    MAXUCHAR,
    MAXULONG,
    MAXUSHORT,
    MAX_NATURAL_ALIGNMENT,
    MAX_UCSCHAR,
    MEMORY_ALLOCATION_ALIGNMENT,
    MINCHAR,
    MINLONG,
    MINSHORT,
    MIN_UCSCHAR,
    NLS_VALID_LOCALE_MASK,
    NOP_FUNCTION,
    NPSTR,
    NTAPI,
    NTAPI_INLINE,
    NTSTATUS,
    NTSYSAPI,
    NTSYSCALLAPI,
    NT_ERROR,
    NT_INFORMATION,
    NT_PRODUCT_TYPE,
    NT_SUCCESS,
    NT_WARNING,
    NULL,
    NULL64,
    NWPSTR,
    OBJECTID,
    OBJECT_ATTRIBUTES,
    OBJECT_ATTRIBUTES32,
    OBJECT_ATTRIBUTES64,
    OBJ_CASE_INSENSITIVE,
    OBJ_DONT_REPARSE,
    OBJ_EXCLUSIVE,
    OBJ_FORCE_ACCESS_CHECK,
    OBJ_HANDLE_TAGBITS,
    OBJ_IGNORE_IMPERSONATED_DEVICEMAP,
    OBJ_INHERIT,
    OBJ_KERNEL_HANDLE,
    OBJ_OPENIF,
    OBJ_OPENLINK,
    OBJ_PERMANENT,
    OBJ_VALID_ATTRIBUTES,
    OEM_STRING,
    PANSI_STRING,
    PANSI_STRING32,
    PANSI_STRING64,
    PBOOLEAN,
    PCANSI_STRING,
    PCCH,
    PCCHAR,
    PCH,
    PCHAR,
    PCLONG,
    PCNTSTATUS,
    PCNZCH,
    PCNZTCH,
    PCNZWCH,
    PCOBJECT_ATTRIBUTES,
    PCOBJECT_ATTRIBUTES32,
    PCOBJECT_ATTRIBUTES64,
    PCOEM_STRING,
    PCOMPARTMENT_ID,
    PCSCHAR,
    PCSHORT,
    PCSTR,
    PCSTRING,
    PCSZ,
    PCTCH,
    PCTSTR,
    PCUCHAR,
    PCUCSCHAR,
    PCUCSSTR,
    PCULONG,
    PCUNICODE_STRING,
    PCUNZTCH,
    PCUNZWCH,
    PCUQUAD,
    PCUSHORT,
    PCUTSTR,
    PCUUCSCHAR,
    PCUUCSSTR,
    PCUWCHAR,
    PCUWSTR,
    PCUZZTSTR,
    PCUZZWSTR,
    PCWCH,
    PCWCHAR,
    PCWNF_STATE_NAME,
    PCWSTR,
    PCZPCSTR,
    PCZPCWSTR,
    PCZPSTR,
    PCZPWSTR,
    PCZZSTR,
    PCZZTSTR,
    PCZZWSTR,
    PDWORDLONG,
    PFLOAT128,
    PFORCEINLINE,
    PGROUP_AFFINITY,
    PHANDLE,
    PHYSICAL_ADDRESS,
    PKIRQL,
    PLARGE_INTEGER,
    PLCID,
    PLIST_ENTRY,
    PLIST_ENTRY32,
    PLIST_ENTRY64,
    PLOGICAL,
    PLONG,
    PLONGLONG,
    PLUID,
    PNTSTATUS,
    PNT_PRODUCT_TYPE,
    PNZCH,
    PNZTCH,
    PNZWCH,
    POBJECT_ATTRIBUTES,
    POBJECT_ATTRIBUTES32,
    POBJECT_ATTRIBUTES64,
    POEM_STRING,
    PPHYSICAL_ADDRESS,
    PPROCESSOR_NUMBER,
    PQUAD,
    PRAGMA_DEPRECATED_DDK,
    PRIMARYLANGID,
    PROBE_ALIGNMENT,
    PROBE_ALIGNMENT32,
    PROCESSOR_NUMBER,
    PRODUCT_ANDROMEDA,
    PRODUCT_ARM64_SERVER,
    PRODUCT_AZURE_NANO_SERVER,
    PRODUCT_AZURE_SERVER_CORE,
    PRODUCT_BUSINESS,
    PRODUCT_BUSINESS_N,
    PRODUCT_CLOUD,
    PRODUCT_CLOUDN,
    PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER,
    PRODUCT_CLOUD_STORAGE_SERVER,
    PRODUCT_CLUSTER_SERVER,
    PRODUCT_CLUSTER_SERVER_V,
    PRODUCT_CONNECTED_CAR,
    PRODUCT_CORE,
    PRODUCT_CORE_ARM,
    PRODUCT_CORE_CONNECTED,
    PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC,
    PRODUCT_CORE_CONNECTED_N,
    PRODUCT_CORE_CONNECTED_SINGLELANGUAGE,
    PRODUCT_CORE_COUNTRYSPECIFIC,
    PRODUCT_CORE_N,
    PRODUCT_CORE_SINGLELANGUAGE,
    PRODUCT_DATACENTER_A_SERVER_CORE,
    PRODUCT_DATACENTER_EVALUATION_SERVER,
    PRODUCT_DATACENTER_EVALUATION_SERVER_CORE,
    PRODUCT_DATACENTER_NANO_SERVER,
    PRODUCT_DATACENTER_SERVER,
    PRODUCT_DATACENTER_SERVER_CORE,
    PRODUCT_DATACENTER_SERVER_CORE_V,
    PRODUCT_DATACENTER_SERVER_V,
    PRODUCT_DATACENTER_WS_SERVER_CORE,
    PRODUCT_EDUCATION,
    PRODUCT_EDUCATION_N,
    PRODUCT_EMBEDDED,
    PRODUCT_EMBEDDED_A,
    PRODUCT_EMBEDDED_AUTOMOTIVE,
    PRODUCT_EMBEDDED_E,
    PRODUCT_EMBEDDED_EVAL,
    PRODUCT_EMBEDDED_E_EVAL,
    PRODUCT_EMBEDDED_INDUSTRY,
    PRODUCT_EMBEDDED_INDUSTRY_A,
    PRODUCT_EMBEDDED_INDUSTRY_A_E,
    PRODUCT_EMBEDDED_INDUSTRY_E,
    PRODUCT_EMBEDDED_INDUSTRY_EVAL,
    PRODUCT_EMBEDDED_INDUSTRY_E_EVAL,
    PRODUCT_ENTERPRISE,
    PRODUCT_ENTERPRISEG,
    PRODUCT_ENTERPRISEGN,
    PRODUCT_ENTERPRISE_E,
    PRODUCT_ENTERPRISE_EVALUATION,
    PRODUCT_ENTERPRISE_N,
    PRODUCT_ENTERPRISE_N_EVALUATION,
    PRODUCT_ENTERPRISE_S,
    PRODUCT_ENTERPRISE_SERVER,
    PRODUCT_ENTERPRISE_SERVER_CORE,
    PRODUCT_ENTERPRISE_SERVER_CORE_V,
    PRODUCT_ENTERPRISE_SERVER_IA64,
    PRODUCT_ENTERPRISE_SERVER_V,
    PRODUCT_ENTERPRISE_SUBSCRIPTION,
    PRODUCT_ENTERPRISE_SUBSCRIPTION_N,
    PRODUCT_ENTERPRISE_S_EVALUATION,
    PRODUCT_ENTERPRISE_S_N,
    PRODUCT_ENTERPRISE_S_N_EVALUATION,
    PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL,
    PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC,
    PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT,
    PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC,
    PRODUCT_HOLOGRAPHIC,
    PRODUCT_HOME_BASIC,
    PRODUCT_HOME_BASIC_E,
    PRODUCT_HOME_BASIC_N,
    PRODUCT_HOME_PREMIUM,
    PRODUCT_HOME_PREMIUM_E,
    PRODUCT_HOME_PREMIUM_N,
    PRODUCT_HOME_PREMIUM_SERVER,
    PRODUCT_HOME_SERVER,
    PRODUCT_HUBOS,
    PRODUCT_HYPERV,
    PRODUCT_INDUSTRY_HANDHELD,
    PRODUCT_IOTUAP,
    PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT,
    PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING,
    PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY,
    PRODUCT_MULTIPOINT_PREMIUM_SERVER,
    PRODUCT_MULTIPOINT_STANDARD_SERVER,
    PRODUCT_NANO_SERVER,
    PRODUCT_ONECOREUPDATEOS,
    PRODUCT_PPI_PRO,
    PRODUCT_PROFESSIONAL,
    PRODUCT_PROFESSIONAL_E,
    PRODUCT_PROFESSIONAL_EMBEDDED,
    PRODUCT_PROFESSIONAL_N,
    PRODUCT_PROFESSIONAL_S,
    PRODUCT_PROFESSIONAL_STUDENT,
    PRODUCT_PROFESSIONAL_STUDENT_N,
    PRODUCT_PROFESSIONAL_S_N,
    PRODUCT_PROFESSIONAL_WMC,
    PRODUCT_PRO_CHINA,
    PRODUCT_PRO_FOR_EDUCATION,
    PRODUCT_PRO_FOR_EDUCATION_N,
    PRODUCT_PRO_SINGLE_LANGUAGE,
    PRODUCT_PRO_WORKSTATION,
    PRODUCT_PRO_WORKSTATION_N,
    PRODUCT_SB_SOLUTION_SERVER,
    PRODUCT_SB_SOLUTION_SERVER_EM,
    PRODUCT_SERVERRDSH,
    PRODUCT_SERVER_FOR_SB_SOLUTIONS,
    PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM,
    PRODUCT_SERVER_FOR_SMALLBUSINESS,
    PRODUCT_SERVER_FOR_SMALLBUSINESS_V,
    PRODUCT_SERVER_FOUNDATION,
    PRODUCT_SMALLBUSINESS_SERVER,
    PRODUCT_SMALLBUSINESS_SERVER_PREMIUM,
    PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE,
    PRODUCT_SOLUTION_EMBEDDEDSERVER,
    PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE,
    PRODUCT_STANDARD_A_SERVER_CORE,
    PRODUCT_STANDARD_EVALUATION_SERVER,
    PRODUCT_STANDARD_EVALUATION_SERVER_CORE,
    PRODUCT_STANDARD_NANO_SERVER,
    PRODUCT_STANDARD_SERVER,
    PRODUCT_STANDARD_SERVER_CORE,
    PRODUCT_STANDARD_SERVER_CORE_V,
    PRODUCT_STANDARD_SERVER_SOLUTIONS,
    PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE,
    PRODUCT_STANDARD_SERVER_V,
    PRODUCT_STANDARD_WS_SERVER_CORE,
    PRODUCT_STARTER,
    PRODUCT_STARTER_E,
    PRODUCT_STARTER_N,
    PRODUCT_STORAGE_ENTERPRISE_SERVER,
    PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE,
    PRODUCT_STORAGE_EXPRESS_SERVER,
    PRODUCT_STORAGE_EXPRESS_SERVER_CORE,
    PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER,
    PRODUCT_STORAGE_STANDARD_SERVER,
    PRODUCT_STORAGE_STANDARD_SERVER_CORE,
    PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER,
    PRODUCT_STORAGE_WORKGROUP_SERVER,
    PRODUCT_STORAGE_WORKGROUP_SERVER_CORE,
    PRODUCT_THINPC,
    PRODUCT_ULTIMATE,
    PRODUCT_ULTIMATE_E,
    PRODUCT_ULTIMATE_N,
    PRODUCT_UNDEFINED,
    PRODUCT_UNLICENSED,
    PRODUCT_UTILITY_VM,
    PRODUCT_WEB_SERVER,
    PRODUCT_WEB_SERVER_CORE,
    PRTL_BALANCED_NODE,
    PRTL_REFERENCE_COUNT,
    PRTL_REFERENCE_COUNT32,
    PSCHAR,
    PSHORT,
    PSINGLE_LIST_ENTRY,
    PSINGLE_LIST_ENTRY32,
    PSTR,
    PSTRING,
    PSTRING32,
    PSTRING64,
    PSZ,
    PTCH,
    PTCHAR,
    PTIME,
    PTSTR,
    PTUCHAR,
    PUCHAR,
    PUCSCHAR,
    PUCSSTR,
    PULARGE_INTEGER,
    PULONG,
    PULONGLONG,
    PUNICODE_STRING,
    PUNICODE_STRING32,
    PUNICODE_STRING64,
    PUNZTCH,
    PUNZWCH,
    PUQUAD,
    PUSHORT,
    PUTSTR,
    PUUCSCHAR,
    PUUCSSTR,
    PUWSTR,
    PUZZTSTR,
    PUZZWSTR,
    PVOID,
    PVOID64,
    PWCH,
    PWCHAR,
    PWNF_STATE_NAME,
    PWSTR,
    PZPCSTR,
    PZPCWSTR,
    PZPSTR,
    PZPTSTR,
    PZPWSTR,
    PZZSTR,
    PZZTSTR,
    PZZWSTR,
    QUAD,
    RESTRICTED_POINTER,
    RESTRICTED_POINTERPRLIST_ENTRY,
    RTL_BALANCED_NODE,
    RTL_BALANCED_NODE_GET_PARENT_POINTER,
    RTL_BALANCED_NODE_RESERVED_PARENT_MASK,
    RTL_BITS_OF,
    RTL_BITS_OF_FIELD,
    RTL_CONSTANT_OBJECT_ATTRIBUTES,
    RTL_CONSTANT_STRING,
    RTL_CONST_CAST,
    RTL_CONTAINS_FIELD,
    RTL_FIELD_SIZE,
    RTL_FIELD_TYPE,
    RTL_INIT_OBJECT_ATTRIBUTES,
    RTL_NUMBER_OF,
    RTL_NUMBER_OF_FIELD,
    RTL_NUMBER_OF_V1,
    RTL_NUMBER_OF_V2,
    RTL_PADDING_BETWEEN_FIELDS,
    RTL_REFERENCE_COUNT,
    RTL_REFERENCE_COUNT32,
    RTL_SIZEOF_THROUGH_FIELD,
    RTL_STRING_LENGTH_TYPE,
    RotateLeft16,
    RotateLeft32,
    RotateLeft64,
    RotateLeft8,
    RotateRight16,
    RotateRight32,
    RotateRight64,
    RotateRight8,
    SCHAR,
    SECURITY_STATUS,
    SINGLE_LIST_ENTRY,
    SINGLE_LIST_ENTRY32,
    SORTIDFROMLCID,
    SORTVERSIONFROMLCID,
    SORT_CHINESE_BIG5,
    SORT_CHINESE_BOPOMOFO,
    SORT_CHINESE_PRC,
    SORT_CHINESE_PRCP,
    SORT_CHINESE_RADICALSTROKE,
    SORT_CHINESE_UNICODE,
    SORT_DEFAULT,
    SORT_GEORGIAN_MODERN,
    SORT_GEORGIAN_TRADITIONAL,
    SORT_GERMAN_PHONE_BOOK,
    SORT_HUNGARIAN_DEFAULT,
    SORT_HUNGARIAN_TECHNICAL,
    SORT_INVARIANT_MATH,
    SORT_JAPANESE_RADICALSTROKE,
    SORT_JAPANESE_UNICODE,
    SORT_JAPANESE_XJIS,
    SORT_KOREAN_KSC,
    SORT_KOREAN_UNICODE,
    STDAPI,
    STDAPICALLTYPE,
    STDAPIV,
    STDAPIVCALLTYPE,
    STDAPIV_,
    STDAPI_,
    STDMETHODCALLTYPE,
    STDMETHODIMP,
    STDMETHODIMPV,
    STDMETHODIMPV_,
    STDMETHODIMP_,
    STDMETHODVCALLTYPE,
    STDOVERRIDEMETHODIMP,
    STDOVERRIDEMETHODIMPV,
    STDOVERRIDEMETHODIMPV_,
    STDOVERRIDEMETHODIMP_,
    STKFORCEINLINE,
    STRICT,
    STRING,
    STRING32,
    STRING64,
    SUBLANGID,
    SUBLANG_AFRIKAANS_SOUTH_AFRICA,
    SUBLANG_ALBANIAN_ALBANIA,
    SUBLANG_ALSATIAN_FRANCE,
    SUBLANG_AMHARIC_ETHIOPIA,
    SUBLANG_ARABIC_ALGERIA,
    SUBLANG_ARABIC_BAHRAIN,
    SUBLANG_ARABIC_EGYPT,
    SUBLANG_ARABIC_IRAQ,
    SUBLANG_ARABIC_JORDAN,
    SUBLANG_ARABIC_KUWAIT,
    SUBLANG_ARABIC_LEBANON,
    SUBLANG_ARABIC_LIBYA,
    SUBLANG_ARABIC_MOROCCO,
    SUBLANG_ARABIC_OMAN,
    SUBLANG_ARABIC_QATAR,
    SUBLANG_ARABIC_SAUDI_ARABIA,
    SUBLANG_ARABIC_SYRIA,
    SUBLANG_ARABIC_TUNISIA,
    SUBLANG_ARABIC_UAE,
    SUBLANG_ARABIC_YEMEN,
    SUBLANG_ARMENIAN_ARMENIA,
    SUBLANG_ASSAMESE_INDIA,
    SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC,
    SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN,
    SUBLANG_AZERI_CYRILLIC,
    SUBLANG_AZERI_LATIN,
    SUBLANG_BANGLA_BANGLADESH,
    SUBLANG_BANGLA_INDIA,
    SUBLANG_BASHKIR_RUSSIA,
    SUBLANG_BASQUE_BASQUE,
    SUBLANG_BELARUSIAN_BELARUS,
    SUBLANG_BENGALI_BANGLADESH,
    SUBLANG_BENGALI_INDIA,
    SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC,
    SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_BRETON_FRANCE,
    SUBLANG_BULGARIAN_BULGARIA,
    SUBLANG_CATALAN_CATALAN,
    SUBLANG_CENTRAL_KURDISH_IRAQ,
    SUBLANG_CHEROKEE_CHEROKEE,
    SUBLANG_CHINESE_HONGKONG,
    SUBLANG_CHINESE_MACAU,
    SUBLANG_CHINESE_SIMPLIFIED,
    SUBLANG_CHINESE_SINGAPORE,
    SUBLANG_CHINESE_TRADITIONAL,
    SUBLANG_CORSICAN_FRANCE,
    SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_CROATIAN_CROATIA,
    SUBLANG_CUSTOM_DEFAULT,
    SUBLANG_CUSTOM_UNSPECIFIED,
    SUBLANG_CZECH_CZECH_REPUBLIC,
    SUBLANG_DANISH_DENMARK,
    SUBLANG_DARI_AFGHANISTAN,
    SUBLANG_DEFAULT,
    SUBLANG_DIVEHI_MALDIVES,
    SUBLANG_DUTCH,
    SUBLANG_DUTCH_BELGIAN,
    SUBLANG_ENGLISH_AUS,
    SUBLANG_ENGLISH_BELIZE,
    SUBLANG_ENGLISH_CAN,
    SUBLANG_ENGLISH_CARIBBEAN,
    SUBLANG_ENGLISH_EIRE,
    SUBLANG_ENGLISH_INDIA,
    SUBLANG_ENGLISH_JAMAICA,
    SUBLANG_ENGLISH_MALAYSIA,
    SUBLANG_ENGLISH_NZ,
    SUBLANG_ENGLISH_PHILIPPINES,
    SUBLANG_ENGLISH_SINGAPORE,
    SUBLANG_ENGLISH_SOUTH_AFRICA,
    SUBLANG_ENGLISH_TRINIDAD,
    SUBLANG_ENGLISH_UK,
    SUBLANG_ENGLISH_US,
    SUBLANG_ENGLISH_ZIMBABWE,
    SUBLANG_ESTONIAN_ESTONIA,
    SUBLANG_FAEROESE_FAROE_ISLANDS,
    SUBLANG_FILIPINO_PHILIPPINES,
    SUBLANG_FINNISH_FINLAND,
    SUBLANG_FRENCH,
    SUBLANG_FRENCH_BELGIAN,
    SUBLANG_FRENCH_CANADIAN,
    SUBLANG_FRENCH_LUXEMBOURG,
    SUBLANG_FRENCH_MONACO,
    SUBLANG_FRENCH_SWISS,
    SUBLANG_FRISIAN_NETHERLANDS,
    SUBLANG_FULAH_SENEGAL,
    SUBLANG_GALICIAN_GALICIAN,
    SUBLANG_GEORGIAN_GEORGIA,
    SUBLANG_GERMAN,
    SUBLANG_GERMAN_AUSTRIAN,
    SUBLANG_GERMAN_LIECHTENSTEIN,
    SUBLANG_GERMAN_LUXEMBOURG,
    SUBLANG_GERMAN_SWISS,
    SUBLANG_GREEK_GREECE,
    SUBLANG_GREENLANDIC_GREENLAND,
    SUBLANG_GUJARATI_INDIA,
    SUBLANG_HAUSA_NIGERIA_LATIN,
    SUBLANG_HAWAIIAN_US,
    SUBLANG_HEBREW_ISRAEL,
    SUBLANG_HINDI_INDIA,
    SUBLANG_HUNGARIAN_HUNGARY,
    SUBLANG_ICELANDIC_ICELAND,
    SUBLANG_IGBO_NIGERIA,
    SUBLANG_INDONESIAN_INDONESIA,
    SUBLANG_INUKTITUT_CANADA,
    SUBLANG_INUKTITUT_CANADA_LATIN,
    SUBLANG_IRISH_IRELAND,
    SUBLANG_ITALIAN,
    SUBLANG_ITALIAN_SWISS,
    SUBLANG_JAPANESE_JAPAN,
    SUBLANG_KANNADA_INDIA,
    SUBLANG_KASHMIRI_INDIA,
    SUBLANG_KASHMIRI_SASIA,
    SUBLANG_KAZAK_KAZAKHSTAN,
    SUBLANG_KHMER_CAMBODIA,
    SUBLANG_KICHE_GUATEMALA,
    SUBLANG_KINYARWANDA_RWANDA,
    SUBLANG_KONKANI_INDIA,
    SUBLANG_KOREAN,
    SUBLANG_KYRGYZ_KYRGYZSTAN,
    SUBLANG_LAO_LAO,
    SUBLANG_LATVIAN_LATVIA,
    SUBLANG_LITHUANIAN,
    SUBLANG_LOWER_SORBIAN_GERMANY,
    SUBLANG_LUXEMBOURGISH_LUXEMBOURG,
    SUBLANG_MACEDONIAN_MACEDONIA,
    SUBLANG_MALAYALAM_INDIA,
    SUBLANG_MALAY_BRUNEI_DARUSSALAM,
    SUBLANG_MALAY_MALAYSIA,
    SUBLANG_MALTESE_MALTA,
    SUBLANG_MAORI_NEW_ZEALAND,
    SUBLANG_MAPUDUNGUN_CHILE,
    SUBLANG_MARATHI_INDIA,
    SUBLANG_MOHAWK_MOHAWK,
    SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA,
    SUBLANG_MONGOLIAN_PRC,
    SUBLANG_NEPALI_INDIA,
    SUBLANG_NEPALI_NEPAL,
    SUBLANG_NEUTRAL,
    SUBLANG_NORWEGIAN_BOKMAL,
    SUBLANG_NORWEGIAN_NYNORSK,
    SUBLANG_OCCITAN_FRANCE,
    SUBLANG_ODIA_INDIA,
    SUBLANG_ORIYA_INDIA,
    SUBLANG_PASHTO_AFGHANISTAN,
    SUBLANG_PERSIAN_IRAN,
    SUBLANG_POLISH_POLAND,
    SUBLANG_PORTUGUESE,
    SUBLANG_PORTUGUESE_BRAZILIAN,
    SUBLANG_PULAR_SENEGAL,
    SUBLANG_PUNJABI_INDIA,
    SUBLANG_PUNJABI_PAKISTAN,
    SUBLANG_QUECHUA_BOLIVIA,
    SUBLANG_QUECHUA_ECUADOR,
    SUBLANG_QUECHUA_PERU,
    SUBLANG_ROMANIAN_ROMANIA,
    SUBLANG_ROMANSH_SWITZERLAND,
    SUBLANG_RUSSIAN_RUSSIA,
    SUBLANG_SAKHA_RUSSIA,
    SUBLANG_SAMI_INARI_FINLAND,
    SUBLANG_SAMI_LULE_NORWAY,
    SUBLANG_SAMI_LULE_SWEDEN,
    SUBLANG_SAMI_NORTHERN_FINLAND,
    SUBLANG_SAMI_NORTHERN_NORWAY,
    SUBLANG_SAMI_NORTHERN_SWEDEN,
    SUBLANG_SAMI_SKOLT_FINLAND,
    SUBLANG_SAMI_SOUTHERN_NORWAY,
    SUBLANG_SAMI_SOUTHERN_SWEDEN,
    SUBLANG_SANSKRIT_INDIA,
    SUBLANG_SCOTTISH_GAELIC,
    SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC,
    SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN,
    SUBLANG_SERBIAN_CROATIA,
    SUBLANG_SERBIAN_CYRILLIC,
    SUBLANG_SERBIAN_LATIN,
    SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC,
    SUBLANG_SERBIAN_MONTENEGRO_LATIN,
    SUBLANG_SERBIAN_SERBIA_CYRILLIC,
    SUBLANG_SERBIAN_SERBIA_LATIN,
    SUBLANG_SINDHI_AFGHANISTAN,
    SUBLANG_SINDHI_INDIA,
    SUBLANG_SINDHI_PAKISTAN,
    SUBLANG_SINHALESE_SRI_LANKA,
    SUBLANG_SLOVAK_SLOVAKIA,
    SUBLANG_SLOVENIAN_SLOVENIA,
    SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA,
    SUBLANG_SPANISH,
    SUBLANG_SPANISH_ARGENTINA,
    SUBLANG_SPANISH_BOLIVIA,
    SUBLANG_SPANISH_CHILE,
    SUBLANG_SPANISH_COLOMBIA,
    SUBLANG_SPANISH_COSTA_RICA,
    SUBLANG_SPANISH_DOMINICAN_REPUBLIC,
    SUBLANG_SPANISH_ECUADOR,
    SUBLANG_SPANISH_EL_SALVADOR,
    SUBLANG_SPANISH_GUATEMALA,
    SUBLANG_SPANISH_HONDURAS,
    SUBLANG_SPANISH_MEXICAN,
    SUBLANG_SPANISH_MODERN,
    SUBLANG_SPANISH_NICARAGUA,
    SUBLANG_SPANISH_PANAMA,
    SUBLANG_SPANISH_PARAGUAY,
    SUBLANG_SPANISH_PERU,
    SUBLANG_SPANISH_PUERTO_RICO,
    SUBLANG_SPANISH_URUGUAY,
    SUBLANG_SPANISH_US,
    SUBLANG_SPANISH_VENEZUELA,
    SUBLANG_SWAHILI_KENYA,
    SUBLANG_SWEDISH,
    SUBLANG_SWEDISH_FINLAND,
    SUBLANG_SYRIAC_SYRIA,
    SUBLANG_SYS_DEFAULT,
    SUBLANG_TAJIK_TAJIKISTAN,
    SUBLANG_TAMAZIGHT_ALGERIA_LATIN,
    SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH,
    SUBLANG_TAMIL_INDIA,
    SUBLANG_TAMIL_SRI_LANKA,
    SUBLANG_TATAR_RUSSIA,
    SUBLANG_TELUGU_INDIA,
    SUBLANG_THAI_THAILAND,
    SUBLANG_TIBETAN_PRC,
    SUBLANG_TIGRIGNA_ERITREA,
    SUBLANG_TIGRINYA_ERITREA,
    SUBLANG_TIGRINYA_ETHIOPIA,
    SUBLANG_TSWANA_BOTSWANA,
    SUBLANG_TSWANA_SOUTH_AFRICA,
    SUBLANG_TURKISH_TURKEY,
    SUBLANG_TURKMEN_TURKMENISTAN,
    SUBLANG_UIGHUR_PRC,
    SUBLANG_UI_CUSTOM_DEFAULT,
    SUBLANG_UKRAINIAN_UKRAINE,
    SUBLANG_UPPER_SORBIAN_GERMANY,
    SUBLANG_URDU_INDIA,
    SUBLANG_URDU_PAKISTAN,
    SUBLANG_UZBEK_CYRILLIC,
    SUBLANG_UZBEK_LATIN,
    SUBLANG_VALENCIAN_VALENCIA,
    SUBLANG_VIETNAMESE_VIETNAM,
    SUBLANG_WELSH_UNITED_KINGDOM,
    SUBLANG_WOLOF_SENEGAL,
    SUBLANG_XHOSA_SOUTH_AFRICA,
    SUBLANG_YAKUT_RUSSIA,
    SUBLANG_YI_PRC,
    SUBLANG_YORUBA_NIGERIA,
    SUBLANG_ZULU_SOUTH_AFRICA,
    SUITE_TYPE,
    SYSTEM_CACHE_ALIGNMENT_SIZE,
    TCHAR,
    TEXT,
    TIME,
    TIMER_TYPE,
    TRUE,
    TUCHAR,
    TYPE_ALIGNMENT,
    UCHAR,
    UCSCHAR,
    UCSCHAR_INVALID_CHARACTER,
    UFIELD_OFFSET,
    UInt32x32To64,
    ULARGE_INTEGER,
    ULONGLONG,
    UNALIGNED,
    UNALIGNED64,
    UNICODE_NULL,
    UNICODE_STRING,
    UNICODE_STRING32,
    UNICODE_STRING64,
    UNICODE_STRING_MAX_BYTES,
    UNICODE_STRING_MAX_CHARS,
    UNREFERENCED_PARAMETER,
    UQUAD,
    USHORT,
    USN,
    VER_SERVER_NT,
    VER_SUITE_BACKOFFICE,
    VER_SUITE_BLADE,
    VER_SUITE_COMMUNICATIONS,
    VER_SUITE_COMPUTE_SERVER,
    VER_SUITE_DATACENTER,
    VER_SUITE_EMBEDDEDNT,
    VER_SUITE_EMBEDDED_RESTRICTED,
    VER_SUITE_ENTERPRISE,
    VER_SUITE_MULTIUSERTS,
    VER_SUITE_PERSONAL,
    VER_SUITE_SECURITY_APPLIANCE,
    VER_SUITE_SINGLEUSERTS,
    VER_SUITE_SMALLBUSINESS,
    VER_SUITE_SMALLBUSINESS_RESTRICTED,
    VER_SUITE_STORAGE_SERVER,
    VER_SUITE_TERMINAL,
    VER_SUITE_WH_SERVER,
    VER_WORKSTATION_NT,
    WAIT_TYPE,
    WCHAR,
    WNF_STATE_NAME,
    _ARRAYSIZE,
    _CSTRING,
    _ENUM_FLAG_CONSTEXPR,
    _EVENT_TYPE,
    _FLOAT128,
    _GROUP_AFFINITY,
    _LARGE_INTEGER,
    _LIST_ENTRY,
    _LUID,
    _NT_PRODUCT_TYPE,
    _OBJECTID,
    _OBJECT_ATTRIBUTES,
    _OBJECT_ATTRIBUTES32,
    _OBJECT_ATTRIBUTES64,
    _PROCESSOR_NUMBER,
    _QUAD,
    _RTL_BALANCED_NODE,
    _RTL_CONSTANT_STRING_remove_const_macro,
    _SINGLE_LIST_ENTRY,
    _SINGLE_LIST_ENTRY32,
    _STRING,
    _STRING32,
    _STRING64,
    _SUITE_TYPE,
    _TIME,
    _TIMER_TYPE,
    _ULARGE_INTEGER,
    _UNICODE_STRING,
    _WAIT_TYPE,
    _WNF_STATE_NAME,
    __TEXT,
    max,
    min,
)


SPHANDLE = POINTER(HANDLE)
LPHANDLE = POINTER(HANDLE)

HKEY = POINTER(VOID)
PHKEY = POINTER(HKEY)

HMODULE = POINTER(VOID)
HINSTANCE = POINTER(VOID)
HTASK = POINTER(VOID)
HDESK = POINTER(VOID)
HMF = POINTER(VOID)
HEMF = POINTER(VOID)
HPEN = POINTER(VOID)
HRSRC = POINTER(VOID)
HSTR = POINTER(VOID)
HWINSTA = POINTER(VOID)
HKL = POINTER(VOID)
HGDIOBJ = POINTER(VOID)
HACCEL = POINTER(VOID)
HBITMAP = POINTER(VOID)
HBRUSH = POINTER(VOID)
HCOLORSPACE = POINTER(VOID)
HCONV = POINTER(VOID)
HCONVLIST = POINTER(VOID)
HICON = POINTER(VOID)
HCURSOR = POINTER(VOID)
HDC = POINTER(VOID)
HDDEDATA = POINTER(VOID)
HDROP = POINTER(VOID)
HENHMETAFILE = POINTER(VOID)
HFONT = POINTER(VOID)
HGLOBAL = POINTER(VOID)
HHOOK = POINTER(VOID)
HLOCAL = POINTER(VOID)
HMENU = POINTER(VOID)
HMETAFILE = POINTER(VOID)
HMONITOR = POINTER(VOID)
HPALETTE = POINTER(VOID)
HRGN = POINTER(VOID)
HSZ = POINTER(VOID)
HWND = POINTER(VOID)
SERVICE_STATUS_HANDLE = POINTER(VOID)
HDWP = POINTER(VOID)
HSPRITE = POINTER(VOID)
HLSURF = POINTER(VOID)
HGLRC = POINTER(VOID)
HWINEVENTHOOK = POINTER(VOID)
HUMPD = POINTER(VOID)
GLOBALHANDLE = POINTER(VOID)
LOCALHANDLE = POINTER(VOID)
SC_HANDLE = POINTER(VOID)
HCONTEXT = POINTER(VOID)

HANDLE_PTR = UINT64
SHANDLE_PTR = INT64


SPOINTER_32 = POINTER_SIGNED
UPOINTER_32 = UINT32
POINTER_64_INT = UINT64

COLORREF = DWORD
LPCOLORREF = POINTER(DWORD)

LCTYPE = DWORD
LGRPID = DWORD

QWORD = UINT64
SC_LOCK = LPVOID


class tagRECT(ctypes.Structure):
    _fields_ = [
        ('left', LONG),
        ('top', LONG),
        ('right', LONG),
        ('bottom', LONG),
    ]


RECT = tagRECT
PRECT = POINTER(tagRECT)
LPRECT = POINTER(tagRECT)
LPCRECT = POINTER(RECT)
NPRECT = POINTER(tagRECT)


class _RECTL(ctypes.Structure):
    _fields_ = [
        ('left', LONG),
        ('top', LONG),
        ('right', LONG),
        ('bottom', LONG),
    ]


RECTL = _RECTL
PRECTL = POINTER(_RECTL)
LPRECTL = POINTER(_RECTL)
LPCRECTL = POINTER(RECTL)


class tagPOINT(ctypes.Structure):
    _fields_ = [
        ('x', LONG),
        ('y', LONG),
    ]


POINT = tagPOINT
PPOINT = POINTER(tagPOINT)
LPPOINT = POINTER(tagPOINT)
NPPOINT = POINTER(tagPOINT)


class _POINTL(ctypes.Structure):
    _fields_ = [
        ('x', LONG),
        ('y', LONG),
    ]


POINTL = _POINTL
PPOINTL = POINTER(_POINTL)


class tagSIZE(ctypes.Structure):
    _fields_ = [
        ('cx', LONG),
        ('cy', LONG),
    ]


SIZE = tagSIZE
PSIZE = POINTER(tagSIZE)
LPSIZE = POINTER(tagSIZE)


class tagSIZEL(ctypes.Structure):
    _fields_ = [
        ('cx', LONG),
        ('cy', LONG),
    ]


SIZEL = tagSIZEL
PSIZEL = POINTER(tagSIZEL)
LPSIZEL = POINTER(tagSIZEL)


class tagPOINTS(ctypes.Structure):
    _fields_ = [
        ('x', SHORT),
        ('y', SHORT),
        ('y', SHORT),
        ('x', SHORT),
    ]


POINTS = tagPOINTS
PPOINTS = POINTER(tagPOINTS)
LPPOINTS = POINTER(tagPOINTS)


from shared.guiddef_h import (
    GUID as _GUID,
    GUID_NULL as _GUID_NULL,
    LPGUID as _LPGUID,
    LPCGUID as _LPCGUID,
    IID as _IID,
    LPIID as _LPIID,
    IID_NULL as _IID_NULL,
    CLSID as _CLSID,
    LPCLSID as _LPCLSID,
    CLSID_NULL as _CLSID_NULL,
    FMTID as _FMTID,
    LPFMTID as _LPFMTID,
    FMTID_NULL as _FMTID_NULL,
    REFGUID as _REFGUID,
    REFIID as _REFIID,
    REFCLSID as _REFCLSID,
    REFFMTID as _REFFMTID
) # NOQA


GUID = _GUID
GUID_NULL = _GUID_NULL
LPGUID = _LPGUID
LPCGUID = _LPCGUID
IID = _IID
LPIID = _LPIID
IID_NULL = _IID_NULL
CLSID = _CLSID
LPCLSID = _LPCLSID
CLSID_NULL = _CLSID_NULL
FMTID = _FMTID
LPFMTID = _LPFMTID
FMTID_NULL = _FMTID_NULL
REFGUID = _REFGUID
REFIID = _REFIID
REFCLSID = _REFCLSID
REFFMTID = _REFFMTID


LPUINT = POINTER(UINT)
LPUINT32 = POINTER(UINT32)
HNSTIME = LONGLONG
REFERENCE_TIME = LONGLONG
LPREFERENCE_TIME = POINTER(REFERENCE_TIME)
LPUINT64 = POINTER(UINT64)
LPFLOAT = POINTER(FLOAT)

MFTIME = LONGLONG
FLOAT32 = FLOAT
FLOAT64 = DOUBLE


from um.wtypesbase_h import (
    APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU,
    APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP,
    APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY,
    APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY,
    APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION,
    APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN,
    APPIDREGFLAGS_RESERVED1,
    APPIDREGFLAGS_RESERVED2,
    APPIDREGFLAGS_RESERVED3,
    APPIDREGFLAGS_RESERVED4,
    APPIDREGFLAGS_RESERVED5,
    APPIDREGFLAGS_RESERVED7,
    APPIDREGFLAGS_RESERVED8,
    APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND,
    CLSCTX_VALID_MASK,
    DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL,
    DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES,
    DCOMSCM_PING_DISALLOW_UNSECURE_CALL,
    DCOMSCM_PING_USE_MID_AUTHNSERVICE,
    DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL,
    DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES,
    OLECHAR,
    PACL,
    PSCODE,
    PSECURITY_DESCRIPTOR_CONTROL,
    PSID,
    ROTREGFLAGS_ALLOWANYCLIENT,
    SCODE,
    SECURITY_DESCRIPTOR_CONTROL,
    UP_BYTE_BLOB,
    BYTE_BLOB,
    DWORD_BLOB,
    FLAGGED_BYTE_BLOB,
    FLAGGED_WORD_BLOB,
    UP_DWORD_BLOB,
    UP_FLAGGED_BYTE_BLOB,
    UP_FLAGGED_WORD_BLOB,
    UP_WORD_BLOB,
    tagBLOB,
    tagCLSCTX,
    tagMEMCTX,
    tagMSHCTX,
    tagMSHLFLAGS,
    SECURITY_DESCRIPTOR,
    SECURITY_ATTRIBUTES,
    SID,
    COAUTHIDENTITY,
    WORD_BLOB,
    COAUTHINFO,
    SYSTEMTIME,
    ACL,
    BLOB,
    HYPER_SIZEDARR,
    SHORT_SIZEDARR,
    LONG_SIZEDARR,
    WORD_SIZEDARR,
    DWORD_SIZEDARR,
    BYTE_SIZEDARR,
    SID_IDENTIFIER_AUTHORITY,
    FILETIME,
    SID_AND_ATTRIBUTES,
    PFILETIME,
    LPFILETIME,
    ULONG
)# NOQA


LONGLONG_PTR = LONGLONG
DWORDLONG_PTR = DWORDLONG
DECLSPEC_DEPRECATED_DDK

class tagRemHGLOBAL(ctypes.Structure):
    _fields_ = [
        ('fNullHGlobal', LONG),
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHGLOBAL = tagRemHGLOBAL


class tagRemHMETAFILEPICT(ctypes.Structure):
    _fields_ = [
        ('mm', LONG),
        ('xExt', LONG),
        ('yExt', LONG),
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHMETAFILEPICT = tagRemHMETAFILEPICT


class tagRemHENHMETAFILE(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHENHMETAFILE = tagRemHENHMETAFILE


class tagRemHBITMAP(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHBITMAP = tagRemHBITMAP


class tagRemHPALETTE(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHPALETTE = tagRemHPALETTE


class tagRemBRUSH(ctypes.Structure):
    _fields_ = [
        ('cbData', ULONG),
        ('data', BYTE * 1),
    ]


RemHBRUSH = tagRemBRUSH


class tagPALETTEENTRY(ctypes.Structure):
    _fields_ = [
        ('peRed', BYTE),
        ('peGreen', BYTE),
        ('peBlue', BYTE),
        ('peFlags', BYTE),
    ]


PALETTEENTRY = tagPALETTEENTRY
PPALETTEENTRY = POINTER(tagPALETTEENTRY)
LPPALETTEENTRY = POINTER(tagPALETTEENTRY)


class tagLOGPALETTE(ctypes.Structure):
    _fields_ = [
        ('palVersion', WORD),
        ('palNumEntries', WORD),
        ('palPalEntry', PALETTEENTRY * 1),
    ]


LOGPALETTE = tagLOGPALETTE
PLOGPALETTE = POINTER(tagLOGPALETTE)
LPLOGPALETTE = POINTER(tagLOGPALETTE)


ROTFLAGS_REGISTRATIONKEEPSALIVE = 0x1
ROTFLAGS_ALLOWANYCLIENT = 0x2
ROT_COMPARE_MAX = 0x800


class tagDVASPECT(ENUM):
    DVASPECT_CONTENT = 1
    DVASPECT_THUMBNAIL = 2
    DVASPECT_ICON = 4
    DVASPECT_DOCPRINT = 8


DVASPECT = tagDVASPECT


class tagSTGC(ENUM):
    STGC_DEFAULT = 0
    STGC_OVERWRITE = 1
    STGC_ONLYIFCURRENT = 2
    STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE = 4
    STGC_CONSOLIDATE = 8


STGC = tagSTGC


class tagSTGMOVE(ENUM):
    STGMOVE_MOVE = 0
    STGMOVE_COPY = 1
    STGMOVE_SHALLOWCOPY = 2


STGMOVE = tagSTGMOVE


class tagSTATFLAG(ENUM):
    STATFLAG_DEFAULT = 0
    STATFLAG_NONAME = 1
    STATFLAG_NOOPEN = 2


STATFLAG = tagSTATFLAG


WDT_INPROC_CALL = 0x48746457
WDT_REMOTE_CALL = 0x52746457
WDT_INPROC64_CALL = 0x50746457


class _userCLIPFORMAT(ctypes.Structure):

    class __MIDL_IWinTypes_0001(ctypes.Union):
        _fields_ = [
            ('dwValue', DWORD),
            ('pwszName', POINTER(WCHAR)),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0001),
    ]


userCLIPFORMAT = _userCLIPFORMAT
wireCLIPFORMAT = POINTER(userCLIPFORMAT)

CLIPFORMAT = WORD


class _GDI_NONREMOTE(ctypes.Structure):

    class __MIDL_IWinTypes_0002(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(DWORD_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0002),
    ]


GDI_NONREMOTE = _GDI_NONREMOTE


class _userHGLOBAL(ctypes.Structure):

    class __MIDL_IWinTypes_0003(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(FLAGGED_BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0003),
    ]


userHGLOBAL = _userHGLOBAL
wireHGLOBAL = POINTER(userHGLOBAL)


class _userHMETAFILE(ctypes.Structure):

    class __MIDL_IWinTypes_0004(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0004),
    ]


userHMETAFILE = _userHMETAFILE


class _remoteMETAFILEPICT(ctypes.Structure):
    _fields_ = [
        ('mm', LONG),
        ('xExt', LONG),
        ('yExt', LONG),
        ('hMF', POINTER(userHMETAFILE)),
    ]


remoteMETAFILEPICT = _remoteMETAFILEPICT


class _userHMETAFILEPICT(ctypes.Structure):

    class __MIDL_IWinTypes_0005(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(remoteMETAFILEPICT)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0005),
    ]


userHMETAFILEPICT = _userHMETAFILEPICT


class _userHENHMETAFILE(ctypes.Structure):

    class __MIDL_IWinTypes_0006(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(BYTE_BLOB)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0006),
    ]


userHENHMETAFILE = _userHENHMETAFILE


class _userBITMAP(ctypes.Structure):
    _fields_ = [
        ('bmType', LONG),
        ('bmWidth', LONG),
        ('bmHeight', LONG),
        ('bmWidthBytes', LONG),
        ('bmPlanes', WORD),
        ('bmBitsPixel', WORD),
        ('cbSize', ULONG),
        ('pBuffer', BYTE * 1),
    ]


userBITMAP = _userBITMAP


class _userHBITMAP(ctypes.Structure):

    class __MIDL_IWinTypes_0007(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(userBITMAP)),
            ('hInproc64', INT64),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0007),
    ]


userHBITMAP = _userHBITMAP


class _userHPALETTE(ctypes.Structure):

    class __MIDL_IWinTypes_0008(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', POINTER(LOGPALETTE)),
            ('hInproc64', INT64),
        ]


    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0008),
    ]


userHPALETTE = _userHPALETTE


class _RemotableHandle(ctypes.Structure):

    class __MIDL_IWinTypes_0009(ctypes.Union):
        _fields_ = [
            ('hInproc', LONG),
            ('hRemote', LONG),
        ]

    _fields_ = [
        ('fContext', LONG),
        ('u', __MIDL_IWinTypes_0009),
    ]


RemotableHandle = _RemotableHandle


wireHWND = POINTER(RemotableHandle)
wireHMENU = POINTER(RemotableHandle)
wireHACCEL = POINTER(RemotableHandle)
wireHBRUSH = POINTER(RemotableHandle)
wireHFONT = POINTER(RemotableHandle)
wireHDC = POINTER(RemotableHandle)
wireHICON = POINTER(RemotableHandle)
wireHRGN = POINTER(RemotableHandle)
wireHMONITOR = POINTER(RemotableHandle)


class tagTEXTMETRICW(ctypes.Structure):
    _fields_ = [
        ('tmHeight', LONG),
        ('tmAscent', LONG),
        ('tmDescent', LONG),
        ('tmInternalLeading', LONG),
        ('tmExternalLeading', LONG),
        ('tmAveCharWidth', LONG),
        ('tmMaxCharWidth', LONG),
        ('tmWeight', LONG),
        ('tmOverhang', LONG),
        ('tmDigitizedAspectX', LONG),
        ('tmDigitizedAspectY', LONG),
        ('tmFirstChar', WCHAR),
        ('tmLastChar', WCHAR),
        ('tmDefaultChar', WCHAR),
        ('tmBreakChar', WCHAR),
        ('tmItalic', BYTE),
        ('tmUnderlined', BYTE),
        ('tmStruckOut', BYTE),
        ('tmPitchAndFamily', BYTE),
        ('tmCharSet', BYTE),
    ]


TEXTMETRICW = tagTEXTMETRICW


PTEXTMETRICW = POINTER(tagTEXTMETRICW)
LPTEXTMETRICW = POINTER(tagTEXTMETRICW)


class tagMSG(ctypes.Structure):
    _fields_ = [
        ('hwnd', HWND),
        ('message', UINT),
        ('wParam', WPARAM),
        ('lParam', LPARAM),
        ('time', DWORD),
        ('pt', POINT),
    ]


MSG = tagMSG


PMSG = POINTER(tagMSG)
NPMSG = POINTER(tagMSG)
LPMSG = POINTER(tagMSG)

wireHBITMAP = POINTER(VOID)
wireHPALETTE = POINTER(VOID)
wireHENHMETAFILE = POINTER(VOID)
wireHMETAFILE = POINTER(VOID)
wireHMETAFILEPICT = POINTER(VOID)

HMETAFILEPICT = POINTER(VOID)

DATE = DOUBLE


class tagCY(ctypes.Union):

    class DUMMYSTRUCTNAME(ctypes.Structure):
        _fields_ = [
            ('Lo', ULONG),
            ('Hi', LONG),
        ]

    _fields_ = [
        ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
        ('INT64', LONGLONG),
    ]


CY = tagCY
LPCY = POINTER(CY)


class tagDEC(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        class DUMMYSTRUCTNAME(ctypes.Structure):
            _fields_ = [
                ('scale', BYTE),
                ('sign', BYTE),
            ]

        _fields_ = [
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
            ('signscale', USHORT),
        ]

    class DUMMYUNIONNAME2(ctypes.Union):

        class DUMMYSTRUCTNAME2(ctypes.Structure):
            _fields_ = [
                ('Lo32', ULONG),
                ('Mid32', ULONG),
            ]

        _fields_ = [
            ('DUMMYSTRUCTNAME2', DUMMYSTRUCTNAME2),
            ('Lo64', ULONGLONG),
        ]

    _fields_ = [
        ('wReserved', USHORT),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('Hi32', ULONG),
        ('DUMMYUNIONNAME2', DUMMYUNIONNAME2),
    ]


DECIMAL = tagDEC

DECIMAL_NEG = 0x80


def DECIMAL_SETZERO(dec):
    dec.Lo64 = 0
    dec.Hi32 = 0
    dec.signscale = 0
    return dec


LPDECIMAL = POINTER(DECIMAL)

wireBSTR = POINTER(FLAGGED_WORD_BLOB)

BSTR = POINTER(OLECHAR)
LPBSTR = POINTER(BSTR)

_VARIANT_BOOL = VARIANT_BOOL


class tagBSTRBLOB(ctypes.Structure):
    _fields_ = [
        ('cbSize', ULONG),
        ('pData', POINTER(BYTE)),
    ]


BSTRBLOB = tagBSTRBLOB
LPBSTRBLOB = POINTER(tagBSTRBLOB)

VARIANT_TRUE = -1
VARIANT_FALSE = 0


class tagCLIPDATA(ctypes.Structure):
    _fields_ = [
        ('cbSize', ULONG),
        ('ulClipFmt', LONG),
        ('pClipData', POINTER(BYTE)),
    ]


CLIPDATA = tagCLIPDATA


def CBPCLIPDATA(clipdata):
    return clipdata.cbSize - ctypes.sizeof(clipdata.ulClipFmt)


VARTYPE = USHORT
# * VARENUM usage key,
# *
# * * [V] - may appear in a VARIANT
# * * [T] - may appear in a TYPEDESC
# * * [P] - may appear in an OLE property set
# * * [S] - may appear in a Safe Array
# *
# *
# *  VT_EMPTY            [V]   [P]     nothing
# *  VT_NULL             [V]   [P]     SQL style Null
# *  VT_I2               [V][T][P][S]  2 byte INT
# *  VT_I4               [V][T][P][S]  4 byte INT
# *  VT_R4               [V][T][P][S]  4 byte real
# *  VT_R8               [V][T][P][S]  8 byte real
# *  VT_CY               [V][T][P][S]  currency
# *  VT_DATE             [V][T][P][S]  date
# *  VT_BSTR             [V][T][P][S]  OLE Automation string
# *  VT_DISPATCH         [V][T]   [S]  IDispatch *
# *  VT_ERROR            [V][T][P][S]  SCODE
# *  VT_BOOL             [V][T][P][S]  True=-1, False=0
# *  VT_VARIANT          [V][T][P][S]  VARIANT *
# *  VT_UNKNOWN          [V][T]   [S]  IUnknown *
# *  VT_DECIMAL          [V][T]   [S]  16 byte fixed poINT
# *  VT_RECORD           [V]   [P][S]  user defined type
# *  VT_I1               [V][T][P][s]  INT CHAR
# *  VT_UI1              [V][T][P][S]  UINT CHAR
# *  VT_UI2              [V][T][P][S]  UINT SHORT
# *  VT_UI4              [V][T][P][S]  ULONG
# *  VT_I8                  [T][P]     INT 64-bit INT
# *  VT_UI8                 [T][P]     UINT 64-bit INT
# *  VT_INT              [V][T][P][S]  INT machine INT
# *  VT_UINT             [V][T]   [S]  UINT machine INT
# *  VT_INT_PTR             [T]        INT machine register size width
# *  VT_UINT_PTR            [T]        UINT machine register size width
# *  VT_VOID                [T]        C style VOID
# *  VT_HRESULT             [T]        Standard return type
# *  VT_PTR                 [T]        poINTer type
# *  VT_SAFEARRAY           [T]        (use VT_ARRAY in VARIANT)
# *  VT_CARRAY              [T]        C style array
# *  VT_USERDEFINED         [T]        user defined type
# *  VT_LPSTR               [T][P]     null terminated string
# *  VT_LPWSTR              [T][P]     wide null terminated string
# *  VT_FILETIME               [P]     FILETIME
# *  VT_BLOB                   [P]     Length prefixed bytes
# *  VT_STREAM                 [P]     Name of the stream follows
# *  VT_STORAGE                [P]     Name of the storage follows
# *  VT_STREAMED_OBJECT        [P]     Stream contains an object
# *  VT_STORED_OBJECT          [P]     Storage contains an object
# *  VT_VERSIONED_STREAM       [P]     Stream with a GUID version
# *  VT_BLOB_OBJECT            [P]     Blob contains an object
# *  VT_CF                     [P]     Clipboard format
# *  VT_CLSID                  [P]     A Class ID
# *  VT_VECTOR                 [P]     simple counted array
# *  VT_ARRAY            [V]           SAFEARRAY*
# *  VT_BYREF            [V]           VOID* for local use
# *  VT_BSTR_BLOB                      Reserved for system use


class VARENUM(ENUM):
    VT_EMPTY = 0
    VT_NULL = 1
    VT_I2 = 2
    VT_I4 = 3
    VT_R4 = 4
    VT_R8 = 5
    VT_CY = 6
    VT_DATE = 7
    VT_BSTR = 8
    VT_DISPATCH = 9
    VT_ERROR = 10
    VT_BOOL = 11
    VT_VARIANT = 12
    VT_UNKNOWN = 13
    VT_DECIMAL = 14
    VT_I1 = 16
    VT_UI1 = 17
    VT_UI2 = 18
    VT_UI4 = 19
    VT_I8 = 20
    VT_UI8 = 21
    VT_INT = 22
    VT_UINT = 23
    VT_VOID = 24
    VT_HRESULT = 25
    VT_PTR = 26
    VT_SAFEARRAY = 27
    VT_CARRAY = 28
    VT_USERDEFINED = 29
    VT_LPSTR = 30
    VT_LPWSTR = 31
    VT_RECORD = 36
    VT_INT_PTR = 37
    VT_UINT_PTR = 38
    VT_FILETIME = 64
    VT_BLOB = 65
    VT_STREAM = 66
    VT_STORAGE = 67
    VT_STREAMED_OBJECT = 68
    VT_STORED_OBJECT = 69
    VT_BLOB_OBJECT = 70
    VT_CF = 71
    VT_CLSID = 72
    VT_VERSIONED_STREAM = 73
    VT_BSTR_BLOB = 0xfff
    VT_VECTOR = 0x1000
    VT_ARRAY = 0x2000
    VT_BYREF = 0x4000
    VT_RESERVED = 0x8000
    VT_ILLEGAL = 0xffff
    VT_ILLEGALMASKED = 0xfff
    VT_TYPEMASK = 0xfff


PROPID = ULONG


class _tagpropertykey(ctypes.Structure):
    _fields_ = [
        ('fmtid', GUID),
        ('pid', DWORD),
    ]


PROPERTYKEY = _tagpropertykey


class tagCSPLATFORM(ctypes.Structure):
    _fields_ = [
        ('dwPlatformId', DWORD),
        ('dwVersionHi', DWORD),
        ('dwVersionLo', DWORD),
        ('dwProcessorArch', DWORD),
    ]


CSPLATFORM = tagCSPLATFORM


class tagQUERYCONTEXT(ctypes.Structure):
    _fields_ = [
        ('dwContext', DWORD),
        ('Platform', CSPLATFORM),
        ('Locale', LCID),
        ('dwVersionHi', DWORD),
        ('dwVersionLo', DWORD),
    ]


QUERYCONTEXT = tagQUERYCONTEXT


class tagTYSPEC(ENUM):
    TYSPEC_CLSID = 0
    TYSPEC_FILEEXT = TYSPEC_CLSID + 1
    TYSPEC_MIMETYPE = TYSPEC_FILEEXT + 1
    TYSPEC_FILENAME = TYSPEC_MIMETYPE + 1
    TYSPEC_PROGID = TYSPEC_FILENAME + 1
    TYSPEC_PACKAGENAME = TYSPEC_PROGID + 1
    TYSPEC_OBJECTID = TYSPEC_PACKAGENAME + 1


TYSPEC = tagTYSPEC


class __MIDL___MIDL_itf_wtypes_0000_0001_0001(ctypes.Structure):
    class __MIDL___MIDL_itf_wtypes_0000_0001_0005(ctypes.Union):

        class ByName(ctypes.Structure):
            _fields_ = [
                ('pPackageName', LPOLESTR),
                ('PolicyId', GUID),
            ]

        class ByObjectId(ctypes.Structure):
            _fields_ = [
                ('ObjectId', GUID),
                ('PolicyId', GUID),
            ]

        _fields_ = [
            ('ByName', ByName),
            ('ByObjectId', ByObjectId),
            ('clsid', CLSID),
            ('pFileExt', LPOLESTR),
            ('pMimeType', LPOLESTR),
            ('pProgId', LPOLESTR),
            ('pFileName', LPOLESTR)
        ]

    _fields_ = [
        ('tyspec', DWORD),
        ('tagged_union', __MIDL___MIDL_itf_wtypes_0000_0001_0005),
    ]


uCLSSPEC = __MIDL___MIDL_itf_wtypes_0000_0001_0001


def _wcsicmp(s1, s2):
    if isinstance(s1, bytes):
        s1 = s1.decode('utf-8')

    if isinstance(s2, bytes):
        s2 = s2.decode('utf-8')

    try:
        if isinstance(s1, unicode):
            s1 = s1.decode('utf-8')

        if isinstance(s2, unicode):
            s2 = s2.decode('utf-8')
    except:
        pass

    res = 0

    s1 = list(s1)
    s2 = list(s2)

    for i, char in enumerate(s1):
        sc1 = ord(char)
        if len(s2) > 1:
            sc2 = ord(s2[i])
        else:
            sc2 = 0
        res += sc1 - sc2

    if len(s2) > len(s1):
        for char in s2[:len(s1) - 1]:
            res -= ord(char)

    return res


__all__ = (
    'ACL', 'ALL_PROCESSOR_GROUPS', 'ANSI_NULL', 'ANSI_STRING', 'APIENTRY',
    'ANSI_STRING32', 'ANSI_STRING64', 'ANYSIZE_ARRAY', 'APIPRIVATE', 'CY',
    'APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU', 'ARGUMENT_PRESENT',
    'APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP', 'APPLICATION_ERROR_MASK',
    'APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY', 'ARRAYSIZE', 'ATOM',
    'APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY', 'BLOB',
    'APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION', 'BOOL', 'FAR',
    'APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN', 'BOOLEAN', 'BSTR',
    'APPIDREGFLAGS_RESERVED1', 'APPIDREGFLAGS_RESERVED2', 'BSTRBLOB',
    'APPIDREGFLAGS_RESERVED3', 'APPIDREGFLAGS_RESERVED4', 'BYTE', 'CCHAR',
    'APPIDREGFLAGS_RESERVED5', 'APPIDREGFLAGS_RESERVED7', 'BYTE_BLOB',
    'APPIDREGFLAGS_RESERVED8', 'BYTE_SIZEDARR', 'CALLBACK', 'CBPCLIPDATA',
    'APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND', 'CANSI_STRING',
    'CDECL', 'CFORCEINLINE', 'CHAR', 'CLIPDATA', 'CLIPFORMAT', 'CLONG',
    'CLSCTX_VALID_MASK', 'CLSID', 'CLSID_NULL', 'COAUTHIDENTITY', 'CONST',
    'COAUTHINFO', 'COLORREF', 'COMPARTMENT_ID', 'COMPILETIME_OR_2FLAGS',
    'COMPILETIME_OR_3FLAGS', 'COMPILETIME_OR_4FLAGS', 'CONTAINING_RECORD',
    'COMPILETIME_OR_5FLAGS', 'COMPILETIME_OR_6FLAGS', 'COORD', 'CSHORT',
    'CSPLATFORM', 'CSTRING', 'C_ASSERT', 'DATE', 'DECIMAL', 'DECIMAL_NEG',
    'DBG_UNREFERENCED_LOCAL_VARIABLE', 'DBG_UNREFERENCED_PARAMETER', 'LP',
    'DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL', 'DECIMAL_SETZERO', 'HDC',
    'DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES', 'DECLARE_HANDLE', 'DWORD',
    'DCOMSCM_PING_DISALLOW_UNSECURE_CALL', 'DECLARE_CONST_UNICODE_STRING',
    'DCOMSCM_PING_USE_MID_AUTHNSERVICE', 'DECLARE_UNICODE_STRING_SIZE',
    'DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL', 'DECLSPEC_ADDRSAFE', 'ENUM',
    'DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES', 'DECLSPEC_ALIGN', 'DOUBLE',
    'DECLARE_GLOBAL_CONST_UNICODE_STRING', 'DECLSPEC_CACHEALIGN', 'FALSE',
    'DECLSPEC_CHPE_GUEST', 'DECLSPEC_CHPE_PATCHABLE', 'DECLSPEC_IMPORT',
    'DECLSPEC_DEPRECATED', 'DECLSPEC_GUARDIGNORE', 'DECLSPEC_GUARDNOCF',
    'DECLSPEC_GUARD_SUPPRESS', 'DECLSPEC_NOINLINE', 'DECLSPEC_NORETURN',
    'DECLSPEC_NOTHROW', 'DECLSPEC_NOVTABLE', 'DECLSPEC_SAFEBUFFERS',
    'DECLSPEC_SELECTANY', 'DECLSPEC_UUID', 'DEFAULT_UNREACHABLE', 'FCHAR',
    'DEFINE_ENUM_FLAG_OPERATORS', 'DUMMYUNIONNAME', 'DVASPECT', 'DWORD32',
    'DWORD64', 'DWORDLONG', 'DWORD_BLOB', 'DWORD_PTR', 'DWORD_SIZEDARR',
    'ERROR_SEVERITY_ERROR', 'ERROR_SEVERITY_INFORMATIONAL', 'EVENT_TYPE',
    'ERROR_SEVERITY_SUCCESS', 'ERROR_SEVERITY_WARNING', 'FARPROC', 'GUID',
    'FASTCALL', 'FIELD_OFFSET', 'FILETIME', 'FLAGGED_BYTE_BLOB', 'FLOAT',
    'FLAGGED_WORD_BLOB', 'FLOAT128', 'FLOAT32', 'FLOAT64', 'FLONG', 'HKL',
    'FMTID', 'FMTID_NULL', 'FORCEINLINE', 'FSHORT', 'GDI_NONREMOTE',
    'GLOBALHANDLE', 'GROUP_AFFINITY', 'GUID_NULL', 'HACCEL', 'HALF_PTR',
    'HANDLE', 'HANDLE_PTR', 'HBITMAP', 'HBRUSH', 'HCOLORSPACE', 'HCONV',
    'HCONTEXT', 'HCONVLIST', 'HCURSOR', 'HDDEDATA', 'HDESK', 'HDROP',
    'HDWP', 'HEMF', 'HENHMETAFILE', 'HEVENT', 'HFILE', 'HFONT', 'HGDIOBJ',
    'HGLOBAL', 'HGLRC', 'HHOOK', 'HICON', 'HINSTANCE', 'HKEY', 'HLOCAL',
    'HLSURF', 'HMENU', 'HMETAFILE', 'HMETAFILEPICT', 'HMF', 'HMODULE',
    'HMONITOR', 'HNSTIME', 'HPALETTE', 'HPEN', 'HRESULT', 'HRGN', 'HRSRC',
    'HSPRITE', 'HSTR', 'HSZ', 'HTASK', 'HUMPD', 'HWINEVENTHOOK', 'HWND',
    'HWINSTA', 'HYPER_SIZEDARR', 'HighTime', 'IFACEMETHODIMP', 'IID',
    'IFACEMETHODIMPV', 'IFACEMETHODIMPV_', 'IFACEMETHODIMP_', 'IID_NULL',
    'INT', 'INT16', 'INT32', 'INT64', 'INT8', 'INT_PTR', 'Int32x32To64',
    'InitializeObjectAttributes', 'Int64ShllMod32', 'Int64ShraMod32',
    'Int64ShrlMod32', 'KAFFINITY', 'KIRQL', 'LANGID', 'LANGIDFROMLCID',
    'LANG_AFRIKAANS', 'LANG_ALBANIAN', 'LANG_ALSATIAN', 'LANG_AMHARIC',
    'LANG_ARABIC', 'LANG_ARMENIAN', 'LANG_ASSAMESE', 'LANG_AZERBAIJANI',
    'LANG_AZERI', 'LANG_BANGLA', 'LANG_BASHKIR', 'LANG_BASQUE', 'LANG_YI',
    'LANG_BELARUSIAN', 'LANG_BENGALI', 'LANG_BOSNIAN', 'LANG_BRETON',
    'LANG_BOSNIAN_NEUTRAL', 'LANG_BULGARIAN', 'LANG_CATALAN', 'LANG_DARI',
    'LANG_CENTRAL_KURDISH', 'LANG_CHEROKEE', 'LANG_CHINESE', 'LANG_CZECH',
    'LANG_CHINESE_SIMPLIFIED', 'LANG_CHINESE_TRADITIONAL', 'LANG_DANISH',
    'LANG_CORSICAN', 'LANG_CROATIAN', 'LANG_DIVEHI', 'LANG_DUTCH', 'LCID',
    'LANG_ENGLISH', 'LANG_ESTONIAN', 'LANG_FAEROESE', 'LANG_FARSI', 'MSG',
    'LANG_FILIPINO', 'LANG_FINNISH', 'LANG_FRENCH', 'LANG_FRISIAN', 'PCH',
    'LANG_FULAH', 'LANG_GALICIAN', 'LANG_GEORGIAN', 'LANG_GERMAN', 'LONG',
    'LANG_GREEK', 'LANG_GREENLANDIC', 'LANG_GUJARATI', 'LANG_HAUSA',
    'LANG_HAWAIIAN', 'LANG_HEBREW', 'LANG_HINDI', 'LANG_HUNGARIAN', 'PSZ',
    'LANG_ICELANDIC', 'LANG_IGBO', 'LANG_INDONESIAN', 'LANG_INUKTITUT',
    'LANG_INVARIANT', 'LANG_IRISH', 'LANG_ITALIAN', 'LANG_JAPANESE',
    'LANG_KANNADA', 'LANG_KASHMIRI', 'LANG_KAZAK', 'LANG_KHMER', 'LCTYPE',
    'LANG_KICHE', 'LANG_KINYARWANDA', 'LANG_KONKANI', 'LANG_KOREAN',
    'LANG_KYRGYZ', 'LANG_LAO', 'LANG_LATVIAN', 'LANG_LITHUANIAN', 'LPCCH',
    'LANG_LOWER_SORBIAN', 'LANG_LUXEMBOURGISH', 'LANG_MACEDONIAN', 'LPCH',
    'LANG_MALAY', 'LANG_MALAYALAM', 'LANG_MALTESE', 'LANG_MANIPURI',
    'LANG_MAORI', 'LANG_MAPUDUNGUN', 'LANG_MARATHI', 'LANG_MOHAWK', 'SID',
    'LANG_MONGOLIAN', 'LANG_NEPALI', 'LANG_NEUTRAL', 'LANG_NORWEGIAN',
    'LANG_OCCITAN', 'LANG_ODIA', 'LANG_ORIYA', 'LANG_PASHTO', 'LANG_SAMI',
    'LANG_PERSIAN', 'LANG_POLISH', 'LANG_PORTUGUESE', 'LANG_PULAR', 'USN',
    'LANG_PUNJABI', 'LANG_QUECHUA', 'LANG_ROMANIAN', 'LANG_ROMANSH',
    'LANG_RUSSIAN', 'LANG_SAKHA', 'LANG_SANSKRIT', 'LANG_SCOTTISH_GAELIC',
    'LANG_SERBIAN', 'LANG_SERBIAN_NEUTRAL', 'LANG_SINDHI', 'LANG_SLOVAK',
    'LANG_SINHALESE', 'LANG_SLOVENIAN', 'LANG_SOTHO', 'LANG_SPANISH',
    'LANG_SWAHILI', 'LANG_SWEDISH', 'LANG_SYRIAC', 'LANG_SYSTEM_DEFAULT',
    'LANG_TAJIK', 'LANG_TAMAZIGHT', 'LANG_TAMIL', 'LANG_TATAR', 'LGRPID',
    'LANG_TELUGU', 'LANG_THAI', 'LANG_TIBETAN', 'LANG_TIGRIGNA', 'LONG32',
    'LANG_TIGRINYA', 'LANG_TSWANA', 'LANG_TURKISH', 'LANG_TURKMEN', 'far',
    'LANG_UIGHUR', 'LANG_UKRAINIAN', 'LANG_UPPER_SORBIAN', 'LANG_URDU',
    'LANG_USER_DEFAULT', 'LANG_UZBEK', 'LANG_VALENCIAN', 'LANG_WELSH',
    'LANG_VIETNAMESE', 'LANG_WOLOF', 'LANG_XHOSA', 'LANG_YAKUT', 'LONG64',
    'LANG_YORUBA', 'LANG_ZULU', 'LARGE_INTEGER', 'LIST_ENTRY', 'LOGICAL',
    'LIST_ENTRY32', 'LIST_ENTRY64', 'LOCALE_CUSTOM_DEFAULT', 'LOGPALETTE',
    'LOCALE_CUSTOM_UI_DEFAULT', 'LOCALE_CUSTOM_UNSPECIFIED', 'LONGLONG',
    'LOCALE_INVARIANT', 'LOCALE_NAME_MAX_LENGTH', 'LOCALE_NEUTRAL', 'max',
    'LOCALE_SYSTEM_DEFAULT', 'LOCALE_TRANSIENT_KEYBOARD1', 'LOCALHANDLE',
    'LOCALE_TRANSIENT_KEYBOARD2', 'LOCALE_TRANSIENT_KEYBOARD3', 'LPARAM',
    'LOCALE_TRANSIENT_KEYBOARD4', 'LOCALE_UNASSIGNED_LCID', 'LONG_PTR',
    'LOCALE_USER_DEFAULT', 'LONG_SIZEDARR', 'LPBOOL', 'LPBSTR', 'LPBYTE',
    'LPBSTRBLOB', 'LPCGUID', 'LPCLSID', 'LPCOLESTR', 'LPCOLORREF', 'LPCY',
    'LPCRECT', 'LPCRECTL', 'LPCSTR', 'LPCTCH', 'LPCTSTR', 'LPCUTSTR',
    'LPCUWCHAR', 'LPCUWSTR', 'LPCVOID', 'LPCWCH', 'LPCWCHAR', 'LPCWSTR',
    'LPDECIMAL', 'LPDWORD', 'LPFILETIME', 'LPFLOAT', 'LPFMTID', 'LPGUID',
    'LPHANDLE', 'LPIID', 'LPINT', 'LPLOGPALETTE', 'LPLONG', 'LPMSG',
    'LPOLESTR', 'LPPALETTEENTRY', 'LPPOINT', 'LPPOINTS', 'LPRECT', 'LUID',
    'LPRECTL', 'LPREFERENCE_TIME', 'LPSIZE', 'LPSIZEL', 'LPSTR', 'LPTCH',
    'LPTEXTMETRICW', 'LPTSTR', 'LPUINT', 'LPUINT32', 'LPUINT64', 'LPVOID',
    'LPUTSTR', 'LPUWSTR', 'LPWCH', 'LPWORD', 'LPWSTR', 'LRESULT', 'NEAR',
    'LowTime', 'MAKELANGID', 'MAKELCID', 'MAKESORTLCID', 'MAXCHAR', 'min',
    'MAXIMUM_PROCESSORS', 'MAXIMUM_PROC_PER_GROUP', 'MAXLONG', 'MAXSHORT',
    'MAXLONGLONG', 'MAXUCHAR', 'MAXULONG', 'MAXUSHORT', 'MAX_UCSCHAR',
    'MAX_NATURAL_ALIGNMENT', 'MEMORY_ALLOCATION_ALIGNMENT', 'MFTIME',
    'MINCHAR', 'MINLONG', 'MINSHORT', 'MIN_UCSCHAR', 'NEARPROC', 'NPMSG',
    'NLS_VALID_LOCALE_MASK', 'NOP_FUNCTION', 'NPPOINT', 'NPRECT', 'NPSTR',
    'NTAPI', 'NTAPI_INLINE', 'NTSTATUS', 'NTSYSAPI', 'NTSYSCALLAPI',
    'NT_ERROR', 'NT_INFORMATION', 'NT_PRODUCT_TYPE', 'NT_SUCCESS', 'NULL',
    'NT_WARNING', 'NULL64', 'NWPSTR', 'OBJECTID', 'OBJECT_ATTRIBUTES',
    'OBJECT_ATTRIBUTES32', 'OBJECT_ATTRIBUTES64', 'OBJ_CASE_INSENSITIVE',
    'OBJ_DONT_REPARSE', 'OBJ_EXCLUSIVE', 'OBJ_FORCE_ACCESS_CHECK', 'PACL',
    'OBJ_HANDLE_TAGBITS', 'OBJ_IGNORE_IMPERSONATED_DEVICEMAP', 'OLECHAR',
    'OBJ_INHERIT', 'OBJ_KERNEL_HANDLE', 'OBJ_OPENIF', 'OBJ_OPENLINK',
    'OBJ_PERMANENT', 'OBJ_VALID_ATTRIBUTES', 'OEM_STRING', 'OLESTR',
    'PALETTEENTRY', 'PANSI_STRING', 'PANSI_STRING32', 'PANSI_STRING64',
    'PASCAL', 'PBOOL', 'PBOOLEAN', 'PBYTE', 'PBYTE256', 'PCANSI_STRING',
    'PCCH', 'PCCHAR', 'PCHAR', 'PCLONG', 'PCNTSTATUS', 'PCNZCH', 'PCSTR',
    'PCNZTCH', 'PCNZWCH', 'PCOBJECT_ATTRIBUTES', 'PCOBJECT_ATTRIBUTES32',
    'PCOBJECT_ATTRIBUTES64', 'PCOEM_STRING', 'PCOMPARTMENT_ID', 'PCSCHAR',
    'PCSHORT', 'PCSTRING', 'PCSZ', 'PCTCH', 'PCTSTR', 'PCUCHAR', 'PCWCH',
    'PCUCSCHAR', 'PCUCSSTR', 'PCULONG', 'PCUNICODE_STRING', 'PCUNZTCH',
    'PCUNZWCH', 'PCUQUAD', 'PCUSHORT', 'PCUTSTR', 'PCUUCSCHAR', 'PCUWSTR',
    'PCUUCSSTR', 'PCUWCHAR', 'PCUZZTSTR', 'PCUZZWSTR', 'PCWCHAR', 'PHKEY',
    'PCWNF_STATE_NAME', 'PCWSTR', 'PCZPCSTR', 'PCZPCWSTR', 'PCZPSTR',
    'PCZPWSTR', 'PCZZSTR', 'PCZZTSTR', 'PCZZWSTR', 'PDWORD', 'PDWORD32',
    'PDWORD64', 'PDWORDLONG', 'PDWORD_PTR', 'PFILETIME', 'PFLOAT', 'PINT',
    'PFLOAT128', 'PFORCEINLINE', 'PGROUP_AFFINITY', 'PHALF_PTR', 'PINT16',
    'PHANDLE', 'PHYSICAL_ADDRESS', 'PINT32', 'PINT64', 'PINT8', 'PKIRQL',
    'PINT_PTR', 'PKAFFINITY', 'PLARGE_INTEGER', 'PLCID', 'PLIST_ENTRY',
    'PLIST_ENTRY32', 'PLIST_ENTRY64', 'PLOGICAL', 'PLOGPALETTE', 'PLONG',
    'PLONG32', 'PLONG64', 'PLONGLONG', 'PLONG_PTR', 'PLUID', 'PMSG',
    'PNTSTATUS', 'PNT_PRODUCT_TYPE', 'PNZCH', 'PNZTCH', 'PNZWCH', 'POINT',
    'POBJECT_ATTRIBUTES', 'POBJECT_ATTRIBUTES32', 'POBJECT_ATTRIBUTES64',
    'POEM_STRING', 'POINTER', 'POINTER_32', 'POINTER_64', 'POINTL',
    'POINTER_64_INT', 'POINTER_SIGNED', 'POINTER_UNSIGNED', 'POINTS',
    'PPALETTEENTRY', 'PPHYSICAL_ADDRESS', 'PPOINT', 'PPOINTL', 'PPOINTS',
    'PPROCESSOR_NUMBER', 'PQUAD', 'PRAGMA_DEPRECATED_DDK', 'PRECT',
    'PRECTL', 'PRIMARYLANGID', 'PROBE_ALIGNMENT', 'PROBE_ALIGNMENT32',
    'PROC', 'PROCESSOR_NUMBER', 'PRODUCT_ANDROMEDA', 'PRODUCT_BUSINESS',
    'PRODUCT_ARM64_SERVER', 'PRODUCT_AZURE_NANO_SERVER', 'PRODUCT_CLOUD',
    'PRODUCT_AZURE_SERVER_CORE', 'PRODUCT_BUSINESS_N', 'PRODUCT_CLOUDN',
    'PRODUCT_CLOUD_HOST_INFRASTRUCTURE_SERVER', 'PRODUCT_CLUSTER_SERVER',
    'PRODUCT_CLOUD_STORAGE_SERVER', 'PRODUCT_CLUSTER_SERVER_V', 'PROPID',
    'PRODUCT_CONNECTED_CAR', 'PRODUCT_CORE', 'PRODUCT_CORE_ARM', 'PSCHAR',
    'PRODUCT_CORE_CONNECTED', 'PRODUCT_CORE_CONNECTED_COUNTRYSPECIFIC',
    'PRODUCT_CORE_CONNECTED_N', 'PRODUCT_CORE_CONNECTED_SINGLELANGUAGE',
    'PRODUCT_CORE_COUNTRYSPECIFIC', 'PRODUCT_CORE_N', 'PRODUCT_EDUCATION',
    'PRODUCT_CORE_SINGLELANGUAGE', 'PRODUCT_DATACENTER_A_SERVER_CORE',
    'PRODUCT_DATACENTER_EVALUATION_SERVER', 'PRODUCT_DATACENTER_SERVER',
    'PRODUCT_DATACENTER_EVALUATION_SERVER_CORE', 'PRODUCT_EDUCATION_N',
    'PRODUCT_DATACENTER_NANO_SERVER', 'PRODUCT_DATACENTER_SERVER_CORE',
    'PRODUCT_DATACENTER_SERVER_CORE_V', 'PRODUCT_DATACENTER_SERVER_V',
    'PRODUCT_DATACENTER_WS_SERVER_CORE', 'PRODUCT_EMBEDDED', 'PSCODE',
    'PRODUCT_EMBEDDED_A', 'PRODUCT_EMBEDDED_AUTOMOTIVE', 'PRODUCT_HUBOS',
    'PRODUCT_EMBEDDED_E', 'PRODUCT_EMBEDDED_EVAL', 'PRODUCT_ENTERPRISE',
    'PRODUCT_EMBEDDED_E_EVAL', 'PRODUCT_EMBEDDED_INDUSTRY', 'PROPERTYKEY',
    'PRODUCT_EMBEDDED_INDUSTRY_A', 'PRODUCT_EMBEDDED_INDUSTRY_A_E',
    'PRODUCT_EMBEDDED_INDUSTRY_E', 'PRODUCT_EMBEDDED_INDUSTRY_EVAL',
    'PRODUCT_EMBEDDED_INDUSTRY_E_EVAL', 'PRODUCT_ENTERPRISEG', 'PSHORT',
    'PRODUCT_ENTERPRISEGN', 'PRODUCT_ENTERPRISE_E', 'PRODUCT_HOLOGRAPHIC',
    'PRODUCT_ENTERPRISE_EVALUATION', 'PRODUCT_ENTERPRISE_N', 'PSID',
    'PRODUCT_ENTERPRISE_N_EVALUATION', 'PRODUCT_ENTERPRISE_S', 'PSIZE',
    'PRODUCT_ENTERPRISE_SERVER', 'PRODUCT_ENTERPRISE_SERVER_CORE', 'PSTR',
    'PRODUCT_ENTERPRISE_SERVER_CORE_V', 'PRODUCT_ENTERPRISE_SERVER_IA64',
    'PRODUCT_ENTERPRISE_SERVER_V', 'PRODUCT_ENTERPRISE_SUBSCRIPTION',
    'PRODUCT_ENTERPRISE_SUBSCRIPTION_N', 'PRODUCT_ENTERPRISE_S_N', 'PTCH',
    'PRODUCT_ENTERPRISE_S_EVALUATION', 'PRODUCT_HOME_BASIC', 'PSIZEL',
    'PRODUCT_ENTERPRISE_S_N_EVALUATION', 'PRODUCT_HOME_BASIC_E', 'PTBYTE',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_ADDL', 'PRODUCT_HOME_BASIC_N',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_ADDLSVC', 'PRODUCT_HOME_PREMIUM',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_MGMT', 'PRODUCT_HOME_PREMIUM_E',
    'PRODUCT_ESSENTIALBUSINESS_SERVER_MGMTSVC', 'PRODUCT_HOME_PREMIUM_N',
    'PRODUCT_HOME_PREMIUM_SERVER', 'PRODUCT_HOME_SERVER', 'PSIZE_T',
    'PRODUCT_HYPERV', 'PRODUCT_INDUSTRY_HANDHELD', 'PRODUCT_IOTUAP',
    'PRODUCT_MEDIUMBUSINESS_SERVER_MANAGEMENT', 'PRODUCT_NANO_SERVER',
    'PRODUCT_MEDIUMBUSINESS_SERVER_MESSAGING', 'PRODUCT_ONECOREUPDATEOS',
    'PRODUCT_MEDIUMBUSINESS_SERVER_SECURITY', 'PRODUCT_PPI_PRO', 'PTCHAR',
    'PRODUCT_MULTIPOINT_PREMIUM_SERVER', 'PRODUCT_PROFESSIONAL', 'PTIME',
    'PRODUCT_MULTIPOINT_STANDARD_SERVER', 'PRODUCT_PROFESSIONAL_E',
    'PRODUCT_PROFESSIONAL_EMBEDDED', 'PRODUCT_PROFESSIONAL_N', 'PSSIZE_T',
    'PRODUCT_PROFESSIONAL_S', 'PRODUCT_PROFESSIONAL_STUDENT', 'PSTRING',
    'PRODUCT_PROFESSIONAL_STUDENT_N', 'PRODUCT_PROFESSIONAL_S_N', 'PTSTR',
    'PRODUCT_PROFESSIONAL_WMC', 'PRODUCT_PRO_CHINA', 'PRODUCT_SERVERRDSH',
    'PRODUCT_PRO_FOR_EDUCATION', 'PRODUCT_PRO_FOR_EDUCATION_N', 'PTUCHAR',
    'PRODUCT_PRO_SINGLE_LANGUAGE', 'PRODUCT_PRO_WORKSTATION', 'PSTRING32',
    'PRODUCT_PRO_WORKSTATION_N', 'PRODUCT_SB_SOLUTION_SERVER', 'PUCHAR',
    'PRODUCT_SB_SOLUTION_SERVER_EM', 'PRODUCT_SERVER_FOR_SB_SOLUTIONS',
    'PRODUCT_SERVER_FOR_SB_SOLUTIONS_EM', 'PRODUCT_SERVER_FOUNDATION',
    'PRODUCT_SERVER_FOR_SMALLBUSINESS', 'PRODUCT_SMALLBUSINESS_SERVER',
    'PRODUCT_SERVER_FOR_SMALLBUSINESS_V', 'PRODUCT_STANDARD_NANO_SERVER',
    'PRODUCT_SMALLBUSINESS_SERVER_PREMIUM', 'PRODUCT_STANDARD_SERVER',
    'PRODUCT_SMALLBUSINESS_SERVER_PREMIUM_CORE', 'PRODUCT_STARTER',
    'PRODUCT_SOLUTION_EMBEDDEDSERVER', 'PRODUCT_STANDARD_A_SERVER_CORE',
    'PRODUCT_SOLUTION_EMBEDDEDSERVER_CORE', 'PRODUCT_STANDARD_SERVER_V',
    'PRODUCT_STANDARD_EVALUATION_SERVER', 'PRODUCT_STANDARD_SERVER_CORE',
    'PRODUCT_STANDARD_EVALUATION_SERVER_CORE', 'PRODUCT_STARTER_E',
    'PRODUCT_STANDARD_SERVER_CORE_V', 'PRODUCT_STANDARD_SERVER_SOLUTIONS',
    'PRODUCT_STANDARD_SERVER_SOLUTIONS_CORE', 'PRODUCT_STARTER_N', 'PWCH',
    'PRODUCT_STANDARD_WS_SERVER_CORE', 'PRODUCT_STORAGE_EXPRESS_SERVER',
    'PRODUCT_STORAGE_ENTERPRISE_SERVER', 'PRODUCT_THINPC', 'PSTRING64',
    'PRODUCT_STORAGE_ENTERPRISE_SERVER_CORE', 'PRODUCT_ULTIMATE', 'PUINT',
    'PRODUCT_STORAGE_EXPRESS_SERVER_CORE', 'PRODUCT_ULTIMATE_E', 'PUINT8',
    'PRODUCT_STORAGE_STANDARD_EVALUATION_SERVER', 'PRODUCT_ULTIMATE_N',
    'PRODUCT_STORAGE_STANDARD_SERVER', 'PRODUCT_STORAGE_WORKGROUP_SERVER',
    'PRODUCT_STORAGE_STANDARD_SERVER_CORE', 'PRODUCT_UNDEFINED', 'PULONG',
    'PRODUCT_STORAGE_WORKGROUP_EVALUATION_SERVER', 'PRODUCT_UNLICENSED',
    'PRODUCT_STORAGE_WORKGROUP_SERVER_CORE', 'PRODUCT_UTILITY_VM', 'QUAD',
    'PRODUCT_WEB_SERVER', 'PRODUCT_WEB_SERVER_CORE', 'PRTL_BALANCED_NODE',
    'PRTL_REFERENCE_COUNT', 'PRTL_REFERENCE_COUNT32', 'PTEXTMETRICW',
    'PSECURITY_DESCRIPTOR_CONTROL', 'PSINGLE_LIST_ENTRY', 'PUCSCHAR',
    'PSINGLE_LIST_ENTRY32', 'PUCSSTR', 'PUHALF_PTR', 'PUINT16', 'PUINT32',
    'PUINT64', 'PUINT_PTR', 'PULARGE_INTEGER', 'PULONG32', 'PULONG64',
    'PULONGLONG', 'PULONG_PTR', 'PUNICODE_STRING', 'PUNICODE_STRING32',
    'PUNICODE_STRING64', 'PUNZTCH', 'PUNZWCH', 'PUQUAD', 'PUSHORT',
    'PUTSTR', 'PUUCSCHAR', 'PUUCSSTR', 'PUWSTR', 'PUZZTSTR', 'PUZZWSTR',
    'PVOID', 'PVOID64', 'PWCHAR', 'PWNF_STATE_NAME', 'PWORD', 'PWSTR',
    'PZPCSTR', 'PZPCWSTR', 'PZPSTR', 'PZPTSTR', 'PZPWSTR', 'PZZSTR',
    'PZZTSTR', 'PZZWSTR', 'QUERYCONTEXT', 'QWORD', 'RECT', 'RECTL',
    'REFCLSID', 'REFERENCE_TIME', 'REFFMTID', 'REFGUID', 'REFIID', 'SIZE',
    'RESTRICTED_POINTER', 'RESTRICTED_POINTERPRLIST_ENTRY', 'RTL_BITS_OF',
    'ROTFLAGS_ALLOWANYCLIENT', 'ROTFLAGS_REGISTRATIONKEEPSALIVE', 'SCHAR',
    'ROTREGFLAGS_ALLOWANYCLIENT', 'ROT_COMPARE_MAX', 'RTL_BALANCED_NODE',
    'RTL_BALANCED_NODE_GET_PARENT_POINTER', 'RTL_BITS_OF_FIELD', 'SCODE',
    'RTL_BALANCED_NODE_RESERVED_PARENT_MASK', 'RTL_CONSTANT_STRING',
    'RTL_CONSTANT_OBJECT_ATTRIBUTES', 'RTL_CONST_CAST', 'RTL_FIELD_SIZE',
    'RTL_CONTAINS_FIELD', 'RTL_FIELD_TYPE', 'RTL_INIT_OBJECT_ATTRIBUTES',
    'RTL_NUMBER_OF', 'RTL_NUMBER_OF_FIELD', 'RTL_NUMBER_OF_V1', 'SC_LOCK',
    'RTL_NUMBER_OF_V2', 'RTL_PADDING_BETWEEN_FIELDS', 'RemHBITMAP',
    'RTL_REFERENCE_COUNT', 'RTL_REFERENCE_COUNT32', 'RemHBRUSH', 'SHORT',
    'RTL_SIZEOF_THROUGH_FIELD', 'RTL_STRING_LENGTH_TYPE', 'RemHGLOBAL',
    'RemHENHMETAFILE', 'RemHMETAFILEPICT', 'RemHPALETTE', 'RotateLeft16',
    'RemotableHandle', 'RotateLeft32', 'RotateLeft64', 'RotateLeft8',
    'RotateRight16', 'RotateRight32', 'RotateRight64', 'RotateRight8',
    'SC_HANDLE', 'SECURITY_ATTRIBUTES', 'SECURITY_DESCRIPTOR', 'SIZEL',
    'SECURITY_DESCRIPTOR_CONTROL', 'SECURITY_STATUS', 'SHANDLE_PTR',
    'SERVICE_STATUS_HANDLE', 'SHORT_SIZEDARR', 'SID_AND_ATTRIBUTES',
    'SID_IDENTIFIER_AUTHORITY', 'SINGLE_LIST_ENTRY', 'SIZE_T', 'SPHANDLE',
    'SINGLE_LIST_ENTRY32', 'SMALL_RECT', 'SORTIDFROMLCID', 'SORT_DEFAULT',
    'SORTVERSIONFROMLCID', 'SORT_CHINESE_BIG5', 'SORT_CHINESE_BOPOMOFO',
    'SORT_CHINESE_PRC', 'SORT_CHINESE_PRCP', 'SORT_CHINESE_RADICALSTROKE',
    'SORT_CHINESE_UNICODE', 'SORT_GEORGIAN_MODERN', 'SORT_INVARIANT_MATH',
    'SORT_GEORGIAN_TRADITIONAL', 'SORT_GERMAN_PHONE_BOOK', 'SPOINTER_32',
    'SORT_HUNGARIAN_DEFAULT', 'SORT_HUNGARIAN_TECHNICAL', 'SSIZE_T',
    'SORT_JAPANESE_RADICALSTROKE', 'SORT_JAPANESE_UNICODE', 'STATFLAG',
    'SORT_JAPANESE_XJIS', 'SORT_KOREAN_KSC', 'SORT_KOREAN_UNICODE',
    'STDAPI', 'STDAPICALLTYPE', 'STDAPIV', 'STDAPIVCALLTYPE', 'STDAPIV_',
    'STDAPI_', 'STDMETHODCALLTYPE', 'STDMETHODIMP', 'STDMETHODIMPV',
    'STDMETHODIMPV_', 'STDMETHODIMP_', 'STDMETHODVCALLTYPE', 'STGC',
    'STDOVERRIDEMETHODIMP', 'STDOVERRIDEMETHODIMPV', 'STGMOVE', 'STRICT',
    'STDOVERRIDEMETHODIMPV_', 'STDOVERRIDEMETHODIMP_', 'STKFORCEINLINE',
    'STRING', 'STRING32', 'STRING64', 'SUBLANGID', 'SUBLANG_ARABIC_EGYPT',
    'SUBLANG_AFRIKAANS_SOUTH_AFRICA', 'SUBLANG_ALBANIAN_ALBANIA', 'TBYTE',
    'SUBLANG_ALSATIAN_FRANCE', 'SUBLANG_AMHARIC_ETHIOPIA', 'SUITE_TYPE',
    'SUBLANG_ARABIC_ALGERIA', 'SUBLANG_ARABIC_BAHRAIN', 'SUBLANG_DEFAULT',
    'SUBLANG_ARABIC_IRAQ', 'SUBLANG_ARABIC_JORDAN', 'SUBLANG_ARABIC_OMAN',
    'SUBLANG_ARABIC_KUWAIT', 'SUBLANG_ARABIC_LEBANON', 'SUBLANG_DUTCH',
    'SUBLANG_ARABIC_LIBYA', 'SUBLANG_ARABIC_MOROCCO', 'SUBLANG_FRENCH',
    'SUBLANG_ARABIC_QATAR', 'SUBLANG_ARABIC_SAUDI_ARABIA', 'SYSTEMTIME',
    'SUBLANG_ARABIC_SYRIA', 'SUBLANG_ARABIC_TUNISIA', 'SUBLANG_GERMAN',
    'SUBLANG_ARABIC_UAE', 'SUBLANG_ARABIC_YEMEN', 'SUBLANG_AZERI_LATIN',
    'SUBLANG_ARMENIAN_ARMENIA', 'SUBLANG_ASSAMESE_INDIA', 'TCHAR', 'TEXT',
    'SUBLANG_AZERBAIJANI_AZERBAIJAN_CYRILLIC', 'SUBLANG_AZERI_CYRILLIC',
    'SUBLANG_AZERBAIJANI_AZERBAIJAN_LATIN', 'SUBLANG_BANGLA_BANGLADESH',
    'SUBLANG_BANGLA_INDIA', 'SUBLANG_BASHKIR_RUSSIA', 'SUBLANG_ITALIAN',
    'SUBLANG_BASQUE_BASQUE', 'SUBLANG_BELARUSIAN_BELARUS', 'TEXTMETRICW',
    'SUBLANG_BENGALI_BANGLADESH', 'SUBLANG_BENGALI_INDIA', 'TIME', 'TRUE',
    'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC', 'SUBLANG_ENGLISH_AUS',
    'SUBLANG_BOSNIAN_BOSNIA_HERZEGOVINA_LATIN', 'SUBLANG_BRETON_FRANCE',
    'SUBLANG_BULGARIAN_BULGARIA', 'SUBLANG_CATALAN_CATALAN', 'TIMER_TYPE',
    'SUBLANG_CENTRAL_KURDISH_IRAQ', 'SUBLANG_CHEROKEE_CHEROKEE', 'TUCHAR',
    'SUBLANG_CHINESE_HONGKONG', 'SUBLANG_CHINESE_MACAU', 'SUBLANG_KOREAN',
    'SUBLANG_CHINESE_SIMPLIFIED', 'SUBLANG_CHINESE_SINGAPORE', 'TYSPEC',
    'SUBLANG_CHINESE_TRADITIONAL', 'SUBLANG_CORSICAN_FRANCE', 'UBYTE',
    'SUBLANG_CROATIAN_BOSNIA_HERZEGOVINA_LATIN', 'SUBLANG_CUSTOM_DEFAULT',
    'SUBLANG_CROATIAN_CROATIA', 'SUBLANG_CUSTOM_UNSPECIFIED', 'UCHAR',
    'SUBLANG_CZECH_CZECH_REPUBLIC', 'SUBLANG_DANISH_DENMARK', 'UCSCHAR',
    'SUBLANG_DARI_AFGHANISTAN', 'SUBLANG_DIVEHI_MALDIVES', 'UHALF_PTR',
    'SUBLANG_DUTCH_BELGIAN', 'SUBLANG_ENGLISH_BELIZE', 'SUBLANG_LAO_LAO',
    'SUBLANG_ENGLISH_CAN', 'SUBLANG_ENGLISH_CARIBBEAN', 'SUBLANG_NEUTRAL',
    'SUBLANG_ENGLISH_EIRE', 'SUBLANG_ENGLISH_INDIA', 'SUBLANG_ENGLISH_NZ',
    'SUBLANG_ENGLISH_JAMAICA', 'SUBLANG_ENGLISH_MALAYSIA', 'UINT', 'VOID',
    'SUBLANG_ENGLISH_PHILIPPINES', 'SUBLANG_ENGLISH_SINGAPORE', 'UINT16',
    'SUBLANG_ENGLISH_SOUTH_AFRICA', 'SUBLANG_ENGLISH_TRINIDAD', 'UINT32',
    'SUBLANG_ENGLISH_UK', 'SUBLANG_ENGLISH_US', 'SUBLANG_FINNISH_FINLAND',
    'SUBLANG_ENGLISH_ZIMBABWE', 'SUBLANG_ESTONIAN_ESTONIA', 'UINT64',
    'SUBLANG_FAEROESE_FAROE_ISLANDS', 'SUBLANG_FILIPINO_PHILIPPINES',
    'SUBLANG_FRENCH_BELGIAN', 'SUBLANG_FRENCH_CANADIAN', 'SUBLANG_YI_PRC',
    'SUBLANG_FRENCH_LUXEMBOURG', 'SUBLANG_FRENCH_MONACO', 'UFIELD_OFFSET',
    'SUBLANG_FRENCH_SWISS', 'SUBLANG_FRISIAN_NETHERLANDS', 'UINT8',
    'SUBLANG_FULAH_SENEGAL', 'SUBLANG_GALICIAN_GALICIAN', 'UINT_PTR',
    'SUBLANG_GEORGIAN_GEORGIA', 'SUBLANG_GERMAN_AUSTRIAN', 'ULONG',
    'SUBLANG_GERMAN_LIECHTENSTEIN', 'SUBLANG_GERMAN_LUXEMBOURG', 'UQUAD',
    'SUBLANG_GERMAN_SWISS', 'SUBLANG_GREEK_GREECE', 'SUBLANG_HAWAIIAN_US',
    'SUBLANG_GREENLANDIC_GREENLAND', 'SUBLANG_GUJARATI_INDIA', 'ULONG32',
    'SUBLANG_HAUSA_NIGERIA_LATIN', 'SUBLANG_HEBREW_ISRAEL', 'ULONG64',
    'SUBLANG_HINDI_INDIA', 'SUBLANG_HUNGARIAN_HUNGARY', 'SUBLANG_SPANISH',
    'SUBLANG_ICELANDIC_ICELAND', 'SUBLANG_IGBO_NIGERIA', 'TYPE_ALIGNMENT',
    'SUBLANG_INDONESIAN_INDONESIA', 'SUBLANG_INUKTITUT_CANADA', 'USHORT',
    'SUBLANG_INUKTITUT_CANADA_LATIN', 'SUBLANG_IRISH_IRELAND', 'VARENUM',
    'SUBLANG_ITALIAN_SWISS', 'SUBLANG_JAPANESE_JAPAN', 'SUBLANG_SWEDISH',
    'SUBLANG_KANNADA_INDIA', 'SUBLANG_KASHMIRI_INDIA', 'UInt32x32To64',
    'SUBLANG_KASHMIRI_SASIA', 'SUBLANG_KAZAK_KAZAKHSTAN', 'ULONGLONG',
    'SUBLANG_KHMER_CAMBODIA', 'SUBLANG_KICHE_GUATEMALA', 'ULARGE_INTEGER',
    'SUBLANG_KINYARWANDA_RWANDA', 'SUBLANG_KONKANI_INDIA', 'ULONG_PTR',
    'SUBLANG_KYRGYZ_KYRGYZSTAN', 'SUBLANG_LATVIAN_LATVIA', 'UNALIGNED',
    'SUBLANG_LITHUANIAN', 'SUBLANG_LOWER_SORBIAN_GERMANY', 'UNALIGNED64',
    'SUBLANG_LUXEMBOURGISH_LUXEMBOURG', 'SUBLANG_MACEDONIAN_MACEDONIA',
    'SUBLANG_MALAYALAM_INDIA', 'SUBLANG_MALAY_BRUNEI_DARUSSALAM', 'WCHAR',
    'SUBLANG_MALAY_MALAYSIA', 'SUBLANG_MALTESE_MALTA', 'UNICODE_NULL',
    'SUBLANG_MAORI_NEW_ZEALAND', 'SUBLANG_MAPUDUNGUN_CHILE', 'VARTYPE',
    'SUBLANG_MARATHI_INDIA', 'SUBLANG_MOHAWK_MOHAWK', 'UNICODE_STRING',
    'SUBLANG_MONGOLIAN_CYRILLIC_MONGOLIA', 'SUBLANG_MONGOLIAN_PRC',
    'SUBLANG_NEPALI_INDIA', 'SUBLANG_NEPALI_NEPAL', 'SUBLANG_ODIA_INDIA',
    'SUBLANG_NORWEGIAN_BOKMAL', 'SUBLANG_NORWEGIAN_NYNORSK', 'WAIT_TYPE',
    'SUBLANG_OCCITAN_FRANCE', 'SUBLANG_ORIYA_INDIA', 'SUBLANG_PORTUGUESE',
    'SUBLANG_PASHTO_AFGHANISTAN', 'SUBLANG_PERSIAN_IRAN', 'UPOINTER_32',
    'SUBLANG_POLISH_POLAND', 'SUBLANG_PORTUGUESE_BRAZILIAN', 'WINAPI',
    'SUBLANG_PULAR_SENEGAL', 'SUBLANG_PUNJABI_INDIA', 'UNICODE_STRING32',
    'SUBLANG_PUNJABI_PAKISTAN', 'SUBLANG_QUECHUA_BOLIVIA', 'UP_BYTE_BLOB',
    'SUBLANG_QUECHUA_ECUADOR', 'SUBLANG_QUECHUA_PERU', 'UNICODE_STRING64',
    'SUBLANG_ROMANIAN_ROMANIA', 'SUBLANG_ROMANSH_SWITZERLAND', 'WINAPIV',
    'SUBLANG_RUSSIAN_RUSSIA', 'SUBLANG_SAKHA_RUSSIA', 'UP_DWORD_BLOB',
    'SUBLANG_SAMI_INARI_FINLAND', 'SUBLANG_SAMI_LULE_NORWAY', 'WORD',
    'SUBLANG_SAMI_LULE_SWEDEN', 'SUBLANG_SAMI_NORTHERN_FINLAND', 'WPARAM',
    'SUBLANG_SAMI_NORTHERN_NORWAY', 'SUBLANG_SAMI_NORTHERN_SWEDEN',
    'SUBLANG_SAMI_SKOLT_FINLAND', 'SUBLANG_SAMI_SOUTHERN_NORWAY', '_GUID',
    'SUBLANG_SAMI_SOUTHERN_SWEDEN', 'SUBLANG_SANSKRIT_INDIA', 'WORD_BLOB',
    'SUBLANG_SCOTTISH_GAELIC', 'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_LATIN',
    'SUBLANG_SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC', 'SUBLANG_SINDHI_INDIA',
    'SUBLANG_SERBIAN_CROATIA', 'SUBLANG_SERBIAN_CYRILLIC', 'UP_WORD_BLOB',
    'SUBLANG_SERBIAN_LATIN', 'SUBLANG_SERBIAN_MONTENEGRO_CYRILLIC',
    'SUBLANG_SERBIAN_MONTENEGRO_LATIN', 'SUBLANG_SERBIAN_SERBIA_CYRILLIC',
    'SUBLANG_SERBIAN_SERBIA_LATIN', 'SUBLANG_SINDHI_AFGHANISTAN', '_IID',
    'SUBLANG_SINDHI_PAKISTAN', 'SUBLANG_SINHALESE_SRI_LANKA', 'WSTRING',
    'SUBLANG_SLOVAK_SLOVAKIA', 'SUBLANG_SLOVENIAN_SLOVENIA', '_ARRAYSIZE',
    'SUBLANG_SOTHO_NORTHERN_SOUTH_AFRICA', 'SUBLANG_SPANISH_ARGENTINA',
    'SUBLANG_SPANISH_BOLIVIA', 'SUBLANG_SPANISH_CHILE', 'VARIANT_BOOL',
    'SUBLANG_SPANISH_COLOMBIA', 'SUBLANG_SPANISH_COSTA_RICA', '_CLSID',
    'SUBLANG_SPANISH_DOMINICAN_REPUBLIC', 'SUBLANG_SPANISH_ECUADOR',
    'SUBLANG_SPANISH_EL_SALVADOR', 'SUBLANG_SPANISH_GUATEMALA', '_FMTID',
    'SUBLANG_SPANISH_HONDURAS', 'SUBLANG_SPANISH_MEXICAN', 'VARIANT_TRUE',
    'SUBLANG_SPANISH_MODERN', 'SUBLANG_SPANISH_NICARAGUA', '_CLSID_NULL',
    'SUBLANG_SPANISH_PANAMA', 'SUBLANG_SPANISH_PARAGUAY', 'VARIANT_FALSE',
    'SUBLANG_SPANISH_PERU', 'SUBLANG_SPANISH_PUERTO_RICO', '_CSTRING',
    'SUBLANG_SPANISH_URUGUAY', 'SUBLANG_SPANISH_US', 'SUBLANG_UIGHUR_PRC',
    'SUBLANG_SPANISH_VENEZUELA', 'SUBLANG_SWAHILI_KENYA', 'VER_SERVER_NT',
    'SUBLANG_SWEDISH_FINLAND', 'SUBLANG_SYRIAC_SYRIA', 'VER_SUITE_BLADE',
    'SUBLANG_SYS_DEFAULT', 'SUBLANG_TAJIK_TAJIKISTAN', 'WDT_INPROC_CALL',
    'SUBLANG_TAMAZIGHT_ALGERIA_LATIN', 'SUBLANG_TAMIL_INDIA', '_FLOAT128',
    'SUBLANG_TAMAZIGHT_MOROCCO_TIFINAGH', 'SUBLANG_TAMIL_SRI_LANKA',
    'SUBLANG_TATAR_RUSSIA', 'SUBLANG_TELUGU_INDIA', 'SUBLANG_TIBETAN_PRC',
    'SUBLANG_THAI_THAILAND', 'SUBLANG_TIGRIGNA_ERITREA', 'WINAPI_INLINE',
    'SUBLANG_TIGRINYA_ERITREA', 'SUBLANG_TIGRINYA_ETHIOPIA', '_GUID_NULL',
    'SUBLANG_TSWANA_BOTSWANA', 'SUBLANG_TSWANA_SOUTH_AFRICA', '_IID_NULL',
    'SUBLANG_TURKISH_TURKEY', 'SUBLANG_TURKMEN_TURKMENISTAN', '_LPCGUID',
    'SUBLANG_UI_CUSTOM_DEFAULT', 'SUBLANG_UKRAINIAN_UKRAINE', '_LPCLSID',
    'SUBLANG_UPPER_SORBIAN_GERMANY', 'SUBLANG_URDU_INDIA', '_EVENT_TYPE',
    'SUBLANG_URDU_PAKISTAN', 'SUBLANG_UZBEK_CYRILLIC', 'WDT_REMOTE_CALL',
    'SUBLANG_UZBEK_LATIN', 'SUBLANG_VALENCIAN_VALENCIA', 'WNF_STATE_NAME',
    'SUBLANG_VIETNAMESE_VIETNAM', 'SUBLANG_WELSH_UNITED_KINGDOM', '_LUID',
    'SUBLANG_WOLOF_SENEGAL', 'SUBLANG_XHOSA_SOUTH_AFRICA', '_FMTID_NULL',
    'SUBLANG_YAKUT_RUSSIA', 'SUBLANG_YORUBA_NIGERIA', 'WDT_INPROC64_CALL',
    'SUBLANG_ZULU_SOUTH_AFRICA', 'SYSTEM_CACHE_ALIGNMENT_SIZE', '_LPGUID',
    'UCSCHAR_INVALID_CHARACTER', 'UNICODE_STRING_MAX_BYTES', '_LPFMTID',
    'UNICODE_STRING_MAX_CHARS', 'UNREFERENCED_PARAMETER', 'WORD_SIZEDARR',
    'UP_FLAGGED_BYTE_BLOB', 'UP_FLAGGED_WORD_BLOB', 'VER_SUITE_PERSONAL',
    'VER_SUITE_BACKOFFICE', 'VER_SUITE_COMMUNICATIONS', '_GDI_NONREMOTE',
    'VER_SUITE_COMPUTE_SERVER', 'VER_SUITE_DATACENTER', '_GROUP_AFFINITY',
    'VER_SUITE_EMBEDDEDNT', 'VER_SUITE_EMBEDDED_RESTRICTED', '_LPIID',
    'VER_SUITE_ENTERPRISE', 'VER_SUITE_MULTIUSERTS', 'VER_SUITE_TERMINAL',
    'VER_SUITE_SECURITY_APPLIANCE', 'VER_SUITE_SINGLEUSERTS', '_OBJECTID',
    'VER_SUITE_SMALLBUSINESS', 'VER_SUITE_SMALLBUSINESS_RESTRICTED',
    'VER_SUITE_STORAGE_SERVER', 'VER_SUITE_WH_SERVER', 'WIN32_FIND_DATAA',
    'VER_WORKSTATION_NT', 'WIN32_FIND_DATAW', '_ENUM_FLAG_CONSTEXPR',
    '_LARGE_INTEGER', '_LIST_ENTRY', '_NT_PRODUCT_TYPE', '_POINTL',
    '_OBJECT_ATTRIBUTES', '_OBJECT_ATTRIBUTES32', '_OBJECT_ATTRIBUTES64',
    '_PROCESSOR_NUMBER', '_QUAD', '_RECTL', '_REFCLSID', '_REFFMTID',
    '_REFGUID', '_REFIID', '_RTL_BALANCED_NODE', '_RemotableHandle',
    '_RTL_CONSTANT_STRING_remove_const_macro', '_SINGLE_LIST_ENTRY',
    '_SINGLE_LIST_ENTRY32', '_STRING', '_STRING32', '_STRING64', '_TIME',
    '_SUITE_TYPE', '_TIMER_TYPE', '_ULARGE_INTEGER', '_UNICODE_STRING',
    '_VARIANT_BOOL', '_WAIT_TYPE', '_WNF_STATE_NAME', '__TEXT', 'cdecl',
    '__MIDL___MIDL_itf_wtypes_0000_0001_0001', '_remoteMETAFILEPICT',
    '__REQUIRED_RPCNDR_H_VERSION__', '__REQUIRED_RPCSAL_H_VERSION__',
    '_tagpropertykey', '_userBITMAP', '_userCLIPFORMAT', '_userHBITMAP',
    '_userHENHMETAFILE', '_userHGLOBAL', '_userHMETAFILE', '_wcsicmp',
    '_userHMETAFILEPICT', '_userHPALETTE', 'near', 'pascal', 'tagBLOB',
    'remoteMETAFILEPICT', 'tagBSTRBLOB', 'tagCLIPDATA', 'tagCLSCTX',
    'tagCSPLATFORM', 'tagCY', 'tagDEC', 'tagDVASPECT', 'tagLOGPALETTE',
    'tagMEMCTX', 'tagMSG', 'tagMSHCTX', 'tagMSHLFLAGS', 'tagPALETTEENTRY',
    'tagPOINT', 'tagPOINTS', 'tagQUERYCONTEXT', 'tagRECT', 'tagRemBRUSH',
    'tagRemHBITMAP', 'tagRemHENHMETAFILE', 'tagRemHGLOBAL', 'tagSIZE',
    'tagRemHMETAFILEPICT', 'tagRemHPALETTE', 'tagSIZEL', 'tagSTATFLAG',
    'tagSTGC', 'tagSTGMOVE', 'tagTEXTMETRICW', 'tagTYSPEC', 'uCLSSPEC',
    'userBITMAP', 'userCLIPFORMAT', 'userHBITMAP', 'userHENHMETAFILE',
    'userHGLOBAL', 'userHMETAFILE', 'userHMETAFILEPICT', 'userHPALETTE',
    'wireBSTR', 'wireCLIPFORMAT', 'wireHACCEL', 'wireHBITMAP', 'wireHDC',
    'wireHBRUSH', 'wireHENHMETAFILE', 'wireHFONT', 'wireHGLOBAL',
    'wireHICON', 'wireHMENU', 'wireHMETAFILE', 'wireHMETAFILEPICT',
    'wireHMONITOR', 'wireHPALETTE', 'wireHRGN', 'wireHWND', 'INTERFACE',
    'LONGLONG_PTR', 'DWORDLONG_PTR', 'DECLSPEC_DEPRECATED_DDK'
)
