

from .wtypes_h import (
    ULONG,
    POINTER,
    UINT,
)
import ctypes


DOT4_MAX_CHANNELS = 0x80
NO_TIMEOUT = 0x0
STREAM_TYPE_CHANNEL = 0x1
PACKET_TYPE_CHANNEL = 0x2
DOT4_STREAM_RECEIVED = 0x100
DOT4_STREAM_CREDITS = 0x101
DOT4_MESSAGE_RECEIVED = 0x102
DOT4_DISCONNECT = 0x103
DOT4_CHANNEL_CLOSED = 0x105
DOT4_CHANNEL = 0x0
HP_MESSAGE_PROCESSOR = 0x1
PRINTER_CHANNEL = 0x2
SCANNER_CHANNEL = 0x4
MIO_COMMAND_PROCESSOR = 0x5
ECHO_CHANNEL = 0x6
FAX_SEND_CHANNEL = 0x7
FAX_RECV_CHANNEL = 0x8
DIAGNOSTIC_CHANNEL = 0x9
HP_RESERVED = 0xA
IMAGE_DOWNLOAD = 0xB
HOST_DATASTORE_UPLOAD = 0xC
HOST_DATASTORE_DOWNLOAD = 0xD
CONFIG_UPLOAD = 0xE
CONFIG_DOWNLOAD = 0xF
CHANNEL_HANDLE = UINT
PCHANNEL_HANDLE = POINTER(CHANNEL_HANDLE)


class _DOT4_ACTIVITY(ctypes.Structure):
    _fields_ = [
        ('ulMessage', ULONG),
        ('ulByteCount', ULONG),
        ('hChannel', CHANNEL_HANDLE),
    ]


DOT4_ACTIVITY = _DOT4_ACTIVITY
PDOT4_ACTIVITY = POINTER(_DOT4_ACTIVITY)


__all__ = (
    'CONFIG_DOWNLOAD', 'IMAGE_DOWNLOAD', 'DOT4_STREAM_CREDITS', 'NO_TIMEOUT',
    'PRINTER_CHANNEL', 'FAX_RECV_CHANNEL', 'DIAGNOSTIC_CHANNEL',
    'CONFIG_UPLOAD', 'DOT4_STREAM_RECEIVED', 'HOST_DATASTORE_DOWNLOAD',
    'FAX_SEND_CHANNEL', 'DOT4_CHANNEL', 'DOT4_CHANNEL_CLOSED', 'ECHO_CHANNEL',
    'SCANNER_CHANNEL', 'STREAM_TYPE_CHANNEL', 'DOT4_DISCONNECT',
    'HP_MESSAGE_PROCESSOR', 'DOT4_MESSAGE_RECEIVED', 'DOT4_MAX_CHANNELS',
    'HOST_DATASTORE_UPLOAD', 'HP_RESERVED', 'MIO_COMMAND_PROCESSOR',
    'PACKET_TYPE_CHANNEL', 'DOT4_ACTIVITY', 'PDOT4_ACTIVITY',
    '_DOT4_ACTIVITY', 'CHANNEL_HANDLE', 'PCHANNEL_HANDLE',
)
