import ctypes
from pyWinAPI import *
from pyWinAPI.shared.wtypes_h import *
from pyWinAPI.shared.winapifamily_h import *
from pyWinAPI.shared.sdkddkver_h import *
from pyWinAPI.shared.guiddef_h import *


class _tagKSKSTELEPHONY_DESCRIPTOR(ctypes.Structure):
    pass


KSTELEPHONY_DESCRIPTOR = _tagKSKSTELEPHONY_DESCRIPTOR
PKSTELEPHONY_DESCRIPTOR = POINTER(_tagKSKSTELEPHONY_DESCRIPTOR)


class _tagKSKSTELEPHONY_INSTANCE_DATA(ctypes.Structure):
    pass


KSTELEPHONY_INSTANCE_DATA = _tagKSKSTELEPHONY_INSTANCE_DATA
PKSTELEPHONY_INSTANCE_DATA = POINTER(_tagKSKSTELEPHONY_INSTANCE_DATA)


class CameraPropertyItem(ctypes.Structure):
    pass


PCameraPropertyItem = POINTER(CameraPropertyItem)


class CameraMetadata(ctypes.Structure):
    pass


PCameraMetadata = POINTER(CameraMetadata)


class WPCAMERA_STORYBOARD_HEADER_S(ctypes.Structure):
    pass


PWPCAMERA_STORYBOARD_HEADER_S = POINTER(WPCAMERA_STORYBOARD_HEADER_S)


class FRECT(ctypes.Structure):
    pass


PFRECT = POINTER(FRECT)


class KSPROPERTY_ZOOM_ROI_INFO(ctypes.Structure):
    pass


PKSPROPERTY_ZOOM_ROI_INFO = POINTER(KSPROPERTY_ZOOM_ROI_INFO)


class WPCAMERA_ISPCONTROL_TYPES_UNION(ctypes.Union):
    pass


class WPCAMERA_VARIANT(ctypes.Structure):
    pass


class WPCAMERA_ISPCONTROL_PROPERTY_S(ctypes.Structure):
    pass


PWPCAMERA_ISPCONTROL_PROPERTY_S = POINTER(WPCAMERA_ISPCONTROL_PROPERTY_S)


class WPCAMERA_ISPCONTROL_APPLIED_PROPERTIES_S(ctypes.Structure):
    pass


PWPCAMERA_ISPCONTROL_APPLIED_PROPERTIES_S = POINTER(WPCAMERA_ISPCONTROL_APPLIED_PROPERTIES_S)


class KSPROPERTY_CAMERACONTROL_S_WP(ctypes.Structure):
    pass


PKSPROPERTY_CAMERACONTROL_S_WP = POINTER(KSPROPERTY_CAMERACONTROL_S_WP)


class WPCAMERA_STORYBOARD_FRAME_S(ctypes.Structure):
    pass


PWPCAMERA_STORYBOARD_FRAME_S = POINTER(WPCAMERA_STORYBOARD_FRAME_S)


class KSPROPERTY_CAMERACONTROL_SB_S(ctypes.Structure):
    pass


PKSPROPERTY_CAMERACONTROL_SB_S = POINTER(KSPROPERTY_CAMERACONTROL_SB_S)


class KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE_S(ctypes.Structure):
    pass


PKSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE_S = POINTER(KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE_S)


_KSMEDIA_PHONE_ = None
# /* + + Copyright (c) Microsoft Corporation. All rights reserved. Module
# Name: ksmedia_phone.h Abstract: WDM - CSA Multimedia Definitions. - -
if not defined(_KSMEDIA_PHONE_):
    _KSMEDIA_PHONE_ = 1
    from pyWinAPI.shared.ksmedia_h import * # NOQA

    if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP):
        if NTDDI_VERSION >= NTDDI_WINBLUE:
            # Nodetypes for Windows Phone Audio Routing.

            # {A79D957D-5CD5-458A-B3F1-AF8E789B1F3B}
            STATIC_KSNODETYPE_HFP_SIDEBAND_HEADSET = (
                0xA79D957D,
                0x5CD5,
                0x458A,
                0xB3,
                0xF1,
                0xAF,
                0x8E,
                0x78,
                0x9B,
                0x1F,
                0x3B
            )
            KSNODETYPE_HFP_SIDEBAND_HEADSET = DEFINE_GUIDSTRUCT(
                "{A79D957D-5CD5-458A-B3F1-AF8E789B1F3B}"
            )
            KSNODETYPE_HFP_SIDEBAND_HEADSET = (
                DEFINE_GUIDNAMED(KSNODETYPE_HFP_SIDEBAND_HEADSET)
            )

            # {1CCF610B-F3DB-47C1-834C-B19BC76CE5AB}
            STATIC_KSNODETYPE_SPEAKER_AND_HEADSET = (
                0x1CCF610B,
                0xF3DB,
                0x47C1,
                0x83,
                0x4C,
                0xB1,
                0x9B,
                0xC7,
                0x6C,
                0xE5,
                0xAB
            )
            KSNODETYPE_SPEAKER_AND_HEADSET = DEFINE_GUIDSTRUCT(
                "{1CCF610B-F3DB-47C1-834C-B19BC76CE5AB}"
            )
            KSNODETYPE_SPEAKER_AND_HEADSET = (
                DEFINE_GUIDNAMED(KSNODETYPE_SPEAKER_AND_HEADSET)
            )

            # {9E25F2E6-8387-4DB3-A13F-9FAAC23D28A9}
            STATIC_KSNODETYPE_TEE = (
                0x9E25F2E6,
                0x8387,
                0x4DB3,
                0xA1,
                0x3F,
                0x9F,
                0xAA,
                0xC2,
                0x3D,
                0x28,
                0xA9
            )
            KSNODETYPE_TEE = DEFINE_GUIDSTRUCT(
                "9E25F2E6-8387-4DB3-A13F-9FAAC23D28A9"
            )
            KSNODETYPE_TEE = DEFINE_GUIDNAMED(KSNODETYPE_TEE)

            # {84A3C1BD-88A1-40DD-8420-1D9C6442B524}
            STATIC_KSNODETYPE_AUDIO_TELEPHONY = (
                0x84A3C1BD,
                0x88A1,
                0x40DD,
                0x84,
                0x20,
                0x1D,
                0x9C,
                0x64,
                0x42,
                0xB5,
                0x24
            )
            KSNODETYPE_AUDIO_TELEPHONY = DEFINE_GUIDSTRUCT(
                "84A3C1BD-88A1-40DD-8420-1D9C6442B524"
            )
            KSNODETYPE_AUDIO_TELEPHONY = (
                DEFINE_GUIDNAMED(KSNODETYPE_AUDIO_TELEPHONY)
            )
        # END IF   (NTDDI_VERSION >= NTDDI_WINBLUE)
        # == == == == == == == == == == == == == == == == == == == == == == ==
        # == == == == == == == == == == == == == == =
        # Phone-specific properties and property set

        if NTDDI_VERSION >= NTDDI_WINBLUE:
            _tagKSKSTELEPHONY_DESCRIPTOR._fields_ = [
                ('nRenderPinId', UINT),
                ('nCapturePinId', UINT),
            ]


            class TELEPHONY_PROVIDER_TYPE(ENUM):
                TELEPHONY_PROVIDER_TYPE_CIRCUIT_SWITCHED = 0
                TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED = 1
                TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED_WLAN = 2

            TELEPHONY_PROVIDER_TYPE_CIRCUIT_SWITCHED = TELEPHONY_PROVIDER_TYPE.TELEPHONY_PROVIDER_TYPE_CIRCUIT_SWITCHED
            TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED = TELEPHONY_PROVIDER_TYPE.TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED
            TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED_WLAN = TELEPHONY_PROVIDER_TYPE.TELEPHONY_PROVIDER_TYPE_PACKET_SWITCHED_WLAN

            _tagKSKSTELEPHONY_INSTANCE_DATA._fields_ = [
                ('TelephonyProviderType', TELEPHONY_PROVIDER_TYPE),
                ('TelephonyProviderId', UINT),
            ]
            STATIC_KSPROPSETID_PhoneAudio = (
                0xB0C69F47,
                0xEFF1,
                0x4009,
                0xB2,
                0x2E,
                0xCE,
                0xB6,
                0x22,
                0xF,
                0x6F,
                0xFA
            )
            KSPROPSETID_PhoneAudio = DEFINE_GUIDSTRUCT(
                "B0C69F47-EFF1-4009-B22E-CEB6220F6FFA"
            )
            KSPROPSETID_PhoneAudio = DEFINE_GUIDNAMED(KSPROPSETID_PhoneAudio)


            class KSPROPERTY_PHONEAUDIO(ENUM):
                KSPROPERTY_PHONEAUDIO_TELEPHONY_INSTANCE_DATA = 0
                KSPROPERTY_PHONEAUDIO_TELEPHONY_DESCRIPTOR = 1
                KSPROPERTY_PHONEAUDIO_DEVICE_ORIENTATION = 2

            KSPROPERTY_PHONEAUDIO_TELEPHONY_INSTANCE_DATA = KSPROPERTY_PHONEAUDIO.KSPROPERTY_PHONEAUDIO_TELEPHONY_INSTANCE_DATA
            KSPROPERTY_PHONEAUDIO_TELEPHONY_DESCRIPTOR = KSPROPERTY_PHONEAUDIO.KSPROPERTY_PHONEAUDIO_TELEPHONY_DESCRIPTOR
            KSPROPERTY_PHONEAUDIO_DEVICE_ORIENTATION = KSPROPERTY_PHONEAUDIO.KSPROPERTY_PHONEAUDIO_DEVICE_ORIENTATION
            STATIC_KSPROPSETID_BTSCO_NREC = (
                0x7F50F0BE,
                0x8E26,
                0x4F96,
                0xA0,
                0x79,
                0x1C,
                0xF8,
                0x41,
                0x02,
                0xB9,
                0x18
            )
            KSPROPSETID_BTSCO_NREC = DEFINE_GUIDSTRUCT(
                "7f50f0be-8e26-4f96-a079-1cf84102b918"
            )
            KSPROPSETID_BTSCO_NREC = DEFINE_GUIDNAMED(KSPROPSETID_BTSCO_NREC)


            class KSPROPERTY_BTSCO_NREC(ENUM):
                KSPROPERTY_BTSCO_NREC_STATE = 1

            KSPROPERTY_BTSCO_NREC_STATE = KSPROPERTY_BTSCO_NREC.KSPROPERTY_BTSCO_NREC_STATE
        # END IF   (NTDDI_VERSION >= NTDDI_WINBLUE)

        class KSEVENT_CAMERACONTROL_EXT(ENUM):
            KSEVENT_CAMERACONTROL_FLASH = 2
            KSEVENT_CAMERACONTROL_FOCUS_START = 3
            KSEVENT_CAMERACONTROL_FOCUS_COMPLETE = 4
            KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_START = 5
            KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_COMPLETE = 6
            KSEVENT_CAMERACONTROL_SAMPLE_SCANNED = 7


        KSEVENT_CAMERACONTROL_FLASH = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_FLASH
        KSEVENT_CAMERACONTROL_FOCUS_START = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_FOCUS_START
        KSEVENT_CAMERACONTROL_FOCUS_COMPLETE = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_FOCUS_COMPLETE
        KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_START = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_START
        KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_COMPLETE = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_CONTINUOUSFOCUS_COMPLETE
        KSEVENT_CAMERACONTROL_SAMPLE_SCANNED = KSEVENT_CAMERACONTROL_EXT.KSEVENT_CAMERACONTROL_SAMPLE_SCANNED


        class KSPROPERTY_VIDCAP_CAMERACONTROL_EX(ENUM):
            KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL = 1000
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_CONTROL = 1001
            KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTROL = 1002
            KSPROPERTY_CAMERACONTROL_FOCUS_LENS_POSITION = 1003
            KSPROPERTY_CAMERACONTROL_FOCUS_RECTANGLE = 1004
            KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER = 1005
            KSPROPERTY_CAMERACONTROL_ZOOM_CONTROL = 1006
            KSPROPERTY_CAMERACONTROL_FLASH_MODE = 1007
            KSPROPERTY_CAMERACONTROL_FLASH_POWER_CONTROL = 1008
            KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_MODE = 1009
            KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_POWER_CONTROL = 1010
            KSPROPERTY_CAMERACONTROL_3A_LOCK = 1011
            KSPROPERTY_CAMERACONTROL_WB_MODE = 1012
            KSPROPERTY_CAMERACONTROL_WB_MANUAL_PRESET = 1013
            KSPROPERTY_CAMERACONTROL_WB_MANUAL = 1014
            KSPROPERTY_CAMERACONTROL_FPS_CONTROL = 1015
            KSPROPERTY_CAMERACONTROL_PREVIEW_FPS = 1016
            KSPROPERTY_CAMERACONTROL_VIDEO_FPS = 1017
            KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE = 1018
            KSPROPERTY_CAMERACONTROL_LINEAR_EXPOSURE = 1019
            KSPROPERTY_CAMERACONTROL_EV_COMPENSATION = 1020
            KSPROPERTY_CAMERACONTROL_ISO_MODE = 1021
            KSPROPERTY_CAMERACONTROL_ISO = 1022
            KSPROPERTY_CAMERACONTROL_SCENE_MODE = 1023
            KSPROPERTY_CAMERACONTROL_GET_CAPS = 1024
            KSPROPERTY_CAMERACONTROL_SB = 1025
            KSPROPERTY_CAMERACONTROL_SET_ACTIVE_SB = 1026
            KSPROPERTY_CAMERACONTROL_SB_TRIGGER = 1027
            KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE = 1028
            KSPROPERTY_CAMERACONTROL_EXIF = 1029
            KSPROPERTY_CAMERACONTROL_MCC = 1030
            KSPROPERTY_CAMERACONTROL_ZOOM_ROI_INFO = 1031


        KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL
        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_CONTROL
        KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTROL
        KSPROPERTY_CAMERACONTROL_FOCUS_LENS_POSITION = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_LENS_POSITION
        KSPROPERTY_CAMERACONTROL_FOCUS_RECTANGLE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_RECTANGLE
        KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER
        KSPROPERTY_CAMERACONTROL_ZOOM_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_ZOOM_CONTROL
        KSPROPERTY_CAMERACONTROL_FLASH_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FLASH_MODE
        KSPROPERTY_CAMERACONTROL_FLASH_POWER_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FLASH_POWER_CONTROL
        KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_MODE
        KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_POWER_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_VIDEO_LIGHT_POWER_CONTROL
        KSPROPERTY_CAMERACONTROL_3A_LOCK = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_3A_LOCK
        KSPROPERTY_CAMERACONTROL_WB_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_WB_MODE
        KSPROPERTY_CAMERACONTROL_WB_MANUAL_PRESET = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_WB_MANUAL_PRESET
        KSPROPERTY_CAMERACONTROL_WB_MANUAL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_WB_MANUAL
        KSPROPERTY_CAMERACONTROL_FPS_CONTROL = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_FPS_CONTROL
        KSPROPERTY_CAMERACONTROL_PREVIEW_FPS = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_PREVIEW_FPS
        KSPROPERTY_CAMERACONTROL_VIDEO_FPS = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_VIDEO_FPS
        KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE
        KSPROPERTY_CAMERACONTROL_LINEAR_EXPOSURE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_LINEAR_EXPOSURE
        KSPROPERTY_CAMERACONTROL_EV_COMPENSATION = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_EV_COMPENSATION
        KSPROPERTY_CAMERACONTROL_ISO_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_ISO_MODE
        KSPROPERTY_CAMERACONTROL_ISO = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_ISO
        KSPROPERTY_CAMERACONTROL_SCENE_MODE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_SCENE_MODE
        KSPROPERTY_CAMERACONTROL_GET_CAPS = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_GET_CAPS
        KSPROPERTY_CAMERACONTROL_SB = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_SB
        KSPROPERTY_CAMERACONTROL_SET_ACTIVE_SB = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_SET_ACTIVE_SB
        KSPROPERTY_CAMERACONTROL_SB_TRIGGER = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_SB_TRIGGER
        KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE
        KSPROPERTY_CAMERACONTROL_EXIF = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_EXIF
        KSPROPERTY_CAMERACONTROL_MCC = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_MCC
        KSPROPERTY_CAMERACONTROL_ZOOM_ROI_INFO = KSPROPERTY_VIDCAP_CAMERACONTROL_EX.KSPROPERTY_CAMERACONTROL_ZOOM_ROI_INFO


        class KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_MANUAL = 0x0002


        KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_AUTO = KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_AUTO
        KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_MANUAL = KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_REGION_CONTROL_MANUAL


        class KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_MACRO = 0x0001
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_NORMAL = 0x0002
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_FULL = 0x0004
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_HYPERFOCAL = 0x0008
            KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_INFINITY = 0x0010


        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_MACRO = KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_MACRO
        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_NORMAL = KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_NORMAL
        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_FULL = KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_FULL
        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_HYPERFOCAL = KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_HYPERFOCAL
        KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_INFINITY = KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_RANGE_INFINITY


        class KSPROPERTY_CAMERACONTROL_FOCUS_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_FOCUS_MODE_SINGLE = 0x0001
            KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTINUOUS = 0x0002
            KSPROPERTY_CAMERACONTROL_FOCUS_MODE_MANUAL = 0x0004


        KSPROPERTY_CAMERACONTROL_FOCUS_MODE_SINGLE = KSPROPERTY_CAMERACONTROL_FOCUS_MODE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_MODE_SINGLE
        KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTINUOUS = KSPROPERTY_CAMERACONTROL_FOCUS_MODE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_MODE_CONTINUOUS
        KSPROPERTY_CAMERACONTROL_FOCUS_MODE_MANUAL = KSPROPERTY_CAMERACONTROL_FOCUS_MODE_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_MODE_MANUAL


        class KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_START = 1
            KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_STOP = 2
            KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_RESET = 3
            KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_CANCEL = 4


        KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_START = KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_START
        KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_STOP = KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_STOP
        KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_RESET = KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_RESET
        KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_CANCEL = KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_VALUE.KSPROPERTY_CAMERACONTROL_FOCUS_TRIGGER_CANCEL


        class KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO(ENUM):
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_ON_OFF = 0x0002
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_REDEYE_ON_OFF = 0x0004
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_AUTO = 0x0008
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_POWER = 0x0010
            KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_ON_OFF = 0x0020


        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_AUTO = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_AUTO
        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_ON_OFF = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_ASSISTANT_ON_OFF
        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_REDEYE_ON_OFF = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_REDEYE_ON_OFF
        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_AUTO = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_AUTO
        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_POWER = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_POWER
        KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_ON_OFF = KSPROPERTY_CAMERACONTROL_FLASH_MODE_PHOTO.KSPROPERTY_CAMERACONTROL_PHOTOFLASH_FLASH_ON_OFF


        class KSPROPERTY_CAMERACONTROL_FLASH_MODE_VIDEO(ENUM):
            KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_ON_OFF = 0x0002
            KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_POWER = 0x0004


        KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_AUTO = KSPROPERTY_CAMERACONTROL_FLASH_MODE_VIDEO.KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_AUTO
        KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_ON_OFF = KSPROPERTY_CAMERACONTROL_FLASH_MODE_VIDEO.KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_ON_OFF
        KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_POWER = KSPROPERTY_CAMERACONTROL_FLASH_MODE_VIDEO.KSPROPERTY_CAMERACONTROL_VIDEOFLASH_FLASH_POWER


        class KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_MANUAL = 0x0002


        KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_AUTO = KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_AUTO
        KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_MANUAL = KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_EXPOSURE_MODE_MANUAL


        class KSPROPERTY_CAMERACONTROL_WB_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_WB_MODE_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL = 0x0002
            KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL_PRESET = 0x0004


        KSPROPERTY_CAMERACONTROL_WB_MODE_AUTO = KSPROPERTY_CAMERACONTROL_WB_MODE_VALUE.KSPROPERTY_CAMERACONTROL_WB_MODE_AUTO
        KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL = KSPROPERTY_CAMERACONTROL_WB_MODE_VALUE.KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL
        KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL_PRESET = KSPROPERTY_CAMERACONTROL_WB_MODE_VALUE.KSPROPERTY_CAMERACONTROL_WB_MODE_MANUAL_PRESET


        class KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_WB_PRESET_CLOUDY = 0x0001
            KSPROPERTY_CAMERACONTROL_WB_PRESET_DAYLIGHT = 0x0002
            KSPROPERTY_CAMERACONTROL_WB_PRESET_FLASH = 0x0004
            KSPROPERTY_CAMERACONTROL_WB_PRESET_FLUORESCENT = 0x0008
            KSPROPERTY_CAMERACONTROL_WB_PRESET_TUNGSTEN = 0x0010
            KSPROPERTY_CAMERACONTROL_WB_PRESET_CANDLELIGHT = 0x0020


        KSPROPERTY_CAMERACONTROL_WB_PRESET_CLOUDY = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_CLOUDY
        KSPROPERTY_CAMERACONTROL_WB_PRESET_DAYLIGHT = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_DAYLIGHT
        KSPROPERTY_CAMERACONTROL_WB_PRESET_FLASH = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_FLASH
        KSPROPERTY_CAMERACONTROL_WB_PRESET_FLUORESCENT = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_FLUORESCENT
        KSPROPERTY_CAMERACONTROL_WB_PRESET_TUNGSTEN = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_TUNGSTEN
        KSPROPERTY_CAMERACONTROL_WB_PRESET_CANDLELIGHT = KSPROPERTY_CAMERACONTROL_WB_PRESET_VALUE.KSPROPERTY_CAMERACONTROL_WB_PRESET_CANDLELIGHT


        class KSPROPERTY_CAMERACONTROL_ISO_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_ISO_MODE_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_ISO_MODE_MANUAL = 0x0002


        KSPROPERTY_CAMERACONTROL_ISO_MODE_AUTO = KSPROPERTY_CAMERACONTROL_ISO_MODE_VALUE.KSPROPERTY_CAMERACONTROL_ISO_MODE_AUTO
        KSPROPERTY_CAMERACONTROL_ISO_MODE_MANUAL = KSPROPERTY_CAMERACONTROL_ISO_MODE_VALUE.KSPROPERTY_CAMERACONTROL_ISO_MODE_MANUAL


        class KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_MACRO = 0x0002
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_PORTRAIT = 0x0004
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_SPORT = 0x0008
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_SNOW = 0x0010
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT = 0x0020
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_BEACH = 0x0040
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_SUNSET = 0x0080
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_CANDLE_LIGHT = 0x0100
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_LANDSCAPE = 0x0200
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT_PORTRAIT = 0x0400
            KSPROPERTY_CAMERACONTROL_SCENE_MODE_BACKLIGHT = 0x0800


        KSPROPERTY_CAMERACONTROL_SCENE_MODE_AUTO = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_AUTO
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_MACRO = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_MACRO
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_PORTRAIT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_PORTRAIT
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_SPORT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_SPORT
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_SNOW = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_SNOW
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_BEACH = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_BEACH
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_SUNSET = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_SUNSET
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_CANDLE_LIGHT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_CANDLE_LIGHT
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_LANDSCAPE = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_LANDSCAPE
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT_PORTRAIT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_NIGHT_PORTRAIT
        KSPROPERTY_CAMERACONTROL_SCENE_MODE_BACKLIGHT = KSPROPERTY_CAMERACONTROL_SCENE_MODE_VALUE.KSPROPERTY_CAMERACONTROL_SCENE_MODE_BACKLIGHT


        class KSPROPERTY_CAMERACONTROL_3A_LOCK_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_3A_LOCK_FOCUS = 0x0001
            KSPROPERTY_CAMERACONTROL_3A_LOCK_EXPOSURE = 0x0002
            KSPROPERTY_CAMERACONTROL_3A_LOCK_WB = 0x0004


        KSPROPERTY_CAMERACONTROL_3A_LOCK_FOCUS = KSPROPERTY_CAMERACONTROL_3A_LOCK_VALUE.KSPROPERTY_CAMERACONTROL_3A_LOCK_FOCUS
        KSPROPERTY_CAMERACONTROL_3A_LOCK_EXPOSURE = KSPROPERTY_CAMERACONTROL_3A_LOCK_VALUE.KSPROPERTY_CAMERACONTROL_3A_LOCK_EXPOSURE
        KSPROPERTY_CAMERACONTROL_3A_LOCK_WB = KSPROPERTY_CAMERACONTROL_3A_LOCK_VALUE.KSPROPERTY_CAMERACONTROL_3A_LOCK_WB


        class KSPROPERTY_CAMERACONTROL_FPS_MODE_VALUE(ENUM):
            KSPROPERTY_CAMERACONTROL_FPS_PREVIEW_AUTO = 0x0001
            KSPROPERTY_CAMERACONTROL_FPS_VIDEO_AUTO = 0x0002


        KSPROPERTY_CAMERACONTROL_FPS_PREVIEW_AUTO = KSPROPERTY_CAMERACONTROL_FPS_MODE_VALUE.KSPROPERTY_CAMERACONTROL_FPS_PREVIEW_AUTO
        KSPROPERTY_CAMERACONTROL_FPS_VIDEO_AUTO = KSPROPERTY_CAMERACONTROL_FPS_MODE_VALUE.KSPROPERTY_CAMERACONTROL_FPS_VIDEO_AUTO
        KSPROPERTY_CAMERACONTROL_FLAGS_ASYNCHRONOUS = 0x0004

        # Flattened version of the PropertyItem class defined in imaging.h
        CameraPropertyItem._fields_ = [
            # Size of this structure in bytes
            ('cbSize', SIZE_T),
            # From imaging.h
            ('dwPropId', DWORD),
            # propId type; from imaging.h
            ('dwType', DWORD),
            # Length of byData in bytes
            ('cbData', SIZE_T),
            # First byte of the data
            ('byData', BYTE * 1),
        ]

        # We will modify the CAMERA_METADATA_S structure to accommodate an
        # "array" of variable length CameraPropertyItem structures
        CameraMetadata._fields_ = [
            # Size of this structure in bytes
            ('cbSize', SIZE_T),
            # Number of CameraPropertyItems
            ('cElements', DWORD),
            # The first CameraPropertyItem in the "array"
            ('camPropertyItem', CameraPropertyItem),
        ]

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Pin descriptors ID
        # /////////////////////////////////////////////////////////////////////////////
        #
        # Dedicated Pin ID
        class WPCAMERA_PIN_TYPE(ENUM):
            WPCAMERA_PIN_TYPE_STREAMING_STILL = 1
            WPCAMERA_PIN_TYPE_VIDEO = 2
            WPCAMERA_PIN_TYPE_PREVIEW = 3
            WPCAMERA_PIN_TYPE_STILL = 4
            WPCAMERA_PIN_TYPE_END_OF_PINTYPE = 5


        WPCAMERA_PIN_TYPE_STREAMING_STILL = WPCAMERA_PIN_TYPE.WPCAMERA_PIN_TYPE_STREAMING_STILL
        WPCAMERA_PIN_TYPE_VIDEO = WPCAMERA_PIN_TYPE.WPCAMERA_PIN_TYPE_VIDEO
        WPCAMERA_PIN_TYPE_PREVIEW = WPCAMERA_PIN_TYPE.WPCAMERA_PIN_TYPE_PREVIEW
        WPCAMERA_PIN_TYPE_STILL = WPCAMERA_PIN_TYPE.WPCAMERA_PIN_TYPE_STILL
        WPCAMERA_PIN_TYPE_END_OF_PINTYPE = WPCAMERA_PIN_TYPE.WPCAMERA_PIN_TYPE_END_OF_PINTYPE

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard header and enums
        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard header structure
        WPCAMERA_STORYBOARD_HEADER_S._fields_ = [
            # Unique ID for this storyboard
            ('guidSBId', GUID),
            # Identifies the desired image stats
            ('dwIMGStats', DWORD),
            # The image format appended by the driver
            ('dwMetadataIMGFormat', DWORD),
            # Whether or not to loop
            ('dwSBLoopCount', DWORD),
            # How to loop in the storyboard
            ('dwSBLoopControl', DWORD),
            # Loop until the loop condition is met
            ('dwSBLoopCondition', DWORD),
            # The frame position of the SBLoop
            ('dwSBLoopFramePosition', DWORD),
            # Official data struct to describe FourCC
            ('rawImageInfoHeader', KS_BITMAPINFOHEADER),
        ]

        # Storyboard dwIMGStats values
        class WPCAMERA_STORYBOARD_IMGSTAT_VALUE(ENUM):
            WPCAMERA_STORYBOARD_IMGSTAT_IMG_DATA = 0x00000001
            WPCAMERA_STORYBOARD_IMGSTAT_ISP_METADATA = 0x00000002
            WPCAMERA_STORYBOARD_IMGSTAT_ISP_APPLIED_VALUES = 0x00000004
            WPCAMERA_STORYBOARD_IMGSTAT_ISP_ALL_VALUES = 0x00000008
            WPCAMERA_STORYBOARD_IMGSTAT_EXIF_DATA = 0x00000010


        WPCAMERA_STORYBOARD_IMGSTAT_IMG_DATA = WPCAMERA_STORYBOARD_IMGSTAT_VALUE.WPCAMERA_STORYBOARD_IMGSTAT_IMG_DATA
        WPCAMERA_STORYBOARD_IMGSTAT_ISP_METADATA = WPCAMERA_STORYBOARD_IMGSTAT_VALUE.WPCAMERA_STORYBOARD_IMGSTAT_ISP_METADATA
        WPCAMERA_STORYBOARD_IMGSTAT_ISP_APPLIED_VALUES = WPCAMERA_STORYBOARD_IMGSTAT_VALUE.WPCAMERA_STORYBOARD_IMGSTAT_ISP_APPLIED_VALUES
        WPCAMERA_STORYBOARD_IMGSTAT_ISP_ALL_VALUES = WPCAMERA_STORYBOARD_IMGSTAT_VALUE.WPCAMERA_STORYBOARD_IMGSTAT_ISP_ALL_VALUES
        WPCAMERA_STORYBOARD_IMGSTAT_EXIF_DATA = WPCAMERA_STORYBOARD_IMGSTAT_VALUE.WPCAMERA_STORYBOARD_IMGSTAT_EXIF_DATA


        # Storyboard dwMetadataIMGFormat values
        class WPCAMERA_STORYBOARD_META_IMG_FORMAT_VALUE(ENUM):
            WPCAMERA_STORYBOARD_META_IMG_FORMAT_NONE = 0x0000
            WPCAMERA_STORYBOARD_META_IMG_FORMAT_PRE_RAW = 0x0001
            WPCAMERA_STORYBOARD_META_IMG_FORMAT_IDEAL_RAW = 0x0002


        WPCAMERA_STORYBOARD_META_IMG_FORMAT_NONE = WPCAMERA_STORYBOARD_META_IMG_FORMAT_VALUE.WPCAMERA_STORYBOARD_META_IMG_FORMAT_NONE
        WPCAMERA_STORYBOARD_META_IMG_FORMAT_PRE_RAW = WPCAMERA_STORYBOARD_META_IMG_FORMAT_VALUE.WPCAMERA_STORYBOARD_META_IMG_FORMAT_PRE_RAW
        WPCAMERA_STORYBOARD_META_IMG_FORMAT_IDEAL_RAW = WPCAMERA_STORYBOARD_META_IMG_FORMAT_VALUE.WPCAMERA_STORYBOARD_META_IMG_FORMAT_IDEAL_RAW

        # Storyboard dwSBLoopCondition values
        class WPCAMERA_STORYBOARD_LOOP_COND_VALUE(ENUM):
            WPCAMERA_STORYBOARD_LOOP_COND_NONE = 0x00000000
            WPCAMERA_STORYBOARD_LOOP_COND_FOCUS = 0x00000001
            WPCAMERA_STORYBOARD_LOOP_COND_ZOOM = 0x00000002
            WPCAMERA_STORYBOARD_LOOP_COND_EXPOSURE = 0x00000004
            WPCAMERA_STORYBOARD_LOOP_COND_AWB = 0x00000008
            WPCAMERA_STORYBOARD_LOOP_COND_FLASH_READY = 0x00000010
            WPCAMERA_STORYBOARD_LOOP_COND_ALL = 0xFFFFFFFF


        WPCAMERA_STORYBOARD_LOOP_COND_NONE = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_NONE
        WPCAMERA_STORYBOARD_LOOP_COND_FOCUS = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_FOCUS
        WPCAMERA_STORYBOARD_LOOP_COND_ZOOM = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_ZOOM
        WPCAMERA_STORYBOARD_LOOP_COND_EXPOSURE = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_EXPOSURE
        WPCAMERA_STORYBOARD_LOOP_COND_AWB = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_AWB
        WPCAMERA_STORYBOARD_LOOP_COND_FLASH_READY = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_FLASH_READY
        WPCAMERA_STORYBOARD_LOOP_COND_ALL = WPCAMERA_STORYBOARD_LOOP_COND_VALUE.WPCAMERA_STORYBOARD_LOOP_COND_ALL

        # /////////////////////////////////////////////////////////////////////////////
        #
        # ISP Control property structure and types
        # /////////////////////////////////////////////////////////////////////////////
        #
        FRECT._fields_ = [
            ('left', FLOAT),
            ('top', FLOAT),
            ('right', FLOAT),
            ('bottom', FLOAT),
        ]

        KSPROPERTY_ZOOM_ROI_INFO._fields_ = [
            ('requestedVal', LONG),
            ('actualVal', LONG),
            ('zoomRoI', RECT),
        ]

        # Supported ISP Control Data Types Enumeration
        class WPCAMERA_ISPCONTROL_DATA_TYPE(ENUM):
            WPCAMERA_ISPCONTROL_TYPE_LONG = 1
            WPCAMERA_ISPCONTROL_TYPE_ULONG = 2
            WPCAMERA_ISPCONTROL_TYPE_RECT = 3
            WPCAMERA_ISPCONTROL_TYPE_FRECT = 4
            WPCAMERA_ISPCONTROL_TYPE_STEPPING = 5
            WPCAMERA_ISPCONTROL_TYPE_BYTEARRAY = 6
            WPCAMERA_ISPCONTROL_TYPE_ZOOMINFO = 7


        class WPCAMERA_ISPCONTROL_TYPE_BYTEARRAY(//):
            pass


        WPCAMERA_ISPCONTROL_TYPE_BYTEARRAY._fields_ = [
            ('cbSize', SIZE_T),
            ('byteArray', BYTE * 1),
        ]
        _Struct_1 = WPCAMERA_ISPCONTROL_TYPE_BYTEARRAY
        WPCAMERA_ISPCONTROL_TYPES_UNION._Struct_1 = _Struct_1

        WPCAMERA_ISPCONTROL_TYPES_UNION._anonymous_ = (
            '_Struct_1',
        )

        WPCAMERA_ISPCONTROL_TYPES_UNION._fields_ = [
            # WPCAMERA_ISPCONTROL_TYPE_LONG
            ('lLongValue', LONG),
            # WPCAMERA_ISPCONTROL_TYPE_ULONG
            ('ulLongValue', ULONG),
            # WPCAMERA_ISPCONTROL_TYPE_RECT
            ('rectValue', RECT),
            # WPCAMERA_ISPCONTROL_TYPE_FRECT
            ('fRectValue', FRECT),
            # WPCAMERA_ISPCONTROL_TYPE_STEPPING
            ('boundsAndSteppingValue', KSPROPERTY_STEPPING_LONG),
            # WPCAMERA_ISPCONTROL_TYPE_BYTEARRAY
            ('_Struct_1', WPCAMERA_ISPCONTROL_TYPES_UNION._Struct_1),
            # WPCAMERA_ISPCONTROL_TYPE_ZOOMINFO
            ('zoomRoIInfo', KSPROPERTY_ZOOM_ROI_INFO),
            # Default is LONG
            ('lDefaultValue', LONG),
        ]

        WPCAMERA_VARIANT._fields_ = [
            ('cbSize', DWORD),
            ('Type', WPCAMERA_ISPCONTROL_DATA_TYPE),
            ('dataType', WPCAMERA_ISPCONTROL_TYPES_UNION),
        ]

        # Structure representing an individual ISP control
        WPCAMERA_ISPCONTROL_PROPERTY_S._fields_ = [
            ('cbSize', DWORD),
            ('PropId', KSIDENTIFIER),
            ('propData', WPCAMERA_VARIANT),
        ]

        # This structure can be used to represent an array of ISP controls.
        # It is currently used along with the
        # WPCAMERA_STORYBOARD_IMGSTAT_ISP_APPLIED_VALUES
        # image stats dataType in a WPCAMERA_BLOCK_ITEM_S structure.
        WPCAMERA_ISPCONTROL_APPLIED_PROPERTIES_S._fields_ = [
            # Size of this structure in bytes
            ('cbSize', SIZE_T),
            # Number of WPCAMERA_ISPCONTROL_PROPERTY_S structures
            ('cElements', DWORD),
            # The address of the first
            ('ISPcontrol', WPCAMERA_ISPCONTROL_PROPERTY_S * 1),
        ]

        KSPROPERTY_CAMERACONTROL_S_WP._fields_ = [
            ('Property', KSPROPERTY),
            # value to get or set
            ('Value', LONG),
            # KSPROPERTY_CAMERACONTROL_FLAGS_*
            ('Flags', ULONG),
            # KSPROPERTY_CAMERACONTROL_FLAGS_*
            ('Capabilities', ULONG),
            ('PropData', WPCAMERA_VARIANT),
        ]

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard frame and enums
        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard frame structure
        WPCAMERA_STORYBOARD_FRAME_S._fields_ = [
            # Size of this structure in bytes
            ('cbSize', SIZE_T),
            # Number of WPCAMERA_ISPCONTROL_PROPERTY_S structures
            ('cElements', DWORD),
            # Delay in microseconds between frames
            ('dwSBDelayTime', DWORD),
            # Delay until the condition is met
            ('dwSBDelayCondition', DWORD),
            # The address of the first
            ('ISPcontrol', WPCAMERA_ISPCONTROL_PROPERTY_S * 1),
        ]

        # Storyboard dwSBDelayCondition values
        class WPCAMERA_STORYBOARD_DELAY_COND_VALUE(ENUM):
            WPCAMERA_STORYBOARD_DELAY_COND_NONE = 0x0000
            WPCAMERA_STORYBOARD_DELAY_COND_FOCUS = 0x0001
            WPCAMERA_STORYBOARD_DELAY_COND_ZOOM = 0x0002
            WPCAMERA_STORYBOARD_DELAY_COND_EXPOSURE = 0x0004
            WPCAMERA_STORYBOARD_DELAY_COND_AWB = 0x0008
            WPCAMERA_STORYBOARD_DELAY_COND_FLASH_READY = 0x0010
            WPCAMERA_STORYBOARD_DEALY_COND_ALL = 0x80000000


        WPCAMERA_STORYBOARD_DELAY_COND_NONE = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_NONE
        WPCAMERA_STORYBOARD_DELAY_COND_FOCUS = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_FOCUS
        WPCAMERA_STORYBOARD_DELAY_COND_ZOOM = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_ZOOM
        WPCAMERA_STORYBOARD_DELAY_COND_EXPOSURE = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_EXPOSURE
        WPCAMERA_STORYBOARD_DELAY_COND_AWB = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_AWB
        WPCAMERA_STORYBOARD_DELAY_COND_FLASH_READY = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DELAY_COND_FLASH_READY
        WPCAMERA_STORYBOARD_DEALY_COND_ALL = WPCAMERA_STORYBOARD_DELAY_COND_VALUE.WPCAMERA_STORYBOARD_DEALY_COND_ALL

        # Supported storyboard targets
        class WPCAMERA_STORYBOARD_TARGET(ENUM):
            STORYBOARD_TARGET_STILL = 1
            STORYBOARD_TARGET_PREVIEW = 2
            STORYBOARD_TARGET_VIDEO = 3

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard structure
        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard structure
        KSPROPERTY_CAMERACONTROL_SB_S._fields_ = [
            # Size of this structure in bytes
            ('cbSize', SIZE_T),
            # Destination for this storyboard
            ('sbTarget', WPCAMERA_STORYBOARD_TARGET),
            # The storyboard header structure
            ('sbHeader', WPCAMERA_STORYBOARD_HEADER_S),
            # The number of frames in this storyboard
            ('csbFrames', DWORD),
            # The first storyboard frame in the "array"
            ('SBFrame', WPCAMERA_STORYBOARD_FRAME_S),
        ]

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard resource estimate request structure
        # /////////////////////////////////////////////////////////////////////////////
        #
        # Storyboard resource estimate request
        KSPROPERTY_CAMERACONTROL_SB_RESOURCE_ESTIMATE_S._fields_ = [
            ('ksProp', KSPROPERTY),
            # Unique ID for this storyboard
            ('guidSBId', GUID),
            # The resource estimate in bytes
            ('dwResourceEstimate', DWORD),
        ]

        # /////////////////////////////////////////////////////////////////////////////
        #
        # Device properties for Windows Phone cameras
        # /////////////////////////////////////////////////////////////////////////////
        #

        from pyWinAPI.shared.devpropdef_h import * # NOQA

        if defined(DEFINE_DEVPROPKEY):
            # Device properties, these properties are stored in Windows Phone
            # 8-style camera device interfaces.
            # {B7B4D61C-5A64-4187-A52E-B1539F359099}
            DEVPKEY_WP8Camera_Flags = DEFINE_DEVPROPKEY(
                0xB7B4D61C,
                0x5A64,
                0x4187,
                0xA5,
                0x2E,
                0xB1,
                0x53,
                0x9F,
                0x35,
                0x90,
                0x99,
                2
            )

            # If set, indicates this is an interface on an original WP8 camera
            # device
            WP8CF_ORIGINAL = 0x00000001

            # If set, indicates this is a legacy interface, for accessing a
            # new camera device, using the original WP8 contract
            WP8CF_LEGACY = 0x00001000
        # END IF

        # Note: In the original WP8 camera driver, the following GUIDs
        # appeared in the DEVPKEY_Device_PhysicalDeviceLocation device key.
        # That is now deprecated, and replaced by the property above. Instead,
        # the DEVPKEY_Device_PhysicalDeviceLocation device key should
        # always contain an ACPI_PLD_BUFFER structure.
        # GUID for primary (rear-facing) camera
        # {9D9A0F5E-CDE9-49f5-B464-BF13429DDEB5}
        PRIMARY_CAMERA = DEFINE_GUID(
            0x9D9A0F5E,
            0xCDE9,
            0x49F5,
            0xB4,
            0x64,
            0xBF,
            0x13,
            0x42,
            0x9D,
            0xDE,
            0xB5
        )

        # GUID for front-facing camera
        # {75D53C4E-963E-4415-AA88-89107F08D1EE}
        FRONT_FACING_CAMERA = DEFINE_GUID(
            0x75D53C4E,
            0x963E,
            0x4415,
            0xAA,
            0x88,
            0x89,
            0x10,
            0x7F,
            0x8,
            0xD1,
            0xEE
        )
        if NTDDI_WINTHRESHOLD > NTDDI_VERSION >= NTDDI_WINBLUE:
            # These Modes are defined for PhoneBlue only.
            # Communications mode specifies that the application expects VoIP
            # specific signal processing at the lowest latency and the
            # hardware preferred sample rate for wideband speech
            # (such as 16 kHz).
            # For both Capture and Render.
            STATIC_AUDIO_SIGNALPROCESSINGMODE_COMMUNICATIONS = (
                0x98951333,
                0xB9CD,
                0x48B1,
                0xA0,
                0xA3,
                0xFF,
                0x40,
                0x68,
                0x2D,
                0x73,
                0xF7
            )
            AUDIO_SIGNALPROCESSINGMODE_COMMUNICATIONS = DEFINE_GUIDSTRUCT(
                "98951333-B9CD-48B1-A0A3-FF40682D73F7"
            )
            AUDIO_SIGNALPROCESSINGMODE_COMMUNICATIONS = (
                DEFINE_GUIDNAMED(AUDIO_SIGNALPROCESSINGMODE_COMMUNICATIONS)
            )

            # Speech mode specifies that the application expects speech
            # recognition specific signal processing at the lowest latency and
            # the hardware preferred sample rate for wideband speech
            # (such as 16 kHz).
            # For Capture only.
            STATIC_AUDIO_SIGNALPROCESSINGMODE_SPEECH = (
                0xFC1CFC9B,
                0xB9D6,
                0x4CFA,
                0xB5,
                0xE0,
                0x4B,
                0xB2,
                0x16,
                0x68,
                0x78,
                0xB2
            )
            AUDIO_SIGNALPROCESSINGMODE_SPEECH = DEFINE_GUIDSTRUCT(
                "FC1CFC9B-B9D6-4CFA-B5E0-4BB2166878B2"
            )
            AUDIO_SIGNALPROCESSINGMODE_SPEECH = (
                DEFINE_GUIDNAMED(AUDIO_SIGNALPROCESSINGMODE_SPEECH)
            )

            # Music Mode specifies that the application expects post
            # processing suitable for music content if available or else the
            # same treatments as Default mode.
            # For Render only.
            STATIC_AUDIO_SIGNALPROCESSINGMODE_MUSIC = (
                0x4780004E,
                0x7133,
                0x41D8,
                0x8C,
                0x74,
                0x66,
                0x0D,
                0xAD,
                0xD2,
                0xC0,
                0xEE
            )
            AUDIO_SIGNALPROCESSINGMODE_MUSIC = DEFINE_GUIDSTRUCT(
                "4780004E-7133-41D8-8C74-660DADD2C0EE"
            )
            AUDIO_SIGNALPROCESSINGMODE_MUSIC = (
                DEFINE_GUIDNAMED(AUDIO_SIGNALPROCESSINGMODE_MUSIC)
            )
        # END IF
    # END IF  WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
# END IF   not defined(_KSMEDIA_PHONE_)
