

from wtypes_h import (
    ENUM,
    UCHAR,
    ULONG,
    USHORT,
    POINTER,
    ULONGLONG,
    LONG,
    CHAR,
    INT,
    CLSID,
    BOOLEAN,
    SHORT,
    WCHAR,
    UNALIGNED,
    CONST,
    UINT
)

from ntdef_h import MAXLONG
import ctypes
import ntdef_h


IMAGE_MAJOR_LINKER_VERSION = 0x00000002
IMAGE_DOS_SIGNATURE = 0x00005A4D
IMAGE_OS2_SIGNATURE = 0x0000454E
IMAGE_OS2_SIGNATURE_LE = 0x0000454C
IMAGE_VXD_SIGNATURE = 0x0000454C
IMAGE_NT_SIGNATURE = 0x00004550


class _IMAGE_DOS_HEADER(ctypes.Structure):
    _fields_ = [
        ('e_magic', USHORT),
        ('e_cblp', USHORT),
        ('e_cp', USHORT),
        ('e_crlc', USHORT),
        ('e_cparhdr', USHORT),
        ('e_minalloc', USHORT),
        ('e_maxalloc', USHORT),
        ('e_ss', USHORT),
        ('e_sp', USHORT),
        ('e_csum', USHORT),
        ('e_ip', USHORT),
        ('e_cs', USHORT),
        ('e_lfarlc', USHORT),
        ('e_ovno', USHORT),
        ('e_res', USHORT * 4),
        ('e_oemid', USHORT),
        ('e_oeminfo', USHORT),
        ('e_res2', USHORT * 10),
        ('e_lfanew', LONG),
    ]


IMAGE_DOS_HEADER = _IMAGE_DOS_HEADER
PIMAGE_DOS_HEADER = POINTER(_IMAGE_DOS_HEADER)



class _IMAGE_OS2_HEADER(ctypes.Structure):
    _fields_ = [
        ('ne_magic', USHORT),
        ('ne_ver', CHAR),
        ('ne_rev', CHAR),
        ('ne_enttab', USHORT),
        ('ne_cbenttab', USHORT),
        ('ne_crc', LONG),
        ('ne_flags', USHORT),
        ('ne_autodata', USHORT),
        ('ne_heap', USHORT),
        ('ne_stack', USHORT),
        ('ne_csip', LONG),
        ('ne_sssp', LONG),
        ('ne_cseg', USHORT),
        ('ne_cmod', USHORT),
        ('ne_cbnrestab', USHORT),
        ('ne_segtab', USHORT),
        ('ne_rsrctab', USHORT),
        ('ne_restab', USHORT),
        ('ne_modtab', USHORT),
        ('ne_imptab', USHORT),
        ('ne_nrestab', LONG),
        ('ne_cmovent', USHORT),
        ('ne_align', USHORT),
        ('ne_cres', USHORT),
        ('ne_exetyp', UCHAR),
        ('ne_flagsothers', UCHAR),
        ('ne_pretthunks', USHORT),
        ('ne_psegrefbytes', USHORT),
        ('ne_swaparea', USHORT),
        ('ne_expver', USHORT),
    ]


IMAGE_OS2_HEADER = _IMAGE_OS2_HEADER
PIMAGE_OS2_HEADER = POINTER(_IMAGE_OS2_HEADER)



class _IMAGE_VXD_HEADER(ctypes.Structure):
    _fields_ = [
        ('e32_magic', USHORT),
        ('e32_border', UCHAR),
        ('e32_worder', UCHAR),
        ('e32_level', ULONG),
        ('e32_cpu', USHORT),
        ('e32_os', USHORT),
        ('e32_ver', ULONG),
        ('e32_mflags', ULONG),
        ('e32_mpages', ULONG),
        ('e32_startobj', ULONG),
        ('e32_eip', ULONG),
        ('e32_stackobj', ULONG),
        ('e32_esp', ULONG),
        ('e32_pagesize', ULONG),
        ('e32_lastpagesize', ULONG),
        ('e32_fixupsize', ULONG),
        ('e32_fixupsum', ULONG),
        ('e32_ldrsize', ULONG),
        ('e32_ldrsum', ULONG),
        ('e32_objtab', ULONG),
        ('e32_objcnt', ULONG),
        ('e32_objmap', ULONG),
        ('e32_itermap', ULONG),
        ('e32_rsrctab', ULONG),
        ('e32_rsrccnt', ULONG),
        ('e32_restab', ULONG),
        ('e32_enttab', ULONG),
        ('e32_dirtab', ULONG),
        ('e32_dircnt', ULONG),
        ('e32_fpagetab', ULONG),
        ('e32_frectab', ULONG),
        ('e32_impmod', ULONG),
        ('e32_impmodcnt', ULONG),
        ('e32_impproc', ULONG),
        ('e32_pagesum', ULONG),
        ('e32_datapage', ULONG),
        ('e32_preload', ULONG),
        ('e32_nrestab', ULONG),
        ('e32_cbnrestab', ULONG),
        ('e32_nressum', ULONG),
        ('e32_autodata', ULONG),
        ('e32_debuginfo', ULONG),
        ('e32_debuglen', ULONG),
        ('e32_instpreload', ULONG),
        ('e32_instdemand', ULONG),
        ('e32_heapsize', ULONG),
        ('e32_res3', UCHAR * 12),
        ('e32_winresoff', ULONG),
        ('e32_winreslen', ULONG),
        ('e32_devid', USHORT),
        ('e32_ddkver', USHORT),
    ]


IMAGE_VXD_HEADER = _IMAGE_VXD_HEADER
PIMAGE_VXD_HEADER = POINTER(_IMAGE_VXD_HEADER)


class _IMAGE_FILE_HEADER(ctypes.Structure):
    _fields_ = [
        ('Machine', USHORT),
        ('NumberOfSections', USHORT),
        ('TimeDateStamp', ULONG),
        ('PoINTerToSymbolTable', ULONG),
        ('NumberOfSymbols', ULONG),
        ('SizeOfOptionalHeader', USHORT),
        ('Characteristics', USHORT),
    ]


IMAGE_FILE_HEADER = _IMAGE_FILE_HEADER
PIMAGE_FILE_HEADER = POINTER(_IMAGE_FILE_HEADER)


IMAGE_SIZEOF_FILE_HEADER = 0x00000014
IMAGE_FILE_RELOCS_STRIPPED = 0x00000001
IMAGE_FILE_EXECUTABLE_IMAGE = 0x00000002
IMAGE_FILE_LINE_NUMS_STRIPPED = 0x00000004
IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x00000008
IMAGE_FILE_AGGRESIVE_WS_TRIM = 0x00000010
IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x00000020
IMAGE_FILE_BYTES_REVERSED_LO = 0x00000080
IMAGE_FILE_32BIT_MACHINE = 0x00000100
IMAGE_FILE_DEBUG_STRIPPED = 0x00000200
IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x00000400
IMAGE_FILE_NET_RUN_FROM_SWAP = 0x00000800
IMAGE_FILE_SYSTEM = 0x00001000
IMAGE_FILE_DLL = 0x00002000
IMAGE_FILE_UP_SYSTEM_ONLY = 0x00004000
IMAGE_FILE_BYTES_REVERSED_HI = 0x00008000
IMAGE_FILE_MACHINE_UNKNOWN = 0x00000000
IMAGE_FILE_MACHINE_TARGET_HOST = 0x00000001
IMAGE_FILE_MACHINE_I386 = 0x0000014C
IMAGE_FILE_MACHINE_R3000 = 0x00000162
IMAGE_FILE_MACHINE_R4000 = 0x00000166
IMAGE_FILE_MACHINE_R10000 = 0x00000168
IMAGE_FILE_MACHINE_WCEMIPSV2 = 0x00000169
IMAGE_FILE_MACHINE_ALPHA = 0x00000184
IMAGE_FILE_MACHINE_SH3 = 0x000001A2
IMAGE_FILE_MACHINE_SH3DSP = 0x000001A3
IMAGE_FILE_MACHINE_SH3E = 0x000001A4
IMAGE_FILE_MACHINE_SH4 = 0x000001A6
IMAGE_FILE_MACHINE_SH5 = 0x000001A8
IMAGE_FILE_MACHINE_ARM = 0x000001C0
IMAGE_FILE_MACHINE_THUMB = 0x000001C2
IMAGE_FILE_MACHINE_ARMNT = 0x000001C4
IMAGE_FILE_MACHINE_AM33 = 0x000001D3
IMAGE_FILE_MACHINE_POWERPC = 0x000001F0
IMAGE_FILE_MACHINE_POWERPCFP = 0x000001F1
IMAGE_FILE_MACHINE_IA64 = 0x00000200
IMAGE_FILE_MACHINE_MIPS16 = 0x00000266
IMAGE_FILE_MACHINE_ALPHA64 = 0x00000284
IMAGE_FILE_MACHINE_MIPSFPU = 0x00000366
IMAGE_FILE_MACHINE_MIPSFPU16 = 0x00000466
IMAGE_FILE_MACHINE_AXP64 = IMAGE_FILE_MACHINE_ALPHA64
IMAGE_FILE_MACHINE_TRICORE = 0x00000520
IMAGE_FILE_MACHINE_CEF = 0x00000CEF
IMAGE_FILE_MACHINE_EBC = 0x00000EBC
IMAGE_FILE_MACHINE_AMD64 = 0x00008664
IMAGE_FILE_MACHINE_M32R = 0x00009041
IMAGE_FILE_MACHINE_ARM64 = 0x0000AA64
IMAGE_FILE_MACHINE_CEE = 0x0000C0EE
IMAGE_FILE_MACHINE_CHPE_X86 = 0x00003A64

class _IMAGE_DATA_DIRECTORY(ctypes.Structure):
    _fields_ = [
        ('VirtualAddress', ULONG),
        ('Size', ULONG),
    ]


IMAGE_DATA_DIRECTORY = _IMAGE_DATA_DIRECTORY
PIMAGE_DATA_DIRECTORY = POINTER(_IMAGE_DATA_DIRECTORY)


IMAGE_NUMBEROF_DIRECTORY_ENTRIES = 0x00000010

class _IMAGE_OPTIONAL_HEADER(ctypes.Structure):
    _fields_ = [
        ('Magic', USHORT),
        ('MajorLinkerVersion', UCHAR),
        ('MinorLinkerVersion', UCHAR),
        ('SizeOfCode', ULONG),
        ('SizeOfInitializedData', ULONG),
        ('SizeOfUninitializedData', ULONG),
        ('AddressOfEntryPoINT', ULONG),
        ('BaseOfCode', ULONG),
        ('BaseOfData', ULONG),
        ('ImageBase', ULONG),
        ('SectionAlignment', ULONG),
        ('FileAlignment', ULONG),
        ('MajorOperatingSystemVersion', USHORT),
        ('MinorOperatingSystemVersion', USHORT),
        ('MajorImageVersion', USHORT),
        ('MinorImageVersion', USHORT),
        ('MajorSubsystemVersion', USHORT),
        ('MinorSubsystemVersion', USHORT),
        ('Win32VersionValue', ULONG),
        ('SizeOfImage', ULONG),
        ('SizeOfHeaders', ULONG),
        ('CheckSum', ULONG),
        ('Subsystem', USHORT),
        ('DllCharacteristics', USHORT),
        ('SizeOfStackReserve', ULONG),
        ('SizeOfStackCommit', ULONG),
        ('SizeOfHeapReserve', ULONG),
        ('SizeOfHeapCommit', ULONG),
        ('LoaderFlags', ULONG),
        ('NumberOfRvaAndSizes', ULONG),
        ('DataDirectory', IMAGE_DATA_DIRECTORY * IMAGE_NUMBEROF_DIRECTORY_ENTRIES),
    ]


IMAGE_OPTIONAL_HEADER32 = _IMAGE_OPTIONAL_HEADER
PIMAGE_OPTIONAL_HEADER32 = POINTER(_IMAGE_OPTIONAL_HEADER)


class _IMAGE_ROM_OPTIONAL_HEADER(ctypes.Structure):
    _fields_ = [
        ('Magic', USHORT),
        ('MajorLinkerVersion', UCHAR),
        ('MinorLinkerVersion', UCHAR),
        ('SizeOfCode', ULONG),
        ('SizeOfInitializedData', ULONG),
        ('SizeOfUninitializedData', ULONG),
        ('AddressOfEntryPoINT', ULONG),
        ('BaseOfCode', ULONG),
        ('BaseOfData', ULONG),
        ('BaseOfBss', ULONG),
        ('GprMask', ULONG),
        ('CprMask', ULONG * 4),
        ('GpValue', ULONG),
    ]


IMAGE_ROM_OPTIONAL_HEADER = _IMAGE_ROM_OPTIONAL_HEADER
PIMAGE_ROM_OPTIONAL_HEADER = POINTER(_IMAGE_ROM_OPTIONAL_HEADER)



class _IMAGE_OPTIONAL_HEADER64(ctypes.Structure):
    _fields_ = [
        ('Magic', USHORT),
        ('MajorLinkerVersion', UCHAR),
        ('MinorLinkerVersion', UCHAR),
        ('SizeOfCode', ULONG),
        ('SizeOfInitializedData', ULONG),
        ('SizeOfUninitializedData', ULONG),
        ('AddressOfEntryPoINT', ULONG),
        ('BaseOfCode', ULONG),
        ('ImageBase', ULONGLONG),
        ('SectionAlignment', ULONG),
        ('FileAlignment', ULONG),
        ('MajorOperatingSystemVersion', USHORT),
        ('MinorOperatingSystemVersion', USHORT),
        ('MajorImageVersion', USHORT),
        ('MinorImageVersion', USHORT),
        ('MajorSubsystemVersion', USHORT),
        ('MinorSubsystemVersion', USHORT),
        ('Win32VersionValue', ULONG),
        ('SizeOfImage', ULONG),
        ('SizeOfHeaders', ULONG),
        ('CheckSum', ULONG),
        ('Subsystem', USHORT),
        ('DllCharacteristics', USHORT),
        ('SizeOfStackReserve', ULONGLONG),
        ('SizeOfStackCommit', ULONGLONG),
        ('SizeOfHeapReserve', ULONGLONG),
        ('SizeOfHeapCommit', ULONGLONG),
        ('LoaderFlags', ULONG),
        ('NumberOfRvaAndSizes', ULONG),
        ('DataDirectory', IMAGE_DATA_DIRECTORY * IMAGE_NUMBEROF_DIRECTORY_ENTRIES),
    ]


IMAGE_OPTIONAL_HEADER64 = _IMAGE_OPTIONAL_HEADER64
PIMAGE_OPTIONAL_HEADER64 = POINTER(_IMAGE_OPTIONAL_HEADER64)


IMAGE_NT_OPTIONAL_HDR32_MAGIC = 0x0000010B
IMAGE_NT_OPTIONAL_HDR64_MAGIC = 0x0000020B
IMAGE_ROM_OPTIONAL_HDR_MAGIC = 0x00000107
IMAGE_OPTIONAL_HEADER = IMAGE_OPTIONAL_HEADER64
PIMAGE_OPTIONAL_HEADER = PIMAGE_OPTIONAL_HEADER64
IMAGE_NT_OPTIONAL_HDR_MAGIC = IMAGE_NT_OPTIONAL_HDR64_MAGIC


class _IMAGE_NT_HEADERS64(ctypes.Structure):
    _fields_ = [
        ('Signature', ULONG),
        ('FileHeader', IMAGE_FILE_HEADER),
    ]


IMAGE_NT_HEADERS64 = _IMAGE_NT_HEADERS64
PIMAGE_NT_HEADERS64 = POINTER(_IMAGE_NT_HEADERS64)



class _IMAGE_NT_HEADERS(ctypes.Structure):
    _fields_ = [
        ('Signature', ULONG),
        ('FileHeader', IMAGE_FILE_HEADER),
    ]


IMAGE_NT_HEADERS32 = _IMAGE_NT_HEADERS
PIMAGE_NT_HEADERS32 = POINTER(_IMAGE_NT_HEADERS)



class _IMAGE_ROM_HEADERS(ctypes.Structure):
    _fields_ = [
        ('FileHeader', IMAGE_FILE_HEADER),
    ]


IMAGE_ROM_HEADERS = _IMAGE_ROM_HEADERS
PIMAGE_ROM_HEADERS = POINTER(_IMAGE_ROM_HEADERS)


IMAGE_NT_HEADERS = IMAGE_NT_HEADERS64
PIMAGE_NT_HEADERS = PIMAGE_NT_HEADERS64


def IMAGE_FIRST_SECTION(ntheader):
    return ntheader

IMAGE_SUBSYSTEM_UNKNOWN = 0x00000000
IMAGE_SUBSYSTEM_NATIVE = 0x00000001
IMAGE_SUBSYSTEM_WINDOWS_GUI = 0x00000002
IMAGE_SUBSYSTEM_WINDOWS_CUI = 0x00000003
IMAGE_SUBSYSTEM_OS2_CUI = 0x00000005
IMAGE_SUBSYSTEM_POSIX_CUI = 0x00000007
IMAGE_SUBSYSTEM_NATIVE_WINDOWS = 0x00000008
IMAGE_SUBSYSTEM_WINDOWS_CE_GUI = 0x00000009
IMAGE_SUBSYSTEM_EFI_APPLICATION = 0x0000000A
IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER = 0x0000000B
IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER = 0x0000000C
IMAGE_SUBSYSTEM_EFI_ROM = 0x0000000D
IMAGE_SUBSYSTEM_XBOX = 0x0000000E
IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 0x00000010
IMAGE_SUBSYSTEM_XBOX_CODE_CATALOG = 0x00000011
IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA = 0x00000020
IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x00000040
IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x00000080
IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x00000100
IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x00000200
IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x00000400
IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x00000800
IMAGE_DLLCHARACTERISTICS_APPCONTAINER = 0x00001000
IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x00002000
IMAGE_DLLCHARACTERISTICS_GUARD_CF = 0x00004000
IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x00008000
IMAGE_LOADER_FLAGS_COMPLUS = 0x00000001
IMAGE_LOADER_FLAGS_SYSTEM_GLOBAL = 0x01000000
IMAGE_DIRECTORY_ENTRY_EXPORT = 0x00000000
IMAGE_DIRECTORY_ENTRY_IMPORT = 0x00000001
IMAGE_DIRECTORY_ENTRY_RESOURCE = 0x00000002
IMAGE_DIRECTORY_ENTRY_EXCEPTION = 0x00000003
IMAGE_DIRECTORY_ENTRY_SECURITY = 0x00000004
IMAGE_DIRECTORY_ENTRY_BASERELOC = 0x00000005
IMAGE_DIRECTORY_ENTRY_DEBUG = 0x00000006
IMAGE_DIRECTORY_ENTRY_ARCHITECTURE = 0x00000007
IMAGE_DIRECTORY_ENTRY_GLOBALPTR = 0x00000008
IMAGE_DIRECTORY_ENTRY_TLS = 0x00000009
IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG = 0x0000000A
IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT = 0x0000000B
IMAGE_DIRECTORY_ENTRY_IAT = 0x0000000C
IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT = 0x0000000D
IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 0x0000000E

class ANON_OBJECT_HEADER(ctypes.Structure):
    _fields_ = [
        ('Sig1', USHORT),
        ('Sig2', USHORT),
        ('Version', USHORT),
        ('Machine', USHORT),
        ('TimeDateStamp', ULONG),
        ('ClassID', CLSID),
        ('SizeOfData', ULONG),
    ]


class ANON_OBJECT_HEADER_V2(ctypes.Structure):
    _fields_ = [
        ('Sig1', USHORT),
        ('Sig2', USHORT),
        ('Version', USHORT),
        ('Machine', USHORT),
        ('TimeDateStamp', ULONG),
        ('ClassID', CLSID),
        ('SizeOfData', ULONG),
        ('Flags', ULONG),
        ('MetaDataSize', ULONG),
        ('MetaDataOffset', ULONG),
    ]


class ANON_OBJECT_HEADER_BIGOBJ(ctypes.Structure):
    _fields_ = [
        ('Sig1', USHORT),
        ('Sig2', USHORT),
        ('Version', USHORT),
        ('Machine', USHORT),
        ('TimeDateStamp', ULONG),
        ('ClassID', CLSID),
        ('SizeOfData', ULONG),
        ('Flags', ULONG),
        ('MetaDataSize', ULONG),
        ('MetaDataOffset', ULONG),
        ('NumberOfSections', ULONG),
        ('PoINTerToSymbolTable', ULONG),
        ('NumberOfSymbols', ULONG),
    ]


IMAGE_SIZEOF_SHORT_NAME = 0x00000008


class _IMAGE_SECTION_HEADER(ctypes.Structure):

    class Misc(ctypes.Union):
        _fields_ = [
            ('PhysicalAddress', ULONG),
            ('VirtualSize', ULONG),
        ]

    _fields_ = [
        ('Name', UCHAR * IMAGE_SIZEOF_SHORT_NAME),
        ('Misc', Misc),
        ('VirtualAddress', ULONG),
        ('SizeOfRawData', ULONG),
        ('PoINTerToRawData', ULONG),
        ('PoINTerToRelocations', ULONG),
        ('PoINTerToLinenumbers', ULONG),
        ('NumberOfRelocations', USHORT),
        ('NumberOfLinenumbers', USHORT),
        ('Characteristics', ULONG),
    ]


IMAGE_SECTION_HEADER = _IMAGE_SECTION_HEADER
PIMAGE_SECTION_HEADER = POINTER(_IMAGE_SECTION_HEADER)


IMAGE_SIZEOF_SECTION_HEADER = 0x00000028
IMAGE_SCN_TYPE_NO_PAD = 0x00000008
IMAGE_SCN_CNT_CODE = 0x00000020
IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040
IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080
IMAGE_SCN_LNK_OTHER = 0x00000100
IMAGE_SCN_LNK_INFO = 0x00000200
IMAGE_SCN_LNK_REMOVE = 0x00000800
IMAGE_SCN_LNK_COMDAT = 0x00001000
IMAGE_SCN_NO_DEFER_SPEC_EXC = 0x00004000
IMAGE_SCN_GPREL = 0x00008000
IMAGE_SCN_MEM_FARDATA = 0x00008000
IMAGE_SCN_MEM_PURGEABLE = 0x00020000
IMAGE_SCN_MEM_16BIT = 0x00020000
IMAGE_SCN_MEM_LOCKED = 0x00040000
IMAGE_SCN_MEM_PRELOAD = 0x00080000
IMAGE_SCN_ALIGN_1BYTES = 0x00100000
IMAGE_SCN_ALIGN_2BYTES = 0x00200000
IMAGE_SCN_ALIGN_4BYTES = 0x00300000
IMAGE_SCN_ALIGN_8BYTES = 0x00400000
IMAGE_SCN_ALIGN_16BYTES = 0x00500000
IMAGE_SCN_ALIGN_32BYTES = 0x00600000
IMAGE_SCN_ALIGN_64BYTES = 0x00700000
IMAGE_SCN_ALIGN_128BYTES = 0x00800000
IMAGE_SCN_ALIGN_256BYTES = 0x00900000
IMAGE_SCN_ALIGN_512BYTES = 0x00A00000
IMAGE_SCN_ALIGN_1024BYTES = 0x00B00000
IMAGE_SCN_ALIGN_2048BYTES = 0x00C00000
IMAGE_SCN_ALIGN_4096BYTES = 0x00D00000
IMAGE_SCN_ALIGN_8192BYTES = 0x00E00000
IMAGE_SCN_ALIGN_MASK = 0x00F00000
IMAGE_SCN_LNK_NRELOC_OVFL = 0x01000000
IMAGE_SCN_MEM_DISCARDABLE = 0x02000000
IMAGE_SCN_MEM_NOT_CACHED = 0x04000000
IMAGE_SCN_MEM_NOT_PAGED = 0x08000000
IMAGE_SCN_MEM_SHARED = 0x10000000
IMAGE_SCN_MEM_EXECUTE = 0x20000000
IMAGE_SCN_MEM_READ = 0x40000000
IMAGE_SCN_MEM_WRITE = 0x80000000
IMAGE_SCN_SCALE_INDEX = 0x00000001


class _IMAGE_SYMBOL(ctypes.Structure):

    class N(ctypes.Union):

        class Name(ctypes.Structure):
            _fields_ = [
                ('Short', ULONG),
                ('Long', ULONG),
            ]

        _fields_ = [
            ('ShortName', UCHAR * 8),
            ('Name', Name),
            ('LongName', ULONG * 2),
        ]

    _fields_ = [
        ('N', N),
        ('Value', ULONG),
        ('SectionNumber', SHORT),
        ('Type', USHORT),
        ('StorageClass', UCHAR),
        ('NumberOfAuxSymbols', UCHAR),
    ]


IMAGE_SYMBOL = _IMAGE_SYMBOL


PIMAGE_SYMBOL = POINTER(UNALIGNED)
IMAGE_SIZEOF_SYMBOL = 0x00000012


class _IMAGE_SYMBOL_EX(ctypes.Structure):

    class N(ctypes.Union):

        class Name(ctypes.Structure):
            _fields_ = [
                ('Short', ULONG),
                ('Long', ULONG),
            ]

        _fields_ = [
            ('ShortName', UCHAR * 8),
            ('Name', Name),
            ('LongName', ULONG * 2),
        ]

    _fields_ = [
        ('N', N),
        ('Value', ULONG),
        ('SectionNumber', LONG),
        ('Type', USHORT),
        ('StorageClass', UCHAR),
        ('NumberOfAuxSymbols', UCHAR),
    ]


IMAGE_SYMBOL_EX = _IMAGE_SYMBOL_EX


PIMAGE_SYMBOL_EX = POINTER(UNALIGNED)
IMAGE_SYM_UNDEFINED = 0
IMAGE_SYM_ABSOLUTE = -1
IMAGE_SYM_DEBUG = -2
IMAGE_SYM_SECTION_MAX = 0x0000FEFF
IMAGE_SYM_SECTION_MAX_EX = MAXLONG
IMAGE_SYM_TYPE_NULL = 0x00000000
IMAGE_SYM_TYPE_VOID = 0x00000001
IMAGE_SYM_TYPE_CHAR = 0x00000002
IMAGE_SYM_TYPE_SHORT = 0x00000003
IMAGE_SYM_TYPE_INT = 0x00000004
IMAGE_SYM_TYPE_LONG = 0x00000005
IMAGE_SYM_TYPE_FLOAT = 0x00000006
IMAGE_SYM_TYPE_DOUBLE = 0x00000007
IMAGE_SYM_TYPE_STRUCT = 0x00000008
IMAGE_SYM_TYPE_UNION = 0x00000009
IMAGE_SYM_TYPE_ENUM = 0x0000000A
IMAGE_SYM_TYPE_MOE = 0x0000000B
IMAGE_SYM_TYPE_UCHAR = 0x0000000C
IMAGE_SYM_TYPE_USHORT = 0x0000000D
IMAGE_SYM_TYPE_UINT = 0x0000000E
IMAGE_SYM_TYPE_ULONG = 0x0000000F
IMAGE_SYM_TYPE_PCODE = 0x00008000
IMAGE_SYM_DTYPE_NULL = 0x00000000
IMAGE_SYM_DTYPE_POINTER = 0x00000001
IMAGE_SYM_DTYPE_FUNCTION = 0x00000002
IMAGE_SYM_DTYPE_ARRAY = 0x00000003
IMAGE_SYM_CLASS_END_OF_FUNCTION = -1
IMAGE_SYM_CLASS_NULL = 0x00000000
IMAGE_SYM_CLASS_AUTOMATIC = 0x00000001
IMAGE_SYM_CLASS_EXTERNAL = 0x00000002
IMAGE_SYM_CLASS_STATIC = 0x00000003
IMAGE_SYM_CLASS_REGISTER = 0x00000004
IMAGE_SYM_CLASS_EXTERNAL_DEF = 0x00000005
IMAGE_SYM_CLASS_LABEL = 0x00000006
IMAGE_SYM_CLASS_UNDEFINED_LABEL = 0x00000007
IMAGE_SYM_CLASS_MEMBER_OF_STRUCT = 0x00000008
IMAGE_SYM_CLASS_ARGUMENT = 0x00000009
IMAGE_SYM_CLASS_STRUCT_TAG = 0x0000000A
IMAGE_SYM_CLASS_MEMBER_OF_UNION = 0x0000000B
IMAGE_SYM_CLASS_UNION_TAG = 0x0000000C
IMAGE_SYM_CLASS_TYPE_DEFINITION = 0x0000000D
IMAGE_SYM_CLASS_UNDEFINED_STATIC = 0x0000000E
IMAGE_SYM_CLASS_ENUM_TAG = 0x0000000F
IMAGE_SYM_CLASS_MEMBER_OF_ENUM = 0x00000010
IMAGE_SYM_CLASS_REGISTER_PARAM = 0x00000011
IMAGE_SYM_CLASS_BIT_FIELD = 0x00000012
IMAGE_SYM_CLASS_FAR_EXTERNAL = 0x00000044
IMAGE_SYM_CLASS_BLOCK = 0x00000064
IMAGE_SYM_CLASS_FUNCTION = 0x00000065
IMAGE_SYM_CLASS_END_OF_STRUCT = 0x00000066
IMAGE_SYM_CLASS_FILE = 0x00000067
IMAGE_SYM_CLASS_SECTION = 0x00000068
IMAGE_SYM_CLASS_WEAK_EXTERNAL = 0x00000069
IMAGE_SYM_CLASS_CLR_TOKEN = 0x0000006B
N_BTMASK = 0x0000000F
N_TMASK = 0x00000030
N_TMASK1 = 0x000000C0
N_TMASK2 = 0x000000F0
N_BTSHFT = 0x00000004
N_TSHIFT = 0x00000002


def BTYPE(x):
    return (x & N_BTMASK)


def ISPTR(x):
    return (x & N_TMASK) == (IMAGE_SYM_DTYPE_POINTER << N_BTSHFT)


def ISFCN(x):
    return (x & N_TMASK) == (IMAGE_SYM_DTYPE_FUNCTION << N_BTSHFT)


def ISARY(x):
    return (x & N_TMASK) == (IMAGE_SYM_DTYPE_ARRAY << N_BTSHFT)


def ISTAG(x):
    return (
        x in (
            IMAGE_SYM_CLASS_STRUCT_TAG,
            IMAGE_SYM_CLASS_UNION_TAG,
            IMAGE_SYM_CLASS_ENUM_TAG
        )
    )


def INCREF(x):
    return (
        ((x & ~N_BTMASK) << N_TSHIFT) |
        (IMAGE_SYM_DTYPE_POINTER << N_BTSHFT) |
        (x & N_BTMASK)
    )


def DECREF(x):
    return ((x >> N_TSHIFT) & ~N_BTMASK) | (x & N_BTMASK)



class IMAGE_AUX_SYMBOL_TOKEN_DEF(ctypes.Structure):
    _fields_ = [
        ('bAuxType', UCHAR),
        ('bReserved', UCHAR),
        ('SymbolTableIndex', ULONG),
        ('rgbReserved', UCHAR * 12),
    ]



PIMAGE_AUX_SYMBOL_TOKEN_DEF = POINTER(UNALIGNED)


class _IMAGE_AUX_SYMBOL(ctypes.Union):

    class Sym(ctypes.Structure):

        class Misc(ctypes.Union):

            class LnSz(ctypes.Structure):
                _fields_ = [
                    ('Linenumber', USHORT),
                    ('Size', USHORT),
                ]

            _fields_ = [
                ('LnSz', LnSz),
                ('TotalSize', ULONG),
            ]

        class FcnAry(ctypes.Union):

            class Function(ctypes.Structure):
                _fields_ = [
                    ('PoINTerToLinenumber', ULONG),
                    ('PoINTerToNextFunction', ULONG),
                ]

            class Array(ctypes.Structure):
                _fields_ = [
                    ('Dimension', USHORT * 4),
                ]

            _fields_ = [
                ('Function', Function),
                ('Array', Array),
            ]

        _fields_ = [
            ('TagIndex', ULONG),
            ('Misc', Misc),
            ('FcnAry', FcnAry),
            ('TvIndex', USHORT),
        ]

    class File(ctypes.Structure):
        _fields_ = [
            ('Name', UCHAR * IMAGE_SIZEOF_SYMBOL),
        ]

    class Section(ctypes.Structure):
        _fields_ = [
            ('Length', ULONG),
            ('NumberOfRelocations', USHORT),
            ('NumberOfLinenumbers', USHORT),
            ('CheckSum', ULONG),
            ('Number', SHORT),
            ('Selection', UCHAR),
            ('bReserved', UCHAR),
            ('HighNumber', SHORT),
        ]

    class CRC(ctypes.Structure):
        _fields_ = [
            ('crc', ULONG),
            ('rgbReserved', UCHAR * 14),
        ]

    _fields_ = [
        ('Sym', Sym),
        ('File', File),
        ('Section', Section),
        ('TokenDef', IMAGE_AUX_SYMBOL_TOKEN_DEF),
        ('CRC', CRC),
    ]


IMAGE_AUX_SYMBOL = _IMAGE_AUX_SYMBOL
PIMAGE_AUX_SYMBOL = POINTER(UNALIGNED)


class _IMAGE_AUX_SYMBOL_EX(ctypes.Union):

    class Sym(ctypes.Structure):
        _fields_ = [
            ('WeakDefaultSymIndex', ULONG),
            ('WeakSearchType', ULONG),
            ('rgbReserved', UCHAR * 12),
        ]

    class File(ctypes.Structure):
        _fields_ = [
            ('Name', UCHAR * ctypes.sizeof(IMAGE_SYMBOL_EX)),
        ]

    class Section(ctypes.Structure):
        _fields_ = [
            ('Length', ULONG),
            ('NumberOfRelocations', USHORT),
            ('NumberOfLinenumbers', USHORT),
            ('CheckSum', ULONG),
            ('Number', SHORT),
            ('Selection', UCHAR),
            ('bReserved', UCHAR),
            ('HighNumber', SHORT),
            ('rgbReserved', UCHAR * 2),
        ]

    class DUMMYSTRUCTNAME(ctypes.Structure):
        _fields_ = [
            ('TokenDef', IMAGE_AUX_SYMBOL_TOKEN_DEF),
            ('rgbReserved', UCHAR * 2),
        ]

    class CRC(ctypes.Structure):
        _fields_ = [
            ('crc', ULONG),
            ('rgbReserved', UCHAR * 16),
        ]

    _fields_ = [
        ('Sym', Sym),
        ('File', File),
        ('Section', Section),
        ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
        ('CRC', CRC),
    ]


IMAGE_AUX_SYMBOL_EX = _IMAGE_AUX_SYMBOL_EX
PIMAGE_AUX_SYMBOL_EX = POINTER(UNALIGNED)


class IMAGE_AUX_SYMBOL_TYPE(ENUM):
    IMAGE_AUX_SYMBOL_TYPE_TOKEN_DEF = 1


IMAGE_COMDAT_SELECT_NODUPLICATES = 0x00000001
IMAGE_COMDAT_SELECT_ANY = 0x00000002
IMAGE_COMDAT_SELECT_SAME_SIZE = 0x00000003
IMAGE_COMDAT_SELECT_EXACT_MATCH = 0x00000004
IMAGE_COMDAT_SELECT_ASSOCIATIVE = 0x00000005
IMAGE_COMDAT_SELECT_LARGEST = 0x00000006
IMAGE_COMDAT_SELECT_NEWEST = 0x00000007
IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY = 0x00000001
IMAGE_WEAK_EXTERN_SEARCH_LIBRARY = 0x00000002
IMAGE_WEAK_EXTERN_SEARCH_ALIAS = 0x00000003
IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY = 0x00000004


class _IMAGE_RELOCATION(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):
        _fields_ = [
            ('VirtualAddress', ULONG),
            ('RelocCount', ULONG)
        ]

    _fields_ = [
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('SymbolTableIndex', ULONG),
        ('Type', USHORT),
    ]


IMAGE_RELOCATION = _IMAGE_RELOCATION


PIMAGE_RELOCATION = POINTER(UNALIGNED)
IMAGE_REL_I386_ABSOLUTE = 0x00000000
IMAGE_REL_I386_DIR16 = 0x00000001
IMAGE_REL_I386_REL16 = 0x00000002
IMAGE_REL_I386_DIR32 = 0x00000006
IMAGE_REL_I386_DIR32NB = 0x00000007
IMAGE_REL_I386_SEG12 = 0x00000009
IMAGE_REL_I386_SECTION = 0x0000000A
IMAGE_REL_I386_SECREL = 0x0000000B
IMAGE_REL_I386_TOKEN = 0x0000000C
IMAGE_REL_I386_SECREL7 = 0x0000000D
IMAGE_REL_I386_REL32 = 0x00000014
IMAGE_REL_MIPS_ABSOLUTE = 0x00000000
IMAGE_REL_MIPS_REFHALF = 0x00000001
IMAGE_REL_MIPS_REFWORD = 0x00000002
IMAGE_REL_MIPS_JMPADDR = 0x00000003
IMAGE_REL_MIPS_REFHI = 0x00000004
IMAGE_REL_MIPS_REFLO = 0x00000005
IMAGE_REL_MIPS_GPREL = 0x00000006
IMAGE_REL_MIPS_LITERAL = 0x00000007
IMAGE_REL_MIPS_SECTION = 0x0000000A
IMAGE_REL_MIPS_SECREL = 0x0000000B
IMAGE_REL_MIPS_SECRELLO = 0x0000000C
IMAGE_REL_MIPS_SECRELHI = 0x0000000D
IMAGE_REL_MIPS_TOKEN = 0x0000000E
IMAGE_REL_MIPS_JMPADDR16 = 0x00000010
IMAGE_REL_MIPS_REFWORDNB = 0x00000022
IMAGE_REL_MIPS_PAIR = 0x00000025
IMAGE_REL_ALPHA_ABSOLUTE = 0x00000000
IMAGE_REL_ALPHA_REFLONG = 0x00000001
IMAGE_REL_ALPHA_REFQUAD = 0x00000002
IMAGE_REL_ALPHA_GPREL32 = 0x00000003
IMAGE_REL_ALPHA_LITERAL = 0x00000004
IMAGE_REL_ALPHA_LITUSE = 0x00000005
IMAGE_REL_ALPHA_GPDISP = 0x00000006
IMAGE_REL_ALPHA_BRADDR = 0x00000007
IMAGE_REL_ALPHA_HINT = 0x00000008
IMAGE_REL_ALPHA_INLINE_REFLONG = 0x00000009
IMAGE_REL_ALPHA_REFHI = 0x0000000A
IMAGE_REL_ALPHA_REFLO = 0x0000000B
IMAGE_REL_ALPHA_PAIR = 0x0000000C
IMAGE_REL_ALPHA_MATCH = 0x0000000D
IMAGE_REL_ALPHA_SECTION = 0x0000000E
IMAGE_REL_ALPHA_SECREL = 0x0000000F
IMAGE_REL_ALPHA_REFLONGNB = 0x00000010
IMAGE_REL_ALPHA_SECRELLO = 0x00000011
IMAGE_REL_ALPHA_SECRELHI = 0x00000012
IMAGE_REL_ALPHA_REFQ3 = 0x00000013
IMAGE_REL_ALPHA_REFQ2 = 0x00000014
IMAGE_REL_ALPHA_REFQ1 = 0x00000015
IMAGE_REL_ALPHA_GPRELLO = 0x00000016
IMAGE_REL_ALPHA_GPRELHI = 0x00000017
IMAGE_REL_PPC_ABSOLUTE = 0x00000000
IMAGE_REL_PPC_ADDR64 = 0x00000001
IMAGE_REL_PPC_ADDR32 = 0x00000002
IMAGE_REL_PPC_ADDR24 = 0x00000003
IMAGE_REL_PPC_ADDR16 = 0x00000004
IMAGE_REL_PPC_ADDR14 = 0x00000005
IMAGE_REL_PPC_REL24 = 0x00000006
IMAGE_REL_PPC_REL14 = 0x00000007
IMAGE_REL_PPC_TOCREL16 = 0x00000008
IMAGE_REL_PPC_TOCREL14 = 0x00000009
IMAGE_REL_PPC_ADDR32NB = 0x0000000A
IMAGE_REL_PPC_SECREL = 0x0000000B
IMAGE_REL_PPC_SECTION = 0x0000000C
IMAGE_REL_PPC_IFGLUE = 0x0000000D
IMAGE_REL_PPC_IMGLUE = 0x0000000E
IMAGE_REL_PPC_SECREL16 = 0x0000000F
IMAGE_REL_PPC_REFHI = 0x00000010
IMAGE_REL_PPC_REFLO = 0x00000011
IMAGE_REL_PPC_PAIR = 0x00000012
IMAGE_REL_PPC_SECRELLO = 0x00000013
IMAGE_REL_PPC_SECRELHI = 0x00000014
IMAGE_REL_PPC_GPREL = 0x00000015
IMAGE_REL_PPC_TOKEN = 0x00000016
IMAGE_REL_PPC_TYPEMASK = 0x000000FF
IMAGE_REL_PPC_NEG = 0x00000100
IMAGE_REL_PPC_BRTAKEN = 0x00000200
IMAGE_REL_PPC_BRNTAKEN = 0x00000400
IMAGE_REL_PPC_TOCDEFN = 0x00000800
IMAGE_REL_SH3_ABSOLUTE = 0x00000000
IMAGE_REL_SH3_DIRECT16 = 0x00000001
IMAGE_REL_SH3_DIRECT32 = 0x00000002
IMAGE_REL_SH3_DIRECT8 = 0x00000003
IMAGE_REL_SH3_DIRECT8_WORD = 0x00000004
IMAGE_REL_SH3_DIRECT8_LONG = 0x00000005
IMAGE_REL_SH3_DIRECT4 = 0x00000006
IMAGE_REL_SH3_DIRECT4_WORD = 0x00000007
IMAGE_REL_SH3_DIRECT4_LONG = 0x00000008
IMAGE_REL_SH3_PCREL8_WORD = 0x00000009
IMAGE_REL_SH3_PCREL8_LONG = 0x0000000A
IMAGE_REL_SH3_PCREL12_WORD = 0x0000000B
IMAGE_REL_SH3_STARTOF_SECTION = 0x0000000C
IMAGE_REL_SH3_SIZEOF_SECTION = 0x0000000D
IMAGE_REL_SH3_SECTION = 0x0000000E
IMAGE_REL_SH3_SECREL = 0x0000000F
IMAGE_REL_SH3_DIRECT32_NB = 0x00000010
IMAGE_REL_SH3_GPREL4_LONG = 0x00000011
IMAGE_REL_SH3_TOKEN = 0x00000012
IMAGE_REL_SHM_PCRELPT = 0x00000013
IMAGE_REL_SHM_REFLO = 0x00000014
IMAGE_REL_SHM_REFHALF = 0x00000015
IMAGE_REL_SHM_RELLO = 0x00000016
IMAGE_REL_SHM_RELHALF = 0x00000017
IMAGE_REL_SHM_PAIR = 0x00000018
IMAGE_REL_SH_NOMODE = 0x00008000
IMAGE_REL_ARM_ABSOLUTE = 0x00000000
IMAGE_REL_ARM_ADDR32 = 0x00000001
IMAGE_REL_ARM_ADDR32NB = 0x00000002
IMAGE_REL_ARM_BRANCH24 = 0x00000003
IMAGE_REL_ARM_BRANCH11 = 0x00000004
IMAGE_REL_ARM_TOKEN = 0x00000005
IMAGE_REL_ARM_GPREL12 = 0x00000006
IMAGE_REL_ARM_GPREL7 = 0x00000007
IMAGE_REL_ARM_BLX24 = 0x00000008
IMAGE_REL_ARM_BLX11 = 0x00000009
IMAGE_REL_ARM_SECTION = 0x0000000E
IMAGE_REL_ARM_SECREL = 0x0000000F
IMAGE_REL_ARM_MOV32A = 0x00000010
IMAGE_REL_ARM_MOV32 = 0x00000010
IMAGE_REL_ARM_MOV32T = 0x00000011
IMAGE_REL_THUMB_MOV32 = 0x00000011
IMAGE_REL_ARM_BRANCH20T = 0x00000012
IMAGE_REL_THUMB_BRANCH20 = 0x00000012
IMAGE_REL_ARM_BRANCH24T = 0x00000014
IMAGE_REL_THUMB_BRANCH24 = 0x00000014
IMAGE_REL_ARM_BLX23T = 0x00000015
IMAGE_REL_THUMB_BLX23 = 0x00000015
IMAGE_REL_AM_ABSOLUTE = 0x00000000
IMAGE_REL_AM_ADDR32 = 0x00000001
IMAGE_REL_AM_ADDR32NB = 0x00000002
IMAGE_REL_AM_CALL32 = 0x00000003
IMAGE_REL_AM_FUNCINFO = 0x00000004
IMAGE_REL_AM_REL32_1 = 0x00000005
IMAGE_REL_AM_REL32_2 = 0x00000006
IMAGE_REL_AM_SECREL = 0x00000007
IMAGE_REL_AM_SECTION = 0x00000008
IMAGE_REL_AM_TOKEN = 0x00000009
IMAGE_REL_ARM64_ABSOLUTE = 0x00000000
IMAGE_REL_ARM64_ADDR32 = 0x00000001
IMAGE_REL_ARM64_ADDR32NB = 0x00000002
IMAGE_REL_ARM64_BRANCH26 = 0x00000003
IMAGE_REL_ARM64_PAGEBASE_REL21 = 0x00000004
IMAGE_REL_ARM64_REL21 = 0x00000005
IMAGE_REL_ARM64_PAGEOFFSET_12A = 0x00000006
IMAGE_REL_ARM64_PAGEOFFSET_12L = 0x00000007
IMAGE_REL_ARM64_SECREL = 0x00000008
IMAGE_REL_ARM64_SECREL_LOW12A = 0x00000009
IMAGE_REL_ARM64_SECREL_HIGH12A = 0x0000000A
IMAGE_REL_ARM64_SECREL_LOW12L = 0x0000000B
IMAGE_REL_ARM64_TOKEN = 0x0000000C
IMAGE_REL_ARM64_SECTION = 0x0000000D
IMAGE_REL_ARM64_ADDR64 = 0x0000000E
IMAGE_REL_ARM64_BRANCH19 = 0x0000000F
IMAGE_REL_AMD64_ABSOLUTE = 0x00000000
IMAGE_REL_AMD64_ADDR64 = 0x00000001
IMAGE_REL_AMD64_ADDR32 = 0x00000002
IMAGE_REL_AMD64_ADDR32NB = 0x00000003
IMAGE_REL_AMD64_REL32 = 0x00000004
IMAGE_REL_AMD64_REL32_1 = 0x00000005
IMAGE_REL_AMD64_REL32_2 = 0x00000006
IMAGE_REL_AMD64_REL32_3 = 0x00000007
IMAGE_REL_AMD64_REL32_4 = 0x00000008
IMAGE_REL_AMD64_REL32_5 = 0x00000009
IMAGE_REL_AMD64_SECTION = 0x0000000A
IMAGE_REL_AMD64_SECREL = 0x0000000B
IMAGE_REL_AMD64_SECREL7 = 0x0000000C
IMAGE_REL_AMD64_TOKEN = 0x0000000D
IMAGE_REL_AMD64_SREL32 = 0x0000000E
IMAGE_REL_AMD64_PAIR = 0x0000000F
IMAGE_REL_AMD64_SSPAN32 = 0x00000010
IMAGE_REL_IA64_ABSOLUTE = 0x00000000
IMAGE_REL_IA64_IMM14 = 0x00000001
IMAGE_REL_IA64_IMM22 = 0x00000002
IMAGE_REL_IA64_IMM64 = 0x00000003
IMAGE_REL_IA64_DIR32 = 0x00000004
IMAGE_REL_IA64_DIR64 = 0x00000005
IMAGE_REL_IA64_PCREL21B = 0x00000006
IMAGE_REL_IA64_PCREL21M = 0x00000007
IMAGE_REL_IA64_PCREL21F = 0x00000008
IMAGE_REL_IA64_GPREL22 = 0x00000009
IMAGE_REL_IA64_LTOFF22 = 0x0000000A
IMAGE_REL_IA64_SECTION = 0x0000000B
IMAGE_REL_IA64_SECREL22 = 0x0000000C
IMAGE_REL_IA64_SECREL64I = 0x0000000D
IMAGE_REL_IA64_SECREL32 = 0x0000000E
IMAGE_REL_IA64_DIR32NB = 0x00000010
IMAGE_REL_IA64_SREL14 = 0x00000011
IMAGE_REL_IA64_SREL22 = 0x00000012
IMAGE_REL_IA64_SREL32 = 0x00000013
IMAGE_REL_IA64_UREL32 = 0x00000014
IMAGE_REL_IA64_PCREL60X = 0x0000015
IMAGE_REL_IA64_PCREL60B = 0x00000016
IMAGE_REL_IA64_PCREL60F = 0x00000017
IMAGE_REL_IA64_PCREL60I = 0x00000018
IMAGE_REL_IA64_PCREL60M = 0x00000019
IMAGE_REL_IA64_IMMGPREL64 = 0x0000001A
IMAGE_REL_IA64_TOKEN = 0x0000001B
IMAGE_REL_IA64_GPREL32 = 0x0000001C
IMAGE_REL_IA64_ADDEND = 0x0000001F
IMAGE_REL_CEF_ABSOLUTE = 0x00000000
IMAGE_REL_CEF_ADDR32 = 0x00000001
IMAGE_REL_CEF_ADDR64 = 0x00000002
IMAGE_REL_CEF_ADDR32NB = 0x00000003
IMAGE_REL_CEF_SECTION = 0x00000004
IMAGE_REL_CEF_SECREL = 0x00000005
IMAGE_REL_CEF_TOKEN = 0x00000006
IMAGE_REL_CEE_ABSOLUTE = 0x00000000
IMAGE_REL_CEE_ADDR32 = 0x00000001
IMAGE_REL_CEE_ADDR64 = 0x00000002
IMAGE_REL_CEE_ADDR32NB = 0x00000003
IMAGE_REL_CEE_SECTION = 0x00000004
IMAGE_REL_CEE_SECREL = 0x00000005
IMAGE_REL_CEE_TOKEN = 0x00000006
IMAGE_REL_M32R_ABSOLUTE = 0x00000000
IMAGE_REL_M32R_ADDR32 = 0x00000001
IMAGE_REL_M32R_ADDR32NB = 0x00000002
IMAGE_REL_M32R_ADDR24 = 0x00000003
IMAGE_REL_M32R_GPREL16 = 0x00000004
IMAGE_REL_M32R_PCREL24 = 0x00000005
IMAGE_REL_M32R_PCREL16 = 0x00000006
IMAGE_REL_M32R_PCREL8 = 0x00000007
IMAGE_REL_M32R_REFHALF = 0x00000008
IMAGE_REL_M32R_REFHI = 0x00000009
IMAGE_REL_M32R_REFLO = 0x0000000A
IMAGE_REL_M32R_PAIR = 0x0000000B
IMAGE_REL_M32R_SECTION = 0x0000000C
IMAGE_REL_M32R_SECREL32 = 0x0000000D
IMAGE_REL_M32R_TOKEN = 0x0000000E
IMAGE_REL_EBC_ABSOLUTE = 0x00000000
IMAGE_REL_EBC_ADDR32NB = 0x00000001
IMAGE_REL_EBC_REL32 = 0x00000002
IMAGE_REL_EBC_SECTION = 0x00000003
IMAGE_REL_EBC_SECREL = 0x00000004


def EXT_IMM64(Value, Address, Size, InstPos, ValPos):
    Value |= ((Address >> InstPos) & ((1 << Size) - 1)) << ValPos
    return Value


def INS_IMM64(Value, Address, Size, InstPos, ValPos):
    Address = (
        (Address & ~(((1 << Size) - 1) << InstPos)) |
        ((((Value >> ValPos) & ((1 << Size) - 1))) << InstPos)
    )
    return Address

EMARCH_ENC_I17_IMM7B_INST_WORD_X = 0x00000003
EMARCH_ENC_I17_IMM7B_SIZE_X = 0x00000007
EMARCH_ENC_I17_IMM7B_INST_WORD_POS_X = 0x00000004
EMARCH_ENC_I17_IMM7B_VAL_POS_X = 0x00000000
EMARCH_ENC_I17_IMM9D_INST_WORD_X = 0x00000003
EMARCH_ENC_I17_IMM9D_SIZE_X = 0x00000009
EMARCH_ENC_I17_IMM9D_INST_WORD_POS_X = 0x00000012
EMARCH_ENC_I17_IMM9D_VAL_POS_X = 0x00000007
EMARCH_ENC_I17_IMM5C_INST_WORD_X = 0x00000003
EMARCH_ENC_I17_IMM5C_SIZE_X = 0x00000005
EMARCH_ENC_I17_IMM5C_INST_WORD_POS_X = 0x0000000D
EMARCH_ENC_I17_IMM5C_VAL_POS_X = 0x00000010
EMARCH_ENC_I17_IC_INST_WORD_X = 0x00000003
EMARCH_ENC_I17_IC_SIZE_X = 0x00000001
EMARCH_ENC_I17_IC_INST_WORD_POS_X = 0x0000000C
EMARCH_ENC_I17_IC_VAL_POS_X = 0x00000015
EMARCH_ENC_I17_IMM41a_INST_WORD_X = 0x00000001
EMARCH_ENC_I17_IMM41a_SIZE_X = 0x0000000A
EMARCH_ENC_I17_IMM41a_INST_WORD_POS_X = 0x0000000E
EMARCH_ENC_I17_IMM41a_VAL_POS_X = 0x00000016
EMARCH_ENC_I17_IMM41b_INST_WORD_X = 0x00000001
EMARCH_ENC_I17_IMM41b_SIZE_X = 0x00000008
EMARCH_ENC_I17_IMM41b_INST_WORD_POS_X = 0x00000018
EMARCH_ENC_I17_IMM41b_VAL_POS_X = 0x00000020
EMARCH_ENC_I17_IMM41c_INST_WORD_X = 0x00000002
EMARCH_ENC_I17_IMM41c_SIZE_X = 0x00000017
EMARCH_ENC_I17_IMM41c_INST_WORD_POS_X = 0x00000000
EMARCH_ENC_I17_IMM41c_VAL_POS_X = 0x00000028
EMARCH_ENC_I17_SIGN_INST_WORD_X = 0x00000003
EMARCH_ENC_I17_SIGN_SIZE_X = 0x00000001
EMARCH_ENC_I17_SIGN_INST_WORD_POS_X = 0x0000001B
EMARCH_ENC_I17_SIGN_VAL_POS_X = 0x0000003F
X3_OPCODE_INST_WORD_X = 0x00000003
X3_OPCODE_SIZE_X = 0x00000004
X3_OPCODE_INST_WORD_POS_X = 0x0000001C
X3_OPCODE_SIGN_VAL_POS_X = 0x00000000
X3_I_INST_WORD_X = 0x00000003
X3_I_SIZE_X = 0x00000001
X3_I_INST_WORD_POS_X = 0x0000001B
X3_I_SIGN_VAL_POS_X = 0x0000003B
X3_D_WH_INST_WORD_X = 0x00000003
X3_D_WH_SIZE_X = 0x00000003
X3_D_WH_INST_WORD_POS_X = 0x00000018
X3_D_WH_SIGN_VAL_POS_X = 0x00000000
X3_IMM20_INST_WORD_X = 0x00000003
X3_IMM20_SIZE_X = 0x00000014
X3_IMM20_INST_WORD_POS_X = 0x00000004
X3_IMM20_SIGN_VAL_POS_X = 0x00000000
X3_IMM39_1_INST_WORD_X = 0x00000002
X3_IMM39_1_SIZE_X = 0x00000017
X3_IMM39_1_INST_WORD_POS_X = 0x00000000
X3_IMM39_1_SIGN_VAL_POS_X = 0x00000024
X3_IMM39_2_INST_WORD_X = 0x00000001
X3_IMM39_2_SIZE_X = 0x00000010
X3_IMM39_2_INST_WORD_POS_X = 0x00000010
X3_IMM39_2_SIGN_VAL_POS_X = 0x00000014
X3_P_INST_WORD_X = 0x00000003
X3_P_SIZE_X = 0x00000004
X3_P_INST_WORD_POS_X = 0x00000000
X3_P_SIGN_VAL_POS_X = 0x00000000
X3_TMPLT_INST_WORD_X = 0x00000000
X3_TMPLT_SIZE_X = 0x00000004
X3_TMPLT_INST_WORD_POS_X = 0x00000000
X3_TMPLT_SIGN_VAL_POS_X = 0x00000000
X3_BTYPE_QP_INST_WORD_X = 0x00000002
X3_BTYPE_QP_SIZE_X = 0x00000009
X3_BTYPE_QP_INST_WORD_POS_X = 0x00000017
X3_BTYPE_QP_INST_VAL_POS_X = 0x00000000
X3_EMPTY_INST_WORD_X = 0x00000001
X3_EMPTY_SIZE_X = 0x00000002
X3_EMPTY_INST_WORD_POS_X = 0x0000000E
X3_EMPTY_INST_VAL_POS_X = 0x00000000

class _IMAGE_LINENUMBER(ctypes.Structure):

    class Type(ctypes.Union):
        _fields_ = [
            ('SymbolTableIndex', ULONG),
            ('VirtualAddress', ULONG),
        ]

    _fields_ = [
        ('Type', Type),
        ('Linenumber', USHORT),
    ]


IMAGE_LINENUMBER = _IMAGE_LINENUMBER
PIMAGE_LINENUMBER = POINTER(UNALIGNED)


class _IMAGE_BASE_RELOCATION(ctypes.Structure):
    _fields_ = [
        ('VirtualAddress', ULONG),
        ('SizeOfBlock', ULONG),
    ]


IMAGE_BASE_RELOCATION = _IMAGE_BASE_RELOCATION


PIMAGE_BASE_RELOCATION = UNALIGNED
IMAGE_REL_BASED_ABSOLUTE = 0x00000000
IMAGE_REL_BASED_HIGH = 0x00000001
IMAGE_REL_BASED_LOW = 0x00000002
IMAGE_REL_BASED_HIGHLOW = 0x00000003
IMAGE_REL_BASED_HIGHADJ = 0x00000004
IMAGE_REL_BASED_MACHINE_SPECIFIC_5 = 0x00000005
IMAGE_REL_BASED_RESERVED = 0x00000006
IMAGE_REL_BASED_MACHINE_SPECIFIC_7 = 0x00000007
IMAGE_REL_BASED_MACHINE_SPECIFIC_8 = 0x00000008
IMAGE_REL_BASED_MACHINE_SPECIFIC_9 = 0x00000009
IMAGE_REL_BASED_DIR64 = 0x0000000A
IMAGE_REL_BASED_IA64_IMM64 = 0x00000009
IMAGE_REL_BASED_MIPS_JMPADDR = 0x00000005
IMAGE_REL_BASED_MIPS_JMPADDR16 = 0x00000009
IMAGE_REL_BASED_ARM_MOV32 = 0x00000005
IMAGE_REL_BASED_THUMB_MOV32 = 0x00000007
IMAGE_ARCHIVE_START_SIZE = 0x00000008
IMAGE_ARCHIVE_START = "!<arch>\n"
IMAGE_ARCHIVE_END = "`\n"
IMAGE_ARCHIVE_PAD = "\n"
IMAGE_ARCHIVE_LINKER_MEMBER = "/               "
IMAGE_ARCHIVE_LONGNAMES_MEMBER = "\n"
IMAGE_ARCHIVE_HYBRIDMAP_MEMBER = "/<HYBRIDMAP>/   "


class _IMAGE_ARCHIVE_MEMBER_HEADER(ctypes.Structure):
    _fields_ = [
        ('Name', UCHAR * 16),
        ('Date', UCHAR * 12),
        ('UserID', UCHAR * 6),
        ('GroupID', UCHAR * 6),
        ('Mode', UCHAR * 8),
        ('Size', UCHAR * 10),
        ('EndHeader', UCHAR * 2),
    ]


IMAGE_ARCHIVE_MEMBER_HEADER = _IMAGE_ARCHIVE_MEMBER_HEADER
PIMAGE_ARCHIVE_MEMBER_HEADER = POINTER(_IMAGE_ARCHIVE_MEMBER_HEADER)


IMAGE_SIZEOF_ARCHIVE_MEMBER_HDR = 0x0000003C


class _IMAGE_EXPORT_DIRECTORY(ctypes.Structure):
    _fields_ = [
        ('Characteristics', ULONG),
        ('TimeDateStamp', ULONG),
        ('MajorVersion', USHORT),
        ('MinorVersion', USHORT),
        ('Name', ULONG),
        ('Base', ULONG),
        ('NumberOfFunctions', ULONG),
        ('NumberOfNames', ULONG),
        ('AddressOfFunctions', ULONG),
        ('AddressOfNames', ULONG),
        ('AddressOfNameOrdinals', ULONG),
    ]


IMAGE_EXPORT_DIRECTORY = _IMAGE_EXPORT_DIRECTORY
PIMAGE_EXPORT_DIRECTORY = POINTER(_IMAGE_EXPORT_DIRECTORY)


class _IMAGE_IMPORT_BY_NAME(ctypes.Structure):
    _fields_ = [
        ('HINT', USHORT),
        ('Name', CHAR * 1),
    ]


IMAGE_IMPORT_BY_NAME = _IMAGE_IMPORT_BY_NAME
PIMAGE_IMPORT_BY_NAME = POINTER(_IMAGE_IMPORT_BY_NAME)


class _IMAGE_THUNK_DATA64(ctypes.Structure):

    class u1(ctypes.Union):
        _fields_ = [
            ('ForwarderString', ULONGLONG),
            ('Function', ULONGLONG),
            ('Ordinal', ULONGLONG),
            ('AddressOfData', ULONGLONG),
        ]

    _fields_ = [
        ('u1', u1),
    ]


IMAGE_THUNK_DATA64 = _IMAGE_THUNK_DATA64


PIMAGE_THUNK_DATA64 = IMAGE_THUNK_DATA64


class _IMAGE_THUNK_DATA32(ctypes.Structure):

    class u1(ctypes.Union):
        _fields_ = [
            ('ForwarderString', ULONG),
            ('Function', ULONG),
            ('Ordinal', ULONG),
            ('AddressOfData', ULONG),
        ]

    _fields_ = [
        ('u1', u1),
    ]


IMAGE_THUNK_DATA32 = _IMAGE_THUNK_DATA32


PIMAGE_THUNK_DATA32 = IMAGE_THUNK_DATA32
IMAGE_ORDINAL_FLAG64 = 0x8000000000000000
IMAGE_ORDINAL_FLAG32 = 0x80000000


def IMAGE_ORDINAL64(Ordinal):
    return Ordinal & 0xffff


def IMAGE_ORDINAL32(Ordinal):
    return Ordinal & 0xffff


def IMAGE_SNAP_BY_ORDINAL64(Ordinal):
    return (Ordinal & IMAGE_ORDINAL_FLAG64) != 0


def IMAGE_SNAP_BY_ORDINAL32(Ordinal):
    return (Ordinal & IMAGE_ORDINAL_FLAG32) != 0


class _IMAGE_TLS_DIRECTORY64(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        class DUMMYSTRUCTNAME(ctypes.Structure):

            _fields_ = [
                ('Reserved0', ULONG, 20),
                ('Alignment', ULONG, 4),
                ('Reserved1', ULONG, 8),
            ]

        _fields_ = [
            ('Characteristics', ULONG),
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME)
        ]

    _fields_ = [
        ('StartAddressOfRawData', ULONGLONG),
        ('EndAddressOfRawData', ULONGLONG),
        ('AddressOfIndex', ULONGLONG),
        ('AddressOfCallBacks', ULONGLONG),
        ('SizeOfZeroFill', ULONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
    ]


IMAGE_TLS_DIRECTORY64 = _IMAGE_TLS_DIRECTORY64
PIMAGE_TLS_DIRECTORY64 = IMAGE_TLS_DIRECTORY64


class _IMAGE_TLS_DIRECTORY32(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        class DUMMYSTRUCTNAME(ctypes.Structure):

            _fields_ = [
                ('Reserved0', ULONG, 20),
                ('Alignment', ULONG, 4),
                ('Reserved1', ULONG, 8),
            ]


        _fields_ = [
            ('Characteristics', ULONG),
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME)
        ]


    _fields_ = [
        ('StartAddressOfRawData', ULONG),
        ('EndAddressOfRawData', ULONG),
        ('AddressOfIndex', ULONG),
        ('AddressOfCallBacks', ULONG),
        ('SizeOfZeroFill', ULONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
    ]


IMAGE_TLS_DIRECTORY32 = _IMAGE_TLS_DIRECTORY32


PIMAGE_TLS_DIRECTORY32 = IMAGE_TLS_DIRECTORY32
IMAGE_ORDINAL_FLAG = IMAGE_ORDINAL_FLAG64


def IMAGE_ORDINAL(Ordinal):
    return IMAGE_ORDINAL64(Ordinal)


IMAGE_THUNK_DATA = IMAGE_THUNK_DATA64
PIMAGE_THUNK_DATA = PIMAGE_THUNK_DATA64


def IMAGE_SNAP_BY_ORDINAL(Ordinal):
    return IMAGE_SNAP_BY_ORDINAL64(Ordinal)


IMAGE_TLS_DIRECTORY = IMAGE_TLS_DIRECTORY64
PIMAGE_TLS_DIRECTORY = PIMAGE_TLS_DIRECTORY64


class _IMAGE_IMPORT_DESCRIPTOR(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        _fields_ = [
            ('Characteristics', ULONG),
            ('OriginalFirstThunk', ULONG)
        ]

    _fields_ = [
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('TimeDateStamp', ULONG),
        ('ForwarderChain', ULONG),
        ('Name', ULONG),
        ('FirstThunk', ULONG),
    ]


IMAGE_IMPORT_DESCRIPTOR = _IMAGE_IMPORT_DESCRIPTOR
PIMAGE_IMPORT_DESCRIPTOR = POINTER(UNALIGNED)


class _IMAGE_BOUND_IMPORT_DESCRIPTOR(ctypes.Structure):
    _fields_ = [
        ('TimeDateStamp', ULONG),
        ('OffsetModuleName', USHORT),
        ('NumberOfModuleForwarderRefs', USHORT),
    ]


IMAGE_BOUND_IMPORT_DESCRIPTOR = _IMAGE_BOUND_IMPORT_DESCRIPTOR
PIMAGE_BOUND_IMPORT_DESCRIPTOR = POINTER(_IMAGE_BOUND_IMPORT_DESCRIPTOR)


class _IMAGE_BOUND_FORWARDER_REF(ctypes.Structure):
    _fields_ = [
        ('TimeDateStamp', ULONG),
        ('OffsetModuleName', USHORT),
        ('Reserved', USHORT),
    ]


IMAGE_BOUND_FORWARDER_REF = _IMAGE_BOUND_FORWARDER_REF
PIMAGE_BOUND_FORWARDER_REF = POINTER(_IMAGE_BOUND_FORWARDER_REF)


class _IMAGE_DELAYLOAD_DESCRIPTOR(ctypes.Structure):

    class Attributes(ctypes.Union):

        class DUMMYSTRUCTNAME(ctypes.Structure):
            _fields_ = [
                ('RvaBased : 1', ULONG),
                ('ReservedAttributes : 31', ULONG),
            ]

        _fields_ = [
            ('AllAttributes', ULONG),
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
        ]

    _fields_ = [
        ('Attributes', Attributes),
        ('DllNameRVA', ULONG),
        ('ModuleHandleRVA', ULONG),
        ('ImportAddressTableRVA', ULONG),
        ('ImportNameTableRVA', ULONG),
        ('BoundImportAddressTableRVA', ULONG),
        ('UnloadInformationTableRVA', ULONG),
        ('TimeDateStamp', ULONG),
    ]


IMAGE_DELAYLOAD_DESCRIPTOR = _IMAGE_DELAYLOAD_DESCRIPTOR
PIMAGE_DELAYLOAD_DESCRIPTOR = POINTER(_IMAGE_DELAYLOAD_DESCRIPTOR)


PCIMAGE_DELAYLOAD_DESCRIPTOR = POINTER(IMAGE_DELAYLOAD_DESCRIPTOR)


class _IMAGE_RESOURCE_DIRECTORY(ctypes.Structure):
    _fields_ = [
        ('Characteristics', ULONG),
        ('TimeDateStamp', ULONG),
        ('MajorVersion', USHORT),
        ('MinorVersion', USHORT),
        ('NumberOfNamedEntries', USHORT),
        ('NumberOfIdEntries', USHORT),
    ]


IMAGE_RESOURCE_DIRECTORY = _IMAGE_RESOURCE_DIRECTORY
PIMAGE_RESOURCE_DIRECTORY = POINTER(_IMAGE_RESOURCE_DIRECTORY)


IMAGE_RESOURCE_NAME_IS_STRING = 0x80000000
IMAGE_RESOURCE_DATA_IS_DIRECTORY = 0x80000000


class _IMAGE_RESOURCE_DIRECTORY_ENTRY(ctypes.Structure):
    class DUMMYUNIONNAME(ctypes.Union):
        class DUMMYSTRUCTNAME(ctypes.Structure):
            _fields_ = [
                ('NameOffset', ULONG, 31),
                ('NameIsString', ULONG, 1)
            ]

        _fields_ = [
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
            ('Name', ULONG),
            ('Id', USHORT)

        ]


    class DUMMYUNIONNAME2(ctypes.Union):
        class DUMMYSTRUCTNAME2(ctypes.Structure):
            _fields_ = [
                ('OffsetToDirectory', ULONG, 31),
                ('DataIsDirectory', ULONG, 1)
            ]


        _fields_ = [
            ('OffsetToData', ULONG),
            ('DUMMYSTRUCTNAME2', DUMMYSTRUCTNAME2),
        ]

    _fields_ = [
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('DUMMYUNIONNAME2', DUMMYUNIONNAME2),
    ]


IMAGE_RESOURCE_DIRECTORY_ENTRY = _IMAGE_RESOURCE_DIRECTORY_ENTRY
PIMAGE_RESOURCE_DIRECTORY_ENTRY = POINTER(_IMAGE_RESOURCE_DIRECTORY_ENTRY)


class _IMAGE_RESOURCE_DIRECTORY_STRING(ctypes.Structure):
    _fields_ = [
        ('Length', USHORT),
        ('NameString', CHAR * 1),
    ]


IMAGE_RESOURCE_DIRECTORY_STRING = _IMAGE_RESOURCE_DIRECTORY_STRING
PIMAGE_RESOURCE_DIRECTORY_STRING = POINTER(_IMAGE_RESOURCE_DIRECTORY_STRING)


class _IMAGE_RESOURCE_DIR_STRING_U(ctypes.Structure):
    _fields_ = [
        ('Length', USHORT),
        ('NameString', WCHAR * 1),
    ]


IMAGE_RESOURCE_DIR_STRING_U = _IMAGE_RESOURCE_DIR_STRING_U
PIMAGE_RESOURCE_DIR_STRING_U = POINTER(_IMAGE_RESOURCE_DIR_STRING_U)


class _IMAGE_RESOURCE_DATA_ENTRY(ctypes.Structure):
    _fields_ = [
        ('OffsetToData', ULONG),
        ('Size', ULONG),
        ('CodePage', ULONG),
        ('Reserved', ULONG),
    ]


IMAGE_RESOURCE_DATA_ENTRY = _IMAGE_RESOURCE_DATA_ENTRY
PIMAGE_RESOURCE_DATA_ENTRY = POINTER(_IMAGE_RESOURCE_DATA_ENTRY)


class _IMAGE_LOAD_CONFIG_CODE_INTEGRITY(ctypes.Structure):
    _fields_ = [
        ('Flags', USHORT),
        ('Catalog', USHORT),
        ('CatalogOffset', ULONG),
        ('Reserved', ULONG),
    ]


IMAGE_LOAD_CONFIG_CODE_INTEGRITY = _IMAGE_LOAD_CONFIG_CODE_INTEGRITY
PIMAGE_LOAD_CONFIG_CODE_INTEGRITY = POINTER(_IMAGE_LOAD_CONFIG_CODE_INTEGRITY)


class _IMAGE_DYNAMIC_RELOCATION_TABLE(ctypes.Structure):
    _fields_ = [
        ('Version', ULONG),
        ('Size', ULONG),
    ]


IMAGE_DYNAMIC_RELOCATION_TABLE = _IMAGE_DYNAMIC_RELOCATION_TABLE
PIMAGE_DYNAMIC_RELOCATION_TABLE = POINTER(_IMAGE_DYNAMIC_RELOCATION_TABLE)


class _IMAGE_DYNAMIC_RELOCATION32(ctypes.Structure):
    _fields_ = [
        ('Symbol', ULONG),
        ('BaseRelocSize', ULONG),
    ]


IMAGE_DYNAMIC_RELOCATION32 = _IMAGE_DYNAMIC_RELOCATION32
PIMAGE_DYNAMIC_RELOCATION32 = POINTER(_IMAGE_DYNAMIC_RELOCATION32)


class _IMAGE_DYNAMIC_RELOCATION64(ctypes.Structure):
    _fields_ = [
        ('Symbol', ULONGLONG),
        ('BaseRelocSize', ULONG),
    ]


IMAGE_DYNAMIC_RELOCATION64 = _IMAGE_DYNAMIC_RELOCATION64
PIMAGE_DYNAMIC_RELOCATION64 = POINTER(_IMAGE_DYNAMIC_RELOCATION64)


class _IMAGE_DYNAMIC_RELOCATION32_V2(ctypes.Structure):
    _fields_ = [
        ('HeaderSize', ULONG),
        ('FixupInfoSize', ULONG),
        ('Symbol', ULONG),
        ('SymbolGroup', ULONG),
        ('Flags', ULONG),
    ]


IMAGE_DYNAMIC_RELOCATION32_V2 = _IMAGE_DYNAMIC_RELOCATION32_V2
PIMAGE_DYNAMIC_RELOCATION32_V2 = POINTER(_IMAGE_DYNAMIC_RELOCATION32_V2)


class _IMAGE_DYNAMIC_RELOCATION64_V2(ctypes.Structure):
    _fields_ = [
        ('HeaderSize', ULONG),
        ('FixupInfoSize', ULONG),
        ('Symbol', ULONGLONG),
        ('SymbolGroup', ULONG),
        ('Flags', ULONG),
    ]


IMAGE_DYNAMIC_RELOCATION64_V2 = _IMAGE_DYNAMIC_RELOCATION64_V2
PIMAGE_DYNAMIC_RELOCATION64_V2 = POINTER(_IMAGE_DYNAMIC_RELOCATION64_V2)


IMAGE_DYNAMIC_RELOCATION = IMAGE_DYNAMIC_RELOCATION64
PIMAGE_DYNAMIC_RELOCATION = PIMAGE_DYNAMIC_RELOCATION64
IMAGE_DYNAMIC_RELOCATION_V2 = IMAGE_DYNAMIC_RELOCATION64_V2
PIMAGE_DYNAMIC_RELOCATION_V2 = PIMAGE_DYNAMIC_RELOCATION64_V2
IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE = 0x00000001
IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE = 0x00000002


class _IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER(ctypes.Structure):
    _fields_ = [
        ('PrologueByteCount', UCHAR),
    ]


IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER = _IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER
PIMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER = UNALIGNED


class _IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER(ctypes.Structure):
    _fields_ = [
        ('EpilogueCount', ULONG),
        ('EpilogueByteCount', UCHAR),
        ('BranchDescriptorElementSize', UCHAR),
        ('BranchDescriptorCount', USHORT),
    ]


IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER = _IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER
PIMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER = UNALIGNED


class _IMAGE_LOAD_CONFIG_DIRECTORY32(ctypes.Structure):
    _fields_ = [
        ('Size', ULONG),
        ('TimeDateStamp', ULONG),
        ('MajorVersion', USHORT),
        ('MinorVersion', USHORT),
        ('GlobalFlagsClear', ULONG),
        ('GlobalFlagsSet', ULONG),
        ('CriticalSectionDefaultTimeout', ULONG),
        ('DeCommitFreeBlockThreshold', ULONG),
        ('DeCommitTotalFreeThreshold', ULONG),
        ('LockPrefixTable', ULONG),
        ('MaximumAllocationSize', ULONG),
        ('VirtualMemoryThreshold', ULONG),
        ('ProcessHeapFlags', ULONG),
        ('ProcessAffinityMask', ULONG),
        ('CSDVersion', USHORT),
        ('DependentLoadFlags', USHORT),
        ('EditList', ULONG),
        ('SecurityCookie', ULONG),
        ('SEHandlerTable', ULONG),
        ('SEHandlerCount', ULONG),
        ('GuardCFCheckFunctionPoINTer', ULONG),
        ('GuardCFDispatchFunctionPoINTer', ULONG),
        ('GuardCFFunctionTable', ULONG),
        ('GuardCFFunctionCount', ULONG),
        ('GuardFlags', ULONG),
        ('CodeIntegrity', IMAGE_LOAD_CONFIG_CODE_INTEGRITY),
        ('GuardAddressTakenIatEntryTable', ULONG),
        ('GuardAddressTakenIatEntryCount', ULONG),
        ('GuardLongJumpTargetTable', ULONG),
        ('GuardLongJumpTargetCount', ULONG),
        ('DynamicValueRelocTable', ULONG),
        ('CHPEMetadataPoINTer', ULONG),
        ('GuardRFFailureRoutine', ULONG),
        ('GuardRFFailureRoutineFunctionPoINTer', ULONG),
        ('DynamicValueRelocTableOffset', ULONG),
        ('DynamicValueRelocTableSection', USHORT),
        ('Reserved2', USHORT),
        ('GuardRFVerifyStackPoINTerFunctionPoINTer', ULONG),
        ('HotPatchTableOffset', ULONG),
        ('Reserved3', ULONG),
        ('EnclaveConfigurationPoINTer', ULONG),
    ]


IMAGE_LOAD_CONFIG_DIRECTORY32 = _IMAGE_LOAD_CONFIG_DIRECTORY32
PIMAGE_LOAD_CONFIG_DIRECTORY32 = POINTER(_IMAGE_LOAD_CONFIG_DIRECTORY32)


class _IMAGE_LOAD_CONFIG_DIRECTORY64(ctypes.Structure):
    _fields_ = [
        ('Size', ULONG),
        ('TimeDateStamp', ULONG),
        ('MajorVersion', USHORT),
        ('MinorVersion', USHORT),
        ('GlobalFlagsClear', ULONG),
        ('GlobalFlagsSet', ULONG),
        ('CriticalSectionDefaultTimeout', ULONG),
        ('DeCommitFreeBlockThreshold', ULONGLONG),
        ('DeCommitTotalFreeThreshold', ULONGLONG),
        ('LockPrefixTable', ULONGLONG),
        ('MaximumAllocationSize', ULONGLONG),
        ('VirtualMemoryThreshold', ULONGLONG),
        ('ProcessAffinityMask', ULONGLONG),
        ('ProcessHeapFlags', ULONG),
        ('CSDVersion', USHORT),
        ('DependentLoadFlags', USHORT),
        ('EditList', ULONGLONG),
        ('SecurityCookie', ULONGLONG),
        ('SEHandlerTable', ULONGLONG),
        ('SEHandlerCount', ULONGLONG),
        ('GuardCFCheckFunctionPoINTer', ULONGLONG),
        ('GuardCFDispatchFunctionPoINTer', ULONGLONG),
        ('GuardCFFunctionTable', ULONGLONG),
        ('GuardCFFunctionCount', ULONGLONG),
        ('GuardFlags', ULONG),
        ('CodeIntegrity', IMAGE_LOAD_CONFIG_CODE_INTEGRITY),
        ('GuardAddressTakenIatEntryTable', ULONGLONG),
        ('GuardAddressTakenIatEntryCount', ULONGLONG),
        ('GuardLongJumpTargetTable', ULONGLONG),
        ('GuardLongJumpTargetCount', ULONGLONG),
        ('DynamicValueRelocTable', ULONGLONG),
        ('CHPEMetadataPoINTer', ULONGLONG),
        ('GuardRFFailureRoutine', ULONGLONG),
        ('GuardRFFailureRoutineFunctionPoINTer', ULONGLONG),
        ('DynamicValueRelocTableOffset', ULONG),
        ('DynamicValueRelocTableSection', USHORT),
        ('Reserved2', USHORT),
        ('GuardRFVerifyStackPoINTerFunctionPoINTer', ULONGLONG),
        ('HotPatchTableOffset', ULONG),
        ('Reserved3', ULONG),
        ('EnclaveConfigurationPoINTer', ULONGLONG),
    ]


IMAGE_LOAD_CONFIG_DIRECTORY64 = _IMAGE_LOAD_CONFIG_DIRECTORY64
PIMAGE_LOAD_CONFIG_DIRECTORY64 = POINTER(_IMAGE_LOAD_CONFIG_DIRECTORY64)


class _IMAGE_CHPE_METADATA_X86(ctypes.Structure):
    _fields_ = [
        ('Version', ULONG),
        ('CHPECodeAddressRangeOffset', ULONG),
        ('CHPECodeAddressRangeCount', ULONG),
        ('WowA64ExceptionHandlerFunctionPoINTer', ULONG),
        ('WowA64DispatchCallFunctionPoINTer', ULONG),
        ('WowA64DispatchIndirectCallFunctionPoINTer', ULONG),
        ('WowA64DispatchIndirectCallCfgFunctionPoINTer', ULONG),
        ('WowA64DispatchRetFunctionPoINTer', ULONG),
        ('WowA64DispatchRetLeafFunctionPoINTer', ULONG),
        ('WowA64DispatchJumpFunctionPoINTer', ULONG),
        ('CompilerIATPoINTer', ULONG),
        ('WowA64RdtscFunctionPoINTer', ULONG),
    ]


IMAGE_CHPE_METADATA_X86 = _IMAGE_CHPE_METADATA_X86
PIMAGE_CHPE_METADATA_X86 = POINTER(_IMAGE_CHPE_METADATA_X86)


class _IMAGE_CHPE_RANGE_ENTRY(ctypes.Structure):
    class DUMMYUNIONNAME(ctypes.Union):
        class DUMMYSTRUCTNAME(ctypes.Structure):
            _fields_ = [
                ('NativeCode', ULONG, 1),
                ('AddressBits', ULONG, 31)
            ]

        _fields_ = [
            ('StartOffset', ULONG),
            ('DUMMYSTRUCTNAME', DUMMYSTRUCTNAME),
        ]

    _fields_ = [
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('Length', ULONG),
    ]


IMAGE_CHPE_RANGE_ENTRY = _IMAGE_CHPE_RANGE_ENTRY
PIMAGE_CHPE_RANGE_ENTRY = POINTER(_IMAGE_CHPE_RANGE_ENTRY)

IMAGE_LOAD_CONFIG_DIRECTORY = IMAGE_LOAD_CONFIG_DIRECTORY64
PIMAGE_LOAD_CONFIG_DIRECTORY = PIMAGE_LOAD_CONFIG_DIRECTORY64


class _IMAGE_HOT_PATCH_INFO(ctypes.Structure):
    _fields_ = [
        ('Version', ULONG),
        ('Size', ULONG),
        ('SequenceNumber', ULONG),
        ('BaseImageList', ULONG),
        ('BaseImageCount', ULONG),
        ('BufferOffset', ULONG),
    ]


IMAGE_HOT_PATCH_INFO = _IMAGE_HOT_PATCH_INFO
PIMAGE_HOT_PATCH_INFO = POINTER(_IMAGE_HOT_PATCH_INFO)


class _IMAGE_HOT_PATCH_BASE(ctypes.Structure):
    _fields_ = [
        ('SequenceNumber', ULONG),
        ('Flags', ULONG),
        ('OriginalTimeDateStamp', ULONG),
        ('OriginalCheckSum', ULONG),
        ('CodeIntegrityInfo', ULONG),
        ('CodeIntegritySize', ULONG),
        ('PatchTable', ULONG),
        ('BufferOffset', ULONG),
    ]


IMAGE_HOT_PATCH_BASE = _IMAGE_HOT_PATCH_BASE
PIMAGE_HOT_PATCH_BASE = POINTER(_IMAGE_HOT_PATCH_BASE)


class _IMAGE_HOT_PATCH_HASHES(ctypes.Structure):
    _fields_ = [
        ('SHA256', UCHAR * 32),
        ('SHA1', UCHAR * 20),
    ]


IMAGE_HOT_PATCH_HASHES = _IMAGE_HOT_PATCH_HASHES
PIMAGE_HOT_PATCH_HASHES = POINTER(_IMAGE_HOT_PATCH_HASHES)


IMAGE_HOT_PATCH_BASE_OBLIGATORY = 0x00000001
IMAGE_HOT_PATCH_CHUNK_INVERSE = 0x80000000
IMAGE_HOT_PATCH_CHUNK_OBLIGATORY = 0x40000000
IMAGE_HOT_PATCH_CHUNK_RESERVED = 0x3FF03000
IMAGE_HOT_PATCH_CHUNK_TYPE = 0x000FC000
IMAGE_HOT_PATCH_CHUNK_SOURCE_RVA = 0x00008000
IMAGE_HOT_PATCH_CHUNK_TARGET_RVA = 0x00004000
IMAGE_HOT_PATCH_CHUNK_SIZE = 0x00000FFF
IMAGE_HOT_PATCH_NONE = 0x00000000
IMAGE_HOT_PATCH_FUNCTION = 0x0001C000
IMAGE_HOT_PATCH_ABSOLUTE = 0x0002C000
IMAGE_HOT_PATCH_REL32 = 0x0003C000
IMAGE_HOT_PATCH_CALL_TARGET = 0x00044000
IMAGE_HOT_PATCH_INDIRECT = 0x0005C000
IMAGE_HOT_PATCH_NO_CALL_TARGET = 0x00064000
IMAGE_HOT_PATCH_DYNAMIC_VALUE = 0x00078000
IMAGE_GUARD_CF_INSTRUMENTED = 0x00000100
IMAGE_GUARD_CFW_INSTRUMENTED = 0x00000200
IMAGE_GUARD_CF_FUNCTION_TABLE_PRESENT = 0x00000400
IMAGE_GUARD_SECURITY_COOKIE_UNUSED = 0x00000800
IMAGE_GUARD_PROTECT_DELAYLOAD_IAT = 0x00001000
IMAGE_GUARD_DELAYLOAD_IAT_IN_ITS_OWN_SECTION = 0x00002000
IMAGE_GUARD_CF_EXPORT_SUPPRESSION_INFO_PRESENT = 0x00004000
IMAGE_GUARD_CF_ENABLE_EXPORT_SUPPRESSION = 0x00008000
IMAGE_GUARD_CF_LONGJUMP_TABLE_PRESENT = 0x00010000
IMAGE_GUARD_RF_INSTRUMENTED = 0x00020000
IMAGE_GUARD_RF_ENABLE = 0x00040000
IMAGE_GUARD_RF_STRICT = 0x00080000
IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_MASK = 0xF0000000
IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_SHIFT = 0x0000001C
IMAGE_GUARD_FLAG_FID_SUPPRESSED = 0x00000001
IMAGE_GUARD_FLAG_EXPORT_SUPPRESSED = 0x00000002


class _IMAGE_RUNTIME_FUNCTION_ENTRY(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):
        _fields_ = [
            ('UnwindInfoAddress', ULONG),
            ('UnwindData', ULONG),
        ]

    _fields_ = [
        ('BeginAddress', ULONG),
        ('EndAddress', ULONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
    ]


_PIMAGE_RUNTIME_FUNCTION_ENTRY = POINTER(_IMAGE_RUNTIME_FUNCTION_ENTRY)


IMAGE_IA64_RUNTIME_FUNCTION_ENTRY = _IMAGE_RUNTIME_FUNCTION_ENTRY
PIMAGE_IA64_RUNTIME_FUNCTION_ENTRY = _PIMAGE_RUNTIME_FUNCTION_ENTRY

IMAGE_ENCLAVE_LONG_ID_LENGTH = 0x00000020
IMAGE_ENCLAVE_SHORT_ID_LENGTH = 0x00000010


class _IMAGE_ENCLAVE_CONFIG32(ctypes.Structure):
    _fields_ = [
        ('Size', ULONG),
        ('MinimumRequiredConfigSize', ULONG),
        ('PolicyFlags', ULONG),
        ('NumberOfImports', ULONG),
        ('ImportList', ULONG),
        ('ImportEntrySize', ULONG),
        ('FamilyID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImageID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImageVersion', ULONG),
        ('SecurityVersion', ULONG),
        ('EnclaveSize', ULONG),
        ('NumberOfThreads', ULONG),
        ('EnclaveFlags', ULONG),
    ]


IMAGE_ENCLAVE_CONFIG32 = _IMAGE_ENCLAVE_CONFIG32
PIMAGE_ENCLAVE_CONFIG32 = POINTER(_IMAGE_ENCLAVE_CONFIG32)


class _IMAGE_ENCLAVE_CONFIG64(ctypes.Structure):
    _fields_ = [
        ('Size', ULONG),
        ('MinimumRequiredConfigSize', ULONG),
        ('PolicyFlags', ULONG),
        ('NumberOfImports', ULONG),
        ('ImportList', ULONG),
        ('ImportEntrySize', ULONG),
        ('FamilyID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImageID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImageVersion', ULONG),
        ('SecurityVersion', ULONG),
        ('EnclaveSize', ULONGLONG),
        ('NumberOfThreads', ULONG),
        ('EnclaveFlags', ULONG),
    ]


IMAGE_ENCLAVE_CONFIG64 = _IMAGE_ENCLAVE_CONFIG64
PIMAGE_ENCLAVE_CONFIG64 = POINTER(_IMAGE_ENCLAVE_CONFIG64)


IMAGE_ENCLAVE_CONFIG = IMAGE_ENCLAVE_CONFIG64
PIMAGE_ENCLAVE_CONFIG = PIMAGE_ENCLAVE_CONFIG64

IMAGE_ENCLAVE_POLICY_DEBUGGABLE = 0x00000001
IMAGE_ENCLAVE_FLAG_PRIMARY_IMAGE = 0x00000001


class _IMAGE_ENCLAVE_IMPORT(ctypes.Structure):
    _fields_ = [
        ('MatchType', ULONG),
        ('MinimumSecurityVersion', ULONG),
        ('UniqueOrAuthorID', UCHAR * IMAGE_ENCLAVE_LONG_ID_LENGTH),
        ('FamilyID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImageID', UCHAR * IMAGE_ENCLAVE_SHORT_ID_LENGTH),
        ('ImportName', ULONG),
        ('Reserved', ULONG),
    ]


IMAGE_ENCLAVE_IMPORT = _IMAGE_ENCLAVE_IMPORT
PIMAGE_ENCLAVE_IMPORT = POINTER(_IMAGE_ENCLAVE_IMPORT)


IMAGE_ENCLAVE_IMPORT_MATCH_NONE = 0x00000000
IMAGE_ENCLAVE_IMPORT_MATCH_UNIQUE_ID = 0x00000001
IMAGE_ENCLAVE_IMPORT_MATCH_AUTHOR_ID = 0x00000002
IMAGE_ENCLAVE_IMPORT_MATCH_FAMILY_ID = 0x00000003
IMAGE_ENCLAVE_IMPORT_MATCH_IMAGE_ID = 0x00000004


class _IMAGE_DEBUG_DIRECTORY(ctypes.Structure):
    _fields_ = [
        ('Characteristics', ULONG),
        ('TimeDateStamp', ULONG),
        ('MajorVersion', USHORT),
        ('MinorVersion', USHORT),
        ('Type', ULONG),
        ('SizeOfData', ULONG),
        ('AddressOfRawData', ULONG),
        ('PoINTerToRawData', ULONG),
    ]


IMAGE_DEBUG_DIRECTORY = _IMAGE_DEBUG_DIRECTORY
PIMAGE_DEBUG_DIRECTORY = POINTER(_IMAGE_DEBUG_DIRECTORY)


IMAGE_DEBUG_TYPE_UNKNOWN = 0x00000000
IMAGE_DEBUG_TYPE_COFF = 0x00000001
IMAGE_DEBUG_TYPE_CODEVIEW = 0x00000002
IMAGE_DEBUG_TYPE_FPO = 0x00000003
IMAGE_DEBUG_TYPE_MISC = 0x00000004
IMAGE_DEBUG_TYPE_EXCEPTION = 0x00000005
IMAGE_DEBUG_TYPE_FIXUP = 0x00000006
IMAGE_DEBUG_TYPE_OMAP_TO_SRC = 0x00000007
IMAGE_DEBUG_TYPE_OMAP_FROM_SRC = 0x00000008
IMAGE_DEBUG_TYPE_BORLAND = 0x00000009
IMAGE_DEBUG_TYPE_RESERVED10 = 0x0000000A
IMAGE_DEBUG_TYPE_CLSID = 0x0000000B
IMAGE_DEBUG_TYPE_VC_FEATURE = 0x0000000C
IMAGE_DEBUG_TYPE_POGO = 0x0000000D
IMAGE_DEBUG_TYPE_ILTCG = 0x0000000E
IMAGE_DEBUG_TYPE_MPX = 0x0000000F
IMAGE_DEBUG_TYPE_REPRO = 0x00000010


class _IMAGE_COFF_SYMBOLS_HEADER(ctypes.Structure):
    _fields_ = [
        ('NumberOfSymbols', ULONG),
        ('LvaToFirstSymbol', ULONG),
        ('NumberOfLinenumbers', ULONG),
        ('LvaToFirstLinenumber', ULONG),
        ('RvaToFirstByteOfCode', ULONG),
        ('RvaToLastByteOfCode', ULONG),
        ('RvaToFirstByteOfData', ULONG),
        ('RvaToLastByteOfData', ULONG),
    ]


IMAGE_COFF_SYMBOLS_HEADER = _IMAGE_COFF_SYMBOLS_HEADER
PIMAGE_COFF_SYMBOLS_HEADER = POINTER(_IMAGE_COFF_SYMBOLS_HEADER)


FRAME_FPO = 0x00000000
FRAME_TRAP = 0x00000001
FRAME_TSS = 0x00000002
FRAME_NONFPO = 0x00000003


class _FPO_DATA(ctypes.Structure):
    _fields_ = [
        ('ulOffStart', ULONG),
        ('cbProcSize', ULONG),
        ('cdwLocals', ULONG),
        ('cdwParams', USHORT),
        ('cbProlog : 8', USHORT),
        ('cbRegs   : 3', USHORT),
        ('fHasSEH  : 1', USHORT),
        ('fUseBP   : 1', USHORT),
        ('reserved : 1', USHORT),
        ('cbFrame  : 2', USHORT),
    ]


FPO_DATA = _FPO_DATA
PFPO_DATA = POINTER(_FPO_DATA)


SIZEOF_RFPO_DATA = 0x00000010
IMAGE_DEBUG_MISC_EXENAME = 0x00000001


class _IMAGE_DEBUG_MISC(ctypes.Structure):
    _fields_ = [
        ('DataType', ULONG),
        ('Length', ULONG),
        ('Unicode', BOOLEAN),
        ('Reserved', UCHAR * 3),
        ('Data', UCHAR * 1),
    ]


IMAGE_DEBUG_MISC = _IMAGE_DEBUG_MISC
PIMAGE_DEBUG_MISC = POINTER(_IMAGE_DEBUG_MISC)


class _IMAGE_FUNCTION_ENTRY(ctypes.Structure):
    _fields_ = [
        ('StartingAddress', ULONG),
        ('EndingAddress', ULONG),
        ('EndOfPrologue', ULONG),
    ]


IMAGE_FUNCTION_ENTRY = _IMAGE_FUNCTION_ENTRY
PIMAGE_FUNCTION_ENTRY = POINTER(_IMAGE_FUNCTION_ENTRY)


class _IMAGE_FUNCTION_ENTRY64(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):
        _fields_ = [
            ('EndOfPrologue', ULONGLONG),
            ('UnwindInfoAddress', ULONGLONG),
        ]

    _fields_ = [
        ('StartingAddress', ULONGLONG),
        ('EndingAddress', ULONGLONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
    ]


IMAGE_FUNCTION_ENTRY64 = _IMAGE_FUNCTION_ENTRY64
PIMAGE_FUNCTION_ENTRY64 = POINTER(_IMAGE_FUNCTION_ENTRY64)


class _IMAGE_SEPARATE_DEBUG_HEADER(ctypes.Structure):
    _fields_ = [
        ('Signature', USHORT),
        ('Flags', USHORT),
        ('Machine', USHORT),
        ('Characteristics', USHORT),
        ('TimeDateStamp', ULONG),
        ('CheckSum', ULONG),
        ('ImageBase', ULONG),
        ('SizeOfImage', ULONG),
        ('NumberOfSections', ULONG),
        ('ExportedNamesSize', ULONG),
        ('DebugDirectorySize', ULONG),
        ('SectionAlignment', ULONG),
        ('Reserved', ULONG * 2),
    ]


IMAGE_SEPARATE_DEBUG_HEADER = _IMAGE_SEPARATE_DEBUG_HEADER
PIMAGE_SEPARATE_DEBUG_HEADER = POINTER(_IMAGE_SEPARATE_DEBUG_HEADER)


class _NON_PAGED_DEBUG_INFO(ctypes.Structure):
    _fields_ = [
        ('Signature', USHORT),
        ('Flags', USHORT),
        ('Size', ULONG),
        ('Machine', USHORT),
        ('Characteristics', USHORT),
        ('TimeDateStamp', ULONG),
        ('CheckSum', ULONG),
        ('SizeOfImage', ULONG),
        ('ImageBase', ULONGLONG),
    ]


NON_PAGED_DEBUG_INFO = _NON_PAGED_DEBUG_INFO
PNON_PAGED_DEBUG_INFO = POINTER(_NON_PAGED_DEBUG_INFO)


IMAGE_SEPARATE_DEBUG_SIGNATURE = 0x00004944
NON_PAGED_DEBUG_SIGNATURE = 0x0000494E
IMAGE_SEPARATE_DEBUG_FLAGS_MASK = 0x00008000
IMAGE_SEPARATE_DEBUG_MISMATCH = 0x00008000


class _ImageArchitectureHeader(ctypes.Structure):
    _fields_ = [
        ('AmaskValue', UINT, 1),
        ('', INT, 7),
        ('AmaskShift', UINT, 8),
        ('', INT, 16),
        ('FirstEntryRVA', ULONG),
    ]


IMAGE_ARCHITECTURE_HEADER = _ImageArchitectureHeader
PIMAGE_ARCHITECTURE_HEADER = POINTER(_ImageArchitectureHeader)


class _ImageArchitectureEntry(ctypes.Structure):
    _fields_ = [
        ('FixupInstRVA', ULONG),
        ('NewInst', ULONG),
    ]


IMAGE_ARCHITECTURE_ENTRY = _ImageArchitectureEntry
PIMAGE_ARCHITECTURE_ENTRY = POINTER(_ImageArchitectureEntry)


IMPORT_OBJECT_HDR_SIG2 = 0x0000FFFF


class IMPORT_OBJECT_HEADER(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        _fields_ = [
            ('Ordinal', USHORT),
            ('Hint', USHORT)
        ]

    _fields_ = [
        ('Sig1', USHORT),
        ('Sig2', USHORT),
        ('Version', USHORT),
        ('Machine', USHORT),
        ('TimeDateStamp', ULONG),
        ('SizeOfData', ULONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('Type : 2', USHORT),
        ('NameType : 3', USHORT),
        ('Reserved : 11', USHORT),
    ]


class IMPORT_OBJECT_TYPE(ENUM):
    IMPORT_OBJECT_CODE = 0
    IMPORT_OBJECT_DATA = 1
    IMPORT_OBJECT_CONST = 2


class IMPORT_OBJECT_NAME_TYPE(ENUM):
    IMPORT_OBJECT_ORDINAL = 0
    IMPORT_OBJECT_NAME = 1
    IMPORT_OBJECT_NAME_NO_PREFIX = 2
    IMPORT_OBJECT_NAME_UNDECORATE = 3
    IMPORT_OBJECT_NAME_EXPORTAS = 4


class ReplacesCorHdrNumericDefines(ENUM):
    COMIMAGE_FLAGS_ILONLY = 0x00000001
    COMIMAGE_FLAGS_32BITREQUIRED = 0x00000002
    COMIMAGE_FLAGS_IL_LIBRARY = 0x00000004
    COMIMAGE_FLAGS_STRONGNAMESIGNED = 0x00000008
    COMIMAGE_FLAGS_NATIVE_ENTRYPOINT = 0x00000010
    COMIMAGE_FLAGS_TRACKDEBUGDATA = 0x00010000
    COMIMAGE_FLAGS_32BITPREFERRED = 0x00020000
    COR_VERSION_MAJOR_V2 = 2
    COR_VERSION_MAJOR = COR_VERSION_MAJOR_V2
    COR_VERSION_MINOR = 5
    COR_DELETED_NAME_LENGTH = 8
    COR_VTABLEGAP_NAME_LENGTH = 8
    NATIVE_TYPE_MAX_CB = 1
    COR_ILMETHOD_SECT_SMALL_MAX_DATASIZE = 0xFF
    IMAGE_COR_MIH_METHODRVA = 0x01
    IMAGE_COR_MIH_EHRVA = 0x02
    IMAGE_COR_MIH_BASICBLOCK = 0x08
    COR_VTABLE_32BIT = 0x01
    COR_VTABLE_64BIT = 0x02
    COR_VTABLE_FROM_UNMANAGED = 0x04
    COR_VTABLE_FROM_UNMANAGED_RETAIN_APPDOMAIN = 0x08
    COR_VTABLE_CALL_MOST_DERIVED = 0x10
    IMAGE_COR_EATJ_THUNK_SIZE = 32
    MAX_CLASS_NAME = 1024
    MAX_PACKAGE_NAME = 1024


class IMAGE_COR20_HEADER(ctypes.Structure):

    class DUMMYUNIONNAME(ctypes.Union):

        _fields_ = [
            ('EntryPointToken', ULONG),
            ('EntryPointRVA', ULONG)
        ]

    _fields_ = [
        ('cb', ULONG),
        ('MajorRuntimeVersion', USHORT),
        ('MinorRuntimeVersion', USHORT),
        ('MetaData', IMAGE_DATA_DIRECTORY),
        ('Flags', ULONG),
        ('DUMMYUNIONNAME', DUMMYUNIONNAME),
        ('Resources', IMAGE_DATA_DIRECTORY),
        ('StrongNameSignature', IMAGE_DATA_DIRECTORY),
        ('CodeManagerTable', IMAGE_DATA_DIRECTORY),
        ('VTableFixups', IMAGE_DATA_DIRECTORY),
        ('ExportAddressTableJumps', IMAGE_DATA_DIRECTORY),
        ('ManagedNativeHeader', IMAGE_DATA_DIRECTORY),
    ]


PIMAGE_COR20_HEADER = POINTER(IMAGE_COR20_HEADER)


PUIMAGE_OS2_HEADER = UNALIGNED
PCIMAGE_IMPORT_DESCRIPTOR = POINTER(UNALIGNED)
PCIMAGE_BOUND_IMPORT_DESCRIPTOR = POINTER(CONST)
PCIMAGE_BOUND_FORWARDER_REF = POINTER(CONST)
PCIMAGE_IMPORT_BY_NAME = POINTER(CONST)
PCIMAGE_THUNK_DATA = POINTER(CONST)
PCIMAGE_THUNK_DATA32 = POINTER(CONST)
PCIMAGE_THUNK_DATA64 = POINTER(CONST)
PCIMAGE_TLS_DIRECTORY = POINTER(CONST)
PCIMAGE_TLS_DIRECTORY32 = POINTER(CONST)
PCIMAGE_TLS_DIRECTORY64 = POINTER(CONST)
PCIMAGE_EXPORT_DIRECTORY = POINTER(CONST)
PCIMAGE_SECTION_HEADER = POINTER(CONST)

__all__ = (
    'IMAGE_VXD_SIGNATURE', 'IMAGE_REL_I386_SECTION', 'IMAGE_SCN_ALIGN_MASK',
    'IMAGE_ORDINAL64', 'IMAGE_ARCHIVE_LINKER_MEMBER', 'IMAGE_REL_AM_SECTION',
    'IMAGE_SCN_LNK_REMOVE', 'IMAGE_REL_MIPS_GPREL', 'IMAGE_REL_IA64_IMM14',
    'IMAGE_SIZEOF_ARCHIVE_MEMBER_HDR', 'IMAGE_LOADER_FLAGS_COMPLUS', 'ISTAG',
    'IMAGE_REL_PPC_SECREL', 'EMARCH_ENC_I17_IMM5C_INST_WORD_X', 'ISARY',
    'IMAGE_SNAP_BY_ORDINAL', 'IMAGE_REL_SH_NOMODE', 'IMAGE_REL_AM_ABSOLUTE',
    'IMAGE_SYM_TYPE_STRUCT', 'IMAGE_FILE_MACHINE_MIPSFPU', 'INCREF', 'DECREF',
    'IMAGE_REL_PPC_TOCREL16', 'IMAGE_REL_PPC_TOCREL14', 'IMAGE_REL_SH3_TOKEN',
    'EMARCH_ENC_I17_IMM41a_INST_WORD_X', 'IMAGE_REL_BASED_DIR64', 'N_BTSHFT',
    'IMAGE_REL_BASED_IA64_IMM64', 'IMAGE_REL_THUMB_MOV32', 'X3_I_SIZE_X',
    'IMAGE_REL_ARM64_SECREL', 'IMAGE_SCN_TYPE_NO_PAD', 'IMAGE_SCN_MEM_LOCKED',
    'IMAGE_HOT_PATCH_CHUNK_SOURCE_RVA', 'IMAGE_REL_ALPHA_SECRELLO', 'BTYPE',
    'IMAGE_REL_CEF_ADDR32NB', 'IMAGE_REL_I386_SEG12', 'IMAGE_SYM_UNDEFINED',
    'IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE', 'IMAGE_SYM_CLASS_FUNCTION',
    'IMAGE_SYM_CLASS_TYPE_DEFINITION', 'IMAGE_REL_M32R_ABSOLUTE', 'INS_IMM64',
    'IMAGE_REL_AMD64_SREL32', 'IMAGE_REL_IA64_PCREL21B', 'FRAME_TRAP',
    'IMAGE_FILE_AGGRESIVE_WS_TRIM', 'IMAGE_REL_IA64_DIR32NB', 'IMAGE_ORDINAL',
    'IMAGE_REL_IA64_PCREL21F', 'IMAGE_ENCLAVE_FLAG_PRIMARY_IMAGE', 'N_TSHIFT',
    'IMAGE_REL_MIPS_SECRELLO', 'IMAGE_REL_IA64_PCREL21M', 'EXT_IMM64',
    'IMAGE_NT_OPTIONAL_HDR_MAGIC', 'IMAGE_DEBUG_MISC_EXENAME', 'N_BTMASK',
    'IMAGE_REL_ARM64_BRANCH19', 'IMAGE_SUBSYSTEM_POSIX_CUI', 'X3_P_SIZE_X',
    'IMAGE_REL_SH3_DIRECT4', 'IMAGE_REL_SH3_DIRECT8_LONG', 'IMAGE_ORDINAL32',
    'IMAGE_REL_SH3_DIRECT8', 'IMAGE_FILE_MACHINE_TARGET_HOST', 'ISFCN',
    'IMAGE_SEPARATE_DEBUG_SIGNATURE', 'IMAGE_REL_M32R_REFLO', 'FRAME_NONFPO',
    'IMAGE_REL_AMD64_PAIR', 'IMAGE_REL_ALPHA_SECREL', 'X3_D_WH_INST_WORD_X',
    'IMAGE_ENCLAVE_IMPORT_MATCH_FAMILY_ID', 'IMAGE_ORDINAL_FLAG', 'ISPTR',
    'IMAGE_REL_BASED_ARM_MOV32', 'IMAGE_SCN_LNK_OTHER', 'IMAGE_SYM_TYPE_MOE',
    'IMAGE_REL_ARM64_ADDR32', 'IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA',
    'IMAGE_REL_CEE_SECTION', 'IMAGE_REL_SH3_DIRECT8_WORD', 'X3_EMPTY_SIZE_X',
    'X3_IMM39_2_SIGN_VAL_POS_X', 'IMAGE_REL_THUMB_BLX23', 'IMAGE_FILE_SYSTEM',
    'IMAGE_COMDAT_SELECT_SAME_SIZE', 'IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY',
    'IMAGE_SYM_DTYPE_FUNCTION', 'IMAGE_SUBSYSTEM_UNKNOWN', 'X3_OPCODE_SIZE_X',
    'IMAGE_DIRECTORY_ENTRY_EXCEPTION', 'IMAGE_REL_PPC_BRNTAKEN', 'FRAME_FPO',
    'IMAGE_REL_IA64_IMM64', 'IMAGE_FILE_MACHINE_AMD64', 'IMAGE_REL_AM_TOKEN',
    'EMARCH_ENC_I17_IMM41a_INST_WORD_POS_X', 'IMAGE_SYM_DTYPE_POINTER',
    'X3_TMPLT_INST_WORD_X', 'IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR', 'N_TMASK',
    'IMAGE_DEBUG_TYPE_VC_FEATURE', 'IMAGE_REL_BASED_HIGHADJ', 'N_TMASK1',
    'IMAGE_REL_ALPHA_BRADDR', 'IMAGE_SCN_CNT_UNINITIALIZED_DATA', 'N_TMASK2',
    'IMAGE_REL_SH3_PCREL12_WORD', 'IMAGE_HOT_PATCH_BASE_OBLIGATORY',
    'X3_EMPTY_INST_WORD_POS_X', 'IMAGE_SCN_ALIGN_1024BYTES', 'X3_D_WH_SIZE_X',
    'IMAGE_ARCHIVE_PAD', 'IMAGE_SYM_TYPE_VOID', 'X3_TMPLT_INST_WORD_POS_X',
    'IMAGE_REL_ARM64_SECREL_HIGH12A', 'EMARCH_ENC_I17_IMM41a_VAL_POS_X',
    'IMAGE_REL_PPC_TOKEN', 'IMAGE_FILE_NET_RUN_FROM_SWAP', 'IMAGE_SYM_DEBUG',
    'IMAGE_REL_I386_DIR32', 'IMAGE_FILE_MACHINE_I386', 'IMAGE_OS2_SIGNATURE',
    'IMAGE_DEBUG_TYPE_COFF', 'IMAGE_HOT_PATCH_CHUNK_TYPE', 'X3_P_INST_WORD_X',
    'IMAGE_SYM_CLASS_WEAK_EXTERNAL', 'IMAGE_FILE_BYTES_REVERSED_LO',
    'IMAGE_GUARD_CF_ENABLE_EXPORT_SUPPRESSION', 'X3_EMPTY_INST_VAL_POS_X',
    'EMARCH_ENC_I17_IMM41b_SIZE_X', 'IMAGE_SYM_TYPE_CHAR', 'X3_I_INST_WORD_X',
    'X3_IMM20_INST_WORD_POS_X', 'IMAGE_REL_SH3_DIRECT16', 'IMAGE_REL_PPC_NEG',
    'IMAGE_REL_AM_SECREL', 'IMAGE_SUBSYSTEM_XBOX', 'IMAGE_SCN_MEM_WRITE',
    'IMAGE_REL_ALPHA_REFLONGNB', 'IMAGE_REL_CEE_ADDR32', 'X3_TMPLT_SIZE_X',
    'IMAGE_SYM_CLASS_FILE', 'IMAGE_ENCLAVE_LONG_ID_LENGTH', 'IMAGE_FILE_DLL',
    'EMARCH_ENC_I17_IMM41c_SIZE_X', 'IMAGE_SNAP_BY_ORDINAL32', 'FRAME_TSS',
    'IMAGE_SYM_CLASS_UNION_TAG', 'IMAGE_REL_IA64_SREL22', 'SIZEOF_RFPO_DATA',
    'IMAGE_FIRST_SECTION', 'EMARCH_ENC_I17_IC_SIZE_X', 'IMAGE_REL_MIPS_PAIR',
    'IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_SHIFT', 'IMAGE_SCN_MEM_DISCARDABLE',
    'IMAGE_SYM_CLASS_SECTION', 'IMAGE_REL_SH3_SECREL', 'IMAGE_REL_AM_ADDR32',
    'IMAGE_GUARD_CFW_INSTRUMENTED', 'IMAGE_REL_ARM64_TOKEN', '_FPO_DATA',
    'IMAGE_SCN_ALIGN_4096BYTES', 'X3_BTYPE_QP_INST_WORD_X', 'X3_IMM20_SIZE_X',
    'IMAGE_DEBUG_TYPE_UNKNOWN', 'IMAGE_SCN_NO_DEFER_SPEC_EXC', 'IMAGE_SYMBOL',
    'IMAGE_FILE_RELOCS_STRIPPED', 'IMAGE_REL_CEF_ADDR64', 'X3_IMM39_1_SIZE_X',
    'IMAGE_REL_CEF_ABSOLUTE', 'EMARCH_ENC_I17_IC_INST_WORD_POS_X', 'FPO_DATA',
    'IMAGE_SYM_CLASS_BIT_FIELD', 'IMAGE_ORDINAL_FLAG64', 'X3_BTYPE_QP_SIZE_X',
    'IMAGE_REL_AM_CALL32', 'IMAGE_REL_ALPHA_REFQ2', 'IMAGE_REL_ALPHA_REFQ3',
    'IMAGE_REL_ALPHA_REFQ1', 'IMAGE_REL_ARM_BLX24', 'IMAGE_REL_SHM_REFHALF',
    'IMAGE_FILE_EXECUTABLE_IMAGE', 'IMAGE_SYM_CLASS_ARGUMENT', 'PFPO_DATA',
    'IMAGE_SCN_LNK_NRELOC_OVFL', 'IMAGE_MAJOR_LINKER_VERSION',
    'EMARCH_ENC_I17_IMM7B_SIZE_X', 'IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT',
    'IMAGE_REL_ARM_BRANCH24', 'IMAGE_SCN_MEM_SHARED', 'IMAGE_REL_MIPS_REFLO',
    'IMAGE_REL_ALPHA_GPREL32', 'IMAGE_REL_MIPS_REFWORDNB', 'IMAGE_SCN_GPREL',
    'IMAGE_SUBSYSTEM_EFI_ROM', 'IMAGE_REL_PPC_TYPEMASK', 'IMAGE_REL_SHM_PAIR',
    'IMAGE_DIRECTORY_ENTRY_GLOBALPTR', 'IMAGE_DLLCHARACTERISTICS_NO_SEH',
    'IMAGE_ENCLAVE_SHORT_ID_LENGTH', 'IMAGE_NT_OPTIONAL_HDR64_MAGIC',
    'IMAGE_FILE_MACHINE_POWERPCFP', 'IMAGE_SYM_TYPE_ULONG', 'IMAGE_SYMBOL_EX',
    'IMAGE_REL_IA64_IMM22', 'NON_PAGED_DEBUG_SIGNATURE', 'X3_IMM39_2_SIZE_X',
    'IMAGE_SUBSYSTEM_WINDOWS_GUI', 'IMAGE_FILE_MACHINE_TRICORE',
    'IMAGE_SEPARATE_DEBUG_MISMATCH', 'IMAGE_SYM_CLASS_UNDEFINED_STATIC',
    'IMAGE_WEAK_EXTERN_SEARCH_LIBRARY', 'IMAGE_REL_CEF_TOKEN',
    'IMAGE_FILE_32BIT_MACHINE', 'IMAGE_REL_MIPS_JMPADDR16', '_IMAGE_SYMBOL',
    'EMARCH_ENC_I17_IMM41c_VAL_POS_X', 'IMAGE_REL_MIPS_TOKEN',
    'IMAGE_REL_CEE_SECREL', 'EMARCH_ENC_I17_IMM7B_INST_WORD_X',
    'X3_P_SIGN_VAL_POS_X', 'IMAGE_FILE_UP_SYSTEM_ONLY', 'IMAGE_REL_ARM_TOKEN',
    'IMAGE_REL_M32R_ADDR32NB', 'IMAGE_FILE_LARGE_ADDRESS_AWARE',
    'IMAGE_REL_AMD64_ADDR32NB', 'IMAGE_DLLCHARACTERISTICS_NO_BIND',
    'IMAGE_FILE_MACHINE_UNKNOWN', 'X3_OPCODE_SIGN_VAL_POS_X', 'PIMAGE_SYMBOL',
    'IMAGE_SYM_TYPE_NULL', 'IMAGE_FILE_MACHINE_ARM64', 'IMAGE_REL_CEE_TOKEN',
    'IMAGE_REL_ALPHA_INLINE_REFLONG', 'EMARCH_ENC_I17_IMM5C_VAL_POS_X',
    'IMAGE_REL_BASED_MIPS_JMPADDR', 'IMAGE_SCN_ALIGN_2048BYTES',
    'IMAGE_SUBSYSTEM_NATIVE_WINDOWS', 'IMAGE_SYM_SECTION_MAX_EX',
    'IMAGE_DIRECTORY_ENTRY_EXPORT', 'IMAGE_REL_I386_REL32',
    'IMAGE_GUARD_CF_EXPORT_SUPPRESSION_INFO_PRESENT', 'IMAGE_DEBUG_TYPE_MPX',
    'IMAGE_REL_ARM_BRANCH24T', 'EMARCH_ENC_I17_IMM9D_VAL_POS_X',
    'EMARCH_ENC_I17_IC_INST_WORD_X', 'IMAGE_ARCHIVE_START_SIZE',
    'IMAGE_ENCLAVE_POLICY_DEBUGGABLE', 'IMAGE_SCN_MEM_16BIT',
    'IMAGE_REL_PPC_ADDR32', 'IMAGE_REL_ALPHA_GPRELLO', 'IMAGE_REL_CEF_ADDR32',
    'IMAGE_REL_PPC_ADDR32NB', 'IMAGE_SCN_ALIGN_512BYTES', 'IMAGE_ARCHIVE_END',
    'IMAGE_SYM_CLASS_REGISTER_PARAM', 'X3_IMM20_SIGN_VAL_POS_X',
    'IMAGE_REL_PPC_SECRELLO', 'IMAGE_SYM_TYPE_FLOAT', 'IMAGE_REL_ARM_GPREL7',
    'IMAGE_REL_AMD64_SECREL', 'IMAGE_SYM_CLASS_CLR_TOKEN', 'IMAGE_LINENUMBER',
    'IMAGE_REL_ALPHA_GPDISP', 'IMAGE_REL_PPC_ABSOLUTE', 'IMAGE_REL_M32R_PAIR',
    'IMAGE_REL_SH3_SECTION', 'IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP',
    'IMAGE_REL_ARM64_PAGEOFFSET_12A', 'IMAGE_ENCLAVE_IMPORT_MATCH_UNIQUE_ID',
    'IMAGE_REL_ARM64_PAGEOFFSET_12L', 'IMAGE_REL_MIPS_SECREL',
    'IMAGE_REL_EBC_SECREL', 'IMAGE_DIRECTORY_ENTRY_SECURITY',
    'IMAGE_REL_ALPHA_LITUSE', 'IMAGE_SYM_CLASS_STATIC', 'IMAGE_REL_PPC_GPREL',
    'IMAGE_REL_MIPS_ABSOLUTE', 'IMAGE_REL_ARM_BRANCH11', 'IMAGE_SYM_ABSOLUTE',
    'IMAGE_DEBUG_TYPE_FPO', 'IMAGE_SYM_TYPE_SHORT', 'IMAGE_REL_ALPHA_MATCH',
    'IMAGE_REL_ARM_BRANCH20T', 'IMAGE_REL_BASED_ABSOLUTE', 'IMAGE_OS2_HEADER',
    'X3_TMPLT_SIGN_VAL_POS_X', 'IMAGE_FILE_MACHINE_ARM', 'IMAGE_REL_PPC_PAIR',
    'IMAGE_SCN_ALIGN_8BYTES', 'EMARCH_ENC_I17_SIGN_VAL_POS_X',
    'IMAGE_GUARD_PROTECT_DELAYLOAD_IAT', 'IMAGE_REL_ALPHA_REFLONG',
    'EMARCH_ENC_I17_IC_VAL_POS_X', 'IMAGE_SCN_ALIGN_128BYTES',
    'IMAGE_DEBUG_TYPE_ILTCG', 'IMAGE_REL_CEE_ABSOLUTE', 'IMAGE_DOS_SIGNATURE',
    'EMARCH_ENC_I17_IMM9D_INST_WORD_POS_X', 'IMAGE_DEBUG_TYPE_POGO',
    'IMAGE_REL_AMD64_REL32', 'X3_I_INST_WORD_POS_X', 'IMAGE_HOT_PATCH_REL32',
    'IMAGE_DEBUG_TYPE_OMAP_TO_SRC', 'EMARCH_ENC_I17_IMM41c_INST_WORD_POS_X',
    'X3_BTYPE_QP_INST_WORD_POS_X', 'IMAGE_REL_IA64_DIR64', 'IMAGE_DOS_HEADER',
    'IMAGE_SCN_MEM_PURGEABLE', 'EMARCH_ENC_I17_IMM7B_VAL_POS_X',
    'IMAGE_DLLCHARACTERISTICS_NX_COMPAT', 'IMAGE_REL_ALPHA_LITERAL',
    'IMAGE_REL_ARM_BLX23T', 'IMAGE_REL_IA64_TOKEN', 'IMAGE_SYM_CLASS_BLOCK',
    'IMAGE_SUBSYSTEM_XBOX_CODE_CATALOG', 'IMAGE_REL_IA64_SREL14',
    'IMAGE_REL_AMD64_SSPAN32', 'IMAGE_REL_ARM64_ADDR64', 'IMAGE_NT_SIGNATURE',
    'IMAGE_HOT_PATCH_CHUNK_RESERVED', 'IMAGE_DIRECTORY_ENTRY_DEBUG',
    'IMAGE_GUARD_RF_ENABLE', 'EMARCH_ENC_I17_IMM7B_INST_WORD_POS_X',
    'IMAGE_SEPARATE_DEBUG_FLAGS_MASK', 'IMAGE_SCN_MEM_PRELOAD',
    'IMAGE_REL_BASED_HIGHLOW', 'IMAGE_SYM_TYPE_UNION', 'IMAGE_REL_BASED_HIGH',
    'IMAGE_REL_ALPHA_SECTION', 'IMAGE_REL_PPC_SECRELHI', 'IMAGE_SYM_TYPE_INT',
    'IMAGE_FILE_MACHINE_CEE', 'IMAGE_FILE_MACHINE_CEF', 'X3_I_SIGN_VAL_POS_X',
    'EMARCH_ENC_I17_SIGN_INST_WORD_X', 'IMAGE_SYM_TYPE_USHORT',
    'IMAGE_SYM_SECTION_MAX', 'IMAGE_DEBUG_TYPE_CLSID', 'IMAGE_REL_ALPHA_HINT',
    'IMAGE_REL_SH3_DIRECT4_WORD', 'IMAGE_FILE_MACHINE_R3000',
    'IMAGE_REL_IA64_UREL32', 'IMAGE_RESOURCE_DATA_IS_DIRECTORY',
    'IMAGE_REL_IA64_LTOFF22', 'IMAGE_SCN_ALIGN_64BYTES', 'IMAGE_SCN_LNK_INFO',
    'IMAGE_REL_BASED_MACHINE_SPECIFIC_9', 'IMAGE_REL_M32R_SECREL32',
    'IMAGE_REL_BASED_MACHINE_SPECIFIC_8', 'IMAGE_REL_EBC_ADDR32NB',
    'IMAGE_REL_BASED_MACHINE_SPECIFIC_7', 'IMAGE_REL_IA64_ABSOLUTE',
    'IMAGE_REL_BASED_MACHINE_SPECIFIC_5', 'EMARCH_ENC_I17_IMM41c_INST_WORD_X',
    'X3_IMM39_1_INST_WORD_POS_X', 'IMAGE_REL_MIPS_LITERAL',
    'IMAGE_SYM_CLASS_NULL', 'IMAGE_COMDAT_SELECT_LARGEST', 'IMAGE_DEBUG_MISC',
    'IMAGE_ROM_OPTIONAL_HDR_MAGIC', 'IMAGE_REL_BASED_THUMB_MOV32',
    'IMAGE_SCN_ALIGN_1BYTES', 'IMAGE_SNAP_BY_ORDINAL64', 'IMAGE_SCN_CNT_CODE',
    'IMAGE_GUARD_CF_LONGJUMP_TABLE_PRESENT', 'IMAGE_REL_ARM_MOV32A',
    'IMAGE_REL_ARM_ADDR32NB', 'X3_IMM39_2_INST_WORD_POS_X',
    'IMAGE_SCN_MEM_NOT_CACHED', 'IMAGE_REL_MIPS_REFWORD', 'IMAGE_FILE_HEADER',
    'IMAGE_REL_ARM_MOV32T', 'IMAGE_REL_IA64_SECREL22', 'IMAGE_SCN_LNK_COMDAT',
    'IMAGE_REL_M32R_TOKEN', 'IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG',
    'IMAGE_SYM_TYPE_PCODE', 'IMPORT_OBJECT_HDR_SIG2', 'IMAGE_REL_ALPHA_PAIR',
    'IMAGE_FILE_MACHINE_MIPSFPU16', 'IMAGE_REL_SH3_STARTOF_SECTION',
    'IMAGE_FILE_MACHINE_WCEMIPSV2', 'IMAGE_REL_BASED_LOW', 'IMAGE_VXD_HEADER',
    'EMARCH_ENC_I17_IMM41b_INST_WORD_X', 'IMAGE_HOT_PATCH_CALL_TARGET',
    'IMAGE_REL_IA64_ADDEND', 'IMAGE_HOT_PATCH_DYNAMIC_VALUE',
    'EMARCH_ENC_I17_IMM41a_SIZE_X', 'IMAGE_REL_IA64_SECREL64I',
    'IMAGE_FILE_MACHINE_AM33', 'X3_IMM39_2_INST_WORD_X', 'IMAGE_SCN_MEM_READ',
    'IMAGE_REL_SHM_REFLO', 'IMAGE_SCN_MEM_EXECUTE', 'IMAGE_OS2_SIGNATURE_LE',
    'X3_OPCODE_INST_WORD_POS_X', 'IMAGE_HOT_PATCH_CHUNK_TARGET_RVA',
    'IMAGE_REL_SH3_ABSOLUTE', 'IMAGE_SUBSYSTEM_EFI_APPLICATION',
    'IMAGE_REL_AMD64_TOKEN', 'IMAGE_NUMBEROF_DIRECTORY_ENTRIES',
    'IMAGE_FILE_BYTES_REVERSED_HI', 'EMARCH_ENC_I17_IMM5C_INST_WORD_POS_X',
    'IMAGE_REL_CEE_ADDR64',
    'IMAGE_WEAK_EXTERN_SEARCH_ALIAS', 'IMAGE_DIRECTORY_ENTRY_BASERELOC',
    'IMAGE_REL_SHM_RELLO', 'IMAGE_SYM_CLASS_END_OF_STRUCT',
    'IMAGE_SUBSYSTEM_WINDOWS_CE_GUI', 'IMAGE_REL_SH3_PCREL8_WORD',
    'IMAGE_REL_IA64_DIR32', 'IMAGE_REL_SH3_DIRECT32', 'IMAGE_REL_ARM_SECREL',
    'EMARCH_ENC_I17_IMM9D_SIZE_X', 'IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER',
    'IMAGE_DEBUG_TYPE_FIXUP', 'IMAGE_ENCLAVE_IMPORT_MATCH_NONE',
    'IMAGE_FILE_LOCAL_SYMS_STRIPPED', 'IMAGE_COMDAT_SELECT_EXACT_MATCH',
    'IMAGE_HOT_PATCH_FUNCTION', 'IMAGE_SIZEOF_SECTION_HEADER',
    'IMAGE_ARCHIVE_LONGNAMES_MEMBER', 'IMAGE_REL_IA64_IMMGPREL64',
    'IMAGE_SUBSYSTEM_OS2_CUI', 'IMAGE_REL_IA64_PCREL60F', 'PIMAGE_VXD_HEADER',
    'IMAGE_FILE_MACHINE_ARMNT', 'IMAGE_REL_IA64_PCREL60B', 'IMAGE_RELOCATION',
    'IMAGE_REL_IA64_PCREL60M', 'IMAGE_REL_IA64_PCREL60I', '_IMAGE_OS2_HEADER',
    'IMAGE_DLLCHARACTERISTICS_GUARD_CF', 'IMAGE_FILE_MACHINE_R10000',
    'IMAGE_REL_CEF_SECTION', 'IMAGE_FILE_MACHINE_IA64', 'IMAGE_SIZEOF_SYMBOL',
    'IMAGE_REL_PPC_ADDR24', 'IMAGE_REL_M32R_SECTION', 'IMAGE_REL_EBC_SECTION',
    'IMAGE_DIRECTORY_ENTRY_TLS', 'IMAGE_SYM_CLASS_EXTERNAL_DEF',
    'IMAGE_REL_ALPHA_ABSOLUTE', 'IMAGE_DEBUG_TYPE_MISC', 'IMPORT_OBJECT_TYPE',
    'IMAGE_REL_ALPHA_REFLO', 'IMAGE_COMDAT_SELECT_ASSOCIATIVE',
    'IMAGE_REL_AMD64_SECTION', 'IMAGE_REL_PPC_SECREL16', 'IMAGE_NT_HEADERS64',
    'IMAGE_REL_M32R_GPREL16', 'EMARCH_ENC_I17_IMM41b_VAL_POS_X',
    'IMAGE_DEBUG_TYPE_BORLAND', 'X3_P_INST_WORD_POS_X', 'IMAGE_REL_EBC_REL32',
    'IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION', 'IMAGE_SCN_ALIGN_4BYTES',
    'IMAGE_REL_BASED_MIPS_JMPADDR16', 'IMAGE_REL_I386_DIR16',
    'IMAGE_REL_SH3_DIRECT32_NB', 'IMAGE_HOT_PATCH_CHUNK_OBLIGATORY',
    'IMAGE_FILE_MACHINE_EBC', 'IMAGE_REL_PPC_REL24', 'IMAGE_HOT_PATCH_NONE',
    'IMAGE_SYM_CLASS_MEMBER_OF_UNION', 'IMAGE_DEBUG_TYPE_EXCEPTION',
    'IMAGE_REL_SHM_PCRELPT', 'IMAGE_SCN_ALIGN_8192BYTES', '_IMAGE_DOS_HEADER',
    'IMAGE_FILE_MACHINE_CHPE_X86', 'IMAGE_GUARD_CF_INSTRUMENTED',
    'IMAGE_GUARD_FLAG_EXPORT_SUPPRESSED', 'IMAGE_REL_BASED_RESERVED',
    'IMAGE_REL_ARM_GPREL12', 'IMAGE_ARCHIVE_START', 'IMAGE_REL_PPC_IMGLUE',
    'IMAGE_HOT_PATCH_CHUNK_INVERSE', 'IMAGE_REL_CEF_SECREL',
    'IMAGE_REL_M32R_PCREL8', 'IMAGE_FILE_MACHINE_M32R', 'IMAGE_REL_PPC_REFLO',
    'IMAGE_REL_MIPS_REFHALF', 'IMAGE_SCN_MEM_NOT_PAGED', 'IMAGE_THUNK_DATA64',
    'IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT', 'IMAGE_SYM_DTYPE_NULL',
    'IMAGE_GUARD_CF_FUNCTION_TABLE_PRESENT', 'IMAGE_REL_ARM64_ADDR32NB',
    'IMAGE_DEBUG_TYPE_REPRO', 'IMAGE_REL_ARM64_PAGEBASE_REL21',
    'IMAGE_SCN_ALIGN_16BYTES', 'IMAGE_REL_AMD64_ABSOLUTE', '_IMAGE_SYMBOL_EX',
    'IMAGE_DLLCHARACTERISTICS_WDM_DRIVER', 'IMAGE_SIZEOF_SHORT_NAME',
    'IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY', 'IMAGE_SYM_CLASS_UNDEFINED_LABEL',
    'IMAGE_REL_AMD64_ADDR32', 'IMAGE_FILE_MACHINE_SH3DSP', 'IMAGE_AUX_SYMBOL',
    'IMAGE_ENCLAVE_IMPORT_MATCH_IMAGE_ID', 'IMAGE_SUBSYSTEM_WINDOWS_CUI',
    'X3_D_WH_INST_WORD_POS_X', 'IMAGE_DLLCHARACTERISTICS_APPCONTAINER',
    'IMAGE_LOADER_FLAGS_SYSTEM_GLOBAL', 'IMAGE_SCN_ALIGN_256BYTES',
    'IMAGE_REL_I386_SECREL7', 'IMAGE_COMDAT_SELECT_ANY', '_IMAGE_ROM_HEADERS',
    'IMAGE_NT_OPTIONAL_HDR32_MAGIC', 'IMAGE_REL_IA64_SECREL32',
    'EMARCH_ENC_I17_SIGN_INST_WORD_POS_X', 'EMARCH_ENC_I17_IMM5C_SIZE_X',
    'IMAGE_REL_AM_ADDR32NB', 'IMAGE_DIRECTORY_ENTRY_RESOURCE',
    'IMAGE_REL_SH3_DIRECT4_LONG', 'IMAGE_REL_M32R_ADDR32', 'IMAGE_THUNK_DATA',
    'EMARCH_ENC_I17_IMM41b_INST_WORD_POS_X', 'IMAGE_REL_SH3_PCREL8_LONG',
    'IMAGE_FILE_LINE_NUMS_STRIPPED', 'IMAGE_REL_AMD64_ADDR64',
    'IMAGE_REL_MIPS_SECRELHI', 'IMAGE_REL_ARM_ABSOLUTE', 'PIMAGE_DOS_HEADER',
    'IMAGE_DEBUG_TYPE_RESERVED10', 'IMAGE_GUARD_SECURITY_COOKIE_UNUSED',
    'IMAGE_FILE_MACHINE_SH3E', 'IMAGE_SYM_CLASS_EXTERNAL', 'PIMAGE_SYMBOL_EX',
    'IMAGE_REL_ARM64_BRANCH26', 'IMAGE_SYM_CLASS_STRUCT_TAG',
    'IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE', 'IMAGE_REL_ALPHA_REFHI',
    'IMAGE_SCN_ALIGN_2BYTES', 'IMAGE_REL_I386_REL16', 'IMAGE_SCN_MEM_FARDATA',
    'IMAGE_REL_IA64_GPREL22', 'IMAGE_COMDAT_SELECT_NODUPLICATES',
    'IMAGE_COMDAT_SELECT_NEWEST', 'IMAGE_SIZEOF_FILE_HEADER',
    'IMAGE_SYM_CLASS_AUTOMATIC', 'IMAGE_SYM_CLASS_END_OF_FUNCTION',
    'IMAGE_REL_ARM_ADDR32', 'IMAGE_SYM_TYPE_DOUBLE', 'IMAGE_REL_M32R_PCREL24',
    'IMAGE_HOT_PATCH_NO_CALL_TARGET', 'IMAGE_REL_ARM64_REL21',
    'IMAGE_REL_PPC_REFHI', 'IMAGE_SYM_TYPE_UINT', 'IMAGE_REL_PPC_ADDR64',
    'IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_MASK', 'IMAGE_REL_ARM_SECTION',
    'IMAGE_REL_AM_FUNCINFO', 'IMAGE_SUBSYSTEM_NATIVE', 'X3_IMM20_INST_WORD_X',
    'IMAGE_GUARD_FLAG_FID_SUPPRESSED', 'IMAGE_REL_EBC_ABSOLUTE',
    'IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER',
    'IMAGE_REL_AM_REL32_2', 'X3_EMPTY_INST_WORD_X', 'IMAGE_REL_AM_REL32_1',
    'X3_D_WH_SIGN_VAL_POS_X', 'IMAGE_REL_SH3_GPREL4_LONG', 'IMAGE_NT_HEADERS',
    'EMARCH_ENC_I17_SIGN_SIZE_X', 'IMAGE_DIRECTORY_ENTRY_ARCHITECTURE',
    'IMAGE_SYM_TYPE_LONG', 'IMAGE_REL_M32R_ADDR24', 'IMAGE_REL_IA64_GPREL32',
    'IMAGE_SCN_CNT_INITIALIZED_DATA', 'IMAGE_REL_ARM_BLX11',
    'IMAGE_REL_IA64_SECTION', 'IMAGE_SYM_CLASS_MEMBER_OF_ENUM',
    'IMAGE_DLLCHARACTERISTICS_NO_ISOLATION', 'IMAGE_FILE_MACHINE_ALPHA64',
    'IMAGE_ARCHIVE_HYBRIDMAP_MEMBER', 'IMAGE_REL_SHM_RELHALF',
    'IMAGE_FILE_MACHINE_THUMB', 'IMAGE_SYM_TYPE_ENUM', 'IMAGE_REL_I386_TOKEN',
    'IMAGE_REL_ARM64_SECREL_LOW12A', 'IMAGE_REL_ARM64_ABSOLUTE',
    'IMAGE_REL_AMD64_REL32_3', 'IMAGE_REL_AMD64_REL32_2', 'IMAGE_ROM_HEADERS',
    'IMAGE_REL_AMD64_REL32_1', 'IMAGE_REL_AMD64_REL32_5', '_IMAGE_NT_HEADERS',
    'IMAGE_REL_AMD64_REL32_4', 'IMAGE_REL_PPC_TOCDEFN', 'IMAGE_REL_ARM_MOV32',
    'X3_IMM39_1_INST_WORD_X', 'X3_BTYPE_QP_INST_VAL_POS_X',
    'IMAGE_SCN_ALIGN_32BYTES', 'IMAGE_REL_PPC_SECTION', 'IMAGE_REL_PPC_REL14',
    'IMAGE_REL_CEE_ADDR32NB', 'IMAGE_REL_AMD64_SECREL7', 'PIMAGE_ROM_HEADERS',
    'IMAGE_FILE_MACHINE_POWERPC', 'IMAGE_GUARD_RF_INSTRUMENTED',
    'X3_IMM39_1_SIGN_VAL_POS_X', 'IMAGE_SCN_SCALE_INDEX', 'PIMAGE_DEBUG_MISC',
    'IMAGE_DEBUG_TYPE_OMAP_FROM_SRC', 'IMAGE_FILE_DEBUG_STRIPPED',
    'IMAGE_SYM_CLASS_FAR_EXTERNAL', 'IMAGE_REL_THUMB_BRANCH20',
    'IMAGE_GUARD_DELAYLOAD_IAT_IN_ITS_OWN_SECTION', 'IMAGE_REL_IA64_SREL32',
    'IMAGE_ENCLAVE_IMPORT_MATCH_AUTHOR_ID', 'IMAGE_REL_THUMB_BRANCH24',
    'EMARCH_ENC_I17_IMM9D_INST_WORD_X', 'IMAGE_DEBUG_TYPE_CODEVIEW',
    'IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE', 'IMAGE_REL_PPC_IFGLUE',
    'IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY', 'IMAGE_FILE_MACHINE_R4000',
    'IMAGE_REL_ALPHA_SECRELHI', 'IMAGE_FILE_MACHINE_MIPS16',
    'IMAGE_HOT_PATCH_INDIRECT', 'IMAGE_SYM_CLASS_LABEL', 'IMAGE_COR20_HEADER',
    'IMAGE_SYM_DTYPE_ARRAY', 'IMAGE_FILE_MACHINE_ALPHA', '_IMAGE_DEBUG_MISC',
    'IMAGE_REL_ALPHA_GPRELHI', 'IMAGE_GUARD_RF_STRICT', '_IMAGE_THUNK_DATA32',
    'IMAGE_HOT_PATCH_ABSOLUTE', 'IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE',
    'IMAGE_REL_PPC_ADDR16', 'IMAGE_REL_PPC_ADDR14', 'IMAGE_REL_ARM64_SECTION',
    'IMAGE_REL_I386_DIR32NB', 'IMAGE_REL_SH3_SIZEOF_SECTION',
    'IMAGE_FILE_MACHINE_AXP64', 'IMAGE_RESOURCE_NAME_IS_STRING',
    'IMAGE_REL_ALPHA_REFQUAD', 'IMAGE_ORDINAL_FLAG32', 'IMAGE_SYM_TYPE_UCHAR',
    'IMAGE_REL_MIPS_SECTION', 'IMAGE_DIRECTORY_ENTRY_IAT',
    'IMAGE_SYM_CLASS_REGISTER', 'IMAGE_REL_M32R_PCREL16', '_IMAGE_RELOCATION',
    'IMAGE_SYM_CLASS_MEMBER_OF_STRUCT', 'IMAGE_REL_M32R_REFHI',
    'IMAGE_FILE_MACHINE_SH4', 'IMAGE_FILE_MACHINE_SH5', 'PIMAGE_NT_HEADERS64',
    'IMAGE_FILE_MACHINE_SH3', 'IMAGE_REL_I386_SECREL', 'IMAGE_REL_MIPS_REFHI',
    'IMAGE_SYM_CLASS_ENUM_TAG', 'IMAGE_REL_ARM64_SECREL_LOW12L',
    'X3_OPCODE_INST_WORD_X', 'IMAGE_REL_I386_ABSOLUTE', '_IMAGE_THUNK_DATA64',
    'IMAGE_REL_MIPS_JMPADDR', 'IMAGE_HOT_PATCH_CHUNK_SIZE',
    'IMAGE_REL_PPC_BRTAKEN', 'IMAGE_REL_M32R_REFHALF', 'IMPORT_OBJECT_HEADER',
    'IMAGE_DIRECTORY_ENTRY_IMPORT', 'ReplacesCorHdrNumericDefines',
    'IMAGE_AUX_SYMBOL_TYPE', 'IMPORT_OBJECT_NAME_TYPE', 'PIMAGE_OS2_HEADER',
    '_IMAGE_DATA_DIRECTORY',
    'PIMAGE_COFF_SYMBOLS_HEADER', '_IMAGE_TLS_DIRECTORY32',
    'IMAGE_CHPE_METADATA_X86', 'IMAGE_RESOURCE_DIRECTORY',
    '_IMAGE_LOAD_CONFIG_DIRECTORY32', '_IMAGE_RESOURCE_DIRECTORY_STRING',
    '_IMAGE_DELAYLOAD_DESCRIPTOR', '_IMAGE_CHPE_RANGE_ENTRY',
    'PIMAGE_DELAYLOAD_DESCRIPTOR', 'PIMAGE_HOT_PATCH_HASHES',
    '_IMAGE_HOT_PATCH_HASHES', 'IMAGE_DYNAMIC_RELOCATION32_V2',
    'PIMAGE_CHPE_RANGE_ENTRY',
    'IMAGE_BOUND_IMPORT_DESCRIPTOR', 'IMAGE_ARCHITECTURE_HEADER',
    'IMAGE_HOT_PATCH_HASHES', 'IMAGE_DEBUG_DIRECTORY', 'IMAGE_FUNCTION_ENTRY',
    '_IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER', 'IMAGE_BOUND_FORWARDER_REF',
    'PIMAGE_LOAD_CONFIG_DIRECTORY32', '_IMAGE_ARCHIVE_MEMBER_HEADER',
    '_IMAGE_SEPARATE_DEBUG_HEADER',
    'PIMAGE_BOUND_IMPORT_DESCRIPTOR',
    'PIMAGE_BOUND_FORWARDER_REF',
    '_IMAGE_RESOURCE_DIRECTORY_ENTRY',
    'PIMAGE_LOAD_CONFIG_CODE_INTEGRITY', 'IMAGE_TLS_DIRECTORY64',
    'PIMAGE_ENCLAVE_CONFIG64', 'IMAGE_LOAD_CONFIG_DIRECTORY64',
    'IMAGE_DYNAMIC_RELOCATION64', '_IMAGE_ENCLAVE_CONFIG64',
    'PIMAGE_OPTIONAL_HEADER32', '_IMAGE_HOT_PATCH_BASE', 'IMAGE_NT_HEADERS32',
    '_IMAGE_BOUND_FORWARDER_REF',
    '_IMAGE_ENCLAVE_CONFIG32',
    '_IMAGE_OPTIONAL_HEADER',
    'ANON_OBJECT_HEADER_BIGOBJ', '_IMAGE_BOUND_IMPORT_DESCRIPTOR',
    'IMAGE_ENCLAVE_IMPORT', 'PIMAGE_ARCHITECTURE_ENTRY', 'ANON_OBJECT_HEADER',
    'PIMAGE_RESOURCE_DIR_STRING_U', '_IMAGE_DYNAMIC_RELOCATION64_V2',
    'ANON_OBJECT_HEADER_V2', 'PIMAGE_DYNAMIC_RELOCATION32',
    'IMAGE_CHPE_RANGE_ENTRY', 'IMAGE_IMPORT_DESCRIPTOR', 'IMAGE_THUNK_DATA32',
    '_IMAGE_RESOURCE_DIR_STRING_U',
    'PIMAGE_ARCHITECTURE_HEADER', '_IMAGE_LOAD_CONFIG_DIRECTORY64',
    '_IMAGE_RESOURCE_DIRECTORY', 'IMAGE_ROM_OPTIONAL_HEADER',
    'IMAGE_OPTIONAL_HEADER32', '_IMAGE_DYNAMIC_RELOCATION_TABLE',
    'PIMAGE_SEPARATE_DEBUG_HEADER', 'IMAGE_LOAD_CONFIG_DIRECTORY32',
    'IMAGE_TLS_DIRECTORY32', '_NON_PAGED_DEBUG_INFO', 'PIMAGE_FUNCTION_ENTRY',
    '_IMAGE_DYNAMIC_RELOCATION64', 'IMAGE_DELAYLOAD_DESCRIPTOR',
    'IMAGE_HOT_PATCH_BASE', 'PIMAGE_FUNCTION_ENTRY64', 'IMAGE_HOT_PATCH_INFO',
    '_PIMAGE_RUNTIME_FUNCTION_ENTRY', '_ImageArchitectureHeader',
    'PIMAGE_HOT_PATCH_BASE', 'PIMAGE_DYNAMIC_RELOCATION32_V2',
    '_IMAGE_COFF_SYMBOLS_HEADER', '_IMAGE_RUNTIME_FUNCTION_ENTRY',
    '_IMAGE_TLS_DIRECTORY64', '_IMAGE_HOT_PATCH_INFO', 'IMAGE_SECTION_HEADER',
    'PIMAGE_OPTIONAL_HEADER64', 'IMAGE_RESOURCE_DIR_STRING_U',
    '_IMAGE_EXPORT_DIRECTORY', 'PIMAGE_SECTION_HEADER', '_IMAGE_FILE_HEADER',
    'IMAGE_BASE_RELOCATION', 'IMAGE_ENCLAVE_CONFIG32', 'IMAGE_DATA_DIRECTORY',
    'PIMAGE_DEBUG_DIRECTORY',
    'IMAGE_RESOURCE_DATA_ENTRY', 'PIMAGE_ENCLAVE_CONFIG32',
    'IMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER', 'IMAGE_AUX_SYMBOL_TOKEN_DEF',
    'IMAGE_RESOURCE_DIRECTORY_ENTRY', 'PIMAGE_HOT_PATCH_INFO',
    'IMAGE_FUNCTION_ENTRY64', '_IMAGE_ENCLAVE_IMPORT', 'IMAGE_IMPORT_BY_NAME',
    '_IMAGE_IMPORT_BY_NAME', '_IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER',
    'IMAGE_EXPORT_DIRECTORY', '_ImageArchitectureEntry', '_IMAGE_LINENUMBER',
    '_IMAGE_DYNAMIC_RELOCATION32', '_IMAGE_DYNAMIC_RELOCATION32_V2',
    '_IMAGE_BASE_RELOCATION', 'PIMAGE_ARCHIVE_MEMBER_HEADER',
    'PIMAGE_RESOURCE_DATA_ENTRY', 'PIMAGE_LOAD_CONFIG_DIRECTORY64',
    'IMAGE_DYNAMIC_RELOCATION_TABLE', 'PIMAGE_EXPORT_DIRECTORY',
    'PIMAGE_RESOURCE_DIRECTORY_ENTRY',
    'IMAGE_ARCHIVE_MEMBER_HEADER', 'PIMAGE_DYNAMIC_RELOCATION_TABLE',
    '_IMAGE_FUNCTION_ENTRY', 'PIMAGE_CHPE_METADATA_X86', 'PIMAGE_FILE_HEADER',
    'PIMAGE_IMPORT_BY_NAME', '_IMAGE_DEBUG_DIRECTORY', 'PIMAGE_COR20_HEADER',
    'PIMAGE_DYNAMIC_RELOCATION64', 'PIMAGE_DYNAMIC_RELOCATION64_V2',
    '_IMAGE_ROM_OPTIONAL_HEADER', 'PIMAGE_ENCLAVE_IMPORT',
    '_IMAGE_LOAD_CONFIG_CODE_INTEGRITY', 'IMAGE_OPTIONAL_HEADER64',
    'IMAGE_SEPARATE_DEBUG_HEADER', 'IMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER',
    'IMAGE_ARCHITECTURE_ENTRY', 'IMAGE_DYNAMIC_RELOCATION32',
    'IMAGE_COFF_SYMBOLS_HEADER',
    'IMAGE_DYNAMIC_RELOCATION64_V2', 'NON_PAGED_DEBUG_INFO',
    '_IMAGE_SECTION_HEADER', 'PIMAGE_NT_HEADERS32', 'PNON_PAGED_DEBUG_INFO',
    '_IMAGE_IMPORT_DESCRIPTOR', 'IMAGE_RESOURCE_DIRECTORY_STRING',
    'IMAGE_LOAD_CONFIG_CODE_INTEGRITY',
    'PIMAGE_DATA_DIRECTORY', '_IMAGE_RESOURCE_DATA_ENTRY',
    'IMAGE_ENCLAVE_CONFIG64', 'PIMAGE_RESOURCE_DIRECTORY_STRING',
    '_IMAGE_VXD_HEADER', '_IMAGE_NT_HEADERS64', '_IMAGE_FUNCTION_ENTRY64',
    '_IMAGE_CHPE_METADATA_X86',
    '_IMAGE_OPTIONAL_HEADER64', 'PIMAGE_RESOURCE_DIRECTORY',
    'PIMAGE_ROM_OPTIONAL_HEADER', '_IMAGE_AUX_SYMBOL_EX', '_IMAGE_AUX_SYMBOL',
    'IMAGE_AUX_SYMBOL_EX', 'PUIMAGE_OS2_HEADER', 'PCIMAGE_IMPORT_DESCRIPTOR',
    'PIMAGE_RELOCATION', 'PIMAGE_AUX_SYMBOL_TOKEN_DEF', 'PIMAGE_THUNK_DATA32',
    'PCIMAGE_BOUND_FORWARDER_REF', 'PIMAGE_BASE_RELOCATION',
    'PIMAGE_PROLOGUE_DYNAMIC_RELOCATION_HEADER', 'PCIMAGE_EXPORT_DIRECTORY',
    'IMAGE_LOAD_CONFIG_DIRECTORY', 'PIMAGE_TLS_DIRECTORY32',
    'PIMAGE_THUNK_DATA','PCIMAGE_THUNK_DATA',
    'PCIMAGE_DELAYLOAD_DESCRIPTOR', 'PIMAGE_OPTIONAL_HEADER',
    'PIMAGE_IMPORT_DESCRIPTOR', 'IMAGE_DYNAMIC_RELOCATION_V2',
    'IMAGE_OPTIONAL_HEADER',
    'PIMAGE_LINENUMBER', 'PIMAGE_TLS_DIRECTORY64', 'PIMAGE_NT_HEADERS',
    'IMAGE_IA64_RUNTIME_FUNCTION_ENTRY', 'PIMAGE_LOAD_CONFIG_DIRECTORY',
    'PIMAGE_THUNK_DATA64', 'IMAGE_DYNAMIC_RELOCATION', 'IMAGE_TLS_DIRECTORY',
    'PCIMAGE_IMPORT_BY_NAME',
    'PCIMAGE_TLS_DIRECTORY32', 'PIMAGE_DYNAMIC_RELOCATION',
    'PCIMAGE_SECTION_HEADER', 'PCIMAGE_TLS_DIRECTORY', 'PCIMAGE_THUNK_DATA32',
    'IMAGE_ENCLAVE_CONFIG', 'PIMAGE_AUX_SYMBOL_EX', 'PCIMAGE_TLS_DIRECTORY64',
    'PCIMAGE_THUNK_DATA64', 'PIMAGE_TLS_DIRECTORY', 'PIMAGE_ENCLAVE_CONFIG',
    'PIMAGE_IA64_RUNTIME_FUNCTION_ENTRY', 'PCIMAGE_BOUND_IMPORT_DESCRIPTOR',
    'PIMAGE_EPILOGUE_DYNAMIC_RELOCATION_HEADER', 'PIMAGE_AUX_SYMBOL',
    'PIMAGE_DYNAMIC_RELOCATION_V2',
)
