
from wtypes_h import (
    TEXT
)


from winapifamily_h import * # NOQA
NAMESPACE_CLASS_NAME = TEXT("Namespace")
COUNTRY_CLASS_NAME = TEXT("Country")
LOCALITY_CLASS_NAME = TEXT("Locality")
ORGANIZATION_CLASS_NAME = TEXT("Organization")
ORGANIZATIONUNIT_CLASS_NAME = TEXT("Organizational Unit")
DOMAIN_CLASS_NAME = TEXT("Domain")
COMPUTER_CLASS_NAME = TEXT("Computer")
USER_CLASS_NAME = TEXT("User")
GROUP_CLASS_NAME = TEXT("Group")
GLOBALGROUP_CLASS_NAME = TEXT("GlobalGroup")
LOCALGROUP_CLASS_NAME = TEXT("LocalGroup")
SERVICE_CLASS_NAME = TEXT("Service")
FILESERVICE_CLASS_NAME = TEXT("FileService")
SESSION_CLASS_NAME = TEXT("Session")
RESOURCE_CLASS_NAME = TEXT("Resource")
FILESHARE_CLASS_NAME = TEXT("FileShare")
PRINTER_CLASS_NAME = TEXT("PrINTQueue")
PRINTJOB_CLASS_NAME = TEXT("PrINTJob")
SCHEMA_CLASS_NAME = TEXT("Schema")
CLASS_CLASS_NAME = TEXT("Class")
PROPERTY_CLASS_NAME = TEXT("Property")
SYNTAX_CLASS_NAME = TEXT("Syntax")
ROOTDSE_CLASS_NAME = TEXT("RootDSE")
NO_SCHEMA = TEXT("")
DOMAIN_SCHEMA_NAME = TEXT("Domain")
COMPUTER_SCHEMA_NAME = TEXT("Computer")
USER_SCHEMA_NAME = TEXT("User")
GROUP_SCHEMA_NAME = TEXT("Group")
GLOBALGROUP_SCHEMA_NAME = TEXT("GlobalGroup")
LOCALGROUP_SCHEMA_NAME = TEXT("LocalGroup")
SERVICE_SCHEMA_NAME = TEXT("Service")
PRINTER_SCHEMA_NAME = TEXT("PrINTQueue")
PRINTJOB_SCHEMA_NAME = TEXT("PrINTJob")
FILESERVICE_SCHEMA_NAME = TEXT("FileService")
SESSION_SCHEMA_NAME = TEXT("Session")
RESOURCE_SCHEMA_NAME = TEXT("Resource")
FILESHARE_SCHEMA_NAME = TEXT("FileShare")
FPNW_FILESERVICE_SCHEMA_NAME = TEXT("FPNWFileService")
FPNW_SESSION_SCHEMA_NAME = TEXT("FPNWSession")
FPNW_RESOURCE_SCHEMA_NAME = TEXT("FPNWResource")
FPNW_FILESHARE_SCHEMA_NAME = TEXT("FPNWFileShare")

__all__ = (
    'LOCALITY_CLASS_NAME', 'FILESERVICE_CLASS_NAME', 'SESSION_CLASS_NAME',
    'FILESERVICE_SCHEMA_NAME', 'FPNW_RESOURCE_SCHEMA_NAME', 'NO_SCHEMA',
    'FPNW_FILESERVICE_SCHEMA_NAME', 'GROUP_SCHEMA_NAME', 'COUNTRY_CLASS_NAME',
    'SERVICE_SCHEMA_NAME', 'LOCALGROUP_CLASS_NAME', 'ROOTDSE_CLASS_NAME',
    'RESOURCE_CLASS_NAME', 'PROPERTY_CLASS_NAME', 'COMPUTER_CLASS_NAME',
    'FPNW_FILESHARE_SCHEMA_NAME', 'GLOBALGROUP_CLASS_NAME', 'USER_CLASS_NAME',
    'PRINTER_SCHEMA_NAME', 'PRINTJOB_CLASS_NAME', 'SERVICE_CLASS_NAME',
    'ORGANIZATION_CLASS_NAME', 'GROUP_CLASS_NAME', 'PRINTER_CLASS_NAME',
    'COMPUTER_SCHEMA_NAME', 'FILESHARE_CLASS_NAME', 'NAMESPACE_CLASS_NAME',
    'RESOURCE_SCHEMA_NAME', 'FILESHARE_SCHEMA_NAME', 'DOMAIN_CLASS_NAME',
    'SESSION_SCHEMA_NAME', 'ORGANIZATIONUNIT_CLASS_NAME', 'USER_SCHEMA_NAME',
    'LOCALGROUP_SCHEMA_NAME', 'DOMAIN_SCHEMA_NAME', 'SCHEMA_CLASS_NAME',
    'CLASS_CLASS_NAME', 'FPNW_SESSION_SCHEMA_NAME', 'GLOBALGROUP_SCHEMA_NAME',
    'PRINTJOB_SCHEMA_NAME', 'SYNTAX_CLASS_NAME',
)
